
* Sound intuition
:PROPERTIES:
:org-remark-file: sonic_studies.org
:END:

** It may appear bordering on defensive to get into an in depth investigation of the term /intuition/ in a project that that has attempted to do away with it altogether.

**  In the way that it is used in the title of the project, however, it points to the 

** Also, the word /inside/ here may be confusing as it has not the same meaning as Bergson's /inside/ but, as we will see, may coincide in a useful way. The inside as a qualifier of a perspective is here unique to the artist, whereas in Bergson's method it is a possible perspective for any kind of experience. In Sören Kjörup's contribution to [[citetitle:biggs10]] he comments on what may be the difference between the outside and the inside perspective claiming that: 
Remove from here.

**  One important aspect of this is how the whole relates to the parts

**  Bergson's description of the two profoundly different ways of knowing a thing, through /relative/ 

The segment on artistic research came befor this.

** Though in line with some of the thinking about artistic research that was presented above, this is a quite radical proposition. The concept of actually being able to possess the object, or rather, its motion as Bergson will say, in itself makes possible a range of conceptions. But the distinction between the outside and the inside that is alluded to in this attempt to describe Bergson's theory should also be handled with care.
Move til later

**  Hence, the /perfect absolute/ should be understood in relation to the /imperfect analysis/.

** This borders to embodied cognition and the details here are outside the scope of this essay. Here the purpose is mainly to look at intuition in Bergson's sense as a method for better understanding sonic interaction.

**   When you raise your arm, you accomplish a movement of which you have, from within, a simple perception; but for me, watching it from the outside, your arm passes through one point, then through another, and between these two there will be still other points; so that, if I began to count, the operation would go on forever. [[citep:Bergson1912][p. 6]]

** Bergson is again critiquing an analytical understanding as an activity that is not able to fully understand movement, but only apprehend a sequence of states and concepts.

**  Conceptual knowledge is reached by way of concepts that represent the thing of which knowledge can be said to be had. These, says Bergson, have the "disadvantage of being in reality symbols substituted for the object they symbolize" [[citep:Bergson1912][p. 17]], and as such they demand very little of us. Furthermore, each concept merely expresses a comparison between itself and the object that resembles it. By way of this resemblance it is possible to imagine that by taking concept after concept and putting them side by side we are actually reconstructing the analyzed object.  Through analysis we create concepts and symbols that allow us to structure and organize the world in a systematic manner. If metaphysics, then, is a serious science by which the world can be understood and experienced, rather than just a mind operation

** The consequence of this discussion is that it is not enough to merely attempt to perceive the movement from within, as Bergson is urging us to do, it is first necessary to see the full context of the system for which the intuition is desired, and then experience it from the inside. In other words, to understand an object from the inside, to fully understand its mobility, it is important to understand what the boundaries of the system are. If I wish to understand what it means to play the saxophone, it is not the saxophone I need to enter inside, nor is it merely my own ambition with playing an instrument. I need to engage with the larger system that contains both myself and the instrument. This unity is what creates the conditions for expression and musical creativity, and analyzing the parts by themselves will only tell us what the parts are capable of. Even if I manage to explore the saxophone from the inside, I will only be able to understand it as an independent object. Only if I see the integrated system, and only if I manage to get on the inside of it, will I be able to fully understand it, and the way it is conditioned by its motion.
Detta ska vara med

** nterface between musician and an instrument, and part of it is understanding what type of electronic instrument is being used. My attempt here is not to make a general theory of the various types of electronic instruments that could be of interest, but instead to mainly focus on the particular case of KA of /Goodbye Intuition/. Hence, it should be noted that other types of electronic instruments that holds a whole range of possible modes of engagements, allow for quite a different set of possibilities than what a piece of software does, completely lacking a physical interface. But I believe that it is possible to approach also other kinds of systems with the same method, and even though the results would be different, this could contribute to furthering the knowledge about the musical opportunities of electronic instruments.  The question now is how it may be possible to achieve the kind of /sympathy/ that Bergson is referring to towards KA that will allow for an inside experience of the system as a combination of the performer and the instrument? He describes it in a way that has a great deal of resonance with artistic practice in general 

** It is worth noting that a certain merging of the fields has occurred between the sciences and the arts. Regardless of the extent to which the field of artistic research have reiterated the importance of the difference between the sciences and the arts, the computer is to a significant degree the tool both fields use. In other words, the technology of the artistic research lab is not technologically different from the science lab and, to return to Bergson, the primary tool for deductive analysis is also the primary tool for much of music production today.[cite:For a more elaborate discussion on this topic, see: ;@Tresch2013]

** Though this is probably similar to what Bergson described by way of the moving coil being rolled out and then in again, the compound object complicated things. 
Remove or rewrite

** 1. Assuming that Bergson is right that the method of intuition is a valid means of perceiving the world--which can obviously be contested[fn:7]--the divide .  It is worth noting that a certain merging of the fields has occurred between the sciences and the arts. Regardless of the extent to which the field of artistic research have reiterated the importance of the difference between the sciences and the arts, the computer is to a significant degree the tool both fields use. In other words, the technology of the artistic research lab is not technologically different from the science lab and, to return to Bergson, the primary tool for deductive analysis is also the primary tool for much of music production today.[cite:For a more elaborate discussion on this topic, see: ;@Tresch2013]
Flytta senare

** (in an attempt to change the conditions for the composition process in order to focus on the act of listening.)
:PROPERTIES:
:org-remark-beg: 47333
:org-remark-end: 47444
:org-remark-id: 91e8b5ee
:org-remark-label: nil
:org-remark-link: [[file:sonic_studies.org::316]]
:END:

** In Bergson's description of the two profoundly different ways of knowing a thing, what he calls absolute /absolute/ knowledge from the inside has some resonance with the arguments for the need of artistic research.

** The following discussion departs from the idea that the system that reproduces a sound is part of the sound making process similar to how the saxophone is.

** This, however, does not actually describe access to knowledge other than secondarily. The method gives rise to information that guides the artistic process but what is the knowledge produced here?

** Imagine a field recording from a forest.
:PROPERTIES:
:org-remark-id: 821ec3b2
:org-remark-label: nil
:org-remark-beg: 35052
:org-remark-end: 35092
:org-remark-link: [[file:sonic_studies.org::235]]
:org-remark-original-text: Imagine a field recording from a forest.
:END:
Insert example of field recording
**  the timbral gesture of an abstract sound may provide information used to develop its spatial movement
:PROPERTIES:
:org-remark-id: aba29ad4
:org-remark-label: nil
:org-remark-beg: 36922
:org-remark-end: 37023
:org-remark-link: [[file:sonic_studies.org::246]]
:org-remark-original-text: the timbral gesture of an abstract sound may provide information used to develop its spatial movement
:END:
Add sound example of a typical sonic gesture that implies spatiality and spatial movement.
** By tuning and detuning these intervals relative to each other according to different tuning principles I settle on a subset of intervals whose beatings have a particularly interesting sound
:PROPERTIES:
:org-remark-id: 0c4f8375
:org-remark-label: nil
:org-remark-beg: 40147
:org-remark-end: 40336
:org-remark-link: [[file:sonic_studies.org::264]]
:org-remark-original-text: By tuning and detuning these intervals relative to each other according to different tuning principles I settle on a subset of intervals whose beatings have a particularly interesting sound
:END:
Add sound example of beating patterns and tuning. Add notation?
** To maintain a certain conceptual stability I then notate the intervals, using a system that I have developed and programmed for this purpose,
:PROPERTIES:
:org-remark-id: 0ad87f83
:org-remark-label: nil
:org-remark-beg: 40346
:org-remark-end: 40487
:org-remark-link: [[file:sonic_studies.org::266]]
:org-remark-original-text: To maintain a certain conceptual stability I then notate the intervals, using a system that I have developed and programmed for this purpose,
:END:
Add notation
** Can the sound be understood without also knowing something about /how/ it is produced? I believe that the method of intuition is particularly useful here. 
:PROPERTIES:
:org-remark-id: edb49805
:org-remark-label: nil
:org-remark-beg: 44501
:org-remark-end: 44656
:org-remark-link: [[file:sonic_studies.org::298]]
:org-remark-original-text: Can the sound be understood without also knowing something about /how/ it is produced? I believe that the method of intuition is particularly useful here.
:END:
The fact that our bodies are similarily constructud, whith an oval shaped head and two hears on opposite sides we experience certain properties of sound in a similarl ways. Even if these sonic impressions are subjective they may be intuited by the listening subject in a way that makes the other's experience of them understandable.
** The studies are presented at the end of the paper.
:PROPERTIES:
:org-remark-id: 655e8409
:org-remark-label: nil
:org-remark-beg: 4014
:org-remark-end: 4064
:org-remark-link: [[file:sonic_studies.org::44]]
:org-remark-original-text: The studies are presented at the end of the paper.
:END:

** As a composer working with abstract sound the
:PROPERTIES:
:org-remark-id: e6788d70
:org-remark-label: nil
:org-remark-beg: 36466
:org-remark-end: 36504
:org-remark-link: [[file:sonic_studies.org::243]]
:org-remark-original-text: As a composer working with abstract sound the
:END:
Fixa defintiion enl peer 2
** As an improviser and composer I obviously 
:PROPERTIES:
:org-remark-id: 104fec72
:org-remark-label: nil
:org-remark-beg: 37505
:org-remark-end: 37546
:org-remark-link: [[file:sonic_studies.org::252]]
:org-remark-original-text: As an improviser and composer I obviously
:END:
Fixa enl peer 2
** What I see when I start an application on my computer, what I experience to be the system in play, is just myself and the computer, where in reality it may involve previous input and output, as various positions and biases.
:PROPERTIES:
:org-remark-id: 5ee79faf
:org-remark-label: nil
:org-remark-beg: 29911
:org-remark-end: 30134
:org-remark-link: [[file:sonic_studies.org::209]]
:org-remark-original-text: What I see when I start an application on my computer, what I experience to be the system in play, is just myself and the computer, where in reality it may involve previous input and output, as various positions and biases.
:END:
Work out this paragraph according to peer 1 comment "section starting on p7"
** To understand intuition in a Bergsonian way it may also be necessary to contrast it with other uses and definitions of intuition.
:PROPERTIES:
:org-remark-id: 5f003d39
:org-remark-label: nil
:org-remark-beg: 15261
:org-remark-end: 15390
:org-remark-link: [[file:sonic_studies.org::117]]
:org-remark-original-text: To understand intuition in a Bergsonian way it may also be necessary to contrast it with other uses and definitions of intuition.
:END:
Remove, rephrse
** definitions
:PROPERTIES:
:org-remark-id: fda5335c
:org-remark-label: nil
:org-remark-beg: 15365
:org-remark-end: 15376
:org-remark-link: [[file:sonic_studies.org::117]]
:org-remark-original-text: definitions
:END:

**  that makes possible a further critique of Bergson's division between analysis and intuition.
:PROPERTIES:
:org-remark-id: 496c56f2
:org-remark-label: nil
:org-remark-beg: 31389
:org-remark-end: 31481
:org-remark-link: [[file:sonic_studies.org::219]]
:org-remark-original-text: that makes possible a further critique of Bergson's division between analysis and intuition.
:END:
Remove? No, fixed!
**  Using the method of intuition it may still be possible to learn something in this context. 
:PROPERTIES:
:org-remark-id: 10ce591a
:org-remark-label: nil
:org-remark-beg: 33608
:org-remark-end: 33700
:org-remark-link: [[file:sonic_studies.org::229]]
:org-remark-original-text: Using the method of intuition it may still be possible to learn something in this context.
:END:
Delete?

** Beating is when two waveforms whose frequencies are tuned to a close proximity of each other and give rise to a beating pattern that was never part of the two original waveforms. 
:PROPERTIES:
:org-remark-id: 0bef9cc2
:org-remark-label: nil
:org-remark-beg: 39102
:org-remark-end: 39280
:org-remark-link: [[file:sonic_studies.org::260]]
:org-remark-original-text: Beating is when two waveforms whose frequencies are tuned to a close proximity of each other and give rise to a beating pattern that was never part of the two original waveforms.
:END:
Delete?

* 
:PROPERTIES:
:org-remark-file: sonic_studies_test.org
:END:
