# Created 2020-09-19 lör 14:26
#+TITLE: Sound intuition
#+AUTHOR: Henrik Frisk, henrik.frisk@kmh.se
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil pri:nil tags:not-in-toc toc:nil num:0
# #+INCLUDE: "./setupfile.org"
#+cite_export: csl ~/MyDocuments/articles/biblio/csl-styles/apa-7th.csl
#+LATEX_HEADER: \bibliography{./gi_biblio.bib}

* COMMENT soundfiles
[[file:/Volumes/Freedom/Dropbox/Documents/uppdrag/GI/kimauto/final_project/final_stuff/KA_example_1.wav][file:/Volumes/Freedom/Dropbox/Documents/uppdrag/GI/kimauto/final_project/final_stuff/KA_example_1.wav]]

* COMMENT code
#+begin_src emacs-lisp
  (set-window-margins (selected-window) 10
 10)
  (setq line-spacing 0.9)
#+end_src

#+RESULTS:
: 0.9

* COMMENT stuff
 and I only include some of the earlier expressions here to emphasize the how the view of artistic research as a distinct practice from other kinds of research has been important to the development of the field.

 In this paper I will discuss the way in which one may gain experiential access to the sound
French theorist Pierre Schaeffer's [cite:@schaeffer77] very influential work taught us how the sound becomes accessible to the listener through the process of reduced listening. A listening process in which the source of the sound is less important than the inherent qualities of the sound. Though this has proven to be an important analytical tool for both electroacoustic music and other genres for almost 75 years

* Introduction
In the process of working with sound in artistic practice, be it a sound installation or a musical composition, or something else, the way one may gain access to the sound itself is at the same time both completely unproblematic and very enigmatic.
A sound is a compound a various kinds of information.
It has a source, discernible sonic qualities, it may have a direction and a space, and it may give rise to a number of emotions, sometimes several at the same time.
A sound can be completely metaphysical, imagined as part of a dream, or it can be so physical as it is felt by the entire body.
It can be painful or beautiful, harsh or soft.
The balance between the various components can obviously shift depending on what kind of sound it is, and all of the parameters of the sound as a whole changes over time.
One and the same continuous sound can start as a perfectly sourced sound and end in an almost completely abstracted and deconstructed noise.
How can this amorphic compound be understood in artistic practice? How can it be analyzed and what kind of analysis actually participates in a widened understanding of the meaning of the sound, rather than deductively reducing it? How can artistic research provide complementary knowledge about the function of sound in art and in other contexts?

This work departs from ideas developed in the research project Goodbye Intuition (GI).[fn:13]
The focus of GI was on improvising with "creative" machines and this processes led me to explore the method of intuition.
Playing with a machine that has very little sense of intuition, neither in its standard meaning, nor in the meaning explored in this paper, reveals the complexity of what it means to have an intuitive understanding in working with sound.
One of the results of GI was the extent to which we projected our own intuitive sense unto the machine improviser[fn:15] resulting in the impression that there was in fact an intuitive relation between the machine and the human improviser.
The work discussed here has been carried out using methods similar to those used and developed in GI [cite:see @Frisk2020] where the basic process can be described as a lab in which artistic practice is documented and out of which particular events are extracted and studied.
These are extracted based on my own inner understanding of the practice using purposeful sampling [cite:@Patton2002], but the main aspect discussed here is the use of intuition in the sense that Bergson uses the word may be a useful method in artistic research in sound practices. 
The studies are presented at the end of the paper.

The focus in this paper is on the use intuition of sound as a method in order to approach the questions concerning the understanding of sound from a particular practice of working with composition and improvisation in music.
Henri Bergson's work is used as an inspiration:
How can I understand sounds and sonic gestures evolving in time and space as carriers of meaning?
This question should be seen as an attempt to break with the scientific imperative of the tools I often work with in the studio, and instead explore an intuitive relation to the material these tools may /result/ in.

When playing an instrument the sound is at least to some degree woven together with the gestures one perform as the music evolves over time.
For the composer sitting behind a computer screen for hours the situation is different.
Working with tiny adjustments to microscopic segments of the sonic material relieves the distance that may occur between the composer and the material they work with.
If the sound is seen as an object that is to some degree independent of where and how it was produced and where, why and how it is heard, this may not be seen as a problem.
But if one engages in a more holistic view on sound practicies that I propose in this paper there are a number of questions that arises in the studio practice:

1. Questions relating to the contents of the sound, its ontology, its shape, its gestural aspects, its space are necessary to approach in the studio practice. One by one they may be analyzed deductively, but the general design of the tools with which this is made possible simultaneously makes it difficult to successfully understand them together, as a whole.
2. The tools of a modern studio does allow the composer to turn from a tiny detail, to the whole, in a blink of an eye, which is helpful but may further contribute to a fragmentation of the material rather than an integration.
3. The reproduction of sound in the studio is in almost all cases completely different from the one that the music will ultimately be played back on.
   For that reason the composer will necessarily have to engage in a constant act of imagination to complement the sound produced in the studio with the imagination of what the performance space will ultimately sound like.

These difficulties, nevertheless, are by no means insurmountable.
In artistic practice the issue may be addressed and the hypothesis explored in this paper is that it rests on the developed ability to imagine how sound will be experienced.
Being a composer and improviser I can make myself intuit sound in a way that makes it possible for me to engage in a fluid relation to the material--this is to some extent what I train to do as a musician.
In this case the sound is not an object, but rather an ongoing activity, and despite my inner knowledge a fuller analysis is still difficult achieve.
The sound is not merely perceived but created and recreated in the act of inner and outer[fn:14] listening in a process where the signification of the various aspects of the sound is consciously and constantly changing.
My knowledge and experience as a practicing musician allows me to understand the flow of sound in time and act upon it.
This understanding is not easily translated to analytical knowledge and it is different in kind to the notion of sound as an object. 
I can transform my listening both in time and space and imagine what the music will sound like in another environment: I can experience it, not as an /external object/ that I exploit, but /from within it/, together with it: from the "inside".
The terminology here comes from Bergson, as will be clear later in the text and it has advantages but also obvious difficulties. The word "inside" carries with it an unfortunate connotation that makes assumptions about a division that may not actually make sense and can be counter-productive.
This will be discussed further on in the text but I leave it for now as it provides a segue to the next section.

There have been many attempts to approach the possible ways in which to understand sound over the years.
French theorist Pierre [cite/text:@schaeffer77] and his very influential work made sound objects become accessible to the listener phenomenologically through the process of reduced listening where the source of the sound should be disregarded.
Dennis [cite/text:@smalley86] developed the concept of /spectromorphology/ that builds on Schaeffer's theory and is an analytical tool to trace the spectral changes of a sound over time.
William [cite/text:@Gaver1993] opened up for an ecological perspective and pointed to a new ontology of sound, and Eric [cite/text:@clarke05] further developed the ecological approach.
Other attempts include the concept of sound as an /(Un)repeatable object/ [cite:@Dokic2007]. 

* Artistic Research and the knowledge claim 
In the early days of artistic research, and for a long time to follow, there was a discussion about the difference between artistic research and other kinds of research.
One common argument is that since the artistic researcher is exploring the artistic process in the making, the research is performed from an /inside/ perspective.[fn:1]
This may even be seen as one of the defining ideas of the epistemology of artistic research: there is a difference between knowledge that has been acquired from observing an artistic practice, and knowledge that is the result of practicing art.
A common metaphor used to described the difference between these two modalities is to see the former as knowledge acquired from the outside, from an analytical perspective; and the latter as knowledge from the inside.
Like was noted above this has the unfortunate conceptual drawback of creating a dichotomy between the inside and an implied outside, which is neither entirely correct, nor is it useful for, say, the development of interdisciplinary research.
The often cited categories (and their variations such as those proposed by [cite/text:@borgdorff07]) that [cite/text:@frayling1993]  put forth in his article /Research in art and design/ ‘research into art’, ‘research for art’ and ‘research through art’, are loosely pointing in this direction: there are distinct research modalities from which various types of results emerges.
However, these categories are rarely stable, neither mutually exclusive, and they are often very difficult to determine other than from the point of identity.

To explore the idea of artistic research from an inside perspective it is not enough to merely consider the perspective of the researcher.
Exploring internalized how-to knowledge and the belief systems that surrounds the practice demands stable and transparent methods for revealing the processes in action.
This is similarly discussed by [cite/text:@Galdon2022] concluding that "this type of implicit knowledge creates a problem around how we can be sure that tacit knowledge is communicated and acted upon in a manner consistent with its generation" (p.919) which can again extend to a critique of the /inside/ as a qualifier unique to the artistic researcher.
It tends to give any argument put forth from this perspective a parochial nature difficult to contest when the claim is that the artistic researcher by definition produces research from the /inside/.

Much has been written about these topics over the years of the development of the field of artistic research. In the contribution by Sören [cite/text:@kjorup10] in the /Routledge Companion to Research in the Arts/ he argues that:
   #+begin_quote
   if artistic research is supposed to be different from all other kinds of research, it is natural to focus on the artist as the researcher, and what is specific for the artist is her or his privileged access to her or his own creative process. [cite:@kjorup10; p. 25]
   #+end_quote
   
This "privileged access" could be seen to harbour a possibility for revealing a kind of knowledge that is sometimes mediated by symbols and concepts, but which is primarily founded on unmediated experience, a somewhat paradoxical situation where the goal is to bring forth that which is by nature hidden.
Naturally, one of the recurring themes in the early discussions on the identity of artistic research was, and still is, how to understand its nature, and what kind of relation it would have to other kinds of knowledge.
How can something that evades conceptualization at all be represented in a stable manner?
How may this unmediated experience be useful to the artistic researcher and others? These questions are still of relevance in artistic research and the point on which this discipline is most often criticized.[fn:2]
However, they also rely on the fact that the artist, with their privileged access, knows how to gain access to the experience, or what is often referred to as tacit knowledge, and that this is the source for the methodological mangling, conceptualization and eventually, the expression of meaningful knowledge.
How to achieve this is the primary focus of the discussion for the rest of this paper within the field of artistic research in sound and music.

I will approach the question through Bergson's  method of intuition in the context of my own practice as a composer.
Bergson's method of intuition, I will argue, may contribute to showing that not only is it possible to gain formal knowledge from artistic research in a methodologically stable manner, but also that the difference compared to other fields of research is perhaps less significant than what is commonly believed.
Artistic research could in this regard be seen as a research practice that may contribute to widen the perspectives of how formation of knowledge takes place in sonic practices.

* The method of intuition
Among others French philosopher Henri Bergson sought to address the problem of what knowledge one may have of the world exterior to oneself, and one of the central tenets in this effort was the method of intuition that he developed.
It was a recurring theme in his work but in this paper I mainly draw upon his short text /An introduction to metaphysics/ [cite:@Bergson1912].
Intuition as a method will by necessity include also other modes of thinking, but the point here is not to give a full account of Bergson's philosophy, nor of the method's full implications.[fn:3]
With it I am proposing a method with which the questions above may be addressed.
Contrary to Bergson's point of view, Bertrand Russel, one of Bergson's fiercest critics, saw intuition and instinct as incapable at creating anything new, something only intellect can achieve. Intuition, Bergson writes, "is greater, as a rule, in children than in adults, and in the uneducated than the educated" discrediting the epistemological capacity of intuition as a means of learning and understanding [cite:@russell1981].
Furthermore, from a point of view of the developments of cognitive science the developments over the last few decades may seem to have rendered Bergson's theories obsolete, bu from a philosophical and metaphysical point of view, however, there has been a continuing interest for his work [cite:See @lawlor03;@Shklar1958;@Kelly2010;@yasushi2023]. 

To understand intuition in a Bergsonian way it may also be necessary to contrast it with other uses and definitions of intuition.
The more general interpretation of intuition relates to the things we do without thinking about them; the intuitive knowledge that something is, for example, wrong or dangerous.
In this sense intuition may be likened to an internalized and automated system that pre-reflectively makes us act upon what is going on in the world around us. 
In phenomenology intuition has a slightly different meaning.
Intuition gives the subject first-person knowledge and in this sense an object can be said to be /intuited/.
Bergson's use of intuition is described by [cite:@Kelly2010] "as a method of reflecting on instinctual or sympathetic engagement with things in all their flux before the framework of practical utility obfuscates our relation to them and to life." (p. 10)
It is this meaning of intuition that the rest of this paper is leaning on.

In the essay /An introduction to metaphysics/ [cite/text:@Bergson1912] defines two incommensurable ways to approach an object: either from a point of view through signs and concepts--a /relative/ perspective--or through entering into the object, exploring it from the inside--an /absolute/ apprehension. This second method is achieved by entering into what he calls a /sympathy with the possible states of the object/ which allows for inserting oneself "in them by an effort of imagination"  [cite:@Bergson1912; p. 2].  This enables him to "no longer grasp the movement from without, remaining where I am, but from where it is, from within, as it is in itself" [cite:@Bergson1912; p. 3]. The latter is what he refers to as the /absolute/ knowledge: "the absolute is the object and not its representation, the original and not its translation, is perfect, by being perfectly what it is." [cite:@Bergson1912; p. 5-6]

The example that he gives to describe representational knowledge is a photographic model of a city.
One where all angles and all surfaces have been photographed and documented to achieve something similar to the street view that online map programs sometimes offer.
Exploring such a model can obviously never be equated with the experience of being in the city. It will by necessity offer something rather different.
Another example given is the translation of a poem into different languages.[fn:5]
Each such translation can give the reader a good idea of the meaning of the poem, sometimes revealing new articulations, but it would "never succeed in rendering the inner meaning of the original" [cite:@Bergson1912; p. 5].

One of Bergson's central propositions here is that the kind of knowledge that arises from a /relative/ perspective is always a reduction of the thing under investigation.
By scrutinizing the object from an outside perspective, dividing it into ever smaller elements allows for analytical precision, but whatever comes out of this process is always a reduction:
   #+begin_quote
   In its eternally unsatisfied desire to embrace the object around which it is compelled to turn, analysis multiplies without end the number of its points of view in order to complete its always incomplete representation, and ceaselessly varies its symbols that it may perfect the always imperfect translation. It goes on, therefore, to infinity. But intuition, if intuition is possible, is a simple act. [cite:@Bergson1912; p. 8]  
   #+end_quote

The /absolute/ is given from /intuition/ and the /intellectual sympathy/ with the object that allows for it.
The /intuition/ of the object at hand allows for the perception of its unique qualities: the /perfect absolute/ in contrast to the /imperfect analysis/.
To Bergson, the science of intuition is metaphysics, and metaphysics is "the science which claims to dispense with symbols" [cite:@Bergson1912; p. 9].

The one reality that is almost always seized from within is when we engage in self reflection.
Bergson gives a description of the various strata this process of introspection provides when slowly moving towards the center of the self.
From the outside a protecting "crust" is encountered made up of all the perceptions from the outside world.
Then memories of interpretations of perceptions are encountered, followed by the motor habits that are both connected and detached from the other layers.
But at the core, Bergson describes the continuous flux of a concatenation of states in an ongoing movement back and forth.
The metaphor used here is that of a coil constantly unrolled and rolled up again through the various layers out on the outside and back in again.
Admittedly, this comparison is far from perfect because there are no two identical moments in consciousness and the rolling up of the coil may thus be misleading.
Even going back in memory to past events invades that memory with all prior and present events.
Instead, it evokes a passage in his earlier work, [cite:@bergson91], also describing the motion back and forth through memory and experiences.
Conscious practice is displayed here as a cone whose tip is moving over a similarly moving plane, and the point of the cone represents the present and the cone itself the accumulated memories and experiences: 

   #+begin_quote
   The bodily memory, made up of the sum of the sensori-motor systems organized by habit, is then a quasi-instantaneous memory to which the true memory of the past serves as base. Since they are not two separate things, since the first is only, as we have said, the pointed end, ever moving, inserted by the second in the shifting plane of experience, it is natural that the two functions should lend each other a mutual support. So, on the one hand, the memory of the past offers to the sensori-motor mechanisms all the recollections capable of guiding them in their task and of giving to the motor reaction the direction suggested by the lessons of experience. It is in just this that the associations of contiguity and likeness consist. But, on the other hand, the sensori-motor apparatus furnish to ineffective, that is unconscious, memories, the means of taking on a body, of materializing themselves, in short of becoming present.  [cite:@Bergson1912; p.152-3]
   #+end_quote

The sensory motor-habits are informed by memories through which they will be guided to do the work they are set out to do, and because no single memory is ever stable--it is always altered by the present in the interaction between what Bergson refers to as the "pointed end" and the past memory--the experience is continuously altered by past experience, which in turn is influencing the present.
Interesting for the current discussion is the connection brought up between sensori-motor mechanisms and past experience, and the fact that this connection is not only going one-way, from memory to habit, but also from habit back to memory.
Embodied memory is in a changing flux and in constant interaction with experience and habit.
There is an inclination to understand learned and deeply integrated behavior, such as playing an instrument or lifting a glass of water, as pre-reflective and almost acts independent from reflection.

It is in thinking about embodiment and motor-habits that Bergson's understanding of what an intuition can be is perhaps best understood.
When I move my leg or my hand I have a unique insight into what is going on, one that would be difficult, or impossible, to acquire from the outside in the same way.
Analyzing the movement will result in a failure to understand it completely since the analysis only pins the movement to a sequence of states.
The actual change, the mobility or, as Bergson would put it, the duration, is only possible to understand through intuition.
Furthermore, any new experience within such a movement, as well as any past experience will introduce change in the system.
   #+begin_quote
   When you raise your arm, you accomplish a movement of which you have, from within, a simple perception; but for me, watching it from the outside, your arm passes through one point, then through another, and between these two there will be still other points; so that, if I began to count, the operation would go on forever. p.6
   #+end_quote

I have learned to move my arm, and every new piece of information about what I can do with it will add to my arm-moving-knowledge, and intuition is the modality through which this process is carried out. For a subject able to observe the thing from the inside, intuitively, there are no states, only duration and mobility informed by experience and knowledge.  
Without this inside access one is left with the option of a conceptual analysis from the outside, and regardless of how many different perspectives this analysis is performed from, it will never fully capture the true /motion/ of the object.
The contradictions between this and the intuitive knowledge that Bergson is arguing for
   #+begin_quote
   arise from the fact that we place ourselves in the immobile in order to lie in wait for the moving thing as it passes, instead of replacing ourselves in the moving thing itself, in order to traverse with it the immobile positions. They arise from our professing to reconstruct reality--which is tendency and consequently mobility--with precepts and concepts whose function it is to make it stationary. [cite:@Bergson1912; p. 67]
   #+end_quote

One central aspect of the distinction between analytical and intuitive knowledge made here is that the intuitive, being in the motion or the duration, can always develop concepts and form the basis for analytical knowledge, whereas it is impossible to reconstruct motion from fixed concepts: An analysis may result from intuition, but intuition cannot arise from analysis. The analysis is performed on one particular state of the duration, and from multiple analyses or states it is possible to imagine that the mobile may be reconstructed by simply adding the different states together. This is the critical point that Bergson objects against: It is only through intuition that the variability of reality may be fully experienced as mobility. A succession of static states is radically different, it is a series of frozen frames of time, one slice after the other. The error in thinking that reality may be accessed purely through analysis, claims Bergson, "consists in believing that we can reconstruct the real with these diagrams. As we have already said and may as well repeat here--from intuition one can pass to analysis, but not from analysis to intuition" [cite:@Bergson1912; p. 48] 

* Intuition and sound in practice
In sound and music in the frame of artistic research the mode of thinking that Bergson proposes have some interesting consequences.
As was hinted to in the beginning of this paper one of the obstacles in artistic research are the questions concerning 1) the methods that allows for observing relevant information about the artistic practice in sound, and 2) the means of presenting this information in an accessible manner.
I will mainly discuss the first of these which I argue may be addressed using the proposed method of intuition.
** Acoustic instruments
Playing an acoustic instrument is a complex activity that involves a lot of interaction between the instrument and the musician. Practicing the instrument over many years allows the musician to develop a very instinctual relation to the instrument.
As a saxophonist, when I pick up and play the saxophone I do not experience it as an external object that I analyze deductively.
I enter into a sympathy with it that allows for an intuitive understanding of the processes I engage in.
There is a intimate relation between learning and intuition and the more I learn about my instrument the greater is the possibility to enter into sympathy with it.
The process of learning to play an instrument is often compared to other embodied activities such as cycling: they become second nature and to some extend pre-reflective.

Time is of essence and, following Bergson, it is only through the method of intuition that the continuous flow may be experienced.
To succeed to enter into sympathy with the play situation, however, it may not be the saxophone as an object I need to understand, and the notion of "an object" may be misleading.
Rather, it is the larger system, containing both myself and the instrument and its context that I need to engage with.
This unity creates the conditions for expression and nuanced musical creativity, and analyzing these parts by themselves will only tell us what the parts are capable of, not the whole.
Only if I manage to get "on the inside" of the integrated system will I be able to fully understand it and the way it is conditioned through motion and duration.
If some part of the system changes it is often not enough to only make a small adjustment, the whole system needs to be reconfigured, and certain things needs to be learned again.
One example is if something in the occlusal plane changes ever so little in my mouth I may have to spend months practicing the saxophone to get back to my intuitive experience of playing.
I sense a change which may not be analytically perceivable from my current viewpoint.
The sensory and auditory feedback I get from the instrument continuously adopts how I play it, how much pressure I put into it, and this input clearly depends on the structurality of the instrument and the system as a whole: My motor-habits are changing as I play which changes the feedback I get from the instrument.
In other words, to perceive an object from the inside it is first necessary to understand the way the object integrates with me whereby its status as an independent object to some extent is dissolved.
The instrument becomes embodied, a process that is the result of sympathizing with the object, at first, and then to a gradually increasing degree, with the system at large allowing for intuition.
This integration is part of learning an instrument and may be quick in simpler instances and take a lifetime in more complex ones.

But also sensory data that are external to the saxophone-musican system has an impact on what and how I play.
The moving coil that Bergson describes is a metaphor for how learning also depends on past experiences and on events outside of oneself. this back and forth process which is not, however, limited to two dimensions, but is in a constant motion in a multi-dimensional space that involves all aspects of the system.

** The computer as an instrument
In contrast to the musician-instrument relation described above the musician computer relation is of a more convoluted nature. What I see when I start an application on my computer, what I experience to be the system in play, is just myself and the computer, where in reality it may involve previous input and output, as various positions and biases. 
In this sense the electronic musical instrument is a system which is by some degree larger and more elaborate than an acoustic instrument.
What does it mean to get on the inside of a such systems?
What part of the system has agency and to what extent is the creative act distributed rather than controlled by the musician?
The extents to which such a system stretches out into the unknown is significant. 
It may include programmers and designers that are disconnected from the performer in both time and space, yet connected to the instrument and its design properties.[fn:16]
There may be a range of hidden layers, disguised from both performers and audience that can be remapped during the course of the performance.
An electronic instrument that is connected to the internet and that continuously fetches information that influences its output in live performance is a special case, but not uncommon, and such a system is significantly different from an acoustic musical instrument.
Intuition, I believe, is still a valid method here, but it requires a few considerations which I will discuss in he following.

In this context it is also worth noting that a certain general merge between fields of arts practices and science in general has occurred that makes possible a further critique of Bergson's division between analysis and intuition.
Regardless of the extent to which the field of artistic research have reiterated the importance of the difference between the sciences and the arts, the computer is to a significant degree the tool both fields use.
In other words, the artistic research lab is not technologically different from that of the science lab and the primary tool for deductive analysis is also the primary tool for much of music production today as is pointed out by [cite/text: @Tresch2013].
Though the methodologies of the two fields differ to a significant degree the merge is not profound, it may conceal the fact that the technology, rather than supporting the creative work, also controls it in ways that are not obvious.
The agency of the systems are blurred.
More importantly, in this incipient merge between the computer as a tool and instrument, and other instruments for artistic practice in music, there may be a risk that the scientific nature of the machine constrains the possibility for engaging intuitively with the system of artistic production.
As was noted above, many electronic instruments, by their immediate relation to engineering and science, lend themselves naturally to an understanding based on representation rather than intuition, which enforces their role as mere tools.

The method of entering into sympathy with a recorded sound in a technological system, and understand it from the /inside/ without getting lost in the various ways that the systems for reproduction extends in space and time is accessible yet complex. When it comes to listening perhaps the question should rather be if /any/ listening can be said to /not/ be carried out from "the inside", using Bergson's terminology?
There are a number of widespread listening practices, like Pauline Oliveros' /Deep Listening/ method [cite:@oliveros2005] that proposes methods towards this goal, and that are entirely independent of Bergson's notion of intuition.
With this in mind technologically mediated listening in a studio while in a process of working artistically with sound still provides a mix of modalities that has impact on the present discussion. Using the method of intuition it may still be possible to learn something in this context.  

Could Bergson's proposed method be useful with regard to understanding listening and creativity in the process of composition? As was discussed in the beginning of this paper, one of the challenges in artistic research is to get access to the specific kinds of knowledge that the artistic process generates and makes use of. It appears reasonable to assume that a close relation between a reflective thinking through a Bergsonian method of intuition, within the actual practice as it takes place may help to gain insight about this knowledge.
In my own experience the deductive methods that pertain to the construction of many of the tools in the electronic music studio of analysis previously mentioned, and common in the electronic music studio may disrupt both practice and thinking.
Understanding a recursive filter or a signal processing device, let alone an AI enhanced digital compressor or a generative audio plugin requires an insight into the analytical aspects of sound that may disperse the intuitive focus of the artist's working methods.

Furthermore, there are aspects of a sound that /requires/ the listener to be within the /mobility/ of the sound to understand them. The spatiality of sound can both be purely imagined and highly concrete and it is an aspect of the sound which is very difficult to extract with deductive methods. Imagine a field recording from a forest. It is raining and the dripping water is at the front of the soundscape, but there are other sounds intruding, though they are quite, and it is probably night. As a listener one may move inside of the sound, and all of its discrete aspects, including the particular spatial character of all the component sounds may be gathered through an intuitive analysis, from within the experience of listening.
An experienced sound designer is likely to be able to recreate at least parts of this soundscape with samples and synthesis.
A signal analysis of the same recording may provide a large amount of additional information about the sound from which many aspects of it can be recreated, whereas others are extremely difficult to synthesize merely from an analysis. Especially the spatiality of the sound is difficult to emulate merely from the analysis.

One of the advantages of working from the experience rather than only the analysis is that for the listener the memories are entangled with our listening.
The listeners experience with being in similar environments in the past allows them to reconstruct the space, and the way it transforms over time.
In an act of intuition the past and the future, as in the wish to recreate the sound, gets connected, which can be a powerful advantage to the deductive analysis.[fn:17] 

For a musician working with abstract sound in the studio the ability to transform the listening opens up for modes of analysis that are only available here and not with the tools offered by the studio equipment.
Staging data transformations where one type of sonic gesture is providing information for another gesture in another domain relies on listening practices that are deeply embedded with the compositional intent.
Sound itself becomes the source for the development of the material.
As an example, the timbral gesture of an abstract sound may provide information used to develop its spatial movement.[fn:6]
Access to these layers of the sound is really only available through an intuitive mode of listening.
From this intuition an analysis can be performed that allows for the discovery of sonic properties that can influence sound synthesis and compositional strategies.
This, however, does not actually describe access to knowledge other than secondarily.
As used here the method primarily gives rise to information that guides the artistic process.

As a musician I obviously rely heavily on trying to intuitively understand the sonic materials I work with.
Listening is the main tool out of many in a large toolbox and for a musician listening is by necessity at certain times different to audience listening.
A current project I work with departs from a relative simple idea with sonic material derived from fairly basic oscillators to generate sound waves.
This work in progress will be used in order to point to a possible way to understand the impact that Bergson's method of intuition may nevertheless have.
The goal with this particular project is to attempt to introduce change in my working process through an effort to understand what the conditions for electronic music composition were prior to the introduction of digital technology, in particular the computer.[fn:7] 

The process may appear unnecessarily complicated and departs from the beating that occurs between pitches in certain (in)harmonic relations, typically between large integer ratios, or where the pitch difference between two pitches is small. The use of beatings is common in many contexts and is described in detail by Herman von Helmholtz [cite:@helmholtz1954] in his seminal work /On the Sensations of Tone/.
Sonic effects like the interference that gives rise to beatings,[fn:8] shows example of a certain transgression of the sound that may allow for a widened listening experience: an effect arises that sometimes masks the original sounds and which allows  the sound of the beating to take over: a  "new and peculiar phenomena arise which we term interference"  [cite:@helmholtz1954]: .
Beating is when two waveforms whose frequencies are tuned to a close proximity of each other and give rise to a beating pattern that was never part of the two original waveforms. 
There is nothing new about interference in electronic music and it is widely used in synthesis and processing. What makes it interesting in this context is the way it creates a sonic topology for the listener to navigate. The original sounds are not always, but in some cases still discernible, and the added beating gives the listener a possibility to navigate the sound in dimensions
For this particular composition I derive the relevant intervals by a process where I used a four by four grid with a total of sixteen knobs, each controlling the pitch of sixteen simple waveforms, the frequencies of which are derided from the third, fifth and seventh partials of four fundamentals C, G, D, A.
Although the beating patterns between two intervals can be easily calculated,[fn:9] the sounding result of the interference is obviously different than the calculation.
By tuning and detuning these intervals relative to each other according to different tuning principles I settle on a subset of intervals whose beatings have a particularly interesting sound.[fn:10]

To maintain a certain conceptual stability I then notate the intervals, using a system that I have developed and programmed for this purpose,
The notation, then, is an abstraction of the analysis derived from the intuitive act of listening and tuning.
The next stage involves a realization of the notation back into sound, which will be performed in a studio environment designed in collaboration with EMS in Stockholm.
This studio has been equipped with signal generators, filters and a tape recorder, mainly from the 1950's and 60's. In comparison to the digital studio used almost exclusively today, much of this equipment is noisy and inexact.
Using a reel-to-reel tape recorder I will record one tone at the time onto tape, then play it back and tune a new tone according to the notation until a sonic pattern that fits the ambition is created, and then record that.
Because of slight errors in the oscillator, inexactness of the tape recorder, and the human factor, this will obviously be an approximation of the exactness of the notation.
It is only through listening that the acceptable margin of error can be assessed.
In other words, the "correctness" may only be evaluated from the inside of the sound, not from the system alone and, obviously, to merely set the parameters to the defined values would generate a different result.

It is incontestable that there is an active mode of listening in most compositional practices and I am not proposing that the listening performed in this project is different in nature. 
Meanwhile, as was the case with saxophone-musician system described above, it is only partly correct to claim that it is only from within the sound that the evaluation can be performed in these various steps of the process.
The role of the listening in the various stages is connected to, and affected by, the larger system. The notation affects the listening, as does the equipment made to render the sound and the system in which pitches were chosen. This is where Bergson's method of intuition makes sense as a means to understand the artistic epistemology from within. By creating a system within which intuition and play can operate freely that it becomes possible to get an insight to the choices made and the biases that affected them.


* Final reflections
Following this reasoning sound is not a thing, not on object, that we listen to. It is by necessity a system of interrelated threads much larger than the actual sound by itself (if such a thing at all exists). To compose is to attempt to understand the trajectories of this system and each sound heard in this process will be intuited through the internal mobility of this system.
The method proposed by Bergson is, I believe, both interesting and useful when it comes to artistic practice in music and general practices of listening.
To point out that listening to music is immersive may appear ubiquitous, but due to the fields of technology and artistic practice in the studio merging together, putting focus back on the attempt to understand the object from within still  has some relevance, so long as what constitutes 'the object' is well considered.

Returning to the question of the epistemological nature of artistic practice in music and what shape and form it may have in the future, the proposed method is clearly not enough in and of itself.
Although it helps me to understand the material I am working with as well as the in time  process when making decisions about the next steps in the process, the specific knowledge in this practice lies in the ways these decisions are being made, not merely what material is being discovered.
A process that is certainly informed by intuition, and a process that may well to some extent take place within the intuitive analysis, but it is in the interaction between this, and the decision making /in the reflection upon these results/, that are specific to artistic knowledge in music.





* COMMENT Hur binda ihop?

1. Assuming that Bergson is right that the method of intuition is a valid means of perceiving the world--which can obviously be contested[fn:11]--the divide .

From the notation
the sound is created by setting off two oscillators and tuning the pitch by ear, using a physical knob controller until the right beating pattern occurs. It is clear that at this point it is not possible for me to enter into sympathy with the sound only without considering the rest of the process. Yet, it is possible to approach this sound and its context through intuition and explore many things about it, including its spatiality-

Though in line with some of the thinking about artistic research that was presented above, this is a quite radical proposition. The concept of actually being able to possess the object, or rather, its motion as Bergson will say, in itself makes possible a range of conceptions. But the distinction between the outside and the inside that is alluded to in this attempt to describe Bergson's theory should also be handled with care.

The examples above are specific in the sense that they may be generalised and that they exploit a certain impartial identity.
On some basic level it is possible to agree on the sound of the rainfall at night being precisely a sound of a forest without specifying which forest, becoming a Saussurian sound-image. But what is the mobility of an abstract sound approached from the inside? Again, the question of what it is I attempt to approach from the inside is raised. Can the sound be understood without also knowing something about /how/ it is produced? I believe that the method of intuition is particularly useful here. 
* Bibliography
#+print_bibliography: title: "Bilblio"

* Footnotes

[fn:17] Which is of course a valuable additional piece of the puzzle. 
[fn:16] A more in depth discussion on these topics may be found in /Aesthetics, Interaction and Machine Improvisation/ which also includes the impact of self organizing systems and AI [cite:@Frisk2020].  

[fn:15] It may be debated whether or not this particular improvising machine did act with some notion of intuition. Although it had some simple version of machine learning built into it one of the explicit goals was nevertheless to counteract intuition. Listen to sound examples x1 and x2 for an illustration.
[fn:14] Inner listening in the situation of improvising is the listening to the self [cite:@frisk12-improv] and the outer listening is to listen to the other /and/ to listen to the sound as a listener.

[fn:13] The project started in 2017 and was concluded in 2020 and was financed by NMH, Norwegian Artistic Research Programme, Norwegian Center for Technology in Music and the Arts (NOTAM) and Royal College of Music in Stockholm (https://nmh.no/en/research/projects/goodbye-intuition-1).
[fn:6] This is sometimes referred to as audioparity [cite:@Valle2018], or self-audioparity [cite:@Catena2021]. The latter refers to a recursive interaction between parameters of the sound. 'Spatial Sonorous Object' as discussed by [cite/text:@catena2022] is an analytical tool for understanding these possible transformation in a music analytical way.

[fn:9] The frequency of the beating between two simple tones is derived from subtracting the frequencies of the two tones $f_1-f_2 = b$
[fn:8] More complex auditory phenomena, like combination tones are discussed by [cite/text:@Aron2023] in the thesis /Phainesthai: Discovering Auditory Processes as a Tool for Musical Composition/ which goes into depth with the artistic possibilities with playing with acoustic phenomena that only occurs through the act of listening. For a description of the difference between combination tones and beatings, [cite/text:@helmholtz1954; p. 159].

[fn:7] This, then, is related both to the discussion earlier that the digital studio has a certain influence on the practice of composition, partly related to the fact that the computer has become a general instrument for which it is increasingly difficult to maintain originality. (in an attempt to change the conditions for the composition process in order to focus on the act of listening.)
[fn:10] I made a rough sketch for the basic layout of this composition in 1994 but never completed it then.

[fn:11] Structuralism and more specifically post-structuralism thinking has introduced alternate ways of thinking about some of these matters. 

[fn:1] In this case it may be helpful to bring up the terminology of /emic/ and /etic/ commonly used in ethnography and anthropology and other research fields. The /emic/ field research would here relate to the /inside/ perspective of the artistic researcher.

[fn:12] For a critical overview of the broad discussion and use of  Schaeffer's terminology, see [cite/text:@Kane2007].

[fn:3] Bergson's notion of intuition as a method has been both criticized [cite:@clair1996] and praised [cite:@deleuze88] by many thinkers ever since he first published on the subject, it has been explored affirmatively in post-colonial theory [cite:@Diagne2008] as well as feminist readings [cite:@Tuin2011].

[fn:2] For a broader discussion on this topic, see [cite/text:@frisk-ost13].

[fn:4] Intuition. (n.d.). In /Cambridge Dictionary online/. Retrieved from https://dictionary.cambridge.org/dictionary/english/intuition 

[fn:5] As Swedish artist Andreas Gedin has proved, sequential translations of a poem into multiple languages changes does not only offer different nuances but sometimes a completely different expression.
