# Created 2020-09-19 lör 14:26
#+TITLE: GI and the critique of a machine
#+AUTHOR: Henrik Frisk, henrik.frisk@kmh.se
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil pri:nil tags:not-in-toc toc:nil
#+INCLUDE: "./setupfile.org"
#+LATEX_HEADER: \usepackage{biblatex}
#+LATEX_HEADER: \usepackage[style=authoryear-ibid,natbib=true,backend=biber,hyperref=false]{biblatex}
#+LATEX_HEADER: \bibliography{/home/henrikfr/Dropbox/Documents/articles/biblio/bibliography.bib}

(setq line-spacing 0.8)
* COMMENT Litterature
  [[file:~/Docs/articles/biblio/bibliography.bib::Keyt1987][Keyt 1987: Three Fundamental Theorems Aristotles Politics]]

  [[file:~/Docs/articles/biblio/bibliography.bib::Knoll2017][Jaulin & Güremen 2017: Aristotle Arguments Political]]

  [[https://partiallyexaminedlife.com/2014/03/04/henri-bergson/][PEL on Bergson]]:

  - Bergson, handen avhuggen PEL 39.00
  - The Flux.
  - The severed hand. The hand transforms to a different thing. The hand is a hand if it can fulfill its function. Parts only exist in the way they relate to each other. Reality is mobility.

  https://lucian.uchicago.edu/blogs/elucidations/2012/08/10/episode-38-christopher-frey-discusses-aristotle-on-living-organisms-and-their-parts/

  [[http://classics.mit.edu/Aristotle/politics.1.one.html][Aristotele, 1. 2.]]
  since the whole is of necessity prior to the part; for example, if the whole body be destroyed, there will be no foot or hand, except in an equivocal sense, as we might speak of a stone hand; for when destroyed the hand will be no better than that. But things are defined by their working and power; and we ought not to say that they are the same when they no longer have their proper quality, but only that they have the same name. The proof that the state is a creation of nature and prior to the individual is that the individual, when isolated, is not self-sufficing; and therefore he is like a part in relation to the whole. But he who is unable to live in society, or who has no need because he is sufficient for himself, must be either a beast or a god: he is no part of a state. A social instinct is implanted in all men by nature, and yet he who first founded the state was the greatest of benefactors. For man, when perfected, is the best of animals, but, when separated from law and justice, he is the worst of all; since armed injustice is the more dangerous, and he is equipped at birth with arms, meant to be used by intelligence and virtue, which he may use for the worst ends. Wherefore, if he have not virtue, he is the most unholy and the most savage of animals, and the most full of lust and gluttony. But justice is the bond of men in states, for the administration of justice, which is the determination of what is just, is the principle of order in political society.

  [[http://classics.mit.edu/Aristotle/meteorology.4.iv.html][Aristotele, Meteorology IV, 12]]
  What a thing is always determined by its function: a thing really is itself when it can perform its function; an eye, for instance, when it can see. When a thing cannot do so it is that thing only in name, like a dead eye or one made of stone, just as a wooden saw is no more a saw than one in a picture. The same, then, is true of flesh, except that its function is less clear than that of the tongue. So, too, with fire; but its function is perhaps even harder to specify by physical inquiry than that of flesh. The parts of plants, and inanimate bodies like copper and silver, are in the same case. They all are what they are in virtue of a certain power of action or passion-just like flesh and sinew. But we cannot state their form accurately, and so it is not easy to tell when they are really there and when they are not unless the body is thoroughly corrupted and its shape only remains. So ancient corpses suddenly become ashes in the grave and very old fruit preserves its shape only but not its taste: so, too, with the solids that form from milk.

  [[http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0052%3Abook%3D7%3Asection%3D1035b][Aristotele, Metaphysics, book 7, 1035b]]
  But the body and its parts are posterior to this substance, and it is not the substance, but the concrete whole, which is resolved into these parts as into matter. Therefore in one sense these parts are prior to the concrete whole, and in another not; for they cannot exist in separation. A finger cannot in every state be a part of a living animal; for the dead finger has only the name in common with the living one.Some parts are contemporary with the whole: such as are indispensable and in which the formula and the essence are primarily present; e.g. the heart or perhaps the brain,2 for it does not matter which of them is of this nature.

  [[http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0052%3Abook%3D7%3Asection%3D1036b][Aristotele, Metaphysics, book 7, 1036b]]
  But the case is not similar; for the animal is sensible and cannot be defined without motion, and hence not unless its parts are in some definite condition; for it is not the hand in any condition that is a part of a man, but only when it can perform its function, and so has life in it. Without life in it it is not a part.

  [[file:~/Dropbox/Documents/articles/lib/Bergson1912.pdf::%PDF-1.4 (agl)][Bergson, metaphysics page 47]]
  analysis always operate on the immobile

  Aristoteles from /Categories/:
  "When things have only a name in common and the account of being [λόγος τῆς οὐσίας] which corresponds to the name is different, they are called homonymous … When things have the name in common and the account of being which corresponds to the name is the same, they are called synonymous"

  See: https://core.ac.uk/download/pdf/30817764.pdf

  ebib:sontag2013
  [[file:~/Docs/articles/biblio/notes/bibnotes.org::#Sontag1986][Sontag, S. (1986): Against interpretation: and other essays]]

* Method development, style and the nature of machine improvisation
** COMMENT Aristotele
   A useful mode of thinking about an improvising group is to take a holistic view, simply put as the whole is greater than the sum of its parts. However, this whole as well as the parts, are bound together in a very heterogenous manner and their inherent relations to each other are especially interesting in the case of a musician playing their instrument. The kind of instrument obviously plays a part, but in the case of an acoustic instrument its function while beeing played is very diferent from when it is not being played. One could possibly say that, say a saxophone, is becoming music, but the thought I would like to propse here is that it is not even that. It is little more than a collection of brass, cork and rubber. In the hands of an able musicina, however, it is no longer that, it is an extension of the musician's body in a way that transforms it. It is not an object but part of the limbs and hands of the musician. This can be compared to the famous passage in Aristotele's Politics where he says that a hand is no longer a hand if it is detached from the body. The nature of the hand is fully dependent on it's ability fo perform its task. 

   Playing an electronic instrument, one that has some kind of intelligence build in to it challenges this understanding of the musical instrument as an extension of the body in a number of ways. First, if the instrument is generative we may conclude that it is not dependent on a musician to play it. It could be used all by itself. Secondly, unless it has a very advanced UI for interaction, it will be very difficult to get to the point where the player will experience it as an extension of their body.

** Introduction
   One of the great challenges of any research project that spans over several years is to keep the project contained and avoid it from going into directions that are not fruitful for answering the questions posed. Yet, it has to be kept open enough to allow for unexpected findings in the fringes of the practice. This is especially true of artistic research projects that have a tendency to be interdisiplinary and soemtimes broad-brushed which in fact may be seen as one of the qualities of the field. The practice, in some cases also initself difficult to describe and contain, and its context are commonly the original bounds of an artistic research project and should participate in delimiting the field of research, at least at the outset. The main difficulty, however, is to know when a chosen path should be given up, or when to stay, and not give up, what appears to be hopelessly unfruitful trajectory and it is through method development that a field of research practice can develop.
   
  The main purpose of this paper is to explore the methods used in the artistic research project Goodbye Intuition from the point of view of the often repeated claim that artistic research is about acquiring knowledge from within the process, from the inside. This claim is often put forward in opposition to scientific research in which, in this extremely simplified model, the researching subject is not as often entangled with the object of research. Exactly what constitutes this priveleged /inside/ or how it is made accessible to an artist is perhaps less commonly addressed. On the surface it is principally a way to explain the central ambition of much artistic research, namely to research the artistic process, either by doing it while being engaged in it, or by working with documentation of the practice that allows the subject to reenter the process. The research performed in this /Goodbye Intuition/ has been performed in both of these modes, but it is primarily the work that has taken place in the actual artistic process that is the main concern for this paper.
  
  At a larger scale the definition of an outside/inside divider points to there being an ontological difference between the two: there is a knowledge in artistic practice that is only accessible from the inside, and another kind of knowledge that is primarily oriented towards analysis. The ontology of research on art, in a very rude simplification, is more concerned with the tradition--and how to break with it--than with finding the true nature of the music from the inside. This has to do with the particular status this /inside/ has, and the ways in which it is inaccessible except for the artist (why else is it important that artists do the research?). This may at first appear to be at odds with traditional scientific analysis since the object under scrutiny is also concurrently altered by the researcher: process and analysis is carried out simultaneously. In reality this view is likely to say more of a traditionally oriented view on science rooted in a positivistic attitude than it does of artistic research.
  
  The /inside/ is often mystified and given a shimmer of romantic light as the sight for true creativity and this convention should be addressed by artistic research but is sometimes reinforced by it. The main challenge lies in the lack of credible research methods with which the /inside/ can be investigated properly and this should be a focus area for artistic researchers for the years to come. This paper is an attempt to open up the discussion and lokking at the /inside/ as a metaphysical space that has a lot in common with any other human practice such as thinking, running or plainly observing. One of the advantages with this view is that the gap  between metaphysical experience and analytical knowledge is reduces by the way that it opens up for exploring anything in the world by placing oneself on the /inside/ of the object and experiencing it in time. The French philospher Henri Bergson and his theory of duration, metaphysics and intuition constitutes the point of departure when looking at the methods employed and developed in the project Goodby Intuition. Bergson is particularly interesting in that he is proposing a unified theory in which the possibility for an experience from the /inside/ is not a priveleged to only the artist, even though some types of information concerning ones own body would be more accessible to the subject, and that the same method would used regardless of if it is the artistic work or the artistic process that is the focus. This paper is not concerned with the results of the project, nor with the actual process other than in methodological terms. For this I would like to direct the reader to the paper citetitle:Frisk2020 citep:Frisk2020 as well as to other texts on this website.[fn:8]

** On the experience of machine improvisation
   The meaning of the expression /Goodbye Intuition/ is on the one hand, at least for a musician that has engaged in improvisation, easy to understand. There is something stifling about the need to be intuitive when music making so often is about knowledge, skill and experience. On the other hand, trying to make music together with other musicians without intuition would be extremely difficult, if not impossible. So, is the project /Goodbye Intuition/ then reducible to the attempt to raise awareness on the various roles that intuition may have in musical practice? No, the topic is more complex than that, and the discussion here touches on a wide range of topics that are all related to concepts like interpretation, communication, narrative, form and conctent, and style. At the center of the interrogation is an improvising machine developed during the course of the project, henceforth named KimAudo, or KA, whose primary purpose is to provoke the discussion between the project members and move it out of the various safe zones that all musiciancs build up for themselves. That being perhaps the practical side the machine also provided intellectual resistence. The quality of the possible music afforded by improvising with KA was hard to judge: By which standards can the output of an improvising machine be judged without also judging ourselves? Who has the power of authority on what is "good music", and how transparent are these roles? What is the actual autonomy of KA and how does it affect ours?

   These questions can then be expanded and used to further our understanding of much larger questions pertaining to the giant revolution in which data is the currency used to gain economic, social and political control. It is an enormous transformation where human labour is replaced by automated processes and transactions are even more abstract and opaque than ever. This change has been described and almost fetischised since a century in a way that makes it difficult to see whether it is the fiction that has produced the future or if the future simply was predestined in a way that made it easy for the science fiction narrative to project it. As the theory of the worlds predestination also disallows free will, the most rational explanation appears to be that the present is so influenced by culturally iconic descriptions of the future produced in the past, that these are reproduced. That these commonly has had a negative connotation, such as Skynet created by Cyberdyne Systems in the Terminator movies, or the surveillance society of Orwell's Nineteen Eighty-Four may not have mattered. The benefits may still appear to be greater than the risks. This discussion is obviously closely related to the huge topic of artificial intelligens (AI). AI in music production has also a long history, and specific technologies have been created for different reasons and with different purposes for decades. AI is already used in many areas of music production: audio processing plug-ins, composition tools, analysis tool and many other types of software explore different kinds of machine intelligence in order to assist musicians to better perform their tasks. To distinguish what part of the result is actually the outcome of human rather than machine intelligence, is not a distinction that is easily drawn, nor is it necessarily an interesting one. As long as the intelligent machine has been created by humans the distinction is only one in time where the AI can be seen as a delayed action determined by a human programmer. This may not be easily detected as it is a feature of connectionist strategies for artificial intelligence that the structures that guide them are hidden.

   The use of technology in artistic practices, however, can have a range of different objectives. First, from a general standpoint one may argue that art should engage in available technologies for the simple reason that this contributes to our understanding of its social and cultural impact. Though this general notion is sometimes contested, most famously by Heidegger who instead warned about the ways in which technology frames the human capacity  citep:heidegger93, it may be considered equally reasonable to claim that AI should be a field for artistic exploration. Secondly, from the point of view of innovation, it has been seen in the past that artists' use of technology push the boundaries for what is possible citep:harris1999. Although this has arguably been true, the resources that the multinational technology and media industry now control, along with the increased complexity of the technology, make it more difficult for an independent artist, or even an institution or a university, to invent methods of production that can compete with the powers of these companies. The artistic qualities in and of themselves may be uncontested, but as far as creative power is concerned the playing field has changed. Thirdly, the challenge to create a machine that is able to compose music with the same level of integrity, witfulness and inspiration as that of a great musician may be seen as a test of the potentiality of the technology. A machine that can compose music is likely to be able to perform a whole range of tasks with a high level of proficiency. However, unlike, say, a self driving car, it is difficult to fully grasp the (economic) value of such an achievement. There is an underlying ethical dilemma that has impact on the whole field of AI, also in the field of music. The emergence of AI depends on designers and programmers that create the systems and as has been shown through studies such as citet:snow2018 technology as a valueless blank slate should be contested. With an increased use of intelligent technology in artistic practice, there is a broadening of the practice where not only the programmer of the software but also the designer and manufacturer of the hardware should be included.
   
   A rudimentary machine such as KA, an automated improvisor, may have nothing directly to say about the dystopic development of an economy governed by data access and acquisition, but it nevertheless opens up a window to the question of an ethics of communication technology in a way that is of relevance for the wider discussion of this field. The sensibility of a musician improvising  with another musician is an activity that is still exceptionally difficult to model in a machine, and one that we still know very little about. It can by itself be seen as the critical thing that still separates us from machines and that cannot be reduced to a statistical or heuristic model. Focussing in on this makes it possible to study the interaction between musicinas and this kind of data may prove to be invaluable in understanding how to construct ethically sustainable human-machine systems. One example of this that the method used in GI allowed us to explore is the various ways that we as musicians anthropomorphise the machine and the lengths to which a human musician is willing to go in order to attempt to understand the other. Even if the other is a machine. I will discuss this in more detail further on in this text, but for now it will suffice to say that even though the willingness to sympathize with the co-musician, the particular relation that a musician has to whoever, or whatever, they are listening to and interacting with still has an impact. The other is rarely just a utilitarian object, or an object for interpretation. At its best musical interaction is one in which the negoatiation is constantly taking place. This in order to understand the other, the subject with whom one is improvising, and this understanding does not require knowing what or who the other is, it rests on an ethics of listening, on the willingsness to engage. The main interest may be said to be focused on the question on what the music /does/, rather than what it is. Far from all musical interaction fulfills this objective but all possible interactions have the potential to do so. For these reasons music specifically, and artistic practice in general, are useful practices to study the future impact on the communication with machines, or lack thereof.

   Meanwhile, to return to the introductory remarks on the ontological status of artistic research, a useful, albeit not conclusive, definition for what artistic research in music is could be summarized as in the following: The study of what artistic practice does based on the assumption that the /doing/ in the practice rests on a knowledge that may be communicated. There is a some empirical justification in the assumption that the /doing/ of the music has an epistemological impact on our wellbeing. Judging from the many testimonies that music has the potential to move us, engages us, and that it has a deliberating effect on us, and it can make us angry or happy, sad or euphoric, it is not difficult to understand the curiousity in finding out what exactly it is that arouses our sensibilities and emotions. In other words, one of the primary drives behind artistic research is not /if/ there are emotional responses connected to practicing and listening to music, but rather how these responses are established.

** COMMENT Not sure
   I have discussed the necessity for taking this kind of musical relation seriously and abandon some of the mer prevailing modes of historical and musicological analysis in the past and some of those threads will be briefly revisited here 

   And following this there are at least two intriguing questions that arise:

   1. What, if any, are the artistic and ethical responsibilities in the development of AI in music? What are the implications on aspects such as copyright?
   2. If musical machine intelligence is truly possible, to what extent are we prepared for it to develop its own musical aesthetics? After all, a body less musician is likely to develop a different musical conception than a human embodied musician.

   Or, to summarize: What are the artistic implications of AI?

** Method development in GI

   French philosopher Henri Bergson sought to address the problem of what possible knowledge one may have of the world exterior to oneself and in this effort he defined the method of intuition. It may appear almost defensive to get into an indepth investigation of the term /intuition/ in a project that that has attempted to do away with it altogether. In the way that it is used in the title of the project intuition points to the ordinary use of the word which can be summarized as the "ability to understand or know something immediately based on your feelings rather than facts."[fn:2] Though not completely unrelated, Bergson's notion of intuition is rather different and for this reason also of interest for the present discussion. Intuition as a method can be useful and will by necessity include also other modes of thinking than the immediately present status of our more common view of intuition. The point here is not to give a full account of Bergson's philosophy, nor of his method, but, in order to better understand its kinship to the method development in GI, and the actual work that was performed within the project I will make a brief overview of what it entails. However, anyone with a particular philosophical interest should go to the source for more information. Furthermore, the method contains certain idiosyncharsies that may or may not work to the full extent in the frame of the other theories presented.

   To understand intuition in the a Bergsonian way it may be necessary to contrst it with other definitions of intuition. The more general interpretation of intuition relates to the things we do without thinking about them; the intuitive knowledge that something is wrong or dangerous. Almost as if there is an automated system that gives us information through consiousness about what is going on in the world around us. In phenomenology intuition has a slightly different meaning where first-person knowledge can be acquired through intuition whereby an object can be /intuited/. Kant's distinction between concept and intuition is clearly a point of departure for Bergson's argument here and his use of the word is even further bemusing.

   Bergson defines two incommensurable ways to approach an object: either from a point of view through signs and concepts, a /relative/ perspective, or through entering into the object, exploring it from the inside: an /absolute/ apprehension. This second method is achieved by entering into sympathy with the possible states of the object which allows him, as he describes it, to "insert myself in them by an effort of imagination." [[citep:Bergson1912][p. 2]] This, he continues, enables him to "no longer grasp the movement from without, remaining where I am, but from where it is, from within, as it is in itself." [[citep:Bergson1912][p. 3]] The latter is what he refers to as the /absolute/ knowledge: "the absolute is the object and not its representation, the original and not its translation, is perfect, by being perfectly what it is" [[citep:Bergson1912][p. 5-6]]. This is a quite radical proposition, in contrast to the dominant theories of mediated perception that most notably Kant had put forward. The concept of actually being able to possess the object, or rather, its motion, in itself makes possible a range of conceptions.

   The example that Bergson gives us to better understand what he means by representational knowledge is a photographic model of a city. One where all angles and all surfaces have been photographed and documented to achieve something similar to a street view that online map programs sometimes offer. Exploring such a model can obviously  never be equated with the experience of being in the city. Another example brought up is the translation of a poem into many languages[fn:1] and how it can give the reader a good idea of its meaing, sometimes with even more details, but it will never form a complete image and would "never suceed in rendering the inner meaning of the original" [[citep:Bergson1912][p. 5]]. One of the central propositions is that analytical knowledge is always a reduction of the thing being analyzed. /Analysis/ is what might be referred to as an empirical understanding to which a defining aspect is its reductive force, dividing the objects into ever smaller elements that eventually resonate more with what we already know than with the thing we analyze. The thing analyzed then becomes merely a function of the perceiver rather than an object in and of itself. Auch an analysis creates representations that are discontinuous in the flow of time:

   #+begin_quote
   In its eternally unsatisfied desire to embrace the object around which it is compelled to turn, analysis multiplies without end the number of its points of view in order to complete its always incomplete representation, and ceaslessly varies its symbols that it may perfect the always imperfect translation. It goes on, therefore, to infinity. But intuition, if intuition is possible, is a simple act. [[citep:Bergson1912][p. 8]]
   #+end_quote 
   The /absolute/ is given from this /intuition/ and an /intellectual sympathy/ with an object that allows one to perceive its unique qualities beyond words. Hence, the /perfect absolute/ should be understood in relation to the imperfect analysis, and metaphysics is what allows one to experience what it means to have an intuition of the object at hand. To Bergson, the science of intuition is metaphysics, and metaphysics is "the science which claims to dispense with symbols" [[citep:Bergson1912][p. 9]]. Rather then engaging in representations of objects by means of symbols and concepts, we are urged to understand the object from within. This may be compared to self-reflection and Bergson describes the various strata of introspection that he goes through moving from the outside towards the centre of the self. A protecting "crust" via memories down to the motor habits that are both connected and detached from memories and perceptions. But at the core, Bergson describes the continuous flux of a concatenation of states, the beinnings and ends of which are merged together and extend back and forward. The metaphor used here is that of a coil constantly unrolled and rolled up again, although, admittedly, this is not very close to the truth. There are no two identical moments in consciousness and the rolling up of the coil may thus be misleading. Even going back in memory to a past event invades that memory with all the present and past events. This evokes the image presented in his earlier work, [[citetitle:bergson91]], of the cone whose tip is moving over a moving plane, and where the point of the cone represents the present and the cone itself the accumulated memories and experiences: 

   #+begin_quote
   The bodily memory, made up of the sum of the sensori-motor systems organized by habit, is then a quasi-instantaneous memory to which the true memory of the past serves as base. Since they are not two separate things, since the first is only, as we have said, the pointed end, ever moving, inserted by the second in the shifting plane of experience, it is natural that the two functions should lend each other a mutual support.  So, on the one hand, the memory of the past offers to the sensori-motor mechanisms all the recollections capable of guiding them in their task and of giving to the motor reaction the direction suggested by the lessons of experience. It is in just this that the associations of contiguity and likeness consist. But, on the other hand, the sensori-motor apparatus furnish to ineffective, that is unconscious, memories, the means of taking on a body, of materializing themselves, in short of becoming present. [[citep:bergson91][p. 152-3]]
   #+end_quote

   The sensory motor-habits are informed by memories through which they will be guided to do the work they need to do, and because no single memory is ever stable--it is always altered by the present in the interaction between what Bergson refers to as the "pointed end" and the past memory--the present experience is continously altered by past experience which in turn is influencing the present. Hence, the general understanding of intuition, as an action guided by feelings rather than by facts, may be said to still hold true, but a comparison quickly becomes very difficult without defining what constitutes a /feeling/ or a /fact/. This is, however, not the primary purpose of this text, but what is of interest is the connection between sensori-motor mechanisms and past experience, and the fact that this connection is not only going one-way, from memory to habit, but also from habit back to memory. Embodied memory is in a changing flux and in constant interaction with experience and habit. There is an inclination to understand learned behaviour, such as playing an instrument or lifting a glass of water, as an act that is settled, almost as if it was independent of the conscious mind. To this there is a whole range of relevant research in  embodied cognition and consciousness that is out of scope to the topic of this essay, the purpose of which is mainly to look at intuition as a method for a better understanding of musical interaction with electronic instruments.

   It is in thinking about embodiement and motor-habits that Bergson's understanding of what an intuition can be is perhaps best understood. If I move my leg or my hand, or even if it is my own body that is moving, I can only access the information that guides this movement through intuition. Analyzing the movement fails to understand it completely since the analysis only pins the movement to a sequence of states: first the arm was here, then here, then there. The actual change, the mobility or, as Bergson would put it, the duration, is only understood from the intuition. Furthermore, it would be wrong to say that the mobility is merely part of an automated task such as moving the hand, because any new experience within the movement, and any past experience will introduce change:

   #+begin_quote
   When you raise your arm, you accomplish a movement of which you have, from within, a simple perception; but for me, watching it from the outside, your arm passes through one point, then through another, and between these two there will be still other points; so that, if I began to count, the operation would go on forever. [[citep:Bergson1912][p. 6]]
   #+end_quote

   I have learned to move my arm but any new information about what I can do with it will add to my arm-moving-knowledge, and intuition is the modality through which this process is carried out. For the observer that is able to observe the thing from the inside, intuitively, there are no states, only duration and mobility informed by experience and knowledge. 

   Conceptual knowledge is reached by way of concepts that represent the thing of which knowledge can be said to be had. These, says Bergson, have the "disadvantage of being in reality symbols substituted for the object they symbolize" [[citep:Bergson1912][p. 17]], and as such they demand very little of us. Furthermore, each concept merely expresses a comparison between itself and the object that resembles it and by way of this resemblance we imagine that by taking concept after concept and putting them side by side we are actually reconstructing the analyzed object. Through analysis we create concepts and symbols that allow us to structure and organize the world in a systematic manner. If metaphysics, then, is a serious science by which the world can be understood and experienced rather than just a mind operation, "it must transcend concepts in order to reach intuition" [[citep:Bergson1912][p.21]].  

   The methods of analysis and the method of intuition proposed by Bergson has important relevance to the field of artistic research in general and to the project /Goodbye Intuition/ specifically, though perhpas less because of the project's title and more due to the method development has evolved over time. One of the defining ideas for artistic research is that there is a difference between knowledge that has been acquired from observing an artistic practice, and knowledge that is the result of taking part in the artistic practice. A common metaphor used to described this difference is to see the former as knowledge from the inside and the latter as knowledge from the outside--problematic in itself as the concepts of /inside/ and /outside/ are difficult to determine and rarely stable. In S\{o}ren Kj\{o}rup's contribution to [[citetitle:biggs10]] he comments on what may be the difference between the outside and the inside perspective and writes that:

   #+begin_quote
   if artistic research is supposed to be different from all other kinds of research, it is natural to focus on the artist as the researcher, and what is specific for the artist is he or his priveleged access to her of his own creative process. [[citep:kjorup10][p. 25]]
   #+end_quote

   This "priveleged access" may be seen as an alternative to knowledge mediated by symbols and concepts but a particular difficulty lies in the problematic relation between traditional epistemology and this inside perspective. One of the recurring themes in the early discussions on the identity of artistic research was, and still is, what kind of knowledge artistic knowledge and methodology could lead to, and what kind of relation it would have to other kinds of knowledge. How can artistic research as a discipline make sense "in a way that does not subordinate [it] to other activities of thought taken to be superior modes of knowing" [[citep:johnson2010][p. 150]]? Johnson further stresses that the potential in this kind of knowing lies in the experience rather than empirical knowledge:

   #+begin_quote
   The /research/ here would not be geared toward the accumulation of empirical facts or propositional knowledge, although that might be part of the story. Instead, /arts research/ would be inquiry into how to experience and transform the unifying quality of a given experience in search of deepened meaning, enhanced freedom, and increase of connections and relations. [[citep:johnson2010][p. 150]]
   #+end_quote

   Henk Borgdorff is an other often mentioned reference and has been one of the key figures in defining the development of European artistic research. His claim that "it is not formal knowledge that is the subject matter of artistic research, but thinking in, through, and with art" [[citep:borgdorff2012][p. 143]] has gained traction in the field in that it attempts to put the focus on the activity of creating art. It is possible to contest the proposed opposition between formal knowledge and what may be extracted from thinking in, through or with art, but what Borgdorff is pointing to is that there is a possibility for a "special articulation of the pre-reflective, non-conceptual content of art." [[citep:borgdorff2012][p. 143]] This may be understood as leaning on a Kantian notion of aesthetic experiences as pre-conceptual, again invoking a free-play of imagination, with the consequence that the kind of mediation through conceptual and symbolic representation that characterize most forms of knowledge is sidestepped. This creates a number of conflicts, the most obvious of which is the question of what kind of knowledge we are dealing with if the art (practice) is understood directly, in and of itself, and how it can be represented in a stable manner. The question at hand, then, is how can this unmediated experience be useful to the artistic researcher and, more importantly, how can it be described in a way that makes the results relevant for other researchers?

   This is, without a doubt, one of the more pressing and still controversial questions in artistic research and the point on which this discipline is most oftenly criticized, but it is not my aim to address it directly here.[fn:3] Instead, my focus is to put Bergson's method of intuition in the context of the method development of the project /Goodbye Intuition/ and how I have approached the method in my attempt to understand what KA is and can be in an artistic practice. Bergson's method of intuition may contribute to showing that not only is it possible to gain formal knowledge from artistic research in a methodologially sound manner, but also, although artistic research has much to contribute the difference compared to other fields of knowledge production is perhaps less significant then what is commonly believed.

   Bergson's description of the two profoundly different ways of knowing a thing, through /relative/ and /absolute/ knowledge may at first adhere to the idea of non-conceptual knowledge, but as was described above, it is in fact in starch contrast. According to Bergson it is in every way possible to achive absolute knowledge about a thing through the method of intuition and by way of /sympathy/ that allows for an understanding from the /inside/ of an object. Without this point of view one is left with the option of analysis and regardless of how many different perspectives this analysis is performed from, it will never fully capture the true motion of the object. Yet, this is the faculty of knowledge that is often seen as the principle mode of thinking. The contradictions between this and the intuitive, absolute, knowledge that Bergson is arguing for:

   #+begin_quote
   arise from the fact that we place ourselves in the immobile in order to lie in wait for the moving thing as it passes, instead of replacing ourselves in the moving thing itself, in order to traverse with it the immobile positions. They arise from our professing to reconstruct reality--which is tendency and consequently mobility--with percepts and concepts whose function it is to make it stationary. [[citep:Bergson1912][p. 67]]
   #+end_quote

   One central aspect of this distinction between analytical and intuitive knowledge is that the intuitive can always develop concepts and form the basis for analytical knowledge, whereas it is impossible to reconstruct mobility from fixed concepts. An analysis may result from intuition, but intuition cannot arise from analysis. The analysis is performed on one particular state of the duration and from multiple analyses it possible to think that the mobile may be reconstructed by simply adding the different states together. This is however the critical point that Bergson objects against. It is only through intuition that the variability of reality may be fully experienced as mobility, whereas the element, or the state, is the opposite. It is a frozen frame and an isolated view of reality. The error in thinking that reality may be accessed through analysis, claims Bergson, "consists in believing that we can reconstruct the real with these diagrams. As we have already said and may as well repeat here--from intuition on can pass to analysis, but not from analysis to intuition" [[citep:Bergson1912][p. 48]]

   One important aspect of this is how the whole relates to the parts. According to Bergson dividing a whole up in parts is possible, but reconstructing the whole from the parts is utterly impossible. Again, taking the example of the moving hand, it is possible to analyze its movement as a successsion of states, but impossible to reconstruct the motion from these states. This holds true regardless of the precision and resolution of the collected frames--there will always be a space between current and previous frame. This corresponds to the Aristotelian view that the whole is always prior to the parts and that things can not be reduced to parts without loosing a significant part their identity.[fn:4] The hand is not a hand, except by name, unless it can perform the function of a hand. If the hand is removed from the body, the hand is no longer a hand although by its appearance it is still a hand:

   #+begin_quote
   What a thing is always determined by its function: a thing really is itself when it can perform its function; an eye, for instance, when it can see. When a thing cannot do so it is that thing only in name, like a dead eye or one made of stone, just as a wooden saw is no more a saw than one in a picture. The same, then, is true of flesh, except that its function is less clear than that of the tongue. [fn:5]
   #+end_quote

   In essence this means that the hand as an object is less than the hand that also performs its function, and that the hand, when still a part of the body, obviously stretches out beyond the merely physical hand; it is connected to the arm with muscles and tendons and to the brain with nerves. This is true of most instruments that has a specified function. A hammer can be said to only be a hammer when it performs as a hammer, and a piano is only a piano when it is performed by a pianist. The hammer as a sign is signified by both the physical hammer in general, and the hammer that performs a function, although the latter, of course, is dependent on a whole range of other things and energies in order to perform. From a more personal perspective, for me as a saxophonist, my saxophone similarily is perhpas primarily an object--a saxophone, or a musical instrument. However, once I pick it up and start playing it, it is a rather different thing. In my hands it becomes an extension of my body similar to the hand, primarily as a result of the many hours of practice that I have performed and as such it becomes an extension of my musical ambition. But as soon as I put it down it is nothing more than a piece of brass again and as such it is as useless as the severed hand.

   Though it may at first be counterintuitive to look at a musical instrument as two different kinds of objects depending on if they are being played or not, this fact is further complicated by the fact that instruments also hold socio-cultural meanings that are independent, but related, to the music they are used perform, multiplying their possible signifiers manifold. With electronic instruments it is even more complex due to the fact that they commonly lack a physical interface that has a clear relation to the core engine of it that makes the sound. If the instrument is also intelligent in some way, that is, if its musical output is greater more than what it is given as input, the relations can become very obscure. In other words, while the musician playing an acoustic instrument quite easily becomes one system in which it is possible to enter into and gain an intuitive understanding of, that is, understnading it from within, for the electronic instrument this is much more convoluted. It is not much help to approach the electronic music instrument as an object independent of the person playing it. The issue for this discussion is consequently that it is not enough to perceive the movement from within, it is first necessary to see the full context of the system for which the intuition is desired and then move inside of it. If not it will mainly only be possible to perform an analysis of the parts which is always an incomplete picture, notwithstanding that only analysis rather than intuition is possible.

   To do what Bergson asks us to do, to move inside an object to fully understand it and its mobility, its duration, it is important to understand what kind of object it is we attempt to move inside. As mentioned earlier, this is far removed from the Kantian view of the external world as something unreachable and impossible to have any true knowledge about. If I wish to understand what it means to play the saxophone, it is not the saxophone I need to enter inside, nor is it merely my own ambition with playing an instrument, I need to enter inside the larger performative system of both myself and the instrument. This unity is what creates the conditions for expression and musical creativity and analyzing the parts by themselves will only tell us what the parts are capable of and even if we manage to inside, say the saxophone, we will only be able to understand its motion as an independent object. Only if we see the whole as an integrated system, and only if we manage to get on the inside of this system, will we be able to fully understand it and the way it is conditioned by its motion. It from this analysis we then can proceed to analysis.

   But what does it mean to get on the inside of a system such as a computerized instrument, the boundaries of which are seemingly unknown? An electronic instrument that, for example, is connected to the internet and that continously fetches information that influences its output in live performance is a very different thing from an acoustic musical instrument. Especially so if the mapping of the physical input from one or several performers is hidden from both performers and audience, or even remapped during the course of the performance. What is the embodied relation between such an instrument and the performer that allows for it to be understood as a unified system? While the saxophone can be said to cease to be the independent object 'saxophone' once it is picked up and played on, with the typical computer based instrument in the shape of a software running on a computer, which is what KA is, at what ways can the software instrument be embedded in a similar way?

   An argument can be made is that for self-playing systems involving some kind of artificial intelligence, the system that rules the musical outcome is much larger than what may be experienced at first. What I see when I start such a program on my laptop, what I experience to be the system in play is just myself and the computer, where in reality it may involve previous input and output and the programmer's various positions and biases. The programmer is obviously concealed in this system, detached in both time and space, which makes it difficult to fully understand their impact. In a sense the electronic musical instrument is a system which is by some degree larger and more elaborate than the previous example with a an acoustic instrument. Furthermore, many electronic instruments, by their immediate relation to engineering and science lend themself naturally to an understanding based on analysis rather than intuition, which enforces their role as mere tools. The development of musical artificial intelligence and advanced electronic instruments has obviously profited from this and has clearly contributed to their fast development. At the same time there is a great interest in interfaces and systems that convey a certain stability that encourages long term development between performer and instrument. In other words, whereas quick development serves its purpose at several stages of the design of the instrument, it may become an obstacle when trying to understand it in a musical context and as an integrated part of a larger system.

   Clearly, part of the challenge is understanding the interface between musician and an instrument, and part of it is understanding what type of electronic instrument is under scrutiny. My attempt here is not to make a general theory of the various types of electronic instruments that could be of interest to such a study, but instead to mainly focus on a particular case, the KA of /Goodbye Intuition/. Nonetheless it should be noted that other types of electronic instruments, such as a modular synthesizer, for example, that holds a whole range of possible modes of engagements, allow for quite a different set of possibilities than what a piece of software does that is completely lacking a physical interface. I believe that it is possible to approach also other kinds of systems with the same method and that this could contribute to furthering the knowledge about the musical opportunities of electronic instruments.

   The question now is, how may it be possible to achieve the kind of /sympathy/ that Bergson is referring to that allows for an interior experience of system that is the combination of the performer and the instrument? He describes it in a way that have a great deal of resonance with artistic practice when referring to the /absolute/ movement and the states of mind that gives him access to the interior:

   #+begin_quote
   I also imply that I am in sympathy with those states, and that I insert myself in them by an effort of imagination. Then, according as the object is movin or stationary, according as it adopt one movement or another, what I experience will vary. And what I experience will depend neither on the point of view I may take up in regard to te object, since I am inside the object itself, nor on the symbold by which I may translate the motion, since I have rejected all translations in order to possess the original.[[citep:Bergson1912][p. 2-3]]
   #+end_quote

   # Such an instrument can also become a part of the duration of whoever is playing it and thereby allowing one to get on the inside of it, or rather, on the inside of the system of the musicians and KA. This, however, requires a process that is consistent and stable.

   Since I have been an active part in many of the workshops and laboratories performed by the group Goodbye Intuition from the initiation of the project in 2017, I am obviously involved in, and influenced by, any findings and discussions. In the workshop in Stockholm in February 2019 I also played with the group, but in general my role has been that of an external partner, or critical friend.

** Method development in Goodbye Intuition
   Goodbye Intuition is an artistic research project that methodologically is relatively close connected to the stream of artistic research projects in neighbouring fields of practice over the last decade. The Swedish projects Music in Disorder[fn:6] and (Re)Thinking Improvisation [[citep:friskostersjo2013]] both shared the kind of discursive based methodologies with GI. These, which Östersjö and myself have developed further using stimulated recall, have proved to be rather effective to surface the knowledge embedded in musician's practices. The general idea is to allow for a safe space where the musicians involved in the artistic practice under srutiny are allowed to discuss what they did, would have liked to do, and did not like that they did, and to open for the possibility to rethink, or redo the performance, starting it anew so to speak, after which a new round of reflection starts. Commonly, and in order to increase the possible strata of reflections guests are invited to the sessions that can introduce new and alternative perspectives.
   In GI the purpose was not merely to discuss the performances and interactions of the group memebers but specifically to investigate in what ways the improvising machine could participate in the improvisations. Perhaps  more importantly, the purpose was to see how the machine could disrupt the improvisational motor-habits and give rise to aesthetically different music than that of the group's usual performances. As already mentioned, these sessions were usually carried out with one or more external guests in the room and more often than not, with only one musician at the time playing with KA. In most sessions that I was part of there would have been a new set of features in KA that had to be discussed and a lot of the introductory discusssions commonly circled around the core issue for the project relating to the core research questions:
   
   - How do we improvise with "creative" machines, how do we listen, how do we play?
   - How will improvising within an interactive human-machine domain challenge our roles as improvisers? 
   - What music emerge from the human-machine improvisatory dialogue?

There is clearly no way to quantitatively compare a with-machine-improvisation to a without-machine-performance, so an investigation directed towards answering these questions has to be carried out qualitatively. The quoted work "creative" in the first research question points to the fact that there is no real creativity present within the machines performance since its activities are governed mainly by statistical analysis of the material being fed to it. Hence, the only true creative act is that performed by the human improvisor.
     The method, to work through the different stages of development of KA through conversation is only one of many possible means to apporach this task. Conversation on improvisation is of course a discourse interwoven with aesthetical judgements, social practices and stylistic preferences, but if the goal is to reach beyond language and approach the music, in Bergsonians terms, from the inside, conversations and discussions about the music is an effective method. However, it would likewise be fair to argue /against/ using discourse, because language by its symbolic nature may be seen to disguise the inside rather than relieve it. Similar to how Roland Barthes describes the photograph as "always invisible: it is not it that we see" [[citep:Barthes1980][p. 6]] the purpose is to remove the layers of signification that surrounds the music and understand and analyze it for what it is, rather than what it could have been, or should have been. In this case the discourse on improvisation is what hides away the potentiality of the development of the music, and it is only through unwrapping this discourse, through discussion paradoxically, that the concealed qualities may surface. This is by no means simple and it requires time and patience and it is important to appreciate all the different kinds of discussion on music that may take place.
     Susan Sontag, in her still highly topical citetitle:Sontag1986, points to the dangers of interpretation to excavate and destroy the thing interpreted in search for its true and inner meaning [[citep:Sontag1986][ch. 3]]. This kind of interpretation has an ideological undertone that organizes the contents in a way that fits the purpose of the interpeter and thus, events "have no meaning without interpretation" [[citep:Sontag1986][ch. 3]]. She continues: "To interpet is to impoverish, to deplete the world--in order to set up a shadow world of 'meanings.' It is to turn the wold into /this/ world" [[citep:Sontag1986][Ch. 4]]. The focus, according to Sontag, should be on what art /is/ rather than what it /means/. This should precisely also be the focus on the discursive method proposed here and that was carried out in GI.[fn:7] The main point is not to explain what is or should be going but to make it possible to move inside it, to observe the ways in which it is ticking from the inside, so to speak. In order to avoid "intuition", that is, the automated responses of the motor-habits that are the result of years and years of training it is necessary to get on the inside of these habits and experience them from the inside, to be in the same duration.
     An example of how the disruption of discourse can create access to the material reality of the artwork is Annie Dorsen's /Hello Hi There/ citep:dorsen2010. The work is derived from a televised debate between Noam Chomsky and Michel Foucault the voices of whom are rendered by two chat bots. In a single stroke the discursive power balance of the two men is neutralized and given a comic nature, although som of the utterings they make is clearly derived from the two philosophers thinking. Annie Dorsen took part in one of the GI workshops in which we discussed similar topics which in turn made it possible for the group to dwell even deeper into their own deconstruction of the language of the playing.
     One of the principal difficulties, however, is to get on the inside of a mchine. Even if we were given a rudimentary idea of the logic of the system it took us a long time to understand how it worked in a way that would make it possible to predict--predict in the wide sense of the word--the output. This is very odd because playing with a human improvisor operating in the same general genre, although I will not be able to predict exatly what they will play, I will quite quickly have a basic idea of it.



     against Interpretation -> against motor-habits
     to understand motor-habits -> intuition
     interpretation disguises the object as it is.
     intuition can get us to the object as it is
     
** COMMENT from os
   As was mentioned in the introduction, in GI there is a strong aspect
   of anthropomorphism that becomes obvious in a number of situations. KA
   is often talked about as "trying to do" something, being in a
   particular state of mind, or consciously going in a particular
   direction. On the one hand this is obviously false, KA does not have a
   consciousness in the way implied by this way of talking. It mainly
   listens to a few parameters of its input and records sound (a more
   detailed description is found below). On the other hand it says
   something about its output that leads us to anthropomorphise. This can
   be seen as a consequence of the close relationship between traditional
   musical practice and interactive music practices, as is pointed to by

   #+begin_quote
   Interpreting the attitude of the performer of a composed
   instrument with the help of categories from the traditional way
   music is created leads to various metaphors such as that of
   playing a musical instrument, conducting an orchestra, playing
   together (ensemble) with a machine, acting as a one-man
   band. \citep[140]{Schnell2002} 
   #+end_quote


   The use of technology in art practices can have several different
   objectives. From a general standpoint one may argue that art should
   engage in available technologies for the simple reason that this
   contributes to our understanding of its social and cultural
   impact. Though this general notion is sometimes contested, most
   famously by Heidegger who instead saw the opposite, that the
   technology frames the human capacity
   \citep{heidegger93},\footnote{Aden Evens has written an interesting
   commentary on it in the digital age \citep{evens05}.} there are
   good reasons to evaluate uses of technology through artistic
   practices. From the point of view of innovation it has been seen in
   the past that artists' use of technology push the boundaries for what
   is possible \citep[e.g. ][]{harris1999}. Although this has arguably
   been true, the resources that the multinational technology and media
   industry now are in control of makes it increasingly difficult for an
   independent artist, or even a university, to produce artefacts that
   may compete with the RD budgets of these companies, although the
   artistic qualities in and of themselves may be uncontested.


   # #+begin_quote
   # This means that analysis operates always on the immobile, whilst intuition places itself in mobility,or, what comma to the same thing, in duration. There lies the very distinct line of demarcation between intuition and analysis. The real, the experienced, and the concrete are recognized by the face that they are variability itself, the element by the fact that it is invariable. And the element is invariable by definition, being a diagram, a simplified reconstruction, often a mere symbol, in any case a motionless view of the moving reality.

   # But the error consists in believng that we can reconstruct the real with these diagrams. As we have already said and may as well repeat here--from intuition on can pass to analysis, but not from analysis to intuition.
   # #+end_quote

   ather than relying on merely the /analysis/. The case that Bergson brings up as an example of /intuition/ and that resists analysis in the scientific sense is ones own personality "our self which endures" [[citep:Bergson1912][p. 9]].

   that makes it possible to access it

   whatever is not an intuition "falls within the province of /analysis/" [[citep:Bergson1912][p. 7]]


   It is important to stress that Bergson is focusing here on 



** Understanding improvisation{
** What does music do beyond without interpretation?
** Acknowledgments
** Biblography
   \printbibliography
* Footnotes

[fn:8] See https://www.researchcatalogue.net/view/411228/424771 (visited on October 12, 2020)XS 

[fn:7] It should be pointed out that this is not related to (Critical) Discourse Analysis since we did not attempt to do any systematic analysis of the discourse, but many of the core aspects of discourse analysis holds true also here in that the discourse here is a social practice, and the way we talk about e.g. improvisation is, as has already been mentioned, to a high degree shaped by the larger discourse on music.

[fn:6] See http://musicindisorder.se/ (visited on October 8, 2020)

[fn:5] See Aristotele, /Meteorology/ IV, 12 

[fn:4] See Aristotele /Politics/, \RN{1}.2 and /Metaphysics/ \RN{7}, 1035b.

[fn:3] For a more complete discussion on this topic, see citet:frisk-ost13.

[fn:2] Intuition. (n.d.). In /Cambridge Dictionary online/. Retrieved from https://dictionary.cambridge.org/dictionary/english/intuition 

[fn:1] As Swedish artist Andreas Gedin has proved, sequential translations of a poem into multiple languages changes the character of its content.
