#+title: Jacob Kirkegard interview: the sounds for themselves
#+name: Henrik Frisk
#+options: toc:nil num:nil
#+cite_export: csl ~/Documents/articles/biblio/csl-styles/apa-7th.csl
#+LaTeX_HEADER: \usepackage[x11names]{xcolor}
#+LaTeX_HEADER: \hypersetup{linktoc = all, colorlinks = true, urlcolor = DodgerBlue4, citecolor = black, linkcolor = black}
#+latex_header: \usepackage[scaled]{helvet}
\renewcommand\familydefault{\sfdefault}

In late August 2023 I met composer and sound artist Jacob Kirkegaard for a talk about the ways in which he thinks about sounds, their origins and their agency. Kirkegaard is a highly original composer that has a meticulous method for exploring sounds, and the traces that sounds make. He often engages with materials that make sounds that are not usually heard, reflected upon, or not even accessible to listeners. He stages them in ways that allows them to speak for themselves, and that allows the listener to frame and understand them in their own individual ways.

Works like /Crossfire/, which contains recordings of guns and artillery being fired rapidly and intensively, and /Aion/, where four abandoned spaces in the zone of alienation in the area surrounding the former nuclear power plant in Chernobyl, Ukraine, are made to resonate, evoke thoughts about the meaning of sounds. Departing from these two works I was interested in discussing how Kirkegaard thinks about the politics of sound. In the case of Chernobyl, for example, he is allowing the unheard to be heard in a double sense: most people cannot travel to the Chernobyl site, and even if one can the sounds that are heard in /Aion/ are not accessible. As an artist he gives a site a sound that perhaps was not there before, or that was at least was not heard before, which may, or may not, have political implications I suggested to him.

Our discussion began in a mapping of the meaning, or meaningfulness of at all speaking about a politics of sound, or sounds as political. Kirkegaard initially rejects the idea that there is anything political about his works. What he intends for, he explains, is to explore a set of themes that creates rooms for listening allowing for a free and non-judgmental listening that has no particular purpose other than to evoke the thematics embedded in the sound. The common thread in his practice, he continues, is at the most basic level concerned with what it is to be human. Works like /Labyrinthitis/, /Testimonium/ and /Membrane/ are evidence of this artistic and aesthetic disposition.

Nevertheless, he continues, it happens that the contexts in the world changes which reconfigures the possible interpretations of the works in question. The outbreak of the war in Ukraine, for example, has an impact on both /Crossfire/ with its evocation of sounds of war, and /Aion/, where the contemplative place as created by Kirkegaard now instead is put at the centre of a geopolitical conflict the scale of which we have not seen in post World War II.

Thus, although his work obviously is concerned with themes that has validity in the surrounding world it is not intrinsically concerned with commenting on these subjects on a level that makes the works themselves politically loaded. That world events occur after a work has been instantiated and which charges them with new meanings is interesting, but does not in any substantial way change the core identity of the work, he claims. That their possible interpretations may be altered, and that they may be loaded with new meanings and frames of reference, different to how they were once conceived, does not make the work political.

This attitude is part of Kirkegaard's view on his role as an artist. He is an artist and in this role he asks questions about what happens in the world. He uses his sensibility to create new surfaces for listening, to make listening possible where it was not previously possible. In this process he allows the objects, the themes and the places to speak for themselves. They speak their own language, he says. The sounds found in Chernobyl, he takes as an example, "does not say yes or no, good or bad, left or right; they are not political." According to Kirkegaard he is in no position to tell the listener what or how to feel. It is solely the responsibility of the listener to figure out what they think. Kirkegaard is very clear on this point, he has no interest or wish to figure out what possible interpretations there are of his works, this is up to the listener. The sounds themselves are nothing but sounds and they make no judgments about political matters, nor do they have opinions, and this is precisely his point: the sounds are /not/ political. There is plenty of other kind of sonic communication today that attempts to influence and manipulate the listener in one or another direction.

He uses the metaphor of a /space for sensuousness/ that allows the listener seek out their own point of view, that is, what the listener senses from the process. It is important, says Kirkegaard, to be clear that I have no interest in manipulating the listener in one direction or the other, or convince them that I am right or that I choose one thing over the other. However, this does not mean that he is neutral to the topics he raises, only that the listener should have agency and responsibility to create their own understanding. Kirkegaard says he is interested in instigating change in the world, but more than anything, to create a "breeding bed for a deeper kind sensuousness", one that is less dependent on the onslaught of information and opinions that dominate contemporary Western society.

Kirkegaard's own personal fears often plays a role in the way he picks the themes for his works. Fear of radioactivity, fear of war, or borders, and the process of creating a space for listening to the objects that manifests this fear appears to almost have a therapeutical role in his practice. He obviously makes choices about what sounds to work with, and how, and through these choices he of course influences the outcome. The way he puts microphones and sensors on these objects are one of the more important aspects of his work. But the main objective is to allow for the objects to find their own way, and for the artist to take a step back. "They [the sounds] really speak for themselves" he says, and states that the abstraction that sound has compared to language actually makes them speak even more clearly. This relates in interesting ways to the knowledge claim often put forth in the discussion of artistic research as a possible complement to scientific knowledge. 

We also had a discussion about the ethical aspects of the works that he does, and on the changes of the attitudes over the last few decades that are at the same time good, natural and problematic. To explore difficult topics is an integral part of Kirkegaard's practice and if the boundaries for what is possible becomes too narrow, this obviously poses a threat to this kind of artistic practices. There are also those of his works, he says, that he would not have done today. But he follows up by saying  that this extremely politically correct world almost drives him "to do the opposite of what one would have wanted to."

Kirkekaard's fascination for the quality of the sounds that he records distinguishes him, as he puts it, from some of the sound artists that emanate from the visual arts whose relation to sound in some cases is purely conceptual. This quality that he is talking about has to do with a certain balance in the sound, "that the sound, purely acoustically, has some bass, some mid register, high end--that it has a quality that allows you to get /in to the sound/." It is clear that this has to do, at least in part, with the fact that Kirkegaard has his background in music. He is describing a method of working in which he sets in motion an iterative process, perhaps only partially controlled by him, out of which new things and new sounds appear. The listening that may appear out of this gives way for a mental state "that is right in between the alienated and the well known." He again points to the neutrality and the quality of the sound as factors that facilitate this.

In our discussion Kirekaard often returns to, and emphasizes, that the role of his art is not to dominate the listener with conceptual and political truths. Instead, it is up to the listener to make sense. As an artist he is merely the facilitator, he allows me as a listener to understand something about the world I did not know before, but it is up to me to do the work. The ambition that the music should create a /sensuous space/ that allows for this communication is both beautiful and challenging: "It is only here that you can actually tell what you really think." In this space there are no predefined expectations and no binary distinctions laid on you, and, most importantly, you are not required to have an opinion should you not want to, 

That this rare space, the /space for sensuousness/ may be created through his music becomes clear when I explore Jacob Kirkegaard's works. He clearly succeeds with that ambition. His art pushes boundaries, as art should do, and does not shy away for the complicated questions. His pieces allow the sounds to stand out by themselves in all their beauty. I believe that the discussion on the nature of musical sounds in the way Kirkegaard frames it, as neutral and void of unequivocal meaning, brings forth an interesting side-topic. Traditional music theory is saturated with metaphors that relate to the meaning of certain sonic events, and harmony is probably the most salient one. A dominant chord is a sound with a specific inherent meaning. One of John Cage's greatest contributions that allowed for the move towards an aesthetic of sounds for themselves, the cornerstone of Jacob Kirkegaard's music, was to abandon harmony. 

Another reference I came to think of after my discussion with Jacob Kirkegaard, which also has some relevance to Cage, is a passage in Henry David Thoreau's Walden where he rejects the symbolic meaning of the engine whistles and points to our right to by ourselves define what musical meaning it has: "We will consider what kind of music they are." [cite:@thoreau2004;p. 105]

