# Created 2023-05-11 Thu 17:26
#+title: Forskning som undervisning
#+author: Henrik Frisk
I denna presentation kommer jag diskutera ett samarbete mellan KMH (Kungl. Musikhögskolan) och KTH (Kungl. Tekniska Högskolan) som initierades 2016. En av målsättningarna var att bygga upp en forskningsmiljö i nära interaktion med grundutbildningen samt att möjliggöra en gemensam forskarutbildning. Programmet vände sig till anställda lärare på KMH som hade intresse för forskning. De lärare som blev antagna fortsatte arbeta på 50% som lärare samtidigt som de följde forskarutbildningen på KTH. Samtliga fyra doktorander hittills har involverat sina studenter i sin forskning, som en integrerad del av kurserna de undervisar. Studenterna har på så vis bidragit till forskningen vilket i sin tur har lett till en acceptans, forskningsmedvetenhet och intresse hos studenterna. Härutöver har det påverkat kusrsplaneutveckling inom de ämnen som det rör.

Den konstnärliga forskningen i musik har haft en stark utveckling i Skandinavien under de senaste 20-30 åren. En anledning till framgången är att det relativt begränsade antalet platser har gått till etablerade musiker. Att studenter går från grundutbildning till forskarutbildning direkt är ovanligt, om ens möjligt. Fördelen med detta är att forskarutbildningen inte har behövt koncentrera sig på den konstnärliga delen, utan istället mer på hur detta kan gestaltas som forskning. Nackdelen är att kopplingen mellan grundutbildning och forskning inte har beaktats i tillräckligt stor utsträckning. Forskarutbildningen har skett i ett spår för sig och grundutbildningen har inte sett sig ha behov av den typen av kunskapsbildning som doktoranderna ofta intresserar sig för. Detta skapar flera utmaningar, inte minst som den konstnärliga akademin fortfarande på vissa ställen befinner sig i en konfliktliknande relation till det akademiska och akademiseringen ses som ett hot. Lösningen på den situationen är inte att akademisera det som ännu inte är akademiserat. Istället bör vi sträva efter att å ena sidan göra forskningsresultat användbara i konstnärlig undervisning, och å andra sidan skapa miljöer i vilka även konstnärlig praktik i, och för sig själv, ses som potentiella forskningsresultat. 

* Biografi

Henrik Frisk är bosatt i Uppsala och är aktiv nationellt och internationellt som saxofonist, tonsättare, forskare samt lärare och föreläsare och är professor i musik på institutionen för komposition, dirigering och musikteori på Kungl. Musikhögskolan i Stockholm samt ordförande för utbildnings- och forskningsnämnden. Han arbetar främst med improvisation och elektroakustisk musik men även med ljudinstallationer. Sedan 2008, då han disputerade på det konstnärliga området på avhandlingen "Improvisation, Computers, and Interaction : Rethinking Human-Computer Interaction Through Music" (ISSN 1653-8617), har han markerat sig som konstnärlig forskare i Europa. 
