* Solastalgia - Toward new collaborative models in an interdisciplinary context
:PROPERTIES:
:NOTER_DOCUMENT: Solastalgia - Toward new collaborative models in an interdisciplinary context.pdf
:END:
** Abstract
:PROPERTIES:
:NOTER_PAGE: (1 0.2650602409638554 . 0.4147727272727273)
:END:
#+BEGIN_QUOTE
Solastalgia becomes important for
Hellqvist as an example of how her artistic palette can guide her toward understanding of her
agency and creativity as a performer
#+END_QUOTE
** p.4: Odd sentence
:PROPERTIES:
:NOTER_PAGE: (4 0.28651685393258425 . 0.17727272727272728)
:END:
#+BEGIN_QUOTE
The use of audio recording and processing technology is additionally something rather
unexplored in our respective practices.
#+END_QUOTE
I refuse to believe that either of the composer or the performer have used audio recordings prior to this event.
** p.4 Changing perspectives
:PROPERTIES:
:NOTER_PAGE: (4 0.7560192616372392 . 0.2909090909090909)
:END:
Traditionally a theory survey or a mapping of concepts does not mix in analyses of this kind and it may be good to separate out your reflections from the mapping of the territory, as exemplified in this quote:
#+BEGIN_QUOTE
To me, it exemplifies work where the ideal of Werktreue is profoundly
affecting the level of interaction between its participants.
#+END_QUOTE
Also, though this statement would be correct on the surface level, the reader doesn't yet know enough about Werktreue to judge what it means. The reference of 'it' in this sentence is ambiguous.
** p.5: What are these privileges?
:PROPERTIES:
:NOTER_PAGE: (5 0.5738362760834671 . 0.6)
:END:
``challenges her privileges''
** p.5: Definition of collaborative work
:PROPERTIES:
:NOTER_PAGE: (5 0.6869983948635634 . 0.2693181818181818)
:END:
``Barbara Lüneburg’s holistic approach to performance practice.''

I fail to see why a traditional interaction between composer and performer such as thos described by you earlier does not meet the standard here. 'Working together' does not imply being in the same room, and there is a strong focus on shared goals (the work). Surely they profit from one another.
** p.6: Context?
:PROPERTIES:
:NOTER_PAGE: (6 0.4622792937399679 . 0.11931818181818181)
:END:
``Situated in this research context'', what is this context? The one that includes the names you listed above?
** p.6: Artistic palette
:PROPERTIES:
:NOTER_PAGE: (6 0.6364365971107544 . 0.12045454545454545)
:END:
#+BEGIN_QUOTE
A concept I have created that runs as a red thread through my research is the artistic palette.
#+END_QUOTE
I like this idea but I have a hard time understanding what is the difference between this and your collected artistic experience. Perhaps this could be further explored as a kind of sensibility, that is, an ability rather than merely an experience or piece of knowledge. Something that allows you to do the work you do but which is not reducible to information. Something that /is/ agency rather than a reflection of agency.

** p.7: Reference
:PROPERTIES:
:NOTER_PAGE: (7 0.26003210272873195 . 0.5943181818181817)
:END:
This quote ``Already in the
Antique, techne was connected to the act of making music.'' I think this either should be taken out or it needs a reference. The use of techne is not uncommon in artistic research, but I find it problematic. It has so many different meanings, though most commonly referred to is Aristotele. But his idea of techne, as far as I've understood it correctly, is tightly connected to the end goal, and in that sense techne could seen to be associated with /Werktreue/: the end goal rather than the interactions that leads to it. Perhaps it is both, but in either case you need to develop this thought here or more clearly make it your own. In that regard this sentence ismuch more informative: "I regard techne as a method, a way of exploring the artistic
palette."

** p.6: what are these technological means?
:PROPERTIES:
:NOTER_PAGE: (7 0.3796147672552167 . 0.5488636363636363)
:END:
``technological means''

** p.8: Hierarcical relation
:PROPERTIES:
:NOTER_PAGE: 8
:END:
``hierarchical relation''

I don't think you have described the nature of this relation yet.

** p.8: Quote
:PROPERTIES:
:NOTER_PAGE: (8 0.1187800963081862 . 0.11818181818181818)
:END:
#+BEGIN_QUOTE
According to Östersjö (2017: 90), results from artistic research can be thought of as situated
in three layers; the embodied, artistic and discursive.
#+END_QUOTE
It is not clear to me what this quote adds here. You don't appear to be using these layers and the work your describing is woven together in all three.

** p.8: Methods
:PROPERTIES:
:NOTER_PAGE: (8 0.24157303370786518 . 0.5965909090909091)
:END:
``I further
unfold the artistic methods we have applied and developed.''

Maybe you should more clearly describe what is the difference (if any) between the artistic methods and the methods used.

** p.8: RQ
:PROPERTIES:
:NOTER_PAGE: (8 0.7841091492776886 . 0.2761363636363636)
:END:
``previously established
relationship''

Don't you mean 'previously extablished roles' here? Else, define what this relationship is constituted by.

** p.8: RQ
:PROPERTIES:
:NOTER_PAGE: (8 0.8539325842696629 . 0.18295454545454545)
:END:
#+BEGIN_QUOTE
How does forms of techne function as tools for artistic construction and how do I find
it affecting the ecosystem of composer-performer-work?
#+END_QUOTE
Again, I find the word techne needs a better framing in order to be useful here. Isn't there a siimpler way of describing it (that can still be discussed in relation to 'techne') but that allows you to be in charge of what is meant.

** p.10: Reference
:PROPERTIES:
:NOTER_PAGE: (10 0.31059390048154095 . 0.12727272727272726)
:END:
``Cambridge Dictionary''

** p.10: Artistic palette
:PROPERTIES:
:NOTER_PAGE: (10 0.5280898876404494 . 0.2011363636363636)
:END:
``this mapping process connects me to my artistic palette''

This description is a better description of what I think you are after: that you have a knowledge that becomes accessible through various kinds of interventions while thises interventions also add to the palette?

** p.12: Transcription
:PROPERTIES:
:NOTER_PAGE: (12 0.16693418940609953 . 0.6272727272727272)
:END:
#+BEGIN_QUOTE
Due to the pandemic, the
dialogue between the three of us unfolds over Zoom and email.
#+END_QUOTE
The transcriptions contains only Karin and Carola and is not a dialogue between the three of you.

** p.16: standard tuned violin
:PROPERTIES:
:NOTER_PAGE: (12 0.6396468699839486 . 0.09545454545454546)
:END:
It appears to me that this passage could be explained in simpler terms, but perhaps I just get confused by the term "standard tuned" which makes me think about /scordatura/ whereas you are talking about the range of the instrument. 
** p.16: first para
:PROPERTIES:
:NOTER_PAGE: (16 0.23515248796147672 . 0.8147727272727272)
:END:
#+BEGIN_QUOTE
Carola
not only offers space for me to enter the discussion, she actively encourages me to do so.
#+END_QUOTE
Obvously, we should take your word for it that Carola invites you on equal terms, but it would be good to have a transcription that more clearly shows this. The uncertainty that you express in this situation is clear from the transcription and with Carola's relatively short responses, having experience from the field, it appears to me as an expression of quite traditional power structures. This does not at all mean that it is, but if you can back up your equality claim more strongly here it would improve this passage and the general claim of the paper.
** p.18: Separated process        
:PROPERTIES:
:NOTER_PAGE: (18 0.620545073375262 . 0.11968348170128586)
:END:
I'm not sure what this means, is there something missing in the sentence?
#+BEGIN_QUOTE
I experience how my artistic palette influences the work in ways that would be impossible in
a separated process in line with the ideal of Werktreue.
#+END_QUOTE
Same swith the last sentence before Discussion.
** p.18: Discussion
:PROPERTIES:
:NOTER_PAGE: (18 0.8686233403214535 . 0.11968348170128586)
:END:
#+BEGIN_QUOTE
In Part I-II, I have described how the embodied knowledge of my artistic palette,
#+END_QUOTE
It isn't strictly your artistic palette that have knowledge, but rather that you label embodied knowledge /artistic palette/? That's how I understood it.
** p.19: Typologies...
:PROPERTIES:
:NOTER_PAGE: (19 0.2697414395527603 . 0.11968348170128586)
:END:
Grammatical error
#+BEGIN_QUOTE
According to Taylor (2020), as seen in Fig. 1 (page x), whether the imaginative (idea-
generating) and the evaluative (decision-making) processes are shared between participants,
can categorize work as either hierarchical, co-operative, consultative or collaborative.
#+END_QUOTE
** p:19: Typologies
:PROPERTIES:
:NOTER_PAGE: (19 0.38714185883997204 . 0.5934718100890207)
:END:
I don't think you have explained the ``typologies of shared work''? Are you refering to Taylor again? 'Type' and 'Typology' can't be used interchangeably.
** p.20: Outsider
:PROPERTIES:
:NOTER_PAGE: (20 0.7826694619147448 . 0.43620178041543023)
:END:
Who is this outsider and on what grounds are you making this claim?
#+BEGIN_QUOTE
Through the outsider’s view, information can be
transferred between the artistic layers of the work
#+END_QUOTE
** p.21: Werktreue
:PROPERTIES:
:NOTER_PAGE: (21 0.16701607267645002 . 0.27893175074183973)
:END:
#+BEGIN_QUOTE
Different in this process, from the general Werktreue-influenced field of
Western classical art music, is my involvement as a performer. What has made it possible to
bring my practice from hierarchical work into co-operative and collaborative?
#+END_QUOTE
Personally I'm not so convinced by using Werktreue in this context. What does this concept offer to your discussion beyond giving a name to what it is your collaboration is /not/? Early you write that "my wishes can be seen as conflicting with the ideal of Werktreue, still alive in contemporary music". Couldn't this just as well be "my wishes can be seen as conflicting with the current ideals of classical and contemporary music where there is a strong separation of labor between composer and musician", or similar? If you want to hold on to the term I think you need to better develop you reading of Goehr to avoid it seem like a theoretical overlay. Your collaboration is not that different from those that frequently occur even in contemporary music which might be useful to mention.

Also, this sentence early on: "I review the structures of Werktreue in the light of our collaboration" has not really been fulfilled.
** p.22: bottom
:PROPERTIES:
:NOTER_PAGE: (22 0.6352201257861635 . 0.5074183976261127)
:END:
#+BEGIN_QUOTE
In our case, I now experience
Werktreue as set aside, by a safe space where my contributions as a performer are
acknowledged. Loyalty to the notated work and composer transforms into loyalty to our co-
created work. The fact that the musical composition is a shared product further affects how
the piece is legally registered. A new experience for me is that with shared legal ownership,
performance royalties from GEMA (Gesellschaft für musikalische Aufführungs- und
mechanische Vervielfältigungsrechte) is shared.
#+END_QUOTE
I lack a critical discussion here about the legal ownership. Copyright laws are an important part of the reason why the work concept grew stronger and that the value of the work was judged based on the work itself, nothing else. I think the phrasing by Goehr is that the . What does the registration with GEMA do to the ontology of your work? How is the collaboration represented apart from your name on the score. How is your faithfulness to the collaborative aspects of your work different from faithfulness to a Beethove score? The score in and of itself is thick with meanings and connotations.
** p.23: Missing reference
:PROPERTIES:
:NOTER_PAGE: (23 0.09154437456324248 . 0.41938674579624136)
:END:
The reference ``Barrett 2014: 53'' is not in the reference list at the end. In general secondary citations should be avoided unless really needed, but maybe I'm misunderstnading this.
** p.23: bottom
:PROPERTIES:
:NOTER_PAGE: (23 0.8294898672257163 . 0.21364985163204747)
:END:
#+BEGIN_QUOTE
I have learnt how to use, and see the value of, certain technological means to
communicate personal artistic materials. I have understood how my embodied knowledge
plays a central role in my performances and my creative activities.
#+END_QUOTE
It is of interest to the reader that you have learnt things, and good that you describe how also. Maybe you could refer back to the specific descriptions of how you developed the "technological means". Would it be possible to raise this discussion one level from the personal to the intra-personal and even abstractly: How can these insights be valuable/accessible/useful to others?
** p.24: mid page
:PROPERTIES:
:NOTER_PAGE: (24 0.33962264150943394 . 0.36795252225519287)
:END:
#+BEGIN_QUOTE
Through those situations, I
have developed my ability to appreciate and communicate both artistic materials and thoughts
surrounding my artistic palette. To me, this emerging artistic and communicative ability has
been a driving force in the negotiation of roles during our shared work, and a catalyst for an
equal form for collaboration.
#+END_QUOTE
See previous comment: how can this be explored by others? For example, you could refer to the process.
** p.25: second para
:PROPERTIES:
:NOTER_PAGE: (25 0.1663172606568833 . 0.12265084075173095)
:END:
#+BEGIN_QUOTE
Thinking with the concept of techne instead of separating my activities in ‘engaging with
technology’ and ‘artistic creation’, has provided me with a more holistic understanding of the
complexity of my embodied knowledge and the artistic palette.
#+END_QUOTE
This is an odd sentence. You refer to a holistic view only to create another division, that between embodied knowledge and artistic palette.
