# Created 2020-11-22 sön 13:09
#+TITLE: Before sound
#+AUTHOR: Henrik Frisk, henrik.frisk@kmh.se

* Före eller efter: om konstnärlig erfarenhet och kunskap i konstnärlig praktik
** Introduktion 2500

Konstnärlig forskning har haft en dynamisk och positiv utveckling de senaste 20 åren. Men är fortfarande ojämn och lite knagglig: Det finns fortfarande relativt lite kunskap om vad det egentligen är även på vissa konstnärliga högskolor. Man kan förvisso fråga sig om kunskapen om t.ex. den socialogiska eller antropologiska forskningens metoder och resultat egenligen är större, eller om det finns en bredare insikt i på vilket sätt forskning i fysik bidrar till samhällets utveckling. Dock är dessa exempel ju uppenbart politiskt och kulturellt mer etablerade på ett sätt som den konstnärliga forskningen inte är, varför okunskapen är ett större problem i detta fält än i andra. 

Den konstnärliga forskningen i musik har en på vissa sätt längre historia mycket tack vare de musikvetenskapliga initativ till en forskarutbildning med praktisk ingång som togs i Göteborg i slutet av 80-talet, mycket tack vare professor Jan Ling. Vad vi ser är en mjuk övergång från musikvetenskap, till musikpedagogik, och till konstnärlig forskning i musik. Detta har varit en fördel och delvis också en belastning. Det senare då den konstnärliga forskningen i musik delvis har präglats på detta vetenskapliga arv på ett sätt som inte t.ex. den konstnärliga forskningen i fri konst har gjort. Fördelarna handlar om metodutveckling och etablerade teorier att knyta an till. 

När jag påbörjade min forskarutbildning på konstnärliga fakulteten vid Lunds universitet och Musikhögskolan i Malmö var det ett medvetet val att vi som var doktorander på konst-, musik- och teaterhögskolan skulle närma oss frågan om metod utan större inflytande från etablerade discipliner. På Musikhögskolan innebar det att vi inte skulle ha gemensamma seminarier med musikpedagogiken, som var den enda forskning som fanns innan vi började. Istället hade vi gemensamma seminarier med de andra konstnärliga doktoranderna. Efter ett tag hoppade doktoranderna på teaterhögskolan av och gruppen bestod av oss tre från musikhögskolan och de tre doktoranderna från konsthögskolan där seminarierna också ägde rum. Mycket tack vare Sarat Maharaj, Brittisk konsthistoriker och curator som ledde seminarierna, och Gertrud Sandqvist, professor och då rektor för konsthögskolan, fanns det trots denna relativa isolering ett stort intresse av att vända sig mot discipliner som sociologi, psykologi och historia, vilket gjorde att diskussionerna i stor utsträckning präglades av insterdisciplinäritet. Ambitionen var att de konstnärliga projekten skulle styra valet av metod och teori, även om det i verkligheten nog snarare var en ganska dynamisk interaktion. Hade resultatet blivit ett annat om vi från musikhögskolan istället hade haft vår seminarier med musikpedagogiken? Definitivt, men det är naturligtvis omöjligt att fastställa om det hade varit bättre eller sämre.

Avsaknaden av definierade teoribildningar och metoder är den konstnärliga forskningens välsignelse och förbannelse. Mycket energi har ägnats åt att hävda att den konstnärliga forskningen ska vara fri från den typen av band som annars förväntas från forskning i andra discipliner. En långvarig diskussion i det lilla kluster som jag beskrev ovan var om vi överhuvudtaget skulle ha metod (ett mantra som återkom var "fuck method") och på ett övergripande plan ville man till varje pris undvika en utdragen debatt i fältet. Huruvida det har varit en debatt i fältet eller inte är svårt att avgöra, men det är tydligt att doktorander än idag tycker att metodbegreppet i konstnärliga forskning är svårt att hantera. Det finns ingen brist på metodologiska tillvägagångssätt i konstnärlig forskning i Sverige, men däremot kan det var svårt att hitta en röd tråd vilket gör, vill jag påstå, att fältet i sin helhet blir onödigt disparat. Lösningen på detta är inte homogenitet, utan en för fältet övrgripande diskussion om metodologi som samtidigt är djuplodande.

Anledningen till att vi befinner oss i den här situation har mycket att göra med det som är själva kärnar i utmaningen med konstnärliga forskning, nämligen relationen mellan den konstnärliga praktiken och den forskande aktiviteten och det faktum att denna relation kan se ut och utveckla sig på en rad olika vis. Om forskningsprojektet är helt integrerat, det vill säga att forskningsen utgår helt från den konstnärliga praktiken är det metodologiska behoven naturligtvis annorlunda från ett projekt där en konstnärlig praktik utforskas av konstnären som skftar mellan den praktiska och analyserande rollen. Med andra ord, var den forskande praktiken befinner sig i relation till den konstnärliga är avgörande för valet av metod. Därför är det svårt att se framför sig den typen av metodologisk enhetlighet i konstnärlig forskning som man kan se i vissa andra fält, men, gemensamt för all konstnärlig forskning borde vara den konstnärliga metoden. Det är den som gör forskningen relevant som just konstnärlig forskning då det är den som visar på att valen som har gjorts har gjorts på konstnärlig grund.

Så länge den konstnärliga metoden är väl beskriven, stabil och hållbar, så finns det god sannolikhet för att det finns data som går att utforska. Anledningen till att dessa data är av intresse är det faktum att de kommit till genom konstnärliga överväganden snarare än vetenskapliga. I vår artikel /Beyond Validity/ [[#frisk-ost13][frisk-ost13]] diskuterar Stefan Östersjö och jag bland annat validitet i konstnärlig forskning och pekar på behovet av att dekonstruera den positivistiska betydelsen av detta begrepp. Det förutsätter dock också att vi tittar närmare på några av de begrepp som färgat utvecklingen av konstnärlig forskning, och som relaterar till diskussionen ovan. Henk Borgdorff är en person som har haft en hel del inflytande över den tidiga utvecklingen av konstnärlig forskning i Sverige och fortfarande så i Holland. Han var bland annat medlem i den externa referensgruppen för nationella konstnärliga forskarskolan, likaså professor på GU i en period. I sin bok /Conflict of the Faculties/ artikulerar han den ganska utbredda hållningen att konstnärlig forskning inte söker efter att uttrycka explicit kunskap utan snarare om att:

#+begin_quote
provide a specific articulation of the pre-reflective, non-conceptual content of
art. It thereby invites unfinished thinking. Hence, it is not formal knowledge that is the subject
matter of artistic research, but thinking in, through, and with art. [[#borgdorff2012][borgdorff2012]]
#+end_quote

Att konsten, och det konsten uttrycker, skulle vara icke-konceptuellt är en idé som har präglat den västerländska estetiken under lång tid och som mycket väl förtjänar att granskas kritiskt. Är den inte konceptuell, eller inte låter sig konseptualiseras så kan detta resultat av den inte heller kommuniceras, vilket i så fall skulle göra den till ett objekt som endast svårligen låter sig på eller genom. Åtminstone ställer det väldigt höga metodologiska krav. Samtidigt vore det fel att påstå att konstnärligt uttryck inte kan vara icke-konceptuellt. Ofta refererar vi till en stark upplevelse som något som går rakt in utan att passera en analytisk eller conceptualiserande fas. Huruvida detta per automatik resulterar i /ofärdigt/ tänkande är svårt att säga något om. Istället kan vi se den konstnärliga kunskapsutvecklingen som något som sker i olika strata av medvetande och färdighet och i olika konstnärliga projekt är de olika skikten mer eller mindre framträdande och mer eller mindre möjliga att verbalisera. Som vi konstaterar finns det ett behov av att bättre förstå detta fält:

#+begin_quote
[...] we now have to examine more closely the notions of pre-reflective and non-conceptual contents of art. Are they the same or different things? Does not ‘pre-reflective’ indicate that there is something unfinished in its trajectory? The category of non-conceptual knowing seems to us to be distinct from the unfinished. This appears to be a field not sufficiently discussed and theorized within artistic research, and, still, it is the heart of the matter: in all artistic production, knowledge is created and passed on in ways that are most often distinct from the verbal domain. [[#frisk-ost13][frisk-ost13]]
#+end_quote

Om kunskap är skapad och kommunicerad på sätt som är väsensskilda från verbal kommunikation så är en del av utmaningen i konstnärlig forskning att översätta kunskapen så att den går att konceptualisera på ett stabilt sätt. Det är för att instantiera denna översättningsfas som metoden behövs. Att se på konstnärlig praktik som en multplicitet av potentiella uttryck och kunskapsformer som aktualiseras genom forskning betyder också att metoden inte bara är viktig, utan att många olika typer av metoder är nödvändiga då det måste vara varje projekts individuella konstellation av relationer som styr vilken metod som är den riktiga. Det är viktigt att dessa strata av konstnärlig kommunikation alltså inte på något sätt omöjliggör att någon del av, eller hela erfarenheten, verbaliseras. Istället, menar jag, borde det vara möjligt att:

#+begin_quote
[...] reconsider the theory-practice, method-practice and theory-method relationships beyond their most obvious appearances. If we can reassess the dual nature of these relationships and begin to see them as movements instead, continuities from practice to method to theory and then back, from concept to abstraction to speciﬁcity, the generalising and contextualising power of the theoretical approach may be less of an obstacle to the practice-oriented artistic researcher and doctoral candidate. [[#frisk2015][frisk2015]]
#+end_quote

Här börjar nu själva kärnan av problemet träda fram: hur kan hållbara resultat utvinnas om koncept och kontext är i ständig rörelse och hur kan metoden väljas om ingenting är konstant? Det finns flera sätt att angripa dessa frågor på men först vill jag lägga till denna diskussion till listan av ej tillräckligt diskuterade problem i konstnärlig forskning. Det är utan tvivel så att det stora av fältet vetenskaplig forskning är otroligt disparat, och synen på den ideala, rigida vetenskapliga metoden är överdrivet enhetlig och förenklad. Samtidigt räcker det inte för den konstnärliga forskningen att återkommande hänvisa till att det finns experimentella kvalitativa metoder som änvänds inom vetenskapen också. Metoderna, vare sig de avviker från vetenskapen eller inte, måste kunna förklaras och redovisas och metodutvecklingen inom fältet behöver få ett större fokus.

All konstnärlig praktik befinner sig inte heller i ett ständigt flux. Det finns flera exempel på praktiker som är konceptuellt stabila, men i allmänhet finns det mycket rörelse och det är detta som gör konstnärlig forskning såväl svår att förklara och definiera och samtidigt så otroligt användbar: generella förklaringsmodeller håller inte. Detta är en egenskap som ska underhållas och inte undertryckas. Resultatet av en dynamisk konstnärlig praktik kan fortfarande analyseras genom kvantitativa metoder och forma modeller. Dessa modeller kan ge resultat men för sig själva är det tveksamt vad de representerar. Om praktiken som genererade dem inkluderas i beskrivningen är det större sannolikhet för att de genererar kunskap som är användbar i konstnärlig forskning. Därför är det inte i reduktionen, eller den deduktiva metoden, som resultaten ska sökas utan i komplexiteten och instabiliteten, eller kort, i relationen till kaos. Det är detta som Deleuze och Guattari pekar på som skillnaden mellan filosofi och vetenskap, och jag skulle hävda att det är samma sak som skiljer konst från filosofi och konst från vetenskap:

#+begin_quote
The object of science is not concepts but rather functions that are presented as propositions in discursive systems. The elements of functions are called /functives/. A scientific notion is defined not by concepts but by functions or propositions. This is a very complex idea with many aspects as can be seen already from the use to which it is put buy mathematics and biology respectively. Nevertheless, it is this idea of the function which enables the sciences to reflect and communicate. Science does not need to philosophy for these tasks. On the other hand, when an object---a geometrical space, for example is---scientifically constructed by functions its philosophical concept, which is by no means given in the function, must still be discovered. Furthermore, a concept may take as its components the functives of any possible function without thereby having the least scientific value, but with the aim of marking the differences in kind between concepts and functions.

Under these conditions, the first difference between science and philosophy is their respective attitudes toward chaos. [[#deleuze1994][deleuze1994]]
#+end_quote

De fortsätter med beskriva den vetenskapliga metoden som en process som saktar ner tiden, som tar ett komplext fenomen och reducerar det till en enda funktion. Reduktion och representation vilket genererar tillstånd, funktioner och referentiella propositioner [[#deleuze1994][deleuze1994]]. Även om vetenskapen inte behöver filosofien, eller konsten, kompletterar de tre perspektiven varandra och i [[#deleuze1994][deleuze1994]] strävar Deleuze och Guattari efter att placera filosofin och tänkandet i relation till vetenskapen och konsten och samtidigt undvika att skapa hiearkier dem emellan. Tillblivelse och transformation framför varande. Koncept, inte som former som fylls med innehåll utan som uppstår i relation till varandra i ständig rörelse. Vad betyder detta för diskussionen om den konstnärlig forskningens betydelse och förmåga att skapa resultat relevanta för en värld i chaos? Olika projekt har olika mål men hur vet vi i bedömningen av konstnärlig forskning vad som är avsikten med ett givet projekt, om det är själva verket eller analysen eller båda två som vi ska se på?

Om vi följer Deleuze och Guattaris diskussion ovan måste vi också ställa oss frågan vad konstnärlig forskning är för något i deras beskrivning. Det är ingen tvekan om att de har en relativt traditionell syn på konst och vad betyder det för den typen av transversal praktik som Åsa Stjerna bedriver? Är deras resonemang fortfarande relevanta för den hybrid som konstnärlig forskning utgör eller är det i huvudsak en ganska gammaldags syn på estetik och konstnärlig kunskap? Och vad är förhållandet mellan filosofin som konceptskapande aktivitet och konsten som aktivitet?

Det finns en möjlig negativ, om än ofullständig, definition av vad konstnärlig kunskap kan utgöra som grundar sig i empirisk kunskap. Föreställ dig allt som du kan kan säga någonting om utifrån vedertagna vetenskapliga definitioner såsom gravitationens inverkan på din kropp, luftens och vattnets sammansättning, de politiska och sociala system som du ingår i och påverkas ev, etc. Det konsten kan säga någonting om är allt det andra; hur det känns att vara utsatt för gravitation, hur luften doftar och vattnet smakar och de känslomässiga konsekvenser som det sociala och politiska har på dig. Eller som Eisner skriver: 

"For me, the defining feature that allows us to talk collectively about the arts is that art forms share the common mission of achieving expressiveness through the ways in which form has been crafted or shape. The arts historically have addressed the task of evoking emotion. We sometimes speak of the arts as resources that can take us on a ride. The arts, as I have indicated elsewhere, provide a natural high. They can also provide a natural low. The range of emotional responses is enormous. These emotional consequences in relation to a referent color the referent by virtue of the character of the emotion that the artistically crafted form possesses." [[#Eisner2008][Eisner2008]]

Det är ingen tvekan om att det finns många och stora likheter mellan konstnärlig forskning i musik och till exempel vetensskaplig forskning. Men det är heller ingen tvekan om att det finns stora skillnader. Den kanske främsta anledningen till att det kan vara svårt att samarbeta över gränserna när det gäller konstnärlig forskning det som ger konstnärlig forskning sin särprägel nämligen den konstnärliga metoden och den konstnärliga grunden. Man kan tycka att det borde vara enkelt eftersom det vetenskapliga och det konstnärliga kompletterar varandra så väl. Om vi använder allegorin från början av kapitlet och definierar det konstnärliga som allt det som vi inte säkert kan säga någonting om och resten dvs det som vi kan säga någonting om utifrån vedertagna metoder så blir det tydligt att det kan Vara svårt att samarbete. Själva grundvalen för att avgöra om forskningen är högkvalitativ är helt annorlunda för vilket det måste finnas förståelse och respekt om ett samarbete ska kunna bli ömsesidigt värdefullt.


För Deleuze är filosofi en process som i huvudsak består av att skapa koncept


är ett sätt att flytta fokus från frå



och kommer till slutsatsen att det är genom att framhäva subjektiviteten och subjektets alla olika överlagrade positioner som dett går att närma sig validitet i konstnärlig forskning (p. 44).

En opponent från den sociologika fakulteten kommenterade en doktroands arbete 

Bildkonstens frihet i relation till etablerade teorier och 

** Problemet 4000

Åsa Stjernas avhandling [[#Stjerna2018][Stjerna2018]] är en undersökning av hur plats-specifik konstnärlig praktik i ljudkonst kan frambringa förändring på olika nivåer. Fyra konstnärliga processer, varav tre är platsspecifika, beskrivs detaljerat och de processer som bidrar till det som rör avhandlingens centrala frågeställning: själva omförhandlingen och transformationen av platsen diskuteras utifrån kanske framförallt Gilles Deleuze och Félix Guattaris teori. Som framgår av undertiteln är begreppet transversal centralt i undersökningen. Transversalt ska här ses som "en förståelse av konstnärlig produktion som etablerandet av relationer mellan komponenter i ömsesidig kontinuerlig process av tillblivelse". [[#Stjerna2018][Stjerna2018]] Stjerna strävar efter att undvika de traditionellt starka dikotomier som präglar förståelsen av konstverket och som kan representeras av begrepp som konstnär-publik, skapande-lyssnande, innanför-utanför eller kropp-själ. Istället för dessa ontologiska relationer lyfter hon fram en "förståelse av konstnärlig praktik som befattandet med affektiva, /immanenta/, kraftrelationer i vilka varje komponent har agens, det vill säga kapaciteten att både påverka och påverkas.

Utifrån denna ambition är tre forskningsfrågor formulerade:

#+begin_quote
- På vilket sätt kan jag som konstnär utveckla utforskande tillvägagångssätt som understödjer en transversal skapandeprocess?
- Vilka begrepp behöver jag som konstnär kunna artikulera för att kunna synliggöra och förstå nyanserna av en sådan transversal process?
- Vilka konsekvenser har dessa utforskande tillvägagångssätt och begrepp i förståelsen av den platsspecifika soniska praktiken? [[#Stjerna2018][Stjerna2018]]
#+end_quote

Som metoder, här kallade utforskande tillvägagångssätt, pekar Stjerna på i huvudsak tre strategier: "att kartlägga de affektiva linjerna, att skapa nya sammankopplingar samt att bli icke-autonom" [[#Stjerna2018][Stjerna2018]]. Alla dessa tre är även kopplade till Deleuze och Guattari på olika nivåer, kanske framförallt metoden att skapa nya sammankopplingar som i sig kan ses som en del av den transversala ambitionen. Som en central tes som lyfts fram på flera platser i avhandlingen, och som är bakgrunden till titeln, är ljud något som ska ses som en effekt av affektiva, transversala och immanenta processer som samtliga äger rum /före ljudet/. Etablerandet av nya kopplingar lyfter fram den konstnärliga processen som både transformativ och transversala [[#Stjerna2018][Stjerna2018]] och dessa kopplingar är helt centrala för de olika aspekter, eller modaliteter som Stjerna lyfter fram för sin egen praktik: sonifiering, tekonologi och på-plats installation. Men det är också genom transversala processer som nya kopplingar skapas mellan heterogena objekt, vilket är den central del av den konstnärliga praktiken, som ljudet uppstår.

I avhandlingen diskuteras fyra konstnärliga projekt: /Currents/ (2011), An /Excursion to Nairobi/
(2013), /The Well/ (2014) och /Sky Brought Down/ (2017) och av dessa kommer jag framförallt fokusera på den första, /Currents/. /Currents/ var ett egeninitierat projekt som utvecklade sig till en installation beställd av Ultima-festivalen, en nutida musikfestival i Oslo, avsedd för foajern på nya operahuset i Oslo. Utgångspunkten för verket är data från Nordatlantiska strömmen som uppmättes i ett projekt som studerade issmältningen på norra halvklotet till följd av den globala uppvärmningen. Ambitionen var att utforska i vilken utsträckning ljud som konstnärligt material kan mediera frågor av stor politisk relevans och hur dessa frågor kan ge upphov till förkroppsligade upplevelser i ett publikt sammanhang.

Anledningen till att jag väljer just detta projekt är på grund av de frågor som det ställer kring relationen mellan representation och uttryck och hur de politiska och sociala aspekterna naturligt hamnar i fokus. Dessutom ligger flera av frågeställningarna nära de jag själv ha ställt. Det är samtidigt en tydlig illustration av hur en transversal process kan se ut. De olika komponenterna i de olika faserna av projektet, såsom forskningsprojektet som genererade datainsamlingen, processen att extrahera den vetenskapliga datan, opera huset som social och politisk plats och plats för själva renderingen av verket, den konstnärliga utvecklingen av mjuk- och hårdvara, och Stjerna själv som konstnär [[#Stjerna2018][Stjerna2018]]  är var och en för sig självständiga agenter, maskiner [fn:23], och assemblages och utmaningen, i det här sammanhanget, är att artikulera hur dessa kopplingar uppträder och hur de uppstår.

En annan aspekt av /Currents/ som Stjerna diskuterar i kapitel 5 är frågan om konstnären som subjekt och dennes begränsade oberoende eller autonomi. Det är tydligt att den väv av relationer som skissas här ovan också gör det tydligt att det blir svårt för konstnären att hävda ensidig bestämmanderätt utan snarare ska ses som en agent av många. Slutligen så diskuteras frågan om sonifiering som metod och hur den kan förstås som en transversal process trots att den i mångt och mycket har sina rötter i en annan vetenskapstradition. Som vetenskaplig metod är det i sonifiering ofta nödvändigt att skapa en mer eller mindre direkt korrespondens mellan den data som ska sonifieras och det ljudande resultatet.

#+begin_quote
As I have suggested it through my descriptions, the initial explorative process, the establishment of spatial perception, the development of sonic strategies and technology, and the construction process on site, all emerge as the result of complex, mechinic interconnections that span transversally between the site, the artwork, and the artist-subject. In this, I advocate a move beyond the traditional separations that establish these as three distinct entities.
#+end_quote

[fn:23] Maskin ska här läsas i den mening som Deleuze och Guattari använder /machine/ och /machinic/. Stjerna använder också termen återkommande och kan ses som en metod att förklara en typ av rörelse som opererar rhizomatiskt och som kan skapa transversala kopplingar till andra maskiner.

** Metoder i Before Sound 4000

Är verket en gestaltning av en teori eller är teorin metoden med vilken gestaltningen tar form? 

** Att kommunicera erfarenheten i öppen form 5000

I en avhandling som [[#Stjerna2018][Stjerna2018]] är gränserna mellan praktik, metod och teori inte artikulerad utan ständigt rörlig. Terminologin hämtad från Deleuze och Guattari är till exempel såväl metod, teori och i vissa fall resultat och det är inte alltid självklart vad som är målet. Om vi tittar på den första  forskningsfrågan, /På vilket sätt kan jag som konstnär utveckla utforskande tillvägagångssätt som understödjer en transversal skapandeprocess?/, så är det klart att den transversala skapandeprocessen är ett mål i sig, men lika tydligt är det i kapitel fem att Stjerna genom sin praktik redan i början av projektet etablerar transversala kopplingar [[#Stjerna2018][Stjerna2018]]. Genom hela avhandlingen argumenterar hon för en syn på själva ljudinstallationen som en transformativ praktik som löper mellan ett flertal konstnärliga strategier som var och en är en transversal process. Slutligen pekar hon även på att den komplexa transversala processen är ett analytiskt verktyg som utövar inflytande på den inbegripna processerna. Hur kan då samma begreppsapparat vara mål och metod?

Det är ännu svårt att se konstnärlig forskning som en disciplin som genererar tydliga resultat utifrån väl beprövade metoder. Istället finns det en rad möjliga artikulationer av kunskapsutveckling som alla delar attityden att det i den konstnärliga praktiken finns en epistemologisk potential, en möjlig kunskap som om den begreppsliggörs kan ha stort inflytande på en rad olika fält. I sammanhanget kan det påpekas att denna tro på konsten som kunskapsbärande är delvis överensstämmande med Deleuze och Guattaris resonemang i deras sista samarbete /What is Philosophy?/ där de definierar tre kreativa metoder: filosofi, vetenskap och konst. Egentligen kan mam gå ännu längre och säga att det i princip är överenstämmande med Deleuze hela filosofiska gärning och önskan att bryta ner transcendentala hierarkier att se konst som en form för kunskap. Men om konst är kunskap, eller bär på en kunskapsbärande potential, vari består den? Deleuze och Guattari skriver vidare: 
#+begin_quote
What about the creator? It is independent of the creator through the self positing of the created, which is preserved in itself. What is preserved---this thing for the work of art---/is a bloc of sensations, that is to say, a compound of percepts and affects/. [\ldots] The artist creates blocs of percepts and affects, but the ony law of creation is that the compound must stand up on its own. [[#deleuze1994][deleuze1994]]
#+end_quote
Att konstverket i sig självt, och oberoende av upphovspersonen, har en potential är tydligt men i konstnärlig forskning är det ofta praktiken och vad för slags kunskap den kan bära, snarare än resultatet, som står i centrum. 

Det är möjigt att se konstnärlig praktik som ett sätt att förstå annan kunskap såsom teknik eller filosofi. I dessa fall kan man se den konstnärliga praktiken som en testbädd för ett konceptuellt ramverk. Det finns en aspekt av detta i /Before Sound/ där de filosofiska koncepten prövas mot en existerande praktik och sättet som praktiken utvecklar sig kan då ses som ett utforskande av filosofin. Begreppet /det immanenta planet/ är ett exempel på ett koncept som är centralt för Stjerna och som kan ses på en förklaring genom den konstnärliga praktiken. I teknologisammanhang kan man föreställa sig att en teknik, säg ett programmeringsgränssnitt eller en specifik hårdvara, utforskas i en konstnärlig praktik. Den konstnärliga metoden, som i detta fall ska ses som en experimentell praktik där concept prövas och utvärderas baserat på hur bra eller dåligt de fullföljer den konstnärliga ambitionen, används för att validera teknologin. Det konstnärliga ramverket behöver i sig inte vara experimentell utan kan mycket väl följa en befintlig tradition helt ideomatiskt. En undersökning på denna nivå kan mycket väl leda fram till att till exempel teknologin är bra men den fungerar dåligt i detta konstnärliga sammanhang. Detta förhållningssätt kan ses som en kritiskt evaluering genom konstnärlig metod.

Med en användbar metod kan även själva praktiken ses som en kunskapsgenererande fas. Här ingår de numera ganska vanliga studierna i interpretation eller alternativa tekniker. En frågeställning utforskas genom praktiken och om experimentet lyckas så är det ett bevis på att praktiken är användbar även för andra som söker svar på liknande problem. Även denna typ av undersökningar kan dock sträcka sig bortom den konstnärliga sfären i vilket fall valideringen kan ske åt två håll. En studie i gruppimprovisation kan till exempel visa att visa typer av musikalisk interaktion är gynnsam givet ett visst avsett ändamål. Samma metod kan sedan prövas i andra interaktiva situationer, som social interaktion, och om den visar sig framgångsrik även där så går det att återföra till det musikaliska sammanhanget. Även denna typ av undersökning finns representerad i /Before Sound/, kanske framförallt i relation till den andra forskningsfrågan. I exemplet med /Currents/ är beskrivningen av arbetsmetoderna en kommunikation av en process som inte bara gestaltade dataströmmarna och förhöll sig till de uppställda metoderna utan som också skapar en modell för ett konstnärligt tillvägagångsätt som har politiska och konstnärliga konsekvenser.

En tredje variant är att se det resulterande konstverket som en kunskapskälla på det sätt som Deleuze och Guattari framhåller ovan. Denna strategi har den uppenbara nack- eller fördelar (beroende på hur man ser det). Om det ska stå för sig själv ("stand on its own") så måste det, åtminstone i musik, förlita sig på ickekonceptualiserade kommunikationsformer. Tidigt i kontnärlig forskning var detta normen. Det skulle vara konsten i och för sig själv som utgjorde slutresultatet och det kunskapsbärande elementet i konstnärlig forskning. I praktiken var det endast ett fåtal avhandlingar som gjordes så här men fortfarande är diskussionen om balansen mellan det som lite slarvigt kallas för "det skrivna" och "det gestaltade" aktuell. Det finns naturligtvis flera anledningar till detta, men en relevant punkt som förtjänar att framhållas är att det hela tiden finns en risk att en konstnärlig avhandling är en avhandling med en omfattning som motsvarar monografier inom humaniora inklusive ett konstnärligt arbete som är lika omfångsrikt. Helt enkelt en dubbel avhandling. Om nu det konstnärliga resultatet i sig skulle vara så viktigt hur kan då en avhandling i musik överhuvudtaget kommuniceras utanför sitt uppförande. Om vi accepterar en representation av det i form av en dokumentation, vad är det som säger att en inspelning är bättre än en beskrivande text? Det kan naturligtvis finnas många falla där det är det men den poäng jag försöker göra här är att förutsättningarna för vad som är en relevant dokumentation och/eller diskussion av ett konstnärligt resultat inte kan avgöras på generell nivå utan måste göras på individuell basis.

** Teorin inverkan på metodval och strategier 4000
** Den konstnärliga kunskapens dynamik 4000
** Diskussion 2500
