:PROPERTIES:
:ID:       f6aea3e2-141f-46c2-8757-3fd33f4a0600
:END:
#+title: On the complexities of artistic practice and ethics
#+filetags: :ethics:
#+options: toc:nil num:nil
#+cite_export: csl ~/Dropbox/Documents/articles/biblio/csl-styles/apa-7th.csl
#+LaTeX_HEADER: \usepackage[x11names]{xcolor}
#+LaTeX_HEADER: \hypersetup{linktoc = all, colorlinks = true, urlcolor = DodgerBlue4, citecolor = black, linkcolor = black}
#+latex_header: \usepackage[scaled]{helvet}
\renewcommand\familydefault{\sfdefault}
* COMMENT code
#+begin_src emacs-lisp
  (set-window-margins (selected-window) 20 60)
  (setq line-spacing 0.7)
#+end_src

#+RESULTS:
: 0.7
  
* Introduction
It is fair to assume that both music and ethics lack a clear definition yet play an important role in the life of most people. They are necessary and needed parts of the human condition and have been crucial for many thousands of years. They also have a strong connection: "The relationship between ethics and music is one of the oldest topics in philosophical discussions of music dating at least as far back is Plato" [cite:@cobussen2016; p. 1]. The point I will pursue in this paper is that exploring ethics in artistic practice may complements traditional views on ethics in ways that may be of general interest. This could potentially have an impact on how artistic practices are esteemed in contemporary Western societies. The notion of /the care of the self/ as discussed by Michel Foucault, mainly in /The History of Sexuality/ [cite//c:@foucault1988][fn:7] is used as a method to approach this complex area.

Though the power relations between the arts and current hyper-capitalist and networked culture in the West of the 21st century are unequal to say the least. When all questions and relations are entangled with economy, and thereby to some degree mutilated, the field for alternative understandings of moral questions is shrinking. The panoptic control structures of social-media have become second nature and offer an ethics that is both normative and irrational at the same time. Departing from this rather impenetrable scenario I will introduce ideas about how artistic practice in music can be part of a method with which  challenges may be addressed and offer different values. Values that may offer an interesting opposition, or tension to the values proposed by this structures. These are not necessarily 'better' but can help to unravel the complex questions of what it means to make good decisions and be a good human being. Herein lies also an important distinction between, on the one hand, an ethics of artistic practice as a form for play that I depart from here, and ethics as first philosophy [cite/p:@levinas92] or, an existential ethics of ambiguity [cite:@beauvoir1962] on the other. This is a distinction that makes the two modes of thinking at times incompatible, but not incongruous or inconsistent. I will focus on the former but anticipate acontinuation of this discussion where the thoughts od De Beauvoir will be explored.[fn:8] This text, however, departs from Foucault's ethical condition of the care of the self [cite:@foucault1988] which provides the background to the definition of the main question explored: How can a method be developed that uses artistic practice as an activity in which both ethics and knowledge may be developed, despite the complexities of contemporary social and political systems. In this short format, however, only the surface of this complex discussion will be scratched. The main empirical source is my own artistic work from which I extract experiences, some of which have been previously discussed [cite:see ;@Frisk2013;@frisk12-improv].

In this paper the term /artistic practice in music/ encapsulates all the things a musician[fn:1] do when they engage in making music, preparing for making music, thinking about making music and thinking back on past activities involving music. In fact, there is very little that is not part of the artistic practice. What distinguishes it from other kinds of practices is the central role playfulness has, and the lack of order or destination. Intimately tied to being an artist is that even if activities may be geared towards a particular end or goal, such as a commision or a concert, it is always possible to change direction at any time. Contemporary music since the twentieth century (and also before then), including popular music, is full of examples of this: unexpected and random turns, erratic behaviour and unpredictability are qualities that have been revered and supported.[fn:2] 

* Background
There is an ambiguous relation between artistic practice in music on the one hand, and listening to music on the other that has some impact on the current discussion. It is ambiguous because any creative act obviously has an accompanying act of perceiving, and to be creative in music always involves listening, and listening has a similar creative dimension to it. One of the reasons this relation matters here has to do with the way the field of aesthetics has evolved. If aesthetics originally was involved with the pleasingness of objects, it is quite often used in relation to a range of different topics apart from art and beauty, such as nature, engineering, mathematics, law and order, and much more. In artistic practice it can extend to other aspects of creativity other than the strictly perceptual properties, including the beauty of the design of the music, the systems of creation, and the way the patterns are developing in the construction.[fn:4] Some of these aspects of the music may or may not be obvious or necessary for the listener, while at the same time they may have had a great impact on the creative processes of the artist. They often contribute to what is commonly referred to as an individual aesthetics. For these reasons the aesthetics of musical practice has a different impact, and the focus of the current discussion is the experience of the artist when engaged in their own practice.

The difference, furthermore, introduces an aesthetic distance between the musician and the listener that at first may seem to match the musical semantics of [cite/text/c:@nattiez] and [cite/text/c:@molino].  The model is based on the concept that an analytical understanding of the musical work is, or can be, is based on its total symbolic fact of which mainly two are of interest here: (1) The poietic level may be understood as the stage of creation, where many types of external traces are introduced and produced, all of which pertain to the construction of the work. (2) The esthesic level is inductive in nature and "grounds itself in perceptive introspection" [cite:@nattiez; p. 140]. In essence this model appears to affirms the contrast between the acts of creation and perception.

But her view on the symbolic aspect of music turns out to be rather different.

Susanne [cite:@langer2009] has an at first very similar,  perspective on this. What she labels as the /unconsummated symbol/ in /Philosophy in a New Key/ is related to the way [cite/text/c:@molino] reasons: music does not represent an idea or a fixed meaning. The apprehension of music may even result in contradictory experiences, all of which are /true/ in the meaning that they are subjectively valid.[fn:3] This is one of the first immediate signs of the arts offers a vantage point that is rather different from a social context: One symbol can give rise to contradicting evaluations of which all can be 'right'. In means of communication other than music and the arts, symbolic meanings are consumed and there needs to be a experienced correspondance between sign, signifier and signified. In communication the sign is communicated and consumed, whereby the receiver has an understanding of what the communicator were saying. If not, we may assert that this communication failed. I would go even further and assert that the sounding trace in music is not even an unconsummated sign: it is a proxy, or a becoming. It is a potential that may generate symbolic meaning, but these symbols are not translated in a systematic manner and are not bi-directional. For the artist the associations are organized in a more playful manner, and it is this free play of associations, "this uncritical fusion of impressions, that exercise the powers of symbolic transformation" [cite:@langer2009; p. 124] that will be the main context for the following discussion. .

The semiological models of both Nattiez and Molino as well as Langer are problematic in their own ways, and they are included here mainly to unwrap the complicated topic of aesthetics in perception and creativity. In the discussion of artistic practice and ethics I will reduce this broad view and focus on the aesthetic aspect from the point of view of the artist while engaged in practice, or what [cite/text/c:@langer2009] calls the /artistic import/:
#+begin_quote
This artistic import is what painters and sculptors and forwards express through the depiction of objects and events. Its semantic is the play of lines, masses, colours, textures in plastic hearts, or the play of images, the tension release of ideas, the speed and arrest [...] [cite:@langer2009]
#+end_quote

Play is at the center of this artistic practice. The musician's activities are essentially play acts, also beyond the obvious meaning of /play/, and they allow the listener to experience a connection to similar play acts that are opened up by the free and non-conceptual associations that the music allows for. This notion of play has had a long history and was emphasized by [cite/text/c:@kant2007] in /The Critiques of Judgement/. The basic premise for Kant is that aesthetic appreciation is not rooted in concepts but instead gives rise to a free play of associations, which is in essence what also Langer is referring to. This gives aesthetic communication a somewhat privileged status that is distinct from, say, language and rational thinking, both of which are deeply rooted in symbolic relations. It is privileged because it allows for a type of freedom that promotes actions that would not have been allowed otherwise. Freedom, however, is a word with complicated subtexts. When I use it here I am not primarily talking about the individual's freedom, but about the free association in cognitive activities. The play of children is often used as an example and comparison of this free play. According to Freud /play/ of children is a vehicle for exercising and preparing for life as an adult as described here:
#+begin_quote
Play - let us keep to that name - appears in children while they are learning to make use of words and to put thoughts together. This play probably obeys one of the instincts which compel children to practise their capacities. In doing so they come across pleasurable effects, which arise from a repetition of what is similar, a rediscovery of what is familiar, similarity of sound, etc., and which are to be explained as unsuspected economies in psychical expenditure. It is not to be wondered at that these pleasurable effects encourage children in the pursuit of play [...]. [cite:@freud1971; p. 128]
#+end_quote

These /unsuspected economies/ points to the complex interplay between conscious and subconscious activities and that play is driven by them. Play as a means to learn and discover, but without symbolic transactions, with mental efficiancy. The child is not playing because it will accomplish a goal external to the play. It is /play/ for the sake of playing and the bi-product is knowledge and the wish to discover the meaning of concepts outside of the play. This is in fact very akin to artistic practice. Free associations and free play are essential to creative practice, and it appears to be so both in terms of the level of creativity in the process, and to the quality of the outcome. In short, the level of play affects both. Perhaps it goes without saying that this is very different depending on the context. In most creative situations there is a sensitive balance between how much interference in the form of play the artist may impose on their process before it breaks, and it is interestingly difficult to tell where that limit is.

Play is also a central concept also to [cite/text/c:@langer2009] who explores it in a wide variety of ways.  She points to the fact that play ceases to be important to us only when the value of things outside of the range of the play appear more important, or when there is a fear that these values become threatened:
#+begin_quote
Only people who feel that play displaces something more vital can disapprove of it; otherwise, if the bare necessities were taken care of, work in itself could command no respect, and we would play with all the freedom in the world, if practical work and sheer enjoyment were our only alternatives. [cite:@langer2009]
#+end_quote
Put in different words the player needs to be prepared to engage with the unsuspected economies to approve of it.  Aesthetics becomes a substitute for the lack of play in our adult lives, but only if we accept it to be important. As if there is a sacrifice that one needs to be willing to offer. She is also pointing to the fact that play is the deviation from the norm for the adult. As an art form music offers an opportunity to share the playfulness of artistic creativity with listeners, and thereby compensate for a lack of play and will only work if play is the norm. It is true, as Langer suggests, that this also points to a class aspect of enjoying music. Play is important, but not more important than food on your table, and a such it is a privilege to those who can afford it.

* Method
The important point here is the ways in which the free play in artistic practices allows for new ethical possibilities and relations under circumstances that differ from the traditional views of morality.[fn:10] As part of my method I will situate the musicians' practice in the light of Foucault's idea of the /care of the self/: a method for developing an ethics through engaging with the self's relation to the self, a self that is rooted in "practices of freedom" [cite:@Foucault1997-2; p. 283]: "Freedom is the ontological condition of ethics. But ethics is the considered form that freedom takes when it is informed by reflection" [cite:@Foucault1997-2; p. 284]. The source for Foucault's idea of the care of the self is found in the greco-roman era and his inspiration is thinkers like Socrates ans Seneca. /Care of the self/ has in turn also a dialectical and ontological relation to the wider known paradigm to /know oneself/ and Foucault claims that the former is the condition for the latter: "To take care of oneself consists of knowing oneself. Knowing oneself becomes the object of the quest of concern for self" [cite:@Foucault1997-2; p. 231].

The care of the self can serve here as a bridge between the playful nature of artistic practice, the freedom that is its precursor, and ethics. Although I would hesitate to make any general claims on this relation I will later point to a few examples from my own practice where the link is established. This both in the judicial and political sense of the artist developing their self-agency, and where "one exercises over oneself an authority that nothing limits or threatens"  [cite//c:@foucault1988; p. 64], and in the delight that arises from the process of subjectification. When the subject is freed from external pressures, free from ambition and free from future, past experiences and past practices; different relations with past and future are made possible   [cite//c:@foucault1988; p. 65].  This subjectification is not an imprisonment but a possibility for change. The particular property of the artistic work process as something one may delight oneself in, is of special interest. Important to note is that it is not necessarily the actual object that is delightful, the music or the result of the process, but rather that the driving force is related to a feeling of delight.
#+begin_quote
When you take care of the body you do not take care of the self. The self is not clothing, tools, or possessions; It is to be found in the principle that uses these tools, a principle not of the body of the soul. You have to worry about your soul--that is the principal activity for caring for yourself. The care of the self is the care of the activity and not the care of the soul-as-substance. [cite:@Foucault1997-2; p.231-2]
#+end_quote
The principle that uses the tools of artistic practice is in essence the aesthetics of the creative act: the practice itself.

The care of oneself is also a social practice. It is to create an /art of life/ or an aesthetics of existance: "This 'cultivation of self' can be briefly characterized by the fact that in this case the art of existence--the /techn\=e tou biou/ in its different forms--is dominated by the principle that says one must 'take care of oneself'" [cite:@foucault1988; p. 43]. The commonly used greek word /techne/ is here the origin of Foucault's idea of defining a /Technologies of the self/. /Technology/ should be understood in the sense of an art, or a craft. Care of the self is not merely an attitude towards life and it is not limited to philosophy, or thinking of the self, nor is it deducible to self reflection.[fn:5] The care of the self is active and outward seeking and ongoing, continuous, it is a relfective activity. One important difference between /knowing oneself/ and /care of the self/ is that it is possible to learn to know yourself and be done with--as a concept it signals that there is an end point to the knowing--whereas the care for the self needs to be continuous. 

# this is clear in the passage where Foucault refers to Plato’s /Alcibiades I/ in which the ideas of the self takes shape and leads to the idea that to acquire /techne/ requires care of the self. 
* Artistic practices in music
What may be seen as a rather solipsistic activity of musical artistic practice--practicing an instrument for hours and hours, composing in solitude or improvising--has in fact many similarities with the practice of the care of the self, and may be explored through it. The ambitions of the latter is clearly much wider in scope. The primary aspect of artistic practice that I point to here is the way it explores free play. That is to say that it is the activity of engaging in musical practice that holds the key to an investigation of ethical perspectives, and these may be different to the ruling ethical paradigms driven by contemporary societies. The process is geared towards the promotion of perspectives that may encourage knowledge about the relation of oneself to oneself. 

Though it is obvious that many artists and musician appear to /not/ have taken care of their bodies, so to speak, it is the activities they engage is the primary focus here. First, in developing an active relation to the tools used (e.g. instruments, materials and theoretical perspectives) for the purpose of gradually unfolding the activity which comprises both the art of /doing/ music and the craft of /playing/ it, a notion of the care of the self is instigated. In this activity choices are made that are bound to the framework of it, and that would appear idiosyncratic or even wrong in another context. A musician engaged in an improvisation with other musicians, or a composer working in the studio, may through their artistic practice at times experience a freedom that in itself opens up a field for new practices and new understandings. The choices made here may lead to unexpected results and lead to a particular kind of pleasure that is
#+begin_quote
defined by the fact of not being caused by anything that is independent of ourselves and therefore escapes our control. It arises out of ourselves and within ourselves. [cite:@foucault1988;, p.66, with reference to [cite:@seneca2015]]
#+end_quote

Second, the act of musical collaboration, such as playing with other people, brings about a particular ethical quality that may at times extend beyond what we normally consider being ethical behaviour. This is described by others [cite//c:e.g. ;@cobussen2016] and has its roots in the fact that in the performance, under certain circumstances, it is not the social relations the self is involved in with others that matters, but rather, it is the activity itself that is the end goal. This may loosely be compared to the Foucault's claim that /the care of the self/ is ontologically prior to /knowing thyself/ [cite:@Foucault1997-2; p. 226]. The care of the self in this case is to care for the situation and the pleasure that arises from it and it is only if this succeeds that I can know myself and what my limits are as an individual. The first state is outwards looking, extrospective, and the second is introspective. 

Hence, artistic practice is an arena that may at least in a limited sense be understood through the technologies of the self the way these are defined by Foucault, and of which the care of the self is apart. Aesthetics contributes to the cultivation of the self by way of which an understanding of what artistic practices may contribute to the field of ethics emerges.
One of the main reasons creative practices in music has a special status in this context is that its objective is not controlled by outside forces, but is continuously renegotiated by the musician in a free play. Cultivating this freedom through practicing music is part of the act of taking care of one self, but this also includes new ethical possibilities and limitations.

In my paper /Improvisation and the self: To listen to the other/ [cite:@frisk12-improv] I describe a situation where, for the lack of a better expression, the social ethics, inflicted on the musical practice ethics. In the former I felt obliged to behaved in a way that was, in a way, respectful of the other. In fact, howver, this had a /negative/ effect on the aesthetic possibilities the situation offered. A slightly different situation is described in /The (un)necessary Self/ [cite:@Frisk2013] where the freedom the situation offers, and requires, results in musical choices that may appear unethical both to the other musicians, and to the audience, but which are in fact completely logical within the frame of the practice, which is also to say that they follow the principle of the care of the self. In this example I rose to the demands of the musical situation and had to fight to get rid of expectations of the past. The result of this particular activity may or may not have been 'good' music, and it may well in the end be concluded that I acted unethically, but, as observed from the other side, I cared for myself and took responsibility for my own relation to myself and it clearly developed my own view on the ethics of artistic practices.

Reflecting on how the developments in the current hyper-capitalist market economy of the twenty first century may make the use of ethics, in particular that of artistic practice, seem both peripheral and insignificant. Art is not held in high esteem if valued in the currency of the market economy--unless it may function as an investment. Music is commodified in a way that sometimes makes it difficult to understand it in any other way than as an object and a product. With power and efficiency the market capitalizes on self-help ideologies rooted in religion and psychologye that may resemble the care for the self that Foucault describes. It appropriates concepts as well as actions and is devoid of responsibility and care in the traditional sense. Though critical of Foucault, Jean Baudrillard analyzes the way that capitalism operates through his logic of simulation: "we cannot get direct access to the real because our observations of it and our language about it are theory-dependent" [cite:@Smith1998]. The negative ethics he describes, in what may be interpreted as the abolishment of care of the self in a media obsessed world where reality is replaced by systems of symbols and signs, brings to mind the fact that we are already living in the simulacra:
#+begin_quote
Machines produce only machines. This is increasingly true as the virtual technologies develop. At a certain level of machiniation, of immersion in virtual machinery, there is no longer any man-machine distinction: The machine is on both sides of the interface. [cite:@baudrillard02; p. 177]
#+end_quote
In the quote above it is possible to substitute 'Machine' for 'Market' : there is no longer any man-market distinction. Every subject is a market. Even corporate ethics is commodified and rendered streamlined and efficient. Arguing for the need and increased status of artistic practices in such a world a may be seen as a lost cause. Yet, for the very reason that the role of this practice may appear subordinate and fringe, both the freedom that artistic practice engenders, and the developed sense of ethics that it promotes, share the same urgency: an opportunity for change and development. Foucault might have concurred with the comparison of this to transforming ones existence into an ouevre, an aesthetics of life, but for the artist the idea is rather to make the artistic practice the arena on which ethical perspectives may be developed: a hybrid practice.

If, at least for the time being, the necessity of both arts and ethics has been determined, comparing the arts to ethics may appear to be unequal and difficult to compare. Judgments such as right and wrong are in essence both difficult and useless to employ in music, but are in fact equally difficult to judge in ethics. In both cases there is a need for a framework through which the judgements may applied. To see artistic practice as a way of life through which knowledge of oneself is developed through the care of the self is a means through which ethics can be developed. Foucault's description of how the changing political status altered the ground on which ethical matters were founded in the first centuries A.D. makes an interesting comparison possible:
#+begin_quote
Whereas formerly ethics implied a close connection between power over oneself and power over others, and therefore had to refer to the aesthetics of life that accorded with one's status, the new rules of the political game made it more difficult to define the relations between what one was, what one could do, and what one was expected to accomplish. The formation of oneself as the ethical subject to one's own actions became more problematic. [cite:@foucault1988; p. 84]
#+end_quote
The new rules of the post-political hyper-capitalist game makes it necessary to explore areas that are independent from the ways that the status of the commodified self is commonly raised. Artistic practice is such a field, at least the part of it that occurs before the artistic object has been objectified.[fn:9]

* Discussion

In their book /Music and Ethics/ [cite:@cobussen2016] Marcel Cobussen and Nanette Nielsen states that music and ethics are "both indeterminate concepts, capable of referring to a variety of practices" (p. 3). This is inline with what I try to argue in this paper, even though I would like to push this even further: it is /necessary/ that we refer both music and ethics to a variety of practices and that these practices are allowed to exploit a free play of associations. A little later they write that "once we begin exploring the area music /and/ ethics the complexity increases exponentially" [cite:@cobussen2016; p. 3] which I would argue is not always true, probably mainly since their starting point and general perspective is slightly different from mine. My point is somewhat the opposite. By exploring ethics in and through musical practices a certain clarity may be revealed. The result may be an articulation that is embedded in complexity but this is not in opposition to the simplicity of the method: the care of the self in free play..

Finally, as a closing remark, given that artistic practice is a setting for the care of the self, and for alternate views on ethics, a mention needs to be made for artistic research, a particular case of artistic practices. Artistic research raises complex questions concerning the relation between artistic freedom and research ethics.

The ethics of the artistic practice may at certain times find itself to be in opposition to the research ethics in which case there will always be a risk that the dominant paradigm, in this case the academically certified ethics, will preside. There are clearly obvious rules that also artistic research needs to abide to, but this should not limit the practice to explore other paths and arenas. But it is equally important to not shut down the freedom of the field of practice prematurely but allow the artist and researcher to pursue the project where the project leads them. In methodologically sound projects the conflict will not be a problem. There is a tremendous epistemological capacity in the conflict between two views on ethics that may arise in such circumstances. The activity of artistic practice--and the engagement with the results of that practice--as an act of taking care of the self offers important possibilities to discuss some of the urgent questions today and may give rise to an ethics of aesthetics that may help us understand some of the pressing issues of today.

# whether it concerns the care of the self or fundamental ethical question.
* Bibliography
# #+bibliographystyle: unsrtnat
#+print_bibliography: title: "Bilblio"

* Footnotes
[fn:10] The line of morality rooted in Aristotele's  Nicomachean Ethics 

[fn:9] This is not to say that the appreciation of this object does not also have the possibility to further the subjectification of the self in manners that are similar to those of the practice. 
[fn:8] I am currently working on a related paper that takes this approach. 

[fn:7] I use mainly section two and three of /The History of Sexuality/ and I make explicit references to the text when needed. But I also use the text as an inspiration and have allowed myself to make interpretations that may not be in line with those a Foucault scholar would do here necessary.

[fn:5] Self reflection is a term equally common as it is problematic in todays discourse on artistic practice and education and should, I believe be handled with care to avoid that everything and nothing becomes reflection.
[fn:4] This was a trade mark of early modernism and the later rise of conceptual art. 

[fn:3] They are however not entirely subjective because, as is explained by Roger Scruton in XXX, they may still have a universal claim. See Kant subjective and universal.
[fn:2] A few notable examples are Beethoven's String quartet Op. 131 [cite:@Betthoven1826] that came out in seven movements rather than the expected format of four movements, /Come Out/ by Steve [cite/text/c:@reich1966] which became a memorial as such for the Harlem Six trials and the American civil rights movement that was unexpected even for the composer [cite:@Gopinath2009], and Bob Dylan's decision to take the stage with an electric guitar at the Newport Folk Festival 1965, "backed by a band organized the night before" created havoc and "not only disrupted the closing night of the Festival, but blew apart the music scene that had created it" [cite:@Stone2015].

# As a side note the stylistic changes, sub-genres and definitions in pop and rock that are created  at an ever increasing rate may be seen as an example of this.

[fn:1] I use the term /musician/ throughout and it should be understood to include any and all forms for musical production 
* COMMENT Stuff
# The way aesthetically rooted experiences may be examined through the lens Foucault's /aesthetics of life/ as a tool for a critical analysis is further discussed. 
It is part of the subjectification of the self, of giving the control back to the self. It takes place in a social system but in a way that allows for the formation of an ethical subjectivity, one that is not controlled from an outside power, and which is free from the fear of the future. To summarize: The care of the self allows the subject to engage in its own processes of subjectification.

It may seem like a big jump to Derrida, but he is in fact connecting the dots here between structurality, Freud and free play.[cite:@der78]

 Aesthetically rooted experiences will be examined through the lens of Foucault's /aesthetics of life/ through de Beauvoir's remark of aesthetic masking as a tool for a critical analysis.
 
At the time right after the second world war we were facing similar difficulties trying to comprehend a human disaster of previously unknown proportions. It was from this horizon that Simone DeBeavoir defined her ethics of ambiguity which will be of great significance for this chapter.

Similarly it is only with the strict separation of station auditorium to the spectator is a participant in his her own right everything today conspires to abolish that separation the spectator being brought into a user friendly interactive immersion the apogee of the spectator or his/her N when all our actors there is no action any longer no seen the end of the astatic illusion
[cite:@baudrillard02; p. 176] [cite:@baudrillard02]
# , and how it may be used in relation to other systems of ethics.

The fact that artistic production is a free play

The pleasure that one may find when I as a subject have access to myself for myself, and that I have come to terms with the shortcomings that I have and where I do not allow whatever limits there will be to my capacity to influence me negatively is

is on how beauty, for example, is perceived whereas the discussion on how beauty is created is to a larger extent part of the field of artistic training.

Much points to this free play that artistic practice explores is



** Foucault used
Altough I would hesitate to make any general claims on this relation I would like to propose that there is a link between artistic practices (in music) and Foucault's ideas on the cultivation of the self. This both in the judicial sense of the artist belonging to themselves and of being their own masters and in terms of the particular ability of the work of the artist as something we seek to delight our selves in. Not because this work is delightful, but because the driving force is related to a feeling of delight.

According to Foucault taking care of the self is not merely an attitude towards life and it is not limited to a philosophy, or a thinking of the self, it is not deducible to self reflection--a term equally common as it is problematic in todays discourse on artistic practice. The origin of this particular one of his technologies of the self is greco-roman and stems from figures such as Seneca and Augustine. But in one passage Foucault refers to Plato’s /Alcibiades I/ in which the ideas of the self takes shape and leads to the idea that to acquire /techne/ requires care of the self. Foucault compares this to the farmer that takes care of the land. This care is not only relfective, it is active and outward seeking and ongoing, continuous.

What may appear as the rather egoistic activity of practicing an instrument, composing or improvising has in fact many similarities with care of the self. It is obvious that many artists and musician have not taken care of themselves, but the activities they engage in have some similar boundaries as the taking care of the self. They have an active relation to techne, to the doing in the real world, in a meeting with other people.


