:PROPERTIES:
:ID:       f6aea3e2-141f-46c2-8757-3fd33f4a0600
:END:
#+title: On the complexities ethics in artistic practices
#+filetags: :ethics:
#+options: toc:nil num:nil
#+cite_export: csl ~/Dropbox/Documents/articles/biblio/csl-styles/apa-7th.csl
#+LaTeX_HEADER: \usepackage[x11names]{xcolor}
#+LaTeX_HEADER: \hypersetup{linktoc = all, colorlinks = true, urlcolor = DodgerBlue4, citecolor = black, linkcolor = black}
#+latex_header: \usepackage[scaled]{helvet}
\renewcommand\familydefault{\sfdefault}
* COMMENT code
#+begin_src emacs-lisp
  (set-window-margins (selected-window) 20 40)
  (setq line-spacing 0.7)
#+end_src

#+RESULTS:
: 0.7
  
* Introduction
It is fair to assume that both music and ethics lack a clear definition yet play an important role in the life of most people. They are necessary parts of the human condition and have been so for many thousands of years. There is also a strong connection between them as pointed out in the opening of the book /Music and Ethics/ by  [cite/text/c:@cobussen2016]: "The relationship between ethics and music is one of the oldest topics in philosophical discussions of music dating at least as far back is Plato" (p. 1). The point I will pursue in this paper is that exploring ethics in artistic practice may complement traditional views on ethics in ways that may be of general interest. This could potentially have an impact on how artistic practices are esteemed in contemporary Western societies. The notion of the /Care of the Self/ as discussed by Michel Foucault, mainly in /The History of Sexuality/ [cite//c:@foucault1988][fn:1] is used as a method to approach this complex area.

The power relations between the arts and current hyper-capitalist and networked culture in the West of the 21st century are unequal, to say the least. When all questions and relations are entangled with economy, and thereby to some degree mutilated, the possiblity for alternative understandings of moral questions is shrinking. In only a little more than a decade have the panoptic control structures of social-media become second nature and they offer an understanding of ethics that is both normative and irrational. Departing from this rather impenetrable scenario I will introduce ideas about how artistic practice in music can be part of a method with which some of these challenges may be confronted, as well as introduce different values. Values that may offer an interesting opposition, or tension, to the those proposed by the dominant capitalist structures. These are not necessarily 'better' but can help to reveal how a multiplicity of perspectives can be applied to questions of what it means to make /good decisions/ and be a /good human being/. In this text I primarily refer to an ethics of artistic practice as a form for play which may not be completely line up with other ethical theories, but my point of entry is the artistic practice first and foremost, and how it enables ethical perspectives. In a continuation of this work I anticipate that both ethics as first philosophy [cite/p:@levinas92] and an existential ethics of ambiguity [cite:@beauvoir1962] would provide valuable insights.

To approach this difficult matter Foucault's thoughts about the ethical condition of the care of the self [cite:@foucault1988] provides the background to the definition of the main question: How can a method be developed that uses artistic practice as an activity in which ethics may be developed, despite the complexities of contemporary social and political systems. In this short format only the surface of this complex field will be scratched. The main empirical source is my own artistic work from which I extract experiences, some of which have been previously discussed [cite:see ;@Frisk2013;@frisk12-improv].

In this paper the term /artistic practice in music/ encapsulates all the things a musician[fn:2] do when they engage in making music, preparing for making music, thinking about making music and thinking back on past activities involving music. Similarily, any reference to /musician/ should be understood to include and kind of musician including, but not limited to composers, producers and sound artist. There is very little in the activity of a musician that is not part of the artistic practice which is the reason I sometimes refer to it as an /hybrid practice/.[fn:3] What distinguishes it from other kinds of practices is the central role playfulness has, and the lack of order or destination in some phases of the work. What I mean by this is that intimately tied to being an artist is that even if activities may be geared towards a particular end or goal, such as a commission or a concert, it is always possible to change direction at any time, and that this freedom is a characteristic artistic practices. This freedom is in conflict with the interests of hyper-capitalism, the desire of which it is to narrow down the fields of possibilities. Contemporary music since the twentieth century and earlier, including popular music, is full of examples of this: unexpected and random turns, erratic behaviour and unpredictability are qualities that have been revered and supported by the field.[fn:4] 

* Background
There is an ambiguous relation between artistic practice in music on the one hand, and listening to music on the other that has some impact on the current discussion. It is ambiguous because any creative act in music obviously has an accompanying act of listening. To be creative in music always involves listening, and a listener always engages in a creative activity when listening. One of the reasons the distinction between the different kinds of creativity--listening and creating--matters here has partly to do with the way the field of aesthetics has had a focus on the perception of art rather than the creation. Furthermore, if aesthetics originally was coined by the German philosopher Alexander Gottlieb Baumgarten as the science of sensible knowledge [cite:see ;@danius2012;, chapter 2] it has come to be used in relation to a range of different topics, such as nature, engineering, mathematics, law and order, and much more. In artistic practice it can extend to aspects of creativity other than strictly perceptual or sensible properties, including the beauty of the design of the music, the systems of creation, and the way the patterns are developing in the construction.[fn:5] Some of these aesthetic characteristics of the music may or may not be obvious or necessary for the listener, while at the same time they may have had a great impact on the creative processes of the artist. They contribute to an individual aesthetics, a set of properties defined by a method of working, and, in this case the aesthetics is not necessarily what is sensible but what shapes the sensibility of the practice.

The difference between the experience within the creative act and the sensation of listening to it introduces an aesthetic distance between the musician and the listener that at first may seem to match the musical semantics of [cite/text/c:@nattiez] and [cite/text/c:@molino].  Their semiological theory is concerned with an analytical understanding of the musical work based on its symbolic fact divided in three separate processes. The first and third constitute: (1) the poietic level which may be understood as the stage of creation where many types of external traces are introduced and produced, all of which pertain to the construction of the work, and (2) the esthesic level which is inductive in nature and "grounds itself in perceptive introspection" [cite:@nattiez p. 140]. 

Susanne [cite/text/c:@langer2009] has an at first very similar,  perspective on this. What she labels the /unconsummated symbol/ in her book /Philosophy in a New Key/ is related to the way [cite/text/c:@molino] reasons: music does not represent an idea or a fixed meaning. The apprehension of music may even result in contradictory experiences within the listeners, all of which are /true/ in the meaning that they are subjectively valid. Even so, they may still make universal claims. On this matter music and the arts in general offers a vantage point rather different from a social context: one symbol can give rise to several contradicting evaluations of which all can be 'right'. In most types of communication symbolic meanings are consumed, and there needs to be an agreed correspondence between sign, signifier and signified. In successful communication the sign is communicated and consumed, whereby the receiver has an understanding of what the communicator were saying. If not, we may assert that this communication failed. When listening to music, not only does it not appear to matter if one knows the aesthetic of the musician, it does not matter if the message is communicated properly. There may not even be a message, and this has consequences for the ethical relations that may develop in such contexts.

Following this a possibly even more radical assertion may be made. The sounding trace in music may not even be an unconsummated sign, as Langer says, it may be seen as a proxy, or a becoming. It is a potential that may generate symbolic meaning, but the symbols are not translated in a systematic manner and are not bi-directional. For the artist the associations are organized through a playful manner, and it is this free play of associations, "this uncritical fusion of impressions, that exercise the powers of symbolic transformation" [cite:@langer2009 p. 124] that will be the main context for the following discussion.

The semiological models of both Nattiez and Molino, as well as Langer, are problematic in their own ways, and they are included here mainly to attempt to unwrap the complicated topic of aesthetics in perception and creativity. In the discussion of artistic practice and ethics below I will reduce this broad view and focus on the aesthetic aspect from the point of view of the artist while engaged in practice, or what [cite/text/c:@langer2009] calls the /artistic import/:
#+begin_quote
This artistic import is what painters and sculptors and forwards express through the depiction of objects and events. Its semantic is the play of lines, masses, colours, textures in plastic hearts, or the play of images, the tension release of ideas, the speed and arrest [...] (p. 257)
#+end_quote

Play is at the center of this artistic practice. The musician's activities are essentially play acts, also beyond the obvious meaning of /play/ in music, and they allow the listener to experience a connection to similar individual play acts that are opened up by the free and non-conceptual associations that the music allows for. This notion of play has had a long history and was emphasized by [cite/text/c:@kant2007] in /The Critiques of Judgement/. The basic premise for Kant is that aesthetic appreciation is not rooted in concepts but instead gives rise to a free play of associations, which is in essence what also Langer is referring to above. This gives aesthetic communication a somewhat privileged status that is distinct from, say, language and rational thinking, both of which are deeply rooted in symbolic terminology. It is privileged because it allows for a type of freedom that promotes actions that would not have been allowed otherwise.
Schiller, heavily influenced by Kant, goes further and writes that:
#+begin_quote
the object of the play impulse, conceived in a general notion, can therefore be called living shape, a concept which serves to denote all aesthetic qualities of phenomena and--in a word--what we call /Beauty/ in the widest sense of the term. [cite:@Schiller2004 15th letter, 2nd para.]
#+end_quote 

The complex interplay between conscious and subconscious activities is a driving force behind this play. Play as a means to learn and discover with mental efficiancy, but without symbolic transactions. The artist is not playing because it will accomplish a goal external to the play. The /play/ is for the sake of playing and the bi-product is knowledge and the discovery of the meaning of concepts outside of the play. Free associations and free play are essential to creative practice, and it appears to be so both in terms of the level of creativity in the process, and to the quality of the outcome. In short, the level of play affects both. Perhaps it goes without saying that this is very different depending on the context. In most creative situations there is a sensible balance between the interference the artist may impose on their processes--in the form of play--and the level of structure they maintain, and it is interestingly difficult to tell how that balance will play out in practice.
The freedom that this process generates should in the following be understood as primarily valid in the context of the play of free association in artistic practices.

Susanne [cite/text/c:@langer2009] explores play in a wide variety of ways in her texts, and points to the fact that it ceases to be important to us only when essential needs are not taken care of:
#+begin_quote
Only people who feel that play displaces something more vital can disapprove of it; otherwise, if the bare necessities were taken care of, work in itself could command no respect, and we would play with all the freedom in the world, if practical work and sheer enjoyment were our only alternatives. (p. 158)
#+end_quote
Put in different words, those that engage in play can rejoice in freedom, but only if there is space for it. This points to a class aspect of engaging in musical practice. Play is important, but not more important than food on the table, and as such it is a privilege to those who can afford it. There is a sacrifice that one needs to be willing to offer, a price, insignificant to those that can afford and insurmountable to others. However, it is not due to this particular economy that play is the deviation from the norm. 

The abundance of accessible media is also an obstacle to play. When the landscape is saturated with easily accessible media the play may appear obscure, and the thing more vital than play can be all these outlets for which there is no need to enroll in active relations. The commodified art object is a neoliberal found object, ready to be consumed as is, and it makes it easy to disapprove of the play. Its economy and apparent value is in stark contrast to the slowly developing play of artistic practice. There is an obvious disagreement between the capacity of the freedom of play and the dominant market features of capitalism. Despite the unbalanced power relation between the art field and the neo-capitalist market force, the latter nevertheless fears the freedom of play that art enables and sees it as a threat to the thing most precious to capitalism, the commodified objects market value. As an art form music offers an opportunity to share the playfulness of artistic creativity with listeners, but is oddly disparaged by the media object of post capitalism. I will return to how this imacts on the way that play develope through ethics.

* Method
What are the new ethical possibilities and relations in this play act, and how do they differ from the traditional views of morality?[fn:6] As part of my method I will situate the musicians' practice in the light of Foucault's idea of the care of the self: a method for developing an ethics through engaging with the self's relation to the self, a self that is rooted in "practices of freedom" [cite:@Foucault1997-2 p. 283]: "Freedom is the ontological condition of ethics. But ethics is the considered form that freedom takes when it is informed by reflection" [cite:@Foucault1997-2 p. 284]. Following the discussion in the previous section, and grounding it on this statement by Foucault, I wish to promote the following idea: The free play of artistic practice institutes an expression of freedom that allows for a particular kind of ethics because it is informed by the reflection that the free play encourages. The free play of artistic practice is an activity of the care of the self and the freedom that is generated should not be seen as general, but is rather locally constituted. The care of the self allows for a multiplicity of ethical relations which stand out in strong contrast to the homogeneity favoured by contemporary hyper-capitalism.

The care of the self also has a dialectical and ontological relation to the wider known paradigm to /know oneself/ and [cite/text/c:@Foucault1997-2] claims that the former is the condition for the latter: "To take care of oneself consists of knowing oneself. Knowing oneself becomes the object of the quest of concern for self" (p. 231). 
Hence, the care of the self can serve here as an activity within which the playful nature of artistic practice takes place in a particular kind of freedom that is the precursor of ethics. Although I would hesitate to make any general claims on these relations I will later point to a few examples from my own practice where this link is established. These examples explore the issue both from the judicial and political perspectives where the artist develops their self-agency, as well as a in contexts described by [cite/text/c:@foucault1988] where "one exercises over oneself an authority that nothing limits or threatens" (p. 64). When the subject is freed from external pressures, free from ambition and free from future, past experiences and past practices; new relations with past and future are made possible  [cite//c:@foucault1988 p. 65]. In essence this is a process of subjectification that is not an imprisonment, but a possibility for change. The particular property of the artistic work process as something one may delight oneself in, is of special interest in the care of the self. It is not necessarily the actual object that is delightful, the music or the result of the process, but rather that the driving force is related to a feeling of delight. Furthermore, which is important, the care of the self is not about taking care of the physical self or the appearance:
#+begin_quote
When you take care of the body you do not take care of the self. The self is not clothing, tools, or possessions; It is to be found in the principle that uses these tools, a principle not of the body of the soul. You have to worry about your soul--that is the principal activity for caring for yourself. The care of the self is the care of the activity and not the care of the soul-as-substance. [cite:@Foucault1997-2 p.231-2]
#+end_quote
The principle that uses the tools of artistic practice is in essence the aesthetics of the creative act: it develops in free play, and whitin this practice a possible ethics is revealed.

The care of oneself is a social practice. It is, to quote  [cite/text/c:@foucault1988], to create an /art of life/ or an aesthetics of existance: "This 'cultivation of self' can be briefly characterized by the fact that in this case the art of existence is dominated by the principle that says one must 'take care of oneself'" (p. 43). The commonly used greek word /techne/ is here the origin of Foucault's idea of defining a /Technologies of the self/. /Technology/ should be understood in the sense of an art, or a craft. Care of the self is not merely an attitude towards life and it is not limited to philosophy, or thinking of the self, and nor is it deducible to self reflection.[fn:7] The care of the self is active and outward seeking, ongoing, continuous, it is a relfective activity. One important difference between /knowing oneself/ and /care of the self/ is that it is possible to learn to know yourself and be done with it. As a concept it signals that there is an end point to the knowing, the point at which everything is known.  The care for the self, however, needs to be continuous, and like the practice of music which sees no end to its perfection.

# this is clear in the passage where Foucault refers to Plato’s /Alcibiades I/ in which the ideas of the self takes shape and leads to the idea that to acquire /techne/ requires care of the self. 
* Artistic practices in music
What may appear as a rather solipsistic activity of musical artistic practice--practicing an instrument for hours and hours, composing in solitude or improvising, or any of the related artistic activities--has in fact many similarities with the practice of the care of the self, and may therefore be explored through it. It should be noted that the ambitions of the latter is clearly much wider in scope, and artistic practice can only be said to be able to activate a small portion of what is constituted by the care of the self. The primary aspect of artistic practice here, as was noted above, is the way free play is employed, and as a consequence how freedom is developed.
Since ethics, according to Foucault, is a form that freedom takes, artistic practice as a vehicle of free play, is a way in which ethics may be explored. That is to say that it is the activity of engaging in musical practice that holds the key to this investigation of ethical perspectives, and these may be different to the ruling ethical paradigms driven by contemporary society. The process is geared towards the promotion of perspectives that may encourage knowledge about the relation of oneself to oneself, informed by the care of the self.

Though it is obvious that many artists and musician appear to /not/ have taken care of their bodies, so to speak, as was pointed out by Foucault above, it is the activities they engage in that are the primary focus here. These unfold roughly according to the following two states:

(1) First, in developing an active relation to the tools used in the process (e.g. instruments, materials and theoretical perspectives) a notion of the care of the self is instigated and gradually unfolds the activity which comprises both the art of /doing/ music and the craft of /playing/ it. In this activity choices are commonly made that are at first bound to a chosen framework that may make them appear idiosyncratic or even wrong in another context. Nevertheless, through the free play also these frameworks may be renegotiated in unexpected ways. A musician engaged in an improvisation with other musicians, or a composer working in the studio, may at times experience a freedom that in itself opens up a field for new understandings. The activities here may have unexpected results and lead to a particular kind of pleasure that is:
#+begin_quote
defined by the fact of not being caused by anything that is independent of ourselves and therefore escapes our control. It arises out of ourselves and within ourselves. [cite:@foucault1988 p. 66 with reference to ;@seneca2015]
#+end_quote

(2) Second, the act of musical collaboration, such as playing with other people, brings about a particular ethical quality that may at times extend beyond what we normally consider being ethical behaviour. This is described by others [cite//c:e.g. ;@cobussen2016] and has its roots in the fact that in performance, under certain circumstances, it is not the social relations that the self is involved in with others that matters, but rather, it is the activity itself, the proxy, that is the destination and focus. This may loosely be compared to Foucault's claim that /the care of the self/ is ontologically prior to /knowing thyself/ [cite:@Foucault1997-2 p. 226]. The care of the self in this case is to care for the situation and the pleasure that arises from it, and only if this succeeds can the particpants know themselves and know their limits as individuals.

The first state is outwards looking, extrospective, and the second is introspective. 

Hence, artistic practice is an arena that may, at least in a limited sense, be understood through the technologies of the self the way these are defined by Foucault, and of which the care of the self is a part. Aesthetics contributes to the cultivation of the self by way of which an understanding of what artistic practices may contribute to the field of ethics emerges.
One of the main reasons creative practices in music has a special status in this context is that its objective is not controlled by outside forces, but is continuously renegotiated by the musician(s) in the free play.

* Experiences of artistic practice and ethics
In my paper /Improvisation and the self: To listen to the other/ [cite:@frisk12-improv] I describe a situation where my judgment concerning what was the correct mode of interacting in a rehearsal inflicted on the expectations of the musical practice.  In this particular rehearsal we were trying out material for a new piece by me. It was primarily myself and two Vietnamese musicians, neither of which spoke English very well which further impacted on my behaviour. They were in my studio, as visitors in my home country which made me self conscious and I tried to be very gentle, allowing for their input. Contrary to my intention this had a /negative/ effect on the interaction, and very little was accomplished in the session. From the point of view of the practice, in the play that I intended to initiate, there was instead an expectation of firm decisions, but i doing so I felt would I would have had to disregard the ethical concerns I had in our social interaction. As a consequence of this mismatch, that is, my inability to clearly see what the object of our rehearsal was. No play emerged, and in a later conversation the two Vienamese musicians explained that they found my behvaiour in the session unnecesarily hesitant and that this prevented them to perform well. Though it is clear to me now what happened and why, by any other standard I would argue that my behaviour was perfectly reasonable.

A slightly different situation is described in /The (un)necessary Self/ [cite:@Frisk2013] where the freedom the particular situation offered, and required, allowed for musical choices that may appear to have been unethical both to the other musicians, and to the audience, but which were in fact completely logical within the frame of the practice. The context was a concert during a tour in which I, for various reasons that are not important here, felt a growing frustration with my own performance. This frustration extended and by the time of the concert in question it was unbearable. It culminated right before the start of the show in an uncanny feeling that I had lost my musical agency, or at least, that it was severely limited. I eventually resolved it by approaching my performance by playing the saxophone as if I had never seen the instrument before, pretending I had only a very basic understanding of its functionality. This initiated a very strong feeling of play and freedom which was musically successful in the sense that it resolved part of my frustration and helped me regain my agency. I took care of my self and the situation I was in though it may have been that I put my co-musicians in an awkward position. Nothing of what we had prepared could obviously be played as planned. In this example I rose to the demands of the musical situation and developed a kind of self-agency as it was discussed above, one in which I was able to rid my self of the expectations of the past and future. The result of this particular activity may or may not have been 'good' music, and it may well in the end be concluded that a better option would have been to prepare my fellow musicians and discuss various options instead of forcing them to deal with it on stage. Observed from the other side, however, I argue that exercising my care for the self was the only way forward considering the situation in the group--even if I was not able to make this analysis at the time. I took responsibility for my own relation to myself which clearly developed my own view on the ethics of artistic practices. Furthermore, it is important to stress that the care for the self in this situation does not stand in opposition to what would be considered a mutual care, or care for the other. The care for the self is a vehicle through which the tool of artistic knowledge is focused on the unconssumated symbol, as Susanne Langer puts it, of artistic practice.
My argument here is that artistic practice as a proxy for human relations is /the Other/ towards which the ethics of the situation is related.
In that sense the ethics departs not primarily from the human-human relation but from the human-practice relation, although this too is a simplification. 

There is a common practice in jazz to introduce last minute changes.[fn:8] There are numerous stories of bandleaders that instigate insecurity in their band members right before the start of the performance. There are several accounts of Miles Davis doing this, as well as many other. An analysis of this behaviour based on the current discussion is that they attempt to destabilize the performance situation in order to force the musicians into the logic of the care for the self. A certain urgency is unravelled through this behaviour that appears to benefit the performance. Meanwhile, the practice of consciously making the other uncomfortable certainly could appear to have negative ethical implications. Yet, judged from the point of the practice, and as long as the behaviour is aligned with the needs of the performance, this practice is not only acceptable, it is also useful. Similar, but less ethically charged is how I as a composer, in the act of composing, will easily get lost if an imagined listener is at the forefront of my work. This is not to say that I wish to ignore the potential listener either, there is no binary relation here, only a shift in perspectives in a multidimensional field. The care of the self in this context is to care for all of the sets of conditions that shape the artistic practice, and to do so with the focus on the object of the practice. In this frame of mind ethical standpoints that may deviate from traditional views on ethics may emerge.[fn:9] I will argue that an important aspect of artistic practice is to push the boundaries for what ethics allows for. Even if an ethical judgment of the work from outside of the artistic practice may reveal it to cross boundaries it should not cross, it is important that it still may be able to do it.

Reflecting on how the developments of the neo-liberal market economy of the twenty first century, its use of ethics and its relation to the arts, makes this discussion seem peripheral, and the marginal effect that the ethics of artistic practice may have may insignificant.
Art is not held in high esteem if valued in the currency of the market economy--unless it may function as an investment. Music is commodified in a way that sometimes makes it difficult to understand it in any other way than as a product. Even listening itself, the most ephemeral and fragile mode of becoming is commodified. Furthermore, with power and efficiency the market capitalizes on self-help ideologies that are rooted in crude reductions of self knowledge and care for the self. It appropriates concepts as well as actions and is devoid of responsibility and care in the traditional sense. Jean Baudrillard[fn:10] analyzes the way that capitalism operates through his logic of simulation: "we cannot get direct access to the real because our observations of it and our language about it are theory-dependent" [cite:in @Smith1998]. In this world the role of free play and freedom is brutally reduced and the negative ethics Baudrillard describes may be interpreted as the complete abolishment of care of the self. It is a world in which affirmative ethics, let alone artistic ethics, is not possible. Without acceess to the real /the Other/ can not be addressed. The media obsessed world where reality is replaced by systems of symbols and signs, and everything is transactional and consumed, brings to mind the fact that we are already living in the simulacra:
#+begin_quote
Machines produce only machines. This is increasingly true as the virtual technologies develop. At a certain level of machiniation, of immersion in virtual machinery, there is no longer any man-machine distinction: The machine is on both sides of the interface. [cite:@baudrillard02 p. 177]
#+end_quote
In this passage it is entirely possible to substitute 'Machine' for 'Market': there is no longer any man-market distinction. Every subject is a market. Even corporate ethics is commodified and rendered streamlined and efficient. Arguing for the need and increased status of artistic practices in this environment may be seen as a lost cause. Yet, for the very reason that the role of this practice may appear subordinate and fringe, both the freedom that artistic practice engenders, and the developed sense of ethics that it promotes, share the same urgency: an opportunity for change and development. I align myself to the hopefulness of a continued force of enlightenment and claim that change is possible.
Foucault's ambition to transform his existence into an ouevre through the aesthetics of life, may be compared to this opportunity for change, but for the artist the idea is to make the artistic practice the arena on which ethical perspectives may be developed rather than the self. In its extension it makes possible a hybrid practice where the dividing lines between art, life and practice are no longer possible to draw with clear distinction.

If, at least for the time being, the necessity of both arts and ethics has been determined, comparing the arts to ethics may still not be obvious.
Judgments such as right and wrong are in essence both difficult and useless to employ in music, but are in fact equally difficult to determine in ethics. In both cases there is a need for a framework through which the judgements may be applied.  Artistic practice as a way of life through which knowledge of oneself is developed through the care of the self is such a framework. Foucault's description of how the changing political status altered the grounds on which ethical matters were founded in the first centuries A.D. provides an interesting comparison, even if this is a second hand reference:
#+begin_quote
Whereas formerly ethics implied a close connection between power over oneself and power over others, and therefore had to refer to the aesthetics of life that accorded with one's status, the new rules of the political game made it more difficult to define the relations between what one was, what one could do, and what one was expected to accomplish. The formation of oneself as the ethical subject to one's own actions became more problematic. [cite:@foucault1988 p. 84]
#+end_quote
Foucault's main inspiration is taken from the Greek era and what is described here is how the political agenda of the Roman empire changed the conditions for the intrapersonal values and judgements.
It would not be an exaggeration to state that the new rules enforced by the post-political hyper-capitalist game similarily has created new sets of problems for the ethical self, and it has created the need to explore areas that are independent from the commodified self. Artistic practice is such a field, at least the part of it that occurs before the artistic object has been commodified. As mentioned in the beginning of the paper, in the free play the decisions taken have no order or destination, they move in ways that are irregular to the obscured synchronicity of the market economy. Even though my focus here is the actual practice, the appreciation of the artistic object may also have the possibility to further the subjectification of the self in manners that are similar to those of the practice. 

The ideal situation for the development of ethics through artistic practice in free play that I have described here may appear similar to the romantic ideal of the privileged artist free from the burdens of ordinary life. It may also occur to be a binary distinction between an artistic practice in a system of production of value, and an idealized practice within the care of the self. Both of these assumptions are incorrect in so far as the role of the artist does not, in the situation I argue for, have a privileged position towards others. The freedom can only be a consequence of the artistic practice and will not survive outside of it, and not in a direct relation to others. On this point I acknowledge that the model I am describing would benefit from being complemented by a reference to the ethics of ambiguity by [cite:@beauvoir1962]. From what concerns the second point I argue that the method I propose is not in opposition, it is merely an opportunity. 

* Concluding discussion

In their book /Music and Ethics/ [cite:@cobussen2016] Marcel Cobussen and Nanette Nielsen state that music and ethics are "both indeterminate concepts, capable of referring to a variety of practices" (p. 3). This is in line with what I try to argue in this paper, even though I would like to push this even further: it is /necessary/ that we refer both music and ethics to a variety of practices, and that these practices are allowed to exploit a free play of associations. They also state that "once we begin exploring the area music /and/ ethics the complexity increases exponentially" [cite:@cobussen2016 p. 3] which I would argue is not always true. The difference in our respective assessments is probably mainly due to the fact that their starting point and general perspective is slightly different from mine. The main difference is that my discussion is not concerned with ethics and music in general, but rather constrained to the practice of making music and the ethical implications of this practice. Though still complex, by exploring ethics in and through musical practices a certain clarity may be revealed. The result may be an articulation that is embedded in complexity but this is not in opposition to the simplicity of the method: the care of the self in free play.

Finally, as a closing remark: given that artistic practice is a setting for the care of the self, and for alternate views on ethics, a mention needs to be made for artistic research, a particular case of artistic practices. Artistic research raises complex questions concerning the relation between artistic freedom and research ethics. The view of the freedom of the artist, a view grounded in the romantic and modernist eras, is historically defined by concepts such as freedom of speech, and it has a special place in contemporary narratives. Artistic freedom may initially appear to be greater or more important than academic freedom which is more strictly controlled by rules and regulations. However, the neo-liberal agendas have altered this situation in radical ways that has not yet affected universities as much as it has society, making the university a place where the relative artistic freedom is in fact greater. As such the academic environment contributes to the free play of artistic practice, even though the capitalist forces continuously find new battlefronts that may quickly redraw the map.

The ethics of the artistic practice may at certain times find itself to be in opposition also to the research ethics, for the same reasons described above. In this case there will always be a risk that the dominant paradigm, in this case the academically certified ethics, will preside over the artistic. There are clearly academically defined research guidelines and rules that also artistic research needs to abide to, but this should not limit the practice to explore other paths and arenas. It is important to not limit the ethical freedom of the field of artistic practice prematurely, but allow the artist-researcher to pursue the project in the direction in which it leads them. In methodologically sound projects the conflict, if it arises, will not be a problem, and if they occur, there is a tremendous epistemological capacity in such conflicts between two views on ethics. What is important in these cases is that the ethical perspective of the hybrid practice may also be analyzed from the point of view of the research ethics, and that the two views may co-exist.

Through free play and a continuous and conscious ethical reflection the activity of artistic practice offers important possibilities to discuss some of the urgent questions today. It may give rise to an ethics of aesthetics that can provide us with preliminary answers to difficult questions and that can provide a real alternative to the incessant streamlining efforts of hyper-capitalism.

# whether it concerns the care of the self or fundamental ethical question.
* Bibliography
# #+bibliographystyle: unsrtnat
#+print_bibliography: title: "Bilblio"

* Footnotes
[fn:8] At the time of the performance described above this was not something I had reflected on. 

[fn:3] See the writings by Maj [cite/text/c:@Hasager2015] for a broader view on what a hybrid artistic practice may refer to.
[fn:10] His point of view is valid for this discusssion even though he was highly critical of Foucault [cite:@baudrillard1977]. 

[fn:9] In the visual arts an example that may illustrate this is Carl Michael von Hauswolffs' paintings using ashes from the concentration camp Majdanek in eastern Poland and the debate that followed.
[fn:6] Understood as what follows from the line of morality rooted in Aristotele's  Nicomachean Ethics, though I realize it is a crude generalization to regard this a uniform expression of a complex topic such as ethics.

[fn:1] I use mainly section two and three of /The History of Sexuality/ and I make explicit references to the text when needed. But I also use the text as an inspiration and have allowed myself to make interpretations that may not be in line with those a Foucault scholar would do here necessary.

[fn:7] Self reflection is a term equally common as it is problematic in todays discourse on artistic practice and education and should, I believe be handled with care to avoid that everything, and nothing, becomes reflection.
[fn:5] This was a trade mark of early modernism and the later rise of conceptual art. 

[fn:4] A few notable examples are Beethoven's String quartet Op. 131 [cite:@Betthoven1826] that came out in seven movements rather than the expected format of four movements, /Come Out/ by Steve [cite/text/c:@reich1966] which became a memorial as such for the Harlem Six trials and the American civil rights movement that was unexpected even for the composer [cite:@Gopinath2009], and Bob Dylan's decision to take the stage with an electric guitar at the Newport Folk Festival 1965, "backed by a band organized the night before" created havoc and "not only disrupted the closing night of the Festival, but blew apart the music scene that had created it" [cite:@Stone2015].

# As a side note the stylistic changes, sub-genres and definitions in pop and rock that are created  at an ever increasing rate may be seen as an example of this.

[fn:2] I use the term /musician/ throughout and it should be understood to include any and all forms for musical production 
* COMMENT Stuff
# The way aesthetically rooted experiences may be examined through the lens Foucault's /aesthetics of life/ as a tool for a critical analysis is further discussed. 
It is part of the subjectification of the self, of giving the control back to the self. It takes place in a social system but in a way that allows for the formation of an ethical subjectivity, one that is not controlled from an outside power, and which is free from the fear of the future. To summarize: The care of the self allows the subject to engage in its own processes of subjectification.

It may seem like a big jump to Derrida, but he is in fact connecting the dots here between structurality, Freud and free play.[cite:@der78]

 Aesthetically rooted experiences will be examined through the lens of Foucault's /aesthetics of life/ through de Beauvoir's remark of aesthetic masking as a tool for a critical analysis.
 
At the time right after the second world war we were facing similar difficulties trying to comprehend a human disaster of previously unknown proportions. It was from this horizon that Simone DeBeavoir defined her ethics of ambiguity which will be of great significance for this chapter.

Similarly it is only with the strict separation of station auditorium to the spectator is a participant in his her own right everything today conspires to abolish that separation the spectator being brought into a user friendly interactive immersion the apogee of the spectator or his/her N when all our actors there is no action any longer no seen the end of the astatic illusion
[cite:@baudrillard02 p. 176] [cite:@baudrillard02]
# , and how it may be used in relation to other systems of ethics.

The fact that artistic production is a free play

The pleasure that one may find when I as a subject have access to myself for myself, and that I have come to terms with the shortcomings that I have and where I do not allow whatever limits there will be to my capacity to influence me negatively is

is on how beauty, for example, is perceived whereas the discussion on how beauty is created is to a larger extent part of the field of artistic training.

Much points to this free play that artistic practice explores is



** Foucault used
Altough I would hesitate to make any general claims on this relation I would like to propose that there is a link between artistic practices (in music) and Foucault's ideas on the cultivation of the self. This both in the judicial sense of the artist belonging to themselves and of being their own masters and in terms of the particular ability of the work of the artist as something we seek to delight our selves in. Not because this work is delightful, but because the driving force is related to a feeling of delight.

According to Foucault taking care of the self is not merely an attitude towards life and it is not limited to a philosophy, or a thinking of the self, it is not deducible to self reflection--a term equally common as it is problematic in todays discourse on artistic practice. The origin of this particular one of his technologies of the self is greco-roman and stems from figures such as Seneca and Augustine. But in one passage Foucault refers to Plato’s /Alcibiades I/ in which the ideas of the self takes shape and leads to the idea that to acquire /techne/ requires care of the self. Foucault compares this to the farmer that takes care of the land. This care is not only relfective, it is active and outward seeking and ongoing, continuous.

What may appear as the rather egoistic activity of practicing an instrument, composing or improvising has in fact many similarities with care of the self. It is obvious that many artists and musician have not taken care of themselves, but the activities they engage in have some similar boundaries as the taking care of the self. They have an active relation to techne, to the doing in the real world, in a meeting with other people.


