
* On the complexities of artistic practice and ethics
:PROPERTIES:
:org-remark-file: complexities_of_ap_ethics.org
:END:

** It may seem like a big jump to Derrida, but he is in fact connecting the dots here between structurality, Freud and free play.[cite:@der78]


** The origin of this particular technologies of the self is greco-roman and stems from figures such as Seneca and Augustine

** This is clear in the passage where Foucault refers to Plato’s /Alcibiades I/ in which the ideas of the self takes shape and leads to the idea that to acquire /techne/ requires care of the self. 
:PROPERTIES:
:org-remark-beg: 18453
:org-remark-end: 18646
:org-remark-id: c2eba9c9
:org-remark-label: nil
:org-remark-link: [[file:complexities_of_ap_ethics.org::67]]
:END:

** necessarily

** of

** This is a distinction that makes the two modes of thinking at times incompatible, but not incongruous or inconsistent.

** But her view on the symbolic aspect of music turns out to be rather different.
:PROPERTIES:
:org-remark-beg: 7952
:org-remark-end: 8030
:org-remark-id: 0845a790
:org-remark-label: nil
:org-remark-link: [[file:complexities_of_ap_ethics.org::35]]
:END:

** Neoliberal agendas inhibit play.
:PROPERTIES:
:org-remark-beg: 15556
:org-remark-end: 15588
:org-remark-id: 9518af58
:org-remark-label: nil
:org-remark-link: [[file:complexities_of_ap_ethics.org::62]]
:END:

** I will return to how this imacts on the way that play develope through ethics.
:PROPERTIES:
:org-remark-beg: 15473
:org-remark-end: 15550
:org-remark-id: 23be604b
:org-remark-label: nil
:org-remark-link: [[file:complexities_of_ap_ethics.org::62]]
:END:

** Common to these examples is that and in the delight that arises from the process of subjectification.

** In the former I behaved in a way that was, in a general way, respectful of the other.
:PROPERTIES:
:org-remark-beg: 24326
:org-remark-end: 24411
:org-remark-id: 4aae732b
:org-remark-label: nil
:org-remark-link: [[file:complexities_of_ap_ethics.org::93]]
:END:

** which is also to say that they follow the principle of the care of the self.

** In the former I behaved in a way that was, in a general way, respectful of the other.
:PROPERTIES:
:org-remark-beg: 24293
:org-remark-end: 24378
:org-remark-id: 98c40131
:org-remark-label: nil
:org-remark-link: [[file:complexities_of_ap_ethics.org::93]]
:END:

** The focus of the current discussion is the experience of the artist when engaged in their own practice.

** The focus of the current discussion is the experience of the artist when engaged in their own practice.
