#+title: OTTOsonics: Designing and Implementing an Open and Affordable 3D Spatial Audio System
#+name: 
#+options: toc:nil num:nil
#+cite_export: csl ~/Documents/articles/biblio/csl-styles/apa-7th.csl
#+LaTeX_HEADER: \usepackage[x11names]{xcolor}
#+LaTeX_HEADER: \hypersetup{linktoc = all, colorlinks = true, urlcolor = DodgerBlue4, citecolor = black, linkcolor = black}
#+latex_header: \usepackage[scaled]{helvet}
\renewcommand\familydefault{\sfdefault}


* OSO-2024-0085
:PROPERTIES:
:NOTER_DOCUMENT: OSO-2024-0085_Proof_hi.pdf
:END:

** Overall comments

This is a very well written paper on an interesting an important topic on how to build affordable hardware systems for spatial audio: OTTOsonics. The premise, that "attending an immersive audio concert or a theatrical performance with multichannel audio remains a rare and exceptional experience" is a problem that currently has a negative impact on the field of experimental music where only a few, albeit many more today than just 15 years ago, places allow for the spatial precision needed for rendering works by many composers and artists. The idea of an open source soft and hardware solution is a very compelling idea to remedy this situation.

The technical description in Section 4 is very well written and easy to understand despite the relative complexity of the project.

My general critique, laid out in more detail below, is that the focus on the development and implementation in the paper is at the expense of how the argument for why OTTOsonics is the solution to the defined problem.


** Survey
:PROPERTIES:
:NOTER_PAGE: (3 0.1483739837398374 . 0.1235632183908046)
:END:
On page 2 it is stated that:

#+BEGIN_QUOTE
/Currently, there is no official data, such as academic surveys, that documents the interest of
venues in adopting and utilising immersive audio formats and further research is needed in
this area./
#+END_QUOTE
In the following sentence you refer to your own observation that there is a lack of "musical content referents to fully understand the possibilities of using immersive audio systems" and that the problem is a lack of technical expertise. It would have strengthened the argument if this observation had been in the form of a survey, or at least, a more precise explanation of how these observations were performed.

** Page 4, Interviews with representatives
:PROPERTIES:
:NOTER_PAGE: (4 0.4908536585365854 . 0.35344827586206895)
:END:
You write on page 3 that: 
#+BEGIN_QUOTE
/Through interviews with representatives from these groups, we were able to identify the most critical factors for the successful introduction of surround sound systems./
#+END_QUOTE
It would strengthen the argument here if there was a bit more information about how these interviews were performed. Also, the interviews were performed /after/ the the main development phase of the last tree years was already performed, yet it appears to me that some of the arguments in the paper /for/ the development of the system relies on the results of these interviews. This should be clarified.

On page 4 you conclude that  "Our conclusion was that further development was needed to make immersive
audio more accessible to a broader range of venues." Timing here is unclear: wasn't the interviews made after the main development phase of OTTOsonics?

** Page 4
:PROPERTIES:
:NOTER_PAGE: (5 0.5203252032520326 . 0.12068965517241378)
:END:
This is a gain a bit vague: ``Based on these prior projects and our own observations,''



** Page 14, 5.1
:PROPERTIES:
:NOTER_PAGE: (15 0.1636178861788618 . 0.2514367816091954)
:END:
In the case studies there are several examples of anecdotal evidence. The feedback of composer Mariam Gviniashvili is that the system is ``reliable and suitable for multichannel audio.'' Though it is hard to get reliable data from these kinds of user experiences this feedback does not necessarily map to the key definitions of the system and comes out as a bit vague.

** Page 14-15, 5.2
:PROPERTIES:
:NOTER_PAGE: (15 0.9014227642276423 . 0.29454022988505746)
:END:
``Audience feedback emphasised the comfort and immersion of the sound, which, while loud overall, was not overwhelming due to the even distribution across numerous speakers.''
\noindent
Similar to my comments above: how was this feedback acquired?
** Page 15, 5.2
:PROPERTIES:
:NOTER_PAGE: (16 0.15752032520325204 . 0.12068965517241378)
:END:
On top of page 15 you write:
#+BEGIN_QUOTE
/Our artistic goals in these concerts were to amplify the music while enhancing expressivity
through spatialization. With the usual limited soundcheck time, we developed a suite of
spatial effects ready to insert, like fading signals between positions, moving sounds with
variable speed, and using built-in effects like reverb and delays, all controlled via MIDI
interfaces./
#+END_QUOTE
Though this is very interesting and a crucial part of any system for rendering spatial audio, you move from the artistic interests of invited composers as your mai source of information to your own artistic goals. This creates a shift in the direction of the paper that would need another level of contextualization.
** Page 15, 5.3
:PROPERTIES:
:NOTER_PAGE: (16 0.5548780487804879 . 0.28448275862068967)
:END:
Again, very anecdotal:

#+BEGIN_QUOTE
/In one instance, a string quartet initially
believed the enhanced acoustics were natural and were surprised to learn how different the
venue actually was./
#+END_QUOTE
** Page 18, 6.1
:PROPERTIES:
:NOTER_PAGE: (19 0.5071138211382115 . 0.12068965517241378)
:END:
``The socioeconomic context addressed by OTTOsonics is central to its appeal.''

This argument is very compelling and one of the driving forces behind that project. It appears it is a bit under-developed here. To what extent has systems been created by users and to what extent have you produced them? Has there been any forks yet? 
** Page 18, 6.2
:PROPERTIES:
:NOTER_PAGE: (19 0.7032520325203253 . 0.22270114942528735)
:END:
The statement that your work with festival implementations "have transformed the listening experience" is wide ranging but is not grounded in enough empirical material represented in the paper.
** Page 18, 6.2
:PROPERTIES:
:NOTER_PAGE: (19 0.7804878048780488 . 0.12068965517241378)
:END:
The statement that:
#+BEGIN_QUOTE
/From our experience we can assert that presenting music originally composed in mono or
stereo through multichannel setups has enriched both musicians and audiences./
#+END_QUOTE
again implies an intermediary level of interpretation that allows for an artistically meaningful rendering of a piece of music originally in stereo to a multichannel format that is not at the centre of the ambition of this paper. As it stands now the paper does not give much evidence for the experience referenced. This either needs to be developed or rephrased.
** Page 18, 6.2
:PROPERTIES:
:NOTER_PAGE: (19 0.853658536585366 . 0.7011494252873564)
:END:
#+BEGIN_QUOTE
/Indeed, musicians' auditory imagination is shaped by their formats and media, complicating direct comparisons./
#+END_QUOTE
I'm not sure I understand this sentence, maybe something wrong with the reference of 'their'? I think the whole section needs rewriting as the following sentence, without explanation, suggests to do what is earlier defined as challenging, without any comment of how the challenges will be overcoome methodologically.
** Pate 19, 6.2
:PROPERTIES:
:NOTER_PAGE: (20 0.09552845528455285 . 0.1235632183908046)
:END:
#+BEGIN_QUOTE
/We question if adopting Ambisonics sound reinforcement could mirror the shift in the 1970s
when stereo systems became widespread./
#+END_QUOTE
It is not clear to me whether you question the dominance of ambisonics, or welcome it. The final sentence of the section rhymes well with how I understand the paper, and the question of which formats to use would appear to be a separate, but related, question. Are you advocating ambisonics, make it more explicit here, and perhaps also in the beginning of the paper.
** Page 19, 6.3
:PROPERTIES:
:NOTER_PAGE: (20 0.209349593495935 . 0.15804597701149425)
:END:
This section should perhaps better be incorporated in 7. Future work?
** Page 19, 7.
:PROPERTIES:
:NOTER_PAGE: (20 0.7865853658536586 . 0.49712643678160917)
:END:
#+BEGIN_QUOTE
/Second, we plan to rethink the
manufacturing process of the loudspeakers, exploring more industrialised production
methods and the use of sustainable materials./
#+END_QUOTE

I think it would be good to relate this to the question of open-source development. What will happen to the openness of the project if a more industrialized production is adopted?

The final sentence could be related to my comments above, but specifically to 6.3: are you referring to that study here, or also other kinds of systematic studies?

