* peer-review_ac6238_v1
:PROPERTIES:
:NOTER_DOCUMENT: peer-review_ac6238_v1.pdf
:END:
#+OPTIONS: H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS: TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc 
#+OPTIONS: broken-links:n
#+OPTIONS: toc:nil ^:nil author:nil
** Unsatisfied definition of free improv
:PROPERTIES:
:NOTER_PAGE: 2
:END:
** Very broadly understood
:PROPERTIES:
:NOTER_PAGE: 2
:END:
What is it in the ensemble practice that one is after? This is different in the various source cited here. 
** The aim is too wide
:PROPERTIES:
:NOTER_PAGE: (3 0.4343511450381679 . 0.11857707509881422)
:END:
#+BEGIN_QUOTE
This work seeks to contribute to the broader discussion on the role of artificial agents in musical
discourses, particularly in the context of live, interactive performance, and the unique challenges
posed by integrating machine intelligence into human-centered musical ecosystems.
#+END_QUOTE
** Interesting and relevant
:PROPERTIES:
:NOTER_PAGE: (4 0.333587786259542 . 0.541501976284585)
:END:
But what part of timbre are you abstrating?
#+BEGIN_QUOTE
The musical parameters timbre, register,
intensity, and tempo are categorized by the k-means into varying numbers of clusters
#+END_QUOTE
** How did you reach the conclusion that this is the best way to do it?
:PROPERTIES:
:NOTER_PAGE: (4 0.49923664122137407 . 0.11857707509881422)
:END:
This is time based data. What is the resolution?

#+BEGIN_QUOTE
Each sound parameter has a numerical value to represent their cluster, corresponding to:
#+END_QUOTE
** It is not clear what constitutes a phrase i the system
:PROPERTIES:
:NOTER_PAGE: (5 0.3480916030534351 . 0.6185770750988142)
:END:
``between each phrase played.''
** This is a very strange interpretation of Lewis
:PROPERTIES:
:NOTER_PAGE: (10 0.1633587786259542 . 0.1175889328063241)
:END:
#+BEGIN_QUOTE
This “issue” is addressed in Xxxxxxxxx by disassociating each parameter from the others found in
a phrase, and by also transforming the material through mathematical operations to the numerical
representation of each musical element of the phrases manipulated, as seen in the previous
section.
#+END_QUOTE
** Earlier it was stated both were produced?
:PROPERTIES:
:NOTER_PAGE: (10 0.3198473282442748 . 0.3300395256916996)
:END:
#+BEGIN_QUOTE
The output produced by Xxxxxxxxx also privileges sonic instead of
symbolic responses (such as MIDI), synthesizing sounds
#+END_QUOTE
** Incorrect
:PROPERTIES:
:NOTER_PAGE: (10 0.5366412213740458 . 0.24308300395256915)
:END:
``while a practice particularly focused on the act of collective performance,''
** Not specific to improv
:PROPERTIES:
:NOTER_PAGE: (10 0.8145038167938932 . 0.6185770750988142)
:END:
#+BEGIN_QUOTE
their interaction approaches and
instrumental techniques often question those traditionally associated with classical music,
#+END_QUOTE
** Lack of focus
:PROPERTIES:
:NOTER_PAGE: (11 0.383969465648855 . 0.11956521739130434)
:END:
#+BEGIN_QUOTE
Finally, as discussed by Scott Thomson[30], free improvisation questions the role of the
improviser as a virtuoso, contradicting a historical perspective of European concert music very
recurrent in jazz cultures. In the same way, ubimus is based on creative approaches that embrace
“little-c musical phenomena that were excluded from professional musical practices”[26],
questioning the preeminence of virtuosity in music-making.
#+END_QUOTE
** This conclusion is not clear
:PROPERTIES:
:NOTER_PAGE: (12 0.20763358778625954 . 0.32509881422924897)
:END:
#+BEGIN_QUOTE
In this sense, the use of Xxxxxxxxx for other initiatives focused on a
compositional approach could also be explored.
#+END_QUOTE
** This is not properly backed up
:PROPERTIES:
:NOTER_PAGE: (12 0.5343511450381679 . 0.39624505928853754)
:END:
ppp``the perception that this is an “extended
instrument” with its own personality,''
** Not backed up
:PROPERTIES:
:NOTER_PAGE: (12 0.7847328244274809 . 0.17984189723320157)
:END:
#+BEGIN_QUOTE
We have
observed that, in general, their users have little understanding of how they work, the limits of
these intelligences, and the treatment and purpose of the data generated by interaction with these
systems.
#+END_QUOTE
** This model is not properly described
:PROPERTIES:
:NOTER_PAGE: (13 0.5725190839694656 . 0.3537549407114624)
:END:
#+BEGIN_QUOTE
offers a model for creating adaptive, non-hierarchical, and
community-oriented musical environments.
#+END_QUOTE
** Comments on "Development of an improvising machine in an ubimus context"
The system described appears to be interesting and useful for a variety of uses related to improvised music practices. I read the question on page 2, in the second paragraph, as the research question for the paper. This, however, does not appear to be correct. There is no further discussion of ensemble music practices following this section. Instead, the scope of the paper is far too wide for a short article like this. There are many small statements, such as the sentence following the question on page 2, that are not backed up by any data or even experience. (As a practitioner, I cannot see that in-person musical interactions have decreased post-covid.)

The definition of free improvisation is unsatisfying, and although several of the central sources are cited, there is a much more contemporary discussion of improvisation that could benefit the article's many references to free improvisation.

The aim, as described in the last paragraph of section 1 on page 3 is not followed up. The discussion in the paper does not properly contribute to the "broader discussion on the role of artificial agents in music" in the way that it is described here. It is not at all clear what the DIY perspective here is.

The description of the segmentation of musical parameters into lists on page 4 is far too general for the rest of the discussion to make sense. There are a number of questions not approached, the most important of which include time and segmentation. How are phrases identified and what constitutes a phrase? This can be radically different in different genres and styles of improvisation.

My suggestion for this paper would be to rewrite it into an overview of the field of automated systems for improvisation in the ubimus movement and relate these to the theory of free improvisation brought up in the paper, and then include a short discussion of the system developed by the authors or, to write a full description of the system and a study on when it is used in various contexts, how it is experienced by musicians, or how it is experienced by listeners. Either or all of those perspectives would be interesting.

Either way, the aim and scope of the paper needs to be properly stated.
