#+options: toc:nil num:nil
#+cite_export: csl ~/Documents/articles/biblio/csl-styles/apa-7th.csl
#+LaTeX_HEADER: \usepackage[x11names]{xcolor}
#+LaTeX_HEADER: \hypersetup{linktoc = all, colorlinks = true, urlcolor = DodgerBlue4, citecolor = black, linkcolor = black}


#+begin_src emacs-lisp
  (set-window-margins (selected-window) 20 20)
  (setq line-spacing 0.5)
  #+end_src

  #+RESULTS:
  : 0.5

* Sound, motion and agency


Artistic research has brought light on a number of aspects in the field of music. The perhaps most important is the equally problematic as enlightening concept of an understanding from the inside of an artistic practice. Exactly what constitutes this privileged /inside/, or how it is made accessible to an artist is perhaps less commonly addressed. The /inside/ is no longer merely an angle of perception or a position, it is an epistemological potential. In his essay /An Introduction to Metaphysics/ French philosopher Henri Bergson defines two incommensurable ways to approach an object: either from a point of view through signs and concepts--a /relative/ perspective--or through entering into the object, exploring it from the inside--an /absolute/ apprehension. This approach is what he refers to as /intuition/ and in order to grasp intuition we must transcend concepts [cite:@Bergson1912; p 21]. This paper is an attempt to present this method and explore it in complex music-motion systems involving artificial intelligence. 

With time and motion, both obviously central in music creation, the necessity for an understanding beyond the conceptual is further actualized. When I move my arm to perform on some instrument my understanding of what the arm does on its way will add to my arm-moving-knowledge, and simplified, intuition is the modality through which this process is carried out. In the intuitive observation of this action there are no states, only duration and mobility informed by experience and knowledge. In this sense my arm has both knowledge and agency and both of these affects what I will and want to achieve and the object and its function are intimitely connected. Each part of a music-machine system may be understood this way.

Designing intelligent instruments allowing for complex human-machine interactions is a process that by the immediate relation to engineering and science, lends itself naturally to an understanding based on analysis rather than intuition. This enforces their appearance as tools, rather than objects that possess their own agency. However, similar to the moving arm there is a kind of 'motion' also in these machines. They are more than merely the object itself, as their algorithms relate to previous input and output, and to the  programmer's and engineer's various positions and biases. In this chapter I will discuss how it is possible to infer the properties of the larger system of a musician playing with a generalized artificially intelligent machine and create an /intuitive/ understanding of it that promotes both the performative possibilities and any analytical perspective. This understanding operates from what can be seen as /the inside/ (not as an opposite of /outside/) of the process and allows for an analysis that promotes the discursive practice of the entire system. This is not to be confused with knowledge about the technical aspects of the machine, but is an understanding of what the possible musical actions are, what the agencies are, and what the delimitation of the system are.

* Biography
Henrik Frisk is an active performer (saxophones and electronics) of improvised and contemporary music and a composer of acoustic and electroacoustic music. He is professor of music at the Royal College of Music in Stockholm and head of program for the department for electroacoustic music composition. His research is concerned with improvisation, interactivity, spatialisation and experimental electroacoustic music. Currently involved in the project /Musical Transformations/, exploring musical traditions and change through a postcolonial perspective as well as /Historically informed design of sound synthesis/, employing a multidisciplinary approach to the exploration of electronic music heritage his research focuses on artistic practices. He has contributed to the /Routledge companion to research in the arts/ and is the co-editor and contributor of /Acts of Creation/, an anthology on artistic research supervision, /(Re)Thinking Improvisation/ and co-author on a book on stimulated recall methods on Cambridge University Press due for release in early 2023.

Started out in jazz with performances at the Bell Atlantic Jazz Festival, NYC and Montreux Jazz Festival, Switzerland, his primary focus is composing and playing contemporary music, with an interest in sound installation. He has performed in many countries in Europe, Asia and North America and received commissions from many ensembles and institutions. Numerous recordings are available on American, Canadian, Swedish and Danish record labels.

* Bibliography
# #+bibliographystyle: unsrtnat
#+print_bibliography: title: "Bilblio"

