G# Created 2020-09-19 lör 14:26
#+TITLE: Étude comparative des approches crèatrices et technologiques au groupe de recherches musicales à paris et à l’elektronmusikstudion à stockholm 1965-1980
#+AUTHOR: Henrik Frisk, henrik.frisk@kmh.se
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil pri:nil tags:not-in-toc toc:nil num:0
#+INCLUDE: "./setupfile.org"
     
Denna avhandling, en monografi med den självförklarande undertiteln /deux directions artistiques diffèrentes à partir d’une idèe commune/ är en översikt och jämförelse mellan två ledanade miljöer för elektroakustisk musik mellan åren 1965-1980: /Groupes Recherches Musicales/ (GRM) på franska radion ledd av Pierre Schaeffer, och /Elektronmusikstudion/ (EMS) i Stockholm under ledning av bland andra Knut Wiggen. Den utgår ifrån litteratur och intervjuer, och en rad verk producerade vid respektive institution analyseras. Avhandlingen är omfattande både i omfång (närmare 350 sidor) och med hänsyn till metodologi. Den är producerad i ett samarbete mellan /Sorbonne Université/ i Paris och /Stockholms Univeristet/ och är skriven på franska, dock framlagd på SU.

I den första delen görs en översikt över de konstnärliga och vetenskapliga riktningar i den elektroakustiska musikens (EAM) utveckling under den aktuella tiden, samt en studie över de tekniska utvecklingar som skedde på GRM och vid EMS. Dessa ses i ljuset av de musikaliska inriktningar som representeras av Schaeffers och Wiggens respektive ganska olika visioner och teoretiska utgångspunkter. Det blir tydligt hur teori, estetik och kompositorisk praktik flyter samman, även om avhandlingens primära infallsvinkel är hur utvecklingen vid respektive studio påverkar musiken som komponeras där. Här ges en överblick över hur EAM utvecklades även i andra länder i Europa vid samma tid. Förutom Sverige och Frankrike diskuteras utvecklingen Tyskland, Italien och USA. Den digitala teknikens intåg, samt datorn som ett verktyg, både som instrument och i datorassisterad komposition, lyfts fram i ett historiskt perspektiv.

GRM och EMS gemensamma projekt SYNTOM diskuteras i andra kapitlet där Schaeffers och Wiggens olika ingångar blir synliga och analyseras. Inledningsvis ges en jämförelse mellan Schaeffers och Wiggens musikaliska koncept, där Scheaffers, å ena sidan, tar utgångspunkt i ett fenomenologiskt lyssnande, och Wiggen, å andra sidan, har fokus på praktiken och maskinen. SYNTOM läggs så småningom ner men visar, enligt Balkir, på en avgörande skillnad och entydig närhet mellan de två miljöerna. Denna dialektik är närmast ett resultat för sig själv i avhandlingen. I slutändan var den inte långvarig, då samarbetet i projektet SYNTOM mer eller mindre verkade avstanna i början av sjuttiotalet, men den gav inte desto mindre upphov till en rad mycket intressanta utvecklingsspår. Interaktion där motstånd kan vara en produktiv kraft har jag själv intresserat mig för i konstnärlig praktik [[citep:frisk08phd][Inte minst i min avhandling][]]. Här är dock interaktionen mer på ett strukturellt, snarare än musikaliskt plan. Men likheterna blir ändå tydliga, det är som om både Schaeffer och Wiggen dras till motsättningen, inte för att exploatera den utan för att finna möjliga lösningar genom motståndet.
Kapitlet avslutas med en grundlig jämförelse mellan den teknikska forskningen på GRM respektive EMS.

I den andra delen presenteras analysteori för elektroakustisk musik, analyser av totalt sju verk från de båda institutionerna samt en jämförande semiologisk analys av resultaten av analysen. Nattiez och Molinos tredelade analysmodell diskuteras liksom Lasse Thoresens utveckling av Schaeffers morfologi som har lett till en teori för notation av elektroakustisk musik. Verk av tre tongivande tonsättare verksamma vid GRM (Guy Reibel, Bernard Parmegiani och Francois Bayle) och fyra verksamma vid EMS (Lars Gunnar Bodin, Sten Hanson, Knut Wiggen och Tamas Ungvary) analyseras och jämförs med olika metoder. Analyserna av dessa verk korrelerar hon mot den tidigare diskussionen med utgångspunkt i den teori hon tidigare lyft fram, samt mot hur estetik och teknik har gestaltat sig på de olika institutionerna. Analyserna kan kritiseras för att vara allt för mekaniskt genomförda för att kunna ge ett bra resultat, och metoden för analysen är relativt traditionell. Den visar hur teknikutvecklingen och ideologierna vid respektive institution skapade förutsättningar för olika slags estetik, vilket inte är förvånande; det motsatta vore väldigt förvånande. Samtidigt kan frågan ställas hur mycket information av det slaget som egentligen finns i dessa verk, komponerade under en period som var så präglad av experimenterande. På EMS var tekniken avancerad och endast ett fåtal tonsättare kunde hatera den fullt ut. Korrelationerna hon gör är inte desto mindre intressanta utifrån den diskussion hon för, men jag är inte övertygad att resultatet huvudsakligen framkommer genom musikanalysen. Avhandlingen avslutas av en kortare sammanfattning.

Det är en på många sätt viktig avhandling med stor relevans för aktuell konstnärlig forskning. Som en studie av utvecklingen av svensk elektroakustisk musik bygger den vidare på Sanne Krogh-Groths avhandling citet:groth2016. Till viss del repeterar den det som framkommer i Krogh Groths /Politics and aesthetics in electronic music/, som också lyfter fram mötet mellan Schaeffer och Wiggen i början av sjuttiotalet genom projektet SYNTOM. Det var genom detta projekt som Wiggen i slutet av sextiotalet omnämnde datorn som ett möjligt /instrument/, kanske för första gången:

#+begin_quote
Les premières idées du projet étaient déjà révélées par Wiggen depuis la fin de 1960 et constituaient même l’une des grandes étapes de la recherche et de la création à l’EMS. Le but était de trouver un lien entre la synthèse sonore via l’ordinateur et la pratique de la musique concrète. [[citep:Balkir2018][s. 64]]
#+end_quote
Att den elektroakustiska praktiken medieras genom en dator, som på så vis blir ett amorft /instrument/, är självklart idag. Det har fått ett enormt genomslag under de senaste tjugo åren, men idéen uppstod alltså för mer än femtio år sedan, när en dator fortfarande hade ett eget rum.

Fokus hos såväl GRM och EMS var alltså att integrera datorn i en teori som fortfarande skulle ta avstamp i Schaeffers citetitle:schaeffer77. Visionen var att göra det möjligt för tonsättare att definiera och bearbeta ljud utifrån psyko-akustiska termer. Det är ingen tvekan om att detta var en viktig tid i utvecklingen av EAM i Europa och världen. Det är också en av få perioder i musikhistorien då Sverige har stått på värlsdkartan med EAM och Text-Ljud tonsättare som Bengt Emil Johnson, Lars Gunnar Bodin, Bengt Hambreus och Karl-Erik Welin. Även om historien har visat att Schaeffers teorier om det elektroakustiska ljudets fenomenologi har fått större slagkraft än Wiggens visioner, är det ändå slående när man tittar på Balkirs jämförelse att EMS producerade betydligt fler verk än GRM under den tiden som avhandlingen tittar på. Detta är anmärkningsvärt med tanke på Frankrikes storlek och centrala position i kulturlivet, men också med avseende på resurserna som man där hade tillgång till. Till detta ska man lägga att EMS under samma tid reformerade själva tanken på hur en kompositionsstudio för EAM ska se ut. Där Schaeffer och GRM till en början höll fast i bandspelaren som en av de viktigaste komponenterna byggde EMS upp ett datorbaserat system, unikt i världen och den första digitala studion.

Men det var inte bara som teknikutvecklare Wiggen var visionär. Han och Schaeffer delade synen på att den moderna tonsättaren inte bara är en konstnär utan som utnyttjar forskningens metoder för att med skärpa kunna skapa den koppling mellan intention och resultat som krävs. I sin text citetitle:wiggen1972 lägger han grunden för den framtida tonsättaren:

#+begin_quote
Liksom Schaeffer tror jag att den typ av tonsättare som vi i dag behöver är tonsättaren/forskaren, alltså en konstnär som är medveten om vad han syftar till med sitt kompositionarbete att han kan förmå sig att med forskarens metodik och tålamod leta fram sina uttrycksmedel utan att han under detta arbete förlorar kontakten med det han vill uttrycka 55. [[citep:wiggen1972][s. 124, citerad i Balkir (2018), s. 54]]
#+end_quote

Som [[citet:Balkir2018][s. 53]] sammanfattar det, forskning är själva hjärtat i den praktik som leder fram till elektroakustiska kompositioner. Men, hon pekar också på en central skillnad mellan Schaeffer och Wiggen som jag redan tagit upp men som förtjänar att upprepas: Wiggens fokus ligger på själva /görandet/, praktiken, och Schaeffer riktar sig snarare mot /lyssnandet/. Detta är naturligtvis är en helt central skillnad i attityd och som också, i sig, kan förklara varför Wiggens intresse var för verktygen för komponerandet. Men trots denna skillnad odlade såväl EMS som GRM idén om den forskande tonsättare nära trettio år innan konstnärlig forskning i musik blev verklighet i Sverige.

Balkir påvisar hur musiken och dess estetik, under de år hon tittat på, har vuxit fram ur en växelverkan mellan fenomenologiskt förhållningssätt och en teknologisk utveckling. Hon pekar på likheten mellan de svenska och de franska tonsättarna men också på Wiggens mycket speciella attityd som också är helt sammanvävd med teknikutvecklingen som han drev fram. Den första delen av avhandlingen menar jag lägger till viktig information om en period på femton år då musiken sökte sig åt många nya håll och vår kunskap om lyssnandet som en fenomenologisk aktivitet växte. Det är på många sätt en traditionell musikvetenskaplig avhandling där musikanalysen har en central funktion. Som tidigare nämnt är jag inte övertygad om att analysen bär upp detta arbete, men det blir inte desto mindre en bra grund till fortsatt forskning kring notation av EAM. Analyserna här, och den notation som Blakir använder sig av är beskrivande, deskriptiv, av klangbilden som ges. Därmed ansluter den till den franska traditionen. Det kan ställas mot pågående svensk forskning, som Mattias Skölds arbete med att utifrån samma teoretiska grund skapa en notation av EAM som kan fungera deskriptivt, som ett kompositionsverktyg citep:skold2019. Därmed är kanske cirkeln sluten mellan den franska traditionen rotad i lyssnnandet och den svenska som utgår från görandet: notationsverktyg som utvecklas utifrån Schaeffers fenomenologi blir ett medel för att komponera, för praktiken som Wiggen månade om.


\printbibliography[title={Referenser}]

