#!/bin/sh
APPDIR=`dirname $0`;
java  -cp "$APPDIR/src:$APPDIR/bin:/home/henrikfr/Desktop/apps-src/gwt-linux-1.4.61/gwt-user.jar:/home/henrikfr/Desktop/apps-src/gwt-linux-1.4.61/gwt-dev-linux.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" org.henrikfrisk.DisserReader;
