* Introduktion
  :PROPERTIES:
  :CUSTOM_ID: sec:orgdd1c696
  :END:

* Metoden och resultat
  :PROPERTIES:
  :CUSTOM_ID: sec:orgc2861a5
  :CLASS: unnumbered
  :END:

Som tidigare nämnts kallar Stjerna sina metoder för /explorative
approaches/. Givet hur nära kopplade de är till teorin är det sannolikt
en klok strategi, även om det också kan skapa förvirring. De tre
övergripande utforskande tillvägagångssätten /att kartlägga de affektiva
linjerna/, /att skapa nya sammankopplingar/ samt /att bli icke-autonom/
(som diskuterades en del i förra avsnittet). Denna nära koppling mellan
teori och metod gör det på ett sätt enklare att diskutera utmaningarna i
projektet. Om vi fortsätter utifrån linjen att Deleuze och Guattaris
filosofi framförallt sysslar med begreppskapande (skapande av koncept),
är det inte långsökt att tänka sig att deras verktyg användas för att
skapa nödvändiga begrepp för att förstå och analysera den konstnärliga
praktiken. Frågan är om resultatet av den processen först och främst är
kunskap om konst eller om det är filosofi, men oavsett svaret så kan
resultatet ha validitet som forskning. En annan utmaning till följd av
denna användning av metod är att det av uppenbara skäl helt enkelt kan
uppstå en sammanblandning mellan teori, metod och resultat med utfallet
att den konceptuella stabiliteten blir lidande. Men samtidigt, som också
diskuterades ovan, är detta i realiteten ett sätt att hantera metod och
teori i konstnärlig forskning. Jag ska återkomma till det.

I Stjernas fall uppstår inte dessa problem, delvis tack vare att hon
handskas varsamt och ytterst konsekvent med begreppen. Dessutom ska man
inte glömma att teorin i /Before Sound/ i stor utsträckning relateras
till den kontextualisering och positionering som görs i kapitel två:
/Contextualisation--Artistic Strategies within the Field/. Denna typ av
situering är något som ibland förbises i konstnärliga avhandlingar
vilket kan få till följd att de konstnärliga resultaten blir svåra att
bedöma: Om det är oklart inom vilket konstnärligt fält
konstnären/forskaren rör sig kan det vara svårt att korrelera de
konstnärliga resultaten till konstfältet i stort. Samma problem uppstår
om fältet som beskrivs är alltför disparat eller alltomfattande, eller
alltför smalt. Eller, om fältet som beskrivs är ett annat än ämnet för
avhandlingen eller forskningen. Det finns flera anledningar till att det
tagit lång tid för konstnärlig forskning att hitta rätt på detta område
men några uppenbara skäl är:

1. Bristen på etablerade modeller för att referera till alla typer av
   konstverk och svårigheten beskriva dem på ett sätt som bidrar till
   att skapa en bild av ett fält är påtaglig. Ett sätt runt detta är att
   göra som Stjerna gör och referera till en (vetenskaplig) studie av
   verken i fråga.[fn:8] Detta är i grund och botten ett beprövat sätt
   att såväl inkludera den större diskursen om ett verks validitet för
   ett specifikt sammanhang och kan skapa trovärdighet i argumentationen
   när möjligheten att lyssna och uppleva, om än genom en dokumentation,
   också erbjuds. En eventuell baksida med denna metod är att
   argumentationen kan göra sig beroende av en annan disciplin, som
   filosofi, eller musikvetenskap i det här fallet, eller rent av
   resultera i en i huvudsak vetenskaplig undersökning. Detta är i sig
   inte ett problem, jag menar att konstnärlig forskning är i grunden
   tvärvetenskaplig, men det är samtidigt viktigt att det
   tvärvetenskapliga hanteras på ett sätt så att det understödjer, inte
   raserar, den konstnärliga undersökningen.

2. Det är tydligt att man i konstnärliga avhandlingar har lättare att
   referera till etablerade verk och studier av verk. Men utan en intern
   diskussion, och utan att varje avhandling också relaterar till det
   fält som är i dess omedelbara närhet, såsom samtida konstnärlig
   forskning eller konstnärlig praktik, riskerar studiens validitet att
   begränsas. Stjerna går elegant runt detta genom att med omsorg
   beskriva verktygen, tillvägagånssätten och det teoretiska
   perspektivet hon använder vilket skapar en tydlighet. Men jag skulle
   vilja gå så långt som att säga att den största utmaningen vi har för
   konstnärlig forskning idag är just bristen av ett befintligt
   forskningsfält där den konstnärliga undersökningen står i centrum.
   Detta kan byggas genom att doktorander samarbetar och refererar till
   varandras arbeten, gärna kritiskt men alltid noggrant, och genom att
   större forskningmiljöer skapas. Ett nytt samarbete mellan Kungliga
   Musikhögskolan och Musikhögskolan i Piteå, Luleå Tekniska
   Universitet, samlar mer än tio doktorander, en PostDoc och flera
   seniora forskare i vad vi kallar lab tre gånger per år. Det är en
   början men vi behöver fler samarbeten där utgångspunkten är
   diversitet, samarbete och kritisk granskning. 2018 skrev vi i
   programförklaringen till samarbetet mellan LTU och KMH att vi vill
   ytterligare arbeta för att skapa:

   #+BEGIN_QUOTE
     [...] former för kunskapsbyggande i konstnärlig forskning som är
     baserat på konstnärlig kunskap. Även teoretiskt drivna resonemang
     kan här ta sin utgångspunkt i den konstnärliga praktiken varför
     själva praktiken är central i seminarier och labsessioner. De
     gemensamma seminarier som vi planerar i Piteå och Stockholm ska ta
     formen av ett laboratorium som alla gemensamt ska bidra till den
     fortsatta utvecklingen av detta format. En viktig förutsättning är
     att skapa ett arbetsklimat som bygger på förtroende av samma slag
     som uppstår i konstnärliga samarbeten, och som därigenom skapar
     förutsättningar för en kritisk dialog som kan gå på djupet in i
     konstnärliga processer.[fn:9]
   #+END_QUOTE

   Idén är att sätta den konstnärliga praktiken i centrum i en skyddad
   seminariemiljö som erbjuder möjligheten att experimentera. I detta
   initiativ hoppas vi att det ska bli möjligt att i större utsträckning
   begreppsliggöra praktiken och undersökningen vilket samtidigt kan
   underlätta att arbetena också diskuteras, kritsikt granskas av
   jämlikar, samt att resultaten, såväl som metod och teori, delas.

3. Även det större fältet av konstnärlig praktik, utanför konstnärlig
   forskning, måste vara möjligt att referera till. Musikhögskolan i
   Piteå och konstnärliga fakulteten vid Göteborgs universitet har
   etablerade metoder för att registrera konstnärliga verk vilket gör
   det enkelt att hänvisa till dessa, och KMH och Musikhögskolan i
   Ingesund, Karlstads universitet, har påbörjat ett arbete som
   förhoppningsvis leder till att vi bidrar till ett fält som inkluderar
   akademien och skapar förutsättningar för forskningsanknuten
   undervisning. Om möjligheten för att publicera konstnärliga arbeten i
   forskningsdatabaser erbjuds kommer det uppstå en ackumulativ effekt
   som kan få mycket stor betydelse för hur konst som kunskapsfält kan
   utvecklas.

4. Utan tydliga begrepp för konstnärlig forskning och konstnärlig
   praktik kan det vara svårt att på ett öppet sätt beskriva det
   konstnärliga fält som är det centrala för studien, utan att samtidigt
   bli låst av det. Att använda filosofi, som tidigare diskuterats,
   eller andra discipliner är här en möjlighet som samtidigt kan bidra
   till en breddad förståelse för detta forskningsfält. Dock är det
   nödvändigt att även begreppen växer fram i gemensamma miljöer där
   resultat och diskussioner delas.

Det ackumulativa kunskapsbyggandet som kan bli resultatet av en stabil
forskningsmiljö där forskare på olika sätt bygger vidare på varandras
arbeten på ett genomskinligt och konsekvent sätt är en förutsättning för
att konstnärlig forskning ska få respekt och förtroende som ett
självständigt kunskapsfält, men också för att den interna
kunskapsutvecklingen ska ta fart. Detta sker naturligtvis redan idag i
viss utsträckning, men här finns ett stort utrymme för utveckling. I ett
nytt fält kan det vara naturligt att man framför allt vänder sig till
teoribildning utanför sitt eget fält, men nu är det viktigt att i ännu
större utsträckning rikta blicken också mot annan konstnärlig forskning
för att utvärdera och bygga vidare på dess teori, metod och
resultat.[fn:10] Jag menar att konstnärlig forskning inte bara är
tvärvetenskaplig utan också är multidisciplinär till sin natur, det vill
säga att den i vissa fall rent av är beroende av andra discipliner än
det rent konstnärliga för att kunskapen ska kunna kommuniceras såväl i
som utanför dess egen domän.[fn:11] Symptomatiskt beskriver även Stjerna
arbete med ljudinstallationer som en multidisciplinär praktik, och
själva avhandlingen i sin helthet kan även den ses som multidisciplinär.
Det är dock viktigt att förstå den politisk dimension som det
tvärdisciplinära pekar mot. Samverkan är ett ledord för samtliga
universitet och högskolor idag och tvärvetenskap har i vissa fall blivit
ett neoliberalt självändamål. Detta gagnar inte alltid utvecklingen av
ett forskningsfält där behoven också behöver komma inifrån, snarare än
att de läggs på utifrån.

I Stjernas avhandling harmonierar det sätt hon bygger upp det teoretiska
och metodologiska ramverket i stor utsträckning med hur jag i tidigare
nämnda bokkapitlet föreslår att den den gängse uppfattningen av
relationen mellan teori, metod och praktik behöver omformuleras. Även om
Stjerna inte beskriver det explicit är det min uppfattning att hon
bygger upp definitionen av begreppet "sound art", och dess ontologiska
underbyggnad, genom att korrelera sin egen erfarenhet som praktiker med
en filosofisk och musikvetenskaplig genomgång av hur begreppet har
etablerats.[fn:12] Hon ger följande beskrivning av praktiken:

#+BEGIN_QUOTE
  To engage in sound installation as a site-specific practice is thus to
  position oneself, as an artist, as a node in the heterogenic field of
  what often is referred to as "sound art" respectively "sound art in
  public space." It is to understand that sound installation, in all its
  specificity emanates from a variety of different practices and
  traditions, which together generate a spatially explorative,
  multi-disciplinary practice.[fn:13]
#+END_QUOTE

Även med en rudimentär förståelse av Deleuze och Guattaris filosofi är
det redan i detta citat möjligt att se hur valet av teori är
välmotiverad. Det multidisciplinära angreppssättet förutsätter att de
olika delarna i undersökningen är sammankopplade och hur de kommunicerar
med varandra, vilket är själva kärnan i hur begreppet transversalitet
ska förstås. I en miljö som är genuint multidisciplinär är det
nödvändigt att ha en metod som tillåter obruten kommunikation mellan de
olika delarna av projektet och begreppet transversalitet användes från
början av Guattari i ett liknande syftet, som en kritik mot den
dualistiska synen på relationen mellan analytiker och analysand:

#+BEGIN_QUOTE
  The concept of transversality emerges in part out of Guattari's
  prolonged critique of the 'personological' understanding of language
  at work within psychoanalysis, and, specifically, within Lacanian
  versions of analysis. While not initially conceptualized in terms of
  enunciation, transversality---in Guattari's early writings
  institutional transference (later reframed as 'group transversality')
  --- aims to capture the unconscious as an investment of the broader
  elements and processes within the specific social setting of the
  hospital, a pattern of investment that would come to light only with
  the greatest difficulty in the dyadic enunciative setting of the
  analyst's consulting room.[fn:14]
#+END_QUOTE

Själva begreppet bär alltså redan från början med sig det som Stjerna
beskriver som ett resultat: en sammanvävd transversal process som
omformulerar hierarkier till kontinuerliga och i vissa fall spatiala
system. Här ingår relationen mellan konstnärssubjektet och publiken, som
visserligen har utsatts för kritik sedan 1960-talet.[fn:15] I /Before
Sound/ är fokus processerna i skapandet och produktionen och publiken
framträder inte direkt som en agent som diskuteras. Det transversala
utspelar sig därför primärt mellan platsen, konstverket och
konstnärssubjektet:

#+BEGIN_QUOTE
  In this doctoral research, the concept of assemblage has enabled me to
  articulate a mode of artistic practice in which site-specific sonic
  conditions and production operate as immanent, inter-relational,
  machinic, and transversal processes. I acknowledge the importance of
  this way of thinking in the subtitle of the thesis, "Transversal
  Processes in Site-Specific Sonic Practice," and its influence can be
  seen in the previous chapter's presentation of the field. As I have
  suggested through my descriptions, the initial explorative process,
  the establishment of spatial perception, the development of sonic
  strategies and technology, and the construction process on site, all
  emerge as the result of complex, machinic interconnections that span
  transversally between "the site," "the artwork," and the
  "artist-subject." In this, I advocate a move beyond the traditional
  separations that establish these as three distinct entities.[fn:16]
#+END_QUOTE

Kanske kan man därigenom dra slutsatsen att den transversala processen
är både metod och resultat? Åtminstone är det som metod transversalitet
beskrivs i citatet ovan och som sådan borde den vara intressant även i
annan konstnärlig forskning. Det undermedvetna, som Guattari diskuterar
i citatet ovan och som jag återkommer till längre fram i kapitlet, har
en del med den konstnärliga upplevelsen att göra, och om transversalitet
kan bidra med att begreppsliggöra det som sker även i den konstnärlig
processen så skulle en del vara vunnet. Och, som sagt, /Before Sound/
visar att det kan vara möjligt.

Att begreppet härstammar från Guattaris önskan att fånga förståelsen av
det undermedvetna är inte oväsentligt, inte heller dennes brott med med
den Lacanska traditionen för psykoanalys. Som tidigare nämnts så bygger
mycket av den filosofi som Deleuze och Guattari utvecklade tillsammans
på en kritisk granskning av bland annat den Freudianska teoribildningen.
Lite förenklat kan vi knyta Guattaris ambition att bryta med den binära
analytisk modell som analytiker/analysand innebär till Deleuze kritik av
det transcendentala tänkandet som har varit så central för Europeisk
filosofi. Genom Guattaris analytiska grupptransversalitet kunde man
sannolikt närma sig själva terapisessionen mer som en process av
tillblivelse genom det undermedvetna (nu som en produktiv kraft),
snarare än som en aspekt av det medvetna (eller omvänt). Detta påminner
samtidigt om de försök att dekonstruera de binära eller dyadiska
relationerna mellan olika agenter i den konstnärliga produktionen som så
många konstnärliga forskare, inklusive Åsa Stjerna, har varit upptagna
med. Frågan är hur vi från denna förståelse av relationerna mellan
aktiva och sammanvävda komponenter i det konstnärliga arbetet kan ta oss
mot en insikt i vad dessa relationer säger om den konstnärliga
praktiken.

För att förstå varför det undermedvetna är relevant i det här
sammanhanget vill jag ta upp en text av Gregory Bateson som jag har
använt flera gånger tidigare. Bateson var en brittisk antropolog,
sociolog, filosof och cybernetiker som har en nära relation till
Deleuze. Det finns ett fåtal referenser till Bateson hos Deleuze, bland
annat två i /Mille Plateaux/,[fn:17] men det finns de som menar att
inflytandet från Bateson egentligen var betydligt större än vad som
framgår av referenserna.[fn:18] Det som gör Bateson intressant i den
specifika diskussionen om konstnärlig kunskapsbildning är dock hans syn
på just det undermedvetna och hur olika typer av information och
upplevelser kodas i hjärnan, såväl som i kroppen.

I Freudiansk teori delar man upp mental aktivitet i primära och
sekundära processer. De primära är icke-verbala och drömlika, och
föregriper de sekundära som är det reflekterande och medvetna jagets
uttryck. Konst är generellt "an exercise in communicating about the
species of unconsciousness [...] a play behaviour whose function is
[...] to practice and make more perfect communication of this
kind."[fn:19] Nu kan det framstå som att vi har återinfört en separation
mellan det inre, de primära processerna, och det yttre, de sedundära.
Sannolikt så var det bland annat denna uppdelning som Guattari ville
komma åt när han försökte tänka om terapisituationen. Men dessa två
kategorier av processer behöver inte vara väsensskilda utan kan snarare
ses som två möjliga, och i vissa fall parallella, sätt att koda kunskap
och erfarenhet (eller affekter). Då är inte frågan hur vi ställer de mot
varandra, utan hur vi kommunicerar mellan, eller inom dem. Bateson
skriver:

#+BEGIN_QUOTE
  [The] algorithms of the heart, or, as they say, of the unconscious,
  are, however, coded and organized in a manner totally different from
  the algorithms of language. And since a great deal of conscious
  thought is structured in terms of the logics of language, the
  algorithms of the unconscious are double inaccessible. It is not only
  that the conscious mind has poor access to this material, but also
  that when such access is achieved. /e.g./, in dreams, art, poetry,
  religion, intoxication, and the like, there is still a formidable
  problem of translation.[fn:20]
#+END_QUOTE

I inledningen pekade jag i all korthet på hur konstnärlig kunskap ofta
inte utan vidare låter sig beskrivas verbalt. I ljuset av detta kan det
vara tilltalande att se en översättning från det omedvetna till det
medvetna som lösningen, men det finns flera saker som behöver lyftas för
att vi på ett hållbart sätt ska kunna ta ställning till problemet om
"översättning". För det första har vi frågan om begreppsliggörandet av
den konstnärliga praktiken, det vill säga processen av att skapa begrepp
som gör det möjligt att artikulera en kunskap. I /Before Sound/ gör Åsa
Stjerna detta, bland annat genom att använda Deleuze begreppsapparat.
Detta leder henne också till vissa specifika resultat som i sin tur
relaterar till bland annat det platsspecifika, men också till hur själva
praktiken ter sig. Men om man tänker sig att man är i behov av att
formulera egna begrepp så kan man hamna inför Batesons utmaning: Hur det
är möjligt att omformulera eller översätta en konstnärlig strategi till
en verbal utan att den samtidigt förlorar mening eller fastnar i en
meningslös rad av metaforer eller representationer?

Samtidigt finns det inomkonstnärliga begrepp som inte behöver en
översättning för att fungera. För detta är den kontextualiseringen av
projektet som diskuterades ovan viktig för att begreppen som används ska
få pregnans och tillåter att diskursen inom fältet blir användbar. I
musik kan till exempel musikteoretiska begrepp nyttjas i detta syfte,
förutsatt att dessa relateras till praktiken på ett användbart sätt.
Både Deleuze och Guattari i och Bateson i diskuterar dock framförallt
det som den konstnärliga upplevelsen ger upphov till, rent kognitivt,
snarare än den kreativa processen i sig. Mycket konstnärlig forskning,
så även Åsa Stjernas avhandling, beskäftigar sig framförallt med hur
processen att /göra/ konst fungerar och i den undersökningen så kan
resultatet, förutom att det är konst, vara ett sätt att validera
utforskandet av processen (vilket dock fortfarande gör det angeläget att
kunna diskutera resultatet).

Det är inte säkert att den konstnärliga processen som leder fram till
ett konstnärligt resultat är enkelt jämförbar med upplevelsen av att
erfara resultatet. I vissa fall kan det vara så men i andra fall, som i
/Before Sound/, ligger delar av processen närmare ställningstaganden som
har med praktiska omständigheter att göra; Hur fungerar en sladd? Hur
kan en högtalare installeras? etc. Är även dessa kodade i det
"omedvetnas algoritmer", för att använda Batesons terminologi, eller är
de del av en process som egentligen ligger närmare andra
forskningsdiscipliner än vad man kanske först vill tro? Jag menar att
det kan vara så i vissa fall, men att vi samtidigt inte får glömma att
den centrala aspekten av konstnärlig forskning att det är en konstnärlig
sensibilitet som ligger bakom valen som görs i det konstnärliga arbetet.
Förmågan att föreställa sig det konstnärliga resultatet som just konst,
även i arbetet med tekniska installationer är avgörande och
signifikativt för konstnärligt arbete. Av den anledningen är det svårt
att helt komma bort från det affektiva eller det undermedvetnas logik
när vi vill beskriva den konstnärliga forskningsprocessen.

Frågan är om det egentligen handlar mindre om en översättning och mer om
att förstå hur vi kan förhålla oss till olika former för mänsklig
kommunikation. Guattari ville komma runt det han benämnde det
"personologiska" språkbruket i pyskoterapin, och Bateson pekar på att
konsten har en kommunikationskapacitet som gör den mer lik till exempel
andliga upplevelser, berusning och drömmar. Utmaningen är inte att det
finns olika logiska typer av medvetande och kunskap, utan hur vi kan
förstå dem genom en kommunikativ helhet. Klart är i alla fall att de
transversala processerna kan spela en stor roll här, men kvar är frågan
om dessa i sig kan ge oss mer stringent formulerad konstnärlig forskning
där det blir lättare för andra forskare att förstå och relatera till
resultat, process och metod.

Att det som jag här förenklat benämner det inre och det yttre inte är
två åtskilda paradigm för förståelse, kunskap och kommunikation kan inte
nog poängteras. Konst har länge präglats av idén om det "rena" och
"inre" inre uttrycket som ofta ställs i kontrast till det yttre
"befläckade". I denna modell är det inre idealistiskt, ärligt och
transcendentalt, och det yttre kan vara kommersiellt, beräknande och
materialistiskt. Även om det är förhållandevis lätt att ta avstånd från
dessa grovt tillyxade kategorier har de haft ett stort inflytande över
hur konst- och musikvärlden har utvecklat sig. Denna utveckling
uppmuntrar sökandet efter idéen om det rena uttrycket, det som passerar
förbi medvetandet, förbi det självmedvetna jaget. Ibland är strävan
efter originaliteten själva källan till sökandet efter det av
medvetandet obesudlade uttrycket, färgat av upplysningens bild av
identiteten; om varje individ är unik och oberoende borde också det
genuint personliga /uttrycket/ vara originellt. Saxofonisten Ornette
Coleman, till exempel, talar om strävan efter ett så spontant skapande
som möjligt och om en kreativitet utan minne.[fn:21] Han talar om hur
hans spel innan han nådde framgångar var mera ärligt än det sedan blev
och valde att börja spela trumpet och violin (som han var nybörjare på)
för att kunna spela och samtidigt slippa onödig kunskap.[fn:22]
Naturligtvis var Coleman lika originell efter sitt genombrott som före,
och retoriken här speglar till stor del den sociala och politiska
tidsandan som rådde, men kan ändå sägas peka på kraften i bilden av
personlig originalitet.[fn:23] På skivan /The empty foxhole/ från
1966[fn:24] spelar Coleman tillsammans med sin tioåriga son Denardo
Coleman på trummor och beskriver sin tillfredställelse över att spela
med någon som inte behövde bry sig om kritiker eller konsertarrangörer,
utan som kunde spela och vara fri.[fn:25] Detta hör Coleman när han
lyssnar på Denardo men också för att han har förmågan att lyssna på sig
själv; han kan konstatera att sonen besitter en egenskap han själv har
förlorat. Det yttre lyssnandet, att lyssna på den andre, kompletteras av
det inre lyssnande. Och, jämfört med att lyssna på den andre så är det i
vissa fall betydligt svårare att lyssna på sig själv. Som konstnärlig
metod är det utvidgade lyssnandet central i musikalisk konstnärlig
praktik och det är möjligt att vidareutveckla praktiken enbart genom
lyssnande. Colemans önskan att släppa taget om det invanda och inlärda
kan ses som ett försök att etablera nya transversala relationer mellan
den medvetna och språkligt kodade viljan att förnya, och den
konstnärligt kodade kunskapen om hur detta ska, eller skulle kunna,
gestaltas. Utan att göra en djupare analys av metoderna (lyssnandet), är
risken överhängande att landa i en syn på en relation mellan det
trascendentala inre och det fysiska yttre som i grunden är hierarkisk:
det inre, transcendentala är att föredra framför det yttre. Den bilden
har inte frigjort sig från det politiska bagage den bär med sig och gör
det därför inte lättare att beskriva vad konstnärlig kunskap är.

En anledning till att vi har en tendens att se konstnärlig praktik som
en individuellt artikulerad form för kunskap är att vi i huvudsak ser
konstnärlig verksamhet som en individuellt situerad praktik. Det är den
i vissa fall, och utan tvekan är detta den romantiska bilden av konsten
som något som kretsar kring ett solipsistiskt geni. Stjerna tar spjärn
mot denna bild när hon diskuterar sin metod:

#+BEGIN_QUOTE
  established traditions in contemporary art practice still harbour
  segments of binaries that separate an autonomous active (white, male)
  subject and a (passive) urban text. Rejecting this traditional view,
  in proposing that we become non-autonomous, I advocate that we view
  the artist-subject's agency in artistic production as
  transversal.[fn:26]
#+END_QUOTE

Det finns många anledningar, även utanför argumenten som förs fram i
detta kapitel, att motverka denna normativitet och jag tror att
konstnärlig forskning är ett utomordentligt väl anpassat sätt att göra
det på, åtminstone på det konstnärliga fältet.

Slutsatsen som kan dras av detta resonemang är att det är lätt att hamna
i en dubbelt problematisk situation när konstnärlig forskning
diskuteras: Först är det nödvändigt att beskriva konstnärlig praktik som
något som är byggt på kunskap och erfarenhet och som inte är internt,
mystiskt, hemligt eller underligt. Att skapa trovärdighet kring detta
argument är svårt på grund av den sociala och politiska starka
föreställningen om konstens, respektive (den vetenskapliga) forskningens
funktion i samhället. Först när det är möjligt att i någon mening
dekonstruera denna bild är det möjligt att påvisa att det i konstnärlig
praktik finns kunskap som har ett allmängiltigt värde och att detta kan
diskuteras, kritiseras och kommuniceras som forskning, och i interaktion
med andra forskningsmiljöer. Om inte den första delen av argumentet
finner trovärdighet, kommer inte den andra delen av det göra det heller.
Konstens roll som kunskapsform i ett större perspektiv, bortom enskilda
projekt, kommer jag att diskutera i nästa avsnitt.

* Metodologisk dynamik
  :PROPERTIES:
  :CUSTOM_ID: sec:org463364d
  :CLASS: unnumbered
  :END:

I en avhandling som är gränserna mellan praktik, metod och teori som
tidigare nämnts inte tydligt artikulerade utan ständigt rörliga.
Terminologin hämtad från Deleuze och Guattari är till exempel i vissa
fall såväl metod, teori och i vissa fall tydligt relaterade till
resultatet, och det är inte alltid från början självklart vad som är
avsikten (detta är dock inte en svaghet i Stjernas fall). Om vi tittar
på den första forskningsfrågan, /På vilket sätt kan jag som konstnär
utveckla utforskande tillvägagångssätt som understödjer en transversal
skapandeprocess?/, så är det klart att den transversala
skapandeprocessen är ett mål i sig, men lika tydligt är det i kapitel
fem att Stjerna genom sin praktik redan i början av projektet har
etablerat transversala kopplingar [fn:27]. Det transversala är alltså i
vissa fall både metod och resultat. Stjerna pekar på att det finns ett
stort behov för nya konceptuella verktyg och tillvägagångssätt som kan
gå bortom representation och transcendenta hierarkier, och framför allt,
teorier som kan synliggöra hur transformation etableras utifrån en
gedigen förståelse för konstnärliga processer.[fn:28] Det är i princip
detta avhandlingen sedan visar på genom en syn på själva
ljudinstallationen som en transformativ praktik som löper mellan ett
flertal konstnärliga strategier som var och en är en transversal
process.

Det är ännu svårt att se konstnärlig forskning som en disciplin som
genererar tydliga resultat utifrån väl beprövade metoder. Istället finns
det en rad möjliga artikulationer av kunskapsutveckling som alla pekar
på att det i den konstnärliga praktiken finns en epistemologisk
potential, ett möjligt kunskapssystem som, om den begreppsliggörs, kan
ha stort inflytande på en rad olika fält. I sammanhanget kan det påpekas
att denna tro på konsten som kunskapsbärande är delvis överensstämmande
med Deleuze och Guattaris resonemang i /What is Philosophy?/, där de som
tidigare nämnts definierar tre kreativa metoder för tänkande:
/filosofi/, /vetenskap/ och /konst/. Egentligen kan man gå ännu längre
och säga att det i princip överensstämmer med Deleuzes hela filosofiska
gärning att se konst som en form för kunskap eller som en form för
tänkande. Men om konst är kunskap, eller bär på en kunskapsbärande
potential, vari består den? Deleuze och Guattari skriver vidare:

#+BEGIN_QUOTE
  What about the creator? It is independent of the creator through the
  self positing of the created, which is preserved in itself. What is
  preserved---this thing for the work of art---/is a bloc of sensations,
  that is to say, a compound of percepts and affects/. [...] The artist
  creates blocs of percepts and affects, but the ony law of creation is
  that the compound must stand up on its own. [[[fn:29]][][s.164,
  kursivering av författaren.]]
#+END_QUOTE

Att konstverket i sig självt, och oberoende av upphovspersonen, har en
potential är tydligt, likaså att det kan och bör frigöra sig själv, men
i konstnärlig forskning är det ofta praktiken -- och vad för slags
kunskap den kan bära eller föra med sig -- snarare än resultatet, som
står i centrum. Det finns många exempel på hur denna kunskapsutveckling
kan se ut men här ska jag ge tre korta exempel som är i större eller
mindre grad hämtade från musikfältet.

1. Utöver att studera den konstnärliga praktiken som en kunskap i och
   för sig självt, är det möjligt att se den som ett sätt att förstå
   annan kunskap såsom teknik eller filosofi. I dessa fall kan man se
   den konstnärliga praktiken som en testbädd för ett konceptuellt
   ramverk som är omfattar andra discipliner än bara konsten. Det finns
   en aspekt av detta i /Before Sound/ där de filosofiska koncepten
   prövas mot en existerande praktik och sättet som praktiken utvecklar
   sig kan då ses som ett utforskande av filosofin. Begreppet
   /immanensplanet/ är ett exempel på ett koncept som är viktigt för
   Stjerna -- och helt centralt för Deleuze filosofi -- och som kan ses
   få, om inte en förklaring så en praktisk applikation, genom Stjernas
   konstnärliga praktik. I teknologisammanhang kan man föreställa sig
   att en teknik, säg ett programmeringsgränssnitt eller en specifik
   hårdvara, utforskas i en konstnärlig praktik. Den konstnärliga
   metoden, som i detta fall ska ses som en experimentell praktik där
   koncept prövas och utvärderas baserat på hur bra eller dåligt de
   interagerar med den konstnärliga ambitionen, används för att validera
   teknologin. En undersökning på denna nivå kan mycket väl leda fram
   till att tekniken som studerats bedöms annorlunda än den hade gjort i
   ett rent tekniskt sammanhang: en teknologi som i allt väsentligt ses
   som funktionell och stabil från ett tekniskt synsätt kan framstå som
   mindre användbar genom en konstnärlig undersökning. Det konstnärliga
   ramverket behöver i sig inte vara experimentellt utan kan mycket väl
   följa en befintlig tradition helt idiomatiskt, det är metoden som är
   experimentell: kritiskt evaluering genom konstnärlig metod. Detta
   angrepssätt skulle utan tvekan även generera insikter om den
   konstnärliga praktiken. Skulle studien även utforskas med en
   filosofisk begreppsapparat som Stjerna gör i /Before Sound/ så skulle
   de tre perspektiven konst, vetenskap och filosofi samverka och
   komplettera varandra på ett sätt som påminner om hur Deleuze och
   Guattari föreslår i .[fn:30]

   Insikten om att den konstnärliga sensibiliteten kan behövas i större
   utsträckning än vad vetenskapstraditionen kanske fram till nu har
   velat göra gällande kommer dock inte bara från konstnärlig forskning
   eller filosofin. Det samarbete som Kungliga Musikhögskolan och
   Kungliga Tekniska Högskolan initierade 2016 byggde till exempel på
   KTH:s insikt att en framtida ingenjör behöver en kompetens som går
   bortom den rent vetenskapliga kompetensen och speciellt intressant
   för KTH är det konstnärliga perspektivet. Det är likaledes
   motivationen bakom ett nyligen uppstartat tvärvetenskapligt centrum
   NAVET på KTH där KMH, Stockholms konstnärliga högskola samt Konstfack
   är partner.

2. Med en användbar metod kan även själva praktiken ses som en
   kunskapsgenererande fas. Här ingår de numera ganska vanliga studierna
   i interpretation eller alternativa speltekniker i nutida musik. En
   frågeställning utforskas genom praktiken och om experimentet faller
   väl ut så är det ett bevis på att praktiken är användbar även för
   andra som söker svar på liknande problem och är således en
   undersökning som genererar kunskap i det specifika fältet. Även denna
   typ av undersökningar kan dock sträcka sig bortom den konstnärliga
   sfären i vilket fall valideringen kan ske åt två håll. En studie i
   gruppimprovisation kan till exempel studera hur specifika typer av
   musikalisk interaktion kan ge gynnsamma resultat givet en viss
   problemformulering. Samma metod kan sedan prövas i andra interaktiva
   situationer, som social interaktion, och om den visar sig
   framgångsrik även där så går resultaten att återföra till det
   musikaliska sammanhanget och det uppstår en
   kunskapsåterkoppling.[fn:31] Även denna typ av undersökning finns
   representerad i /Before Sound/, kanske framförallt i relation till
   den andra forskningsfrågan. I exemplet med /Currents/ är
   beskrivningen av arbetsmetoderna en kommunikation av en process som
   inte bara gestaltade dataströmmarna och förhöll sig till de
   uppställda metoderna, utan som också skapade en modell för ett
   konstnärligt tillvägagångsätt som har både politiska och konstnärliga
   implikationer.

3. En tredje variant är att se det resulterande konstverket som en
   kunskapskälla, frigjord från upphovspersonen på det sätt som Deleuze
   och Guattari framhåller ovan. Denna strategi har uppenbara nack-
   eller fördelar (beroende på hur man ser det). Om det ska stå för sig
   själv ("stand up on its own"[fn:32]) så måste det, åtminstone i
   musik, förlita sig på ickekonceptualiserade kommunikationsformer, det
   vill säga dokumentation av verket för att inte bli extremt begränsat.
   Tidigt i konstnärlig forskning var detta normen. Det skulle vara
   konsten, i och för sig själv, som utgjorde slutresultatet i
   forskningsarbetet och därmed utgöra det kunskapsbärande elementet i
   konstnärlig forskning. I praktiken var det endast ett fåtal
   avhandlingar som egentligen fullföljde den principen, men fortfarande
   är diskussionen om balansen mellan det som lite slarvigt kallas för
   "det skrivna" och "det gestaltade" aktuell.[fn:33] Det finns
   naturligtvis flera anledningar till detta, men en relevant punkt som
   förtjänar att framhållas är att det hela tiden finns en risk att en
   konstnärlig avhandling är en avhandling med en omfattning som
   motsvarar en monografi inom humaniora (där detta är normen), men som
   även innehåller ett konstnärligt arbete som är lika omfångsrikt. Helt
   enkelt en dubbel avhandling. Det konstnärliga resultatet i sig måste
   ha en framträdande position i en konstnärlig avhandling då det utgör
   själva objektet och även det man skulle kunna kalla empirin, men det
   behövs en mer initierad diskussion om hur detta ska representeras i
   avhandlingen.[fn:34] Men om vi accepterar en representation av det i
   form av en dokumentation, vad är det som säger att en inspelning är
   bättre än en beskrivande text? Det kan naturligtvis finnas många fall
   där det är det (de flesta), men den poäng jag försöker göra här är
   att förutsättningarna för vad som är en relevant dokumentation
   och/eller diskussion av ett konstnärligt resultat inte kan avgöras på
   generell nivå utan måste göras utifrån de specifika förutsättningarna
   som råder i projektet. Därför kan i vissa fall konstverket i sig
   självt vara det slutgiltiga resultatet, men som sådant behöver det i
   regel vila på någon form för dokumentation och denna kan vara
   multimodal.

I /Before Sound/ pekar de tre forskningsfrågorna mot processen snarare
än resultatet varför jag menar att Stjernas avhandling är ett bra
exempel på hur avgränsningar har gjorts utifrån innehållet i
avhandlingen. Den begränsade dokumentationen kan helt enkelt inte ses
som ett problem eftersom det inte är upplevelsen av verken som är den
centrala diskussionen. Dessutom är det platsspecifika en helt central
parameter i Stjernas praktik såsom den presenteras i avhandlingen,
vilket gör en eventuell dokumentation ännu mindre relevant. Även om
detta är en aspekt som ytterligare kan diskuteras vill jag här först
kommentera hur det för avhandlingen viktiga begreppet /platsspecifik/ är
sammanvävt med den teoretiska ingången i avhandlingen. Centralt för
Deleuze och Guattaris filosofi i /Capitalism and Schizophrenia/ och
/What is Philosophy?/ är som sagt immanensplanet, som i sin tur har sitt
ursprung hos Spinozas panteism,[fn:35] eller tanken på att allt är en
substans snarare än ordnat i en hierarkisk och dualistisk
struktur.[fn:36] Givet att Stjerna utgår från detta immanensplan när hon
beskriver den konstanta rörelse i tillblivelse som de transversala
processerna är sammanvävda i, är idén om det platsspecifika och
odokumenterbara installationen helt konsekvent.[fn:37]

Stjerna beskriver sin praktik som multidisciplinär[fn:38] och även om
det inte är nödvändigt att en undersökning som denna samtidigt är
interdisciplinär[fn:39] betyder det att flera olika kunskapsfält samsas
sida vid sida i forskningen. Detta kan lätt bli en utmaning och även om
Stjerna elegant navigerar runt behovet att beskriva den filosofi som hon
utgår från och lyckas dra rimliga gränser för vad som inkluderas och vad
som exkluderas, är det tveklöst en avhandling i minst två discipliner:
filosofi och konst. Detta är inte, vill jag betona, ett problem, snarare
är det sannolikt en nödvändighet för att komma åt de verkligt
intressanta perspektiven, och här behövs det goda exempel som kan föra
fältet framåt. Men risken finns att det blir en dubbel avhandlingar som
diskuterades ovan, det vill säga omfattande avhandlingar som egentligen
avhandlar två distinkta ämnen. Men här finns även risken för
avhandlingar som helt undviker det konstnärliga perspektivet och
fokuserar på ett angränsande ämne eller avhandlingar som inte tydligt
nog relaterar till det angränsande ämnet, vilket kan leda till att
argumentationen i sin helhet faller. Samtliga dessa faror går att
undvika med rätt handledning, men problemet med att hitta rätt
handledare är uppenbart när det handlar om ämnen som eventuellt inte
finns representerade på fakulteten.

Detta är en av anledningarna till varför bihandledaren ofta fyller en så
viktig roll i konstnärlig forskning på ett sätt som den inte alltid gör
i vetenskaplig forskning.[fn:40] Bihandledaren kan vara den personen som
garanterar att ett angränsande ämnen får tillräckligt stor roll och
genomlysning i arbetets helhet och kan i vissa fall, eller i vissa
perioder av arbetet, framstå som projektets huvudhandledare. Men det
finns ytterligare en anledning till bihandledarens betydelse som har att
göra med den tidigare nämnda svårigheten att hitta rätt
handledarkompetens på fakulteten eller på högskolan. Ännu är endast ett
fåtal lärare på de konstnärliga lärosätena disputerade (även om
variationen här är stor mellan olika lärosätena). Då det ofta finns ett
behov av att huvudhandledaren och doktoranden är på samma institution så
kan en lösning vara att huvudhandledaren blir mer av en
institutionshandledare och att den huvudsakliga handledningen sköts av
bihandledarna. Även om detta inte behöver vara problematiskt i sig kan
det leda till obalans i hur forskningsfältet utvecklar sig i relation
till andra. Handledarkompetens och seminarieverksamahet är uppenbart
centrala delar av en forskningsmiljö.

* Den konstnärliga kunskapens dynamik
  :PROPERTIES:
  :CUSTOM_ID: sec:orgeef416e
  :CLASS: unnumbered
  :END:

Utvecklingen av konstnärlig forskning i Sverige kan ses utifrån minst
tre delvis överlappande processer. Den ena rör den utbildningspolitiska
aspekten av konstnärlig utbildning i Bologna-modellen, men började ännu
tidigare än så, i Sverige med högskolereformen 1977.[fn:41] Den pekade
på att alla högskolor skulle bygga på utbildning som är baserad på
forskning varför även de konstnärliga utbildningarna nu skulle bedriva
forskning. Eftersom dessa bedriver konstnärlig undervisning eller
undervisning med konstnärliga metoder så måste de även bedriva
konstnärlig forskning -- detta kallades dock för konstnärligt
utvecklingsarbete snarare än forskning. I grunden ligger jämställandet
av konstnärlig och vetenskaplig forskning som nu ses som två uttryck för
kunskapsproduktion.[fn:42]

Den andra processen är mer svårfångad men handlar om hur konst- och
kulturlivet i samhället har utvecklat sig under de senaste decennierna.
Det fält inom vilket konstnärliga uttryck diskuteras och kommuniceras
har för vissa uttryck, som musik, förändrats i mycket stor grad.
Dagspressens recensionsverksamhet, Public Service funktion och det
offentligas stöd till musiklivet har förändrats radikalt vilket har
skapat nya behov för ytor att diskutera och experimentera med
konstnärliga uttryck. Här har den konstnärliga forskningen börjat fylla
ett stort hål.

En tredje process rör en mer filosofiskt orienterad epistemologisk fråga
om vad kunskap kan ses vara, och hur den kan kommuniceras. En vanlig,
initial, invändning mot konstnärlig forskning, som diskuterades ovan, är
att något som i allt väsentligt är beroende av sinnesintryck, som
upplevelsen av konstnärligt uttryck kan sägas vara, inte kan utgöra
grunden för forskningsmässig kunskap. Även om denna invändning vilar på
en missuppfattning av såväl forskningsmässig kunskap som konstnärlig
kunskap så rör den vid en viktig grundförutsättning för all
kunskapsutveckling, nämligen att det finns grundläggande förutsättningar
som det går att enas omkring. Utan dessa blir det omöjligt att etablera
ett nytt forskningsfält.

** Konstnärlig forskning som kunskap i praktiken
   :PROPERTIES:
   :CUSTOM_ID: sec:praktiska-exempel
   :CLASS: unnumbered
   :END:

Det är en utmaning att argumentera för konstnärlig kunskap i en samtid
som samtidigt präglas av en övertro på det vetenskapliga
kunskapssystemet, en missriktad postmodernistisk avart[fn:43] där varken
rätt eller fel existerar och en hyperkapitalism som inte ser sina
gränser. Machiarini-fallet på KI[fn:44] är ett exempel på vad som händer
när dessa tre samverkar och havererar. Jag ska försöka peka på några
områden där jag ser att konstnärlig forskning kan komma att få stor
betydelse om kunskapen hanteras på ett adekvat sätt, men jag
argumenterar framförallt utifrån ett musikperspektiv och bilden kan vara
väsentligt annorlunda inom andra konstnärliga fält.

Det digitala har idag helt genomsyrat såväl produktion, distribution som
konsumtion av musik samtidigt som det digitala endast i liten
utsträckning är en teknik som präglas av specifikt konstnärlig
utveckling. Det betyder att produktionsverktyg, som mjukvara för
inspelning och redigering, samt program för uppspelning visserligen för
det allra mesta är anpassade för förutsättningarna för dessa
verksamheter, men det finns förhållandevis liten kunskap om de faktiska
konstnärliga processer som ligger bakom användandet. Etableringen av
artificiell intelligens visar ytterligare på behovet av nya metoder för
att bättre förstå vidden av förändringen som vi är inne i. Även om
internet inte är nytt var det inte många som för tio år sedan hade trott
att vi idag, genom våra telefoner, trådlöst skulle få kontakt med en
till synes oändlig samling musik, bara för att ge ett exempel. Följden
av detta är att en majoritet av människor i västvärlden, själva designar
sin egen ljudmiljö och i någon mening, om man vill se det positivt, har
tagit kontroll över sitt eget musiklyssnande. Många av de verktyg som
har möjliggjort denna transformation är produkter av en ingenjörskonst
på mycket hög nivå. Spotify, till exempel tog utgångspunkt i teknik som
vuxit fram i en dunkel periferi under Pirate Bay, och gjorde delningen
legal och legitim. De fick ett tekniskt försprång och blev snart ensamma
herre på täppan. Detta är dock en utveckling som har skett helt och
hållet på kommersiella grunder och helt utan konstnärliga ambitioner.
Själva förutsättningen för Spotifys framgång var att man sänkte
ersättningen till de artister som spelades vilket kan ses som en
makrovariant av att såga av den gren man sitter på. Trots att detta
företag inte på något sätt kan ses vara en del av det konstnärliga
musiklivet där musik produceras talar man om Spotify som del av det
svenska musikundret.[fn:45]

Det här är ett uttryck för problemet som musik lider av: musiken som
konstform har aldrig gjort upp med musik /som produkt/ utan de båda,
musiken och produkten, är i allt väsentligt sammanvävda. Musiken är helt
och fullt kommodifierad och därför kan "det svenska musikundret"
samtidigt inkludera musikteknikföretag och Ann-Sofie von Otter. Nu finns
det naturligtvis extremt starka kommersiella krafter i operabranschen,
men skillnaden är den att von Otter hade aldrig kunnat ta sig till den
position hon har utan att hon hade otvetydiga konstnärliga kvaliteter,
medan teknikföretag som Spotify kan utvecklas helt utan dessa att
konstnärliga överväganden styr utvecklingen.

Här finns en viktig plats för den konstnärliga forskningen och här kan
dess resultat utvärderas på en marknad långt utanför akademiens
skyddande väggar. I min avhandling från 2008 pekade jag på behovet att
inkludera en konstnärlig dimension när modeller för interaktivitet
skapas.[fn:46] Den bakomliggande idén var den att en teknologiskt
orienterad interaktivitet inte bara riskerar att bli en grov förenkling
av vad vi förväntar oss av en interaktiv upplevelse (välj en färdig
spellista istället för att skapa din egen). Resultatet kan dessutom bli
att användarens förväntningarna på tekniken sänks. Genom att istället se
på utvecklingen av interaktivitet utifrån vad konstnärer, musiker och
tonsättare vill få ut av den skapas en miljö där helt andra beslut tas
och de interaktiva möjligheterna expanderas snarare än begränsas.

Utifrån det komplexa och svårgreppbara fältet av artificiell intelligens
(AI) finns flera möjligheter för konstnärlig forskning att spela en
roll. Liksom i exemplet ovan, beträffande interaktivitet, är AI ett
område där antaganden om mänsklig interaktion spelar roll, men även
antaganden om vad mänsklig erfarenhet utgör. Dessutom ryms otroligt
svåra etiska frågor. Alla dessa kan angripas genom konstnärliga
experiment där det mest omedelbara är att genom experiment utnyttja en
teknologi för konstnärlig produktion. Ett sådant projekt kan säga något
både om teknologins stabilitet och om hur konstnärlig aktivitet fungerar
i interaktion med teknik.[fn:47]

Genom metoder lånade från postkolonialismen har gruppen The Six Tones
under en rad år arbetat med interkulturella möten.[fn:48] Med det
övergripande målet att överbrygga kulturella avstånd har vi metodiskt
arbetat konstnärligt med konserter, skivproduktion och forskning. Målet
i varje projekt har varit att komma fram till ett övertygande
konstnärligt resultat har vi inte strävat efter enkel kunskapsöverföring
utan efter ömsesidigt lärande, differens och lyssnande. Genom en rad
turnéer och skivinspelningar har vi haft möjlighet att utvärdera
praktiken i ett flertal sammanhang. Under 2020 kommer vi att arbeta med
migrerade musiker i Sverige för att bland annat försöka förstå hur och
varför Sverige konsekvent har uteslutit några dessa musikers
kulturtraditioner. Några av de stora grupper som har kommit till
Sverige, som de från Iran och Irak och forna Jugoslavien på 70- och
80-talen, är inte i allmänhet representerade med sina musiktraditioner
på konserthus, scener eller i kulturpolitiska sammanhang. Konsekvensen
är att en del av dessa musiker befinner sig i ett konstnärligt
ingenmansland, långt från sitt hemlands levande traditioner, men
samtidigt utan möjlighet att etablera sig konstnärligt i sitt nya land.
I projektet hoppas vi bättre förstå dessa musikers traditioner, men
också bygga upp en kunskap som kan bidra till en förändring. Att arbeta
med musik på liknande sätt, med väl utarbetade metoder i ett
forskningssammanhang är ett sätt att utnyttja konstnärlig kunskap inom
ett fält där Sverige i dagsläget har svårt att politiskt, etiskt och
kulturellt hitta rätt.

* Diskussion
  :PROPERTIES:
  :CUSTOM_ID: sec:diskussion
  :CLASS: unnumbered
  :END:

Jag vill än en gång återkomma till den interrelation mellan konst,
vetenskap och filosofi som tre former för tänkande som Deleuze och
Guattari propagerar för i , och som jag i någon mening anser präglar
undersökningen i /Before Sound/. Det finns en viktig poäng i deras
resonemang som finner oväntad resonans i den svenska
högskoleförordningen och dess unika uppdelning mellan konstnärlig och
vetenskaplig grund och där dessa två kunskapsformer betraktas som
likvärdiga. Att se det konstnärliga och det vetenskapliga som två
väsenskilda men samtidigt kompletterande former för tänkande får
självklart konsekvenser för hur vi ska, eller kan se, på konstnärlig
forskning och valideringen av resultaten. Konsekvenser som kanske inte
helt utnyttjats i konstnärlig forskning. Det finns en tendens att se
forskning som forskning vilket är adekvat i många fall, men inte alla.
Även om vi till exempel kan peka på en konkret nytta med konstnärlig
forskning, en nytta som i någon mening är relaterad till nyttoaspekten
av en del vetenskaplig forskning, är det inte säkert att detta ska vara
modellen för all konstnärlig forskning. Istället behövs en mer aktiv
diskussion om vilken eller vilka modeller som ska användas för
kvalitetsbedömning av konstnärlig forskning: Vilken roll har den
konstnärliga praktiken och utifrån vilka kriterier ska den bedömas? I
vilka forum ska kvalitet i konstnärlig forskning diskuteras? Hur bedöms
metod och teori i konstnärlig forskning? Hur bedöms /impact/ i
konstnärlig forskning? Ytterligare en fråga som skulle behöva diskuteras
mer för att hantera relationen mellan konstnärlig forskning och
konstnärlig praktik utan forskning, är hur kunskapsöverföringen ska ske.
Med andra ord, hur kommer resultat av konstnärlig forskning hela det
konstnärliga fältet till del?

Eftersom de flesta länder saknar den uppdelning mellan vetenskaplig och
konstnärlig grund, och eftersom det vetenskapliga forskningsfältet är så
dominant, finns det alltid en tendens att konstnärlig forskning glider
mot det vetenskapliga och blir en variant av vetenskaplig forskning,
snarare än ett unikt och självständigt sätt att resonera på. Men vi kan
inte mäta den konstnärliga forskningens värde utifrån vad den kan
åstadkomma /som vetenskap/, helt enkelt för att det inte finns någon
större poäng med det. Hybridkonstellationer kan skapas, likt de jag i
alla korthet presenterar ovan, och dessa kan genom sitt tvärdisciplinära
angreppssätt bli ytterst effektiva sätt att utöka kunskapen till
angränsade fält. Men detta är, och ska vara ett komplement till en
konstnärlig forskning som i huvudsak befinner sig i det konstnärliga
fältet. Men oavsett hur mycket eller litet forskningen relaterar till
olika kunskapsområden som den rör sig omkring måste den ske i en aktiv
samverkan med annan forskning i samma fält och i aktiv samverkan med sin
omvärld, /utan/ att förlora de specifika bedömningsgrunder som gäller
för det konstnärliga fältet.

Ett möjligt sätt att behandla den konstnärliga forskningen utifrån
Deleuze och Guattaris modell i skulle vara att se den som ett kontaktnät
mellan alla tre discipliner. Ungefär som en transversal process som
möjliggör kontakter från konsten till filosofin och vetenskapen. På ett
plan är det det som Stjerna gör i /Before Sound/. Det skulle samtidigt
möjliggöra att konsten som en form för tänkande är delvis oberoende av
den konstnärliga forskningen som här istället blir en /möjligthet/ för
kontakt mellan konsten, vetenskapen och filosofin.

För att ta ett exempel på hur svårt det kan vara att leva upp till de
vetenskapligt definierade kraven på /impact/ räcker det med att
återvända till relationen mellan filosofi och konst och betrakta de
tydliga paralleller mellan dessa två kunskapsområden. Båda har i
allmänhet setts som viktiga delar av (den västerländska)
kunskapsutvecklingen och båda har i någon mening förlorat sin
särställning och betydelse i samtiden. Dessutom så delar de båda ofta en
empiri som utgår från ett individuellt perspektiv. Det räcker med att
ytligt betrakta filosofin, som är en av våra äldsta forskningspraktiker,
för att snabbt konstatera att den har haft svårt att hävda sin
särställning. Lika otvetydigt är det att filosofi som konceptskapande
kraft har lagt grunderna till själva fundamentet för vårt samhälle idag.
Konsten har haft en lika uppenbar funktion för vår kultur och har lika
svårt att mäta sig som filosofin har haft.

För att illustrera vikten av att hålla fast i idén att konsten även kan
vara en distinkt kunskapskälla i sig själv lånar jag filosofen Frank
Jacksons berömda kunskapsargument. Det är ett tankexperiment vars syfte
det är att argumentera mot fysikalismen genom att visa att det måste
finns icke-fysiska aspekter av medvetandet. I grova drag går det ut på
att beskriva en kvinna som växer upp helt avskärmad från omvärlden, i en
helt svartvit miljö. Hon får aldrig uppleva färger, men hon lär sig
allt, precis allt, som finns att veta om dem. Hon lär sig även om det
neurofysiologiska och vad som händer när olika vågländer av ljus träffar
näthinnan. Hon kan föreställa sig hur det fysiskt är att se färg, men
har aldrig upplevt det. Vad händer när hon får komma ut ur sitt rum och
får uppleva färger på riktigt? Lär hon sig då något nytt? Finns det
något utöver det fysiska att lära sig som vi bara kommer åt genom
upplevelsen?[fn:49] Jackson menar att det gör det och att medvetandet är
mer än det neurologiska. Jag drar en parallell till idén om det
konstnärliga som en kunskapsform som går utöver det som vetenskapen kan
lära oss som jag menar såväl Bateson som Deleuze ger visst stöd: Om
vedertagna vetenskapliga definitioner och allmän empiri ger oss de fakta
som vi behöver för att förstå en sida av vår tillvaro så konsten kan
säga någonting om är allt det andra, det vi inte omedelbart kan se.
Vetenskapen kan bara ge oss en del av sanningen och det finns
kompletterande fält av kunskap, grundade i etik och konst, och bygger
liksom vetenskapen på empiri. Dessa är nödvändiga för att vi ska kunna
skapa oss en så komplett bild som möjligt av tillvaron. Det finns det
goda chanser att konstnärlig forskning kan bidra till att vi får en
bättre förståelse och kunskap om dessa andra dimensioner. Exempel på
sådan kunskap, varav några redan har presenterats, kan vara forskning på
förkroppsligad kunskap, kommunikativa strategier och interaktion. Alla
dessa tre har varit fokus för flera konstnärliga projekt och i alla
dessa tre områden har det varit tydligt att den konstnärliga
sensibiliteten och undersökningen har kunna öppna upp för en förståelse
som endast svårligen hade kunna angripas på annat vis.

Samtidigt ska möjligheterna utnyttjas att inom ramarna för de
konstnärliga högskolornas forskningsverksamhet att utnyttja högskolan
som en plats för konstnärlig produktion. I takt med att utrymmet för den
experimentella konsten minskar i samhället så kan denna verksamhet i
större utsträckning äga rum på högskolorna: Konstnärlig forskning som en
ny arena för experimentell konst. Det är inte frågan om en akademisering
av konsten utan snarare det motsatta: låt konsten påverka akademien.
Konsten är i detta fall experimentell i den bemärkelsen att den utmanar
de gängse metoderna för såväl konst som forskning även om inte
resultatet i sig behöver vara experimentellt rent stilistiskt.
Högskolans egna scener som ett öppet fönster mot omvärlden och ett
utomordentligt bra sätt att bedriva samverkan på. Det kan vara
Barockmusik eller elektroakustisk musik, eller någon annan genre.

Jag tror att frågan om vad konstnärlig forskning är, eller vilken nytta
den har, är felställd. Frågan vi borde ställa oss är snarare i linje
med: Hur kommer ett samhälle se ut som inte har aktivt arbetar för att
utveckla möjligheterna till att ta del av, och utveckla, alla
kunskapsformer som påverkar den mänskliga tillvaron, inklusive
konstnärlig sensibilitet och filosofiskt resonerande? Sett till den
frågan blir det klart att detta måste vara en fråga som diskuteras på
bred front i samhället. Det är ingen tvekan om att vi lever i ett
vetenskapssamhälle först och främst och att det i sin tur skapat ett
tekniksamhälle. Om det finns övertygande argument för att vetenskapen
inte behöver konsten och filosofin så är jag beredd att tänka om. Tills
dess menar jag att allt pekar på att vi behöver tillgång till alla typer
av tänkande vi kan komma åt för att lösa de utmaningar vi står inför i
världen idag och att just tänkande genom konstnärlig praktik är ett
mycket användbart verktyg. Det visar inte minst Åsa Stjerna med .

[fn:26] [fn:50].

[fn:27] [fn:51].

[fn:28] [fn:52].

[fn:29] [fn:53].

[fn:30] [fn:54].

[fn:31] [fn:55].

[fn:32] [fn:56].

[fn:33] [fn:57].

[fn:34] [fn:58].

[fn:35] [fn:59].

[fn:36] [fn:60].

[fn:37] [fn:61].

[fn:38] [fn:62].

[fn:39] [fn:63].

[fn:40] [fn:64].

[fn:41] [fn:65].

[fn:42] [fn:66].

[fn:43] [fn:67].

[fn:44] [fn:68].

[fn:45] [fn:69].

[fn:46] [fn:70].

[fn:47] [fn:71].

[fn:48] [fn:72].

[fn:49] [fn:73].

[fn:50] [fn:74].

[fn:51] [fn:75].

[fn:52] [fn:76].

[fn:53] [fn:77].

[fn:54] [fn:78].

[fn:55] [fn:79].

[fn:56] [fn:80].

[fn:57] [fn:81].

[fn:58] [fn:82].

[fn:59] [fn:83].

[fn:60] [fn:84].

[fn:61] [fn:85].

[fn:1] \footcite{hultqvist2019}.

[fn:2] \footcite{Hedelin2017}.

[fn:3] \footcite{frisk-cobussen09}.

[fn:4] \footcite{frisk2016b}.

[fn:5] Se bland annat och .

[fn:6] \footcite{frisk08phd}.

[fn:7] \footcite{frisk2019}.

[fn:8] \footcite[Se
             t.ex. referenser till Cox och LaBelle: ][s.45]{Stjerna2018}.

[fn:9] \footcite{frisk2018:irl}.

[fn:10] Det är intressant att notera att detta behov finns nu, trots de
        isoleringstendenser jag beskrev i början av detta kapitel.

[fn:11] För konstnärlig forskning som är helt inriktad på att skapa ny
        kunskap inom sitt eget fält, som till exempel projekt som
        studerar hur man bäst preparerar ett piano för ett givet verk
        eller liknande, har eventuellt det multidisciplinära
        perspektivet inte samma betydelse.

[fn:12] \footcite[Se kapitel
          tre]{Stjerna2018}.

[fn:13] \footcite[s.42]{Stjerna2018}.

[fn:14] \footcite[s.234]{Goffey2015}.

[fn:15] \footcite[s.48]{Stjerna2018}.

[fn:16] \footcite[s.92]{Stjerna2018}.

[fn:17] \footcite{deleuze80}.

[fn:18] \footcite[Se
          t.ex. ][ Begrepp som \emph{rhizome}, \emph{double bind}, och
          \emph{schizoanalysis} som alla var viktiga för Deleuze och Guattari
          diskuterades långt tidigare av Bateson, även om just \emph{double
          bind} introducerades av Nietsche.]{Shaw2015}.

[fn:19] \footcite[s.137]{bateson72}.

[fn:20] \footcite[s.139]{bateson72}.

[fn:21] \footcite[s.117]{litzweiler92}.

[fn:22] \footcite[Intervju med
          Ornette Coleman i][s.33]{taylor77}.

[fn:23] För övrigt är Coleman's uttalande om att spela utan minne
        påfallande likt Marcel Duchamps tal om traditionens fängelse och
        att glömma med handen: "I unlearned to draw. The point was to
        forget /with my hand/."

[fn:24] \footcite{coleman66}.

[fn:25] \footcite[s.121]{litzweiler92}.

[fn:26] \footcite[s.119-20]{Stjerna2018}.

[fn:27] \footcite[s.145]{Stjerna2018}.

[fn:28] \footcite[s.85]{Stjerna2018}.

[fn:29] \footcite{deleuze1994}.

[fn:30] \footcite{deleuze1994}.

[fn:31] \footcite[Se t.ex. projektet ICASP
              som jobbade enligt denna modell:][]{lewis09}.

[fn:32] \footcite{deleuze1994}.

[fn:33] I sig utgör det ytterligare en dikotomi som det finns all
        anledning att tänka om. När är en text /bara/ en text och när är
        något gestaltat /uteslutande/ konst?

[fn:34] Detta är ett problem som vi har haft i Sverige inom konstnärlig
        forskning: undersökningarna och förväntningarna på resultaten
        bli orimligt höga vilket leder till avhandlingar som är enormt
        omfattande. Nyligen har jag varit opponent i såväl Estland som
        Nederländerna där textdelens omfattning på avhandlingen är ner
        mot en fjärdedel av vad svenska avhandlingar tenderar bli.

[fn:35] \footcite[s.93]{Stjerna2018}.

[fn:36] Detta är inte på något sätt ett försök att ge en fullödig utsaga
        om vad detta begrepp är för Deleuze. Det är centralt för hela
        hans arbete och har vida konsekvenser.

[fn:37] Även om själva begreppet platsspecifik skulle kunna ses som
        problematisk i sammanhanget, men det är delvis en annan
        diskussion.

[fn:38] \footcite[s.42]{Stjerna2018}.

[fn:39] En praktik som kombinerar många olika discipliner men som i
        grunden vilar på konstnärliga frågeställningar kan naturligtvis
        undersökas utifrån en konstnärlig grund och med konstnärliga
        metoder och därmed undvika att forskningen av den anledningen
        bli interdisciplinär.

[fn:40] I KMH:s samarbete med KTH har jag blivit varse detta.
        Bihandledare är inte arvoderade i deras system och ses inte som
        tillnärmesivis lika viktiga i avhandlingsarbetet som
        huvudhandledaren.

[fn:41] \footcite[Se t.ex. ][]{Lilja2015}.

[fn:42] Detta är givetvis en kraftigt förenklad bild.

[fn:43] Jag menar att postmodernismen egentligen har mycket mer att lära
        oss och att det inte är den i sig som är problemet, men detta är
        en diskussion som går bortom ramarna för detta kapitel.

[fn:44] \footcite{macchiarini2019}.

[fn:45] \footcite{konig2018}.

[fn:46] \footcite{frisk08phd}.

[fn:47] I ett pågående projekt på Musikhögskolan i Oslo med titeln
        Goodbye Intuition under ledning av Ivar Grydeland jobbar vi med
        dessa och liknande frågor. En ej ännu publicerad artikel i
        Organised Sound beskriver detta: /Aesthetics, interaction and
        machine improvisation/ (Frisk 2019)

[fn:48] Förutom mig själv består The Six Tones av Nguyen Thanh Thuy, Ngo
        Tra My och Stefan Östersjö. Se www.thesixtones.org för mer
        information.

[fn:49] \footcite[s.130]{Jackson1982}.

[fn:50] \footcite{deAssis2017}.

[fn:51] \footcite{hultqvist2019}.

[fn:52] \footcite{Hedelin2017}.

[fn:53] \footcite{frisk-cobussen09}.

[fn:54] \footcite{frisk2016b}.

[fn:55] \footcite{frisk08phd}.

[fn:56] \footcite{frisk2019}.

[fn:57] \footcite[Se
        t.ex. referenser till Cox och LaBelle: ][s.45]{Stjerna2018}.

[fn:58] \footcite{frisk2018:irl}.

[fn:59] \footcite[Se kapitel
        tre]{Stjerna2018}.

[fn:60] \footcite[s.42]{Stjerna2018}.

[fn:61] \footcite[s.234]{Goffey2015}.

[fn:62] \footcite[s.48]{Stjerna2018}.

[fn:63] \footcite[s.92]{Stjerna2018}.

[fn:64] \footcite{deleuze80}.

[fn:65] \footcite[Se
        t.ex. ][ Begrepp som \emph{rhizome}, \emph{double bind}, och
        \emph{schizoanalysis} som alla var viktiga för Deleuze och Guattari
        diskuterades långt tidigare av Bateson, även om just \emph{double
        bind} introducerades av Nietsche.]{Shaw2015}.

[fn:66] \footcite[s.137]{bateson72}.

[fn:67] \footcite[s.139]{bateson72}.

[fn:68] \footcite[s.117]{litzweiler92}.

[fn:69] \footcite[Intervju med
        Ornette Coleman i][s.33]{taylor77}.

[fn:70] \footcite{coleman66}.

[fn:71] \footcite[s.121]{litzweiler92}.

[fn:72] \footcite[s.119-20]{Stjerna2018}.

[fn:73] \footcite[s.145]{Stjerna2018}.

[fn:74] \footcite[s.85]{Stjerna2018}.

[fn:75] \footcite{deleuze1994}.

[fn:76] \footcite{deleuze1994}.

[fn:77] \footcite[Se t.ex. projektet ICASP
        som jobbade enligt denna modell:][]{lewis09}.

[fn:78] \footcite{deleuze1994}.

[fn:79] \footcite[s.93]{Stjerna2018}.

[fn:80] \footcite[s.42]{Stjerna2018}.

[fn:81] \footcite[Se t.ex. ][]{Lilja2015}.

[fn:82] \footcite{macchiarini2019}.

[fn:83] \footcite{konig2018}.

[fn:84] \footcite{frisk08phd}.

[fn:85] \footcite[s.130]{Jackson1982}.
