# Created 2024-12-29 Sun 12:00
#+title: Har Lyda Ekström Lindebäck lierat sig med högern? - kort
#+author: Henrik Frisk
Jag tycker definitivt diskussionen om konstnärlig forskning, och all annan forskning, är både nödvändig och viktig. Jag vet inte om jag skulle bli just "glad" av den, men jag har inget emot det. Därför svarar jag gärna på Lyda Ekström Lindebäcks frågor som hon ställer i artikeln "Har jag lierat mig med böghatande brunhögern?". 

1. *Ekonomin*

   De 122 miljoner som Ekström Lindebäck syftar på är alltså pengar som inte finns, eller tidigare fanns, i kulturlivet. Det är pengar till konstnärlig forskning som däremot bidrar till det genom att konstnärer får anställningar som doktorander. Det finns ingenting som tyder på att pengarna skulle förflyttas till kulturbudgeten.

   Hela den statliga forsknings- och utbildningsbudgeten ökade nära 4,5% till 2025 medan bidraget till de konstnärlig högskolorna endast ökade med 3,1% (3,4% för forskning). Efter produktivitetsavdraget återstår en ökning på 1,4% och med inflationen blir det i praktiken en sänkning. Inte den fantastiska höjning som Ekström Lindebäck antyder.

   Till övriga universitet menar Ekström Lindebäck att att det tillförs ytterligare ett "par hundra miljoner". Det är bara att titta på de miljöerna för att inse att det inte kan stämma.

   Med endast grundläggande kunskap om högskole- och unviersitetsekonomi kan man räkna ut att av de 122 miljoner som de enskilda konstnärliga högskolorna får i Stockholm återstår gissningsvis runt 55 miljoner till konstnärlig forskning. Skulle man ta bort forskningsanslaget till de fristående konstnärliga högskolorna kommer flera av de redan hårt pressade institutionerna utan tvivel gå i konkurs.

   I Ekström Lindebäck argumentation verkar det som att det är rekryteringen till just forskarutbildningen som ska bort i första hand. I andra hand ska själva forskningsbegreppet bort på kandidat- och masterutbildningarna. Då faller dessutom hela fundamentet som högre utbildning i Sverige bygger på. Den enda lösningen skulle bli att de konstnärliga utbildningarna blir yrkeshögskolor. Då blir de av med sin finansiering och kan bara utbilda om det finns jobb. De flesta program i ämnen som fri konst, komposition och litterär gestaltning kommer då att försvinna.

2. *Internationalsering*

   Konstnärlig forskning är inte, och ska inte vara, en arbetsmarknadsåtgärd för det svenska kulturlivet, alltså är detta en irrelevant invändning.

3. *Den konstnärliga forskningen har en genomgripande inverkan på samtliga kulturfält*

   Utgångspunkten att den ganska marginella betydelse som konstnärlig forskning har skulle vara en fara för hela kulturfältet är minst sagt besynnerligt. Det finns ju absolut ingen poäng med forskning i allmänhet om den inte interagerar med samhället. Detta är en kvalitet, inte ett problem.

   Under de 25 år jag har varit verksam i fältet har jag inte stött på en enda person som tycker att prioritet ska ges åt disputerade framför högt konstnärligt meriterade lärare i samband med rekryteringar. Jag känner /ingen/ i fältet som argumenterar för detta.

4. *Den konstnärliga forskningen förväxlar duktighet med samhällskritik*

   Jag tycker inte det verkar som att Ekström Lindebäck har tagit del av särskilt mycket konstnärlig forskning. Ibland får jag känslan av att det är endast är konstnärlig forskning på SKH som avses i diskussionen? Ekström Lindebäck raljerar över Claessons referens till att SD vill avskaffa såväl konstnärlig forskning som genusvetenskap, men det är en helt rimlig farhåga. Redan 2018 skrev SD i en motion till riksdagen (2018/19:377) att konstnärlig forskning ska avskaffas och genusvetenskap ska vingklippas.

   Forskning som bidrar till utvecklingen av 6G-nätverket, som arbetar med kulturarv, som ifrågasätter verkbegreppet och musikers psykiska hälsa, forskar kring kulturarv och migratinens påverkan på musiktraditioner och mycket mer, är exempel på konstnärlig forskning som gett och ger konkreta resultat. I vissa fall genom att ifrågasätta normer, i andra fall inte. Jag ser inte varför just denna fråga här skulle vara så laddad?

   Viktigt att påpeka är att min upplevelse är att friheten inom akademien i dag är större än i kulturfältet. Ekström Lindebäck påpekar att det är obligatoriskt att ange genusperspektiv i varje ansökan till VR, men i praktiken är dessa krav ännu mer bindande i kulturlivet.

5. *Den konstnärliga forskningen hjärntvättar kulturutövare till att söka sig bort från publiken.*

   När argumenten tryter tar man till storsläggan. Hjärntvättar? Kronvittnet Sophia Kosmaoglou var doktorand på Goldsmiths i London och disputerade 2012 pekar på svårigheten att kritisera institutionen från insidan. Detta var en mycket annorlunda miljö från dagens svenska kontext och säger lite. Men det absolut en viktig diskussion som bör föras utifrån relevanta exempel från vår egen tid och kontext.

   Konstnärlig forskning har förändrat och påverkat den för konsten destruktiva akademiseringen och gör så kontinuerligt och jag skulle kunna ge många exempel på det. Det finns ingenting i budgetpropositionen som tyder på att regeringen tycker att "konstnärerna ska in i akademin". Inget. Tvärtom. Att samtliga konstnärliga högskolor fick samma procentuella höjning är inte ett tecken på en strategisk satsning. I den mån detta är en strid har alltså Ekström Lindebäck redan vunnit den.

Utifrån en reaktionär syn på kulturen, där allt var bättre förr och utbildning i konst skedde i slutna rum med en mästare och en lärling är det ju inte ett dugg svårt att vara radikal. Att raljera över normkritik när man sitter i elfenbenstornet, mitt i ett kulturfältet som man till varje pris vill bevara, och ropa ut felaktigheter luktar misstänkt.

Slutligen, huvudfrågan i Ekström Lindebäck text är den politiska. Konstnärlig forskning är ett begrepp som finns med i högskolelag och högskoleförordning och vill man driva tesen att konstnärlig forskning ska bort så är det, precis som Nils Claesson pekar på, i den brunblåa myllan man ska gräva. Där väntar SD och säkerligen flera Tidöpartier med öppna armar.

Jag ser fram emot att följa diskussionen när Ekström Lindebäck ska övertyga SD om att det är just konstnärlig forskning, och inte samtliga fria teatergrupper, Riksteatern eller Norrköpings symfoniorkester som ska läggas ner. Eller Humaniora som i allmänhet har dränerats i decennier. Risken är att parnassen där Ekström Lindebäck sitter ryker med på köpet. Vad det skulle betyda för det rika kulturliv som Ekström Lindebäck längtar efter vågar jag inte tänka på.

Svaret på titeln på Ekström Lindebäcks rubrikfråga blir således: Ja, du har sannolikt lierat dig med högern. Varför nu just det skulle vara så viktigt. Du har all rätt att driva vilken politisk agenda du vill, men du kommer lyckas bättre om du använder korrekt data och riktiga argument. Vill du ha en fortsatt debatt om konstnärlig forskning ställer jag upp varje dag i veckan.
