# Makefile for etherSound paper.
# 
# Further, this Makefile 
# relies on bash script wrapping up the latex2html parameters.
# This script can be downloaded from:
# http://www.henrikfrisk.com/documents/downloads/l2html.sh
#
# If you wish to adapt this Makefile for your own projects
# follow the excellent instructions at:
# http://troy.jdmz.net/rsync/index.html
# on how to set up a safe but fully automated ssh'ed rsync 
# conection to your server.
#
# 18 March 2008	Henrik Frisk	mail@henrikfrisk.com

SRC_DIR			:= ../../../../ostersjo/svn/ostersjo/branches/dissertation
AUTHOR 			:= "Henrik Frisk, henrik<DOT>frisk<AT>mhm<DOT>lu<DOT>se, Stefan Östersjö, stefan_ostersjo<AT>hotmail<DOT>com"
DB_PREFIX 		:= "negmus_"

include ../common.mk