#+title: Beyond the unnecessary self
#+name: Henrik Frisk
#+options: toc:nil num:nil
#+cite_export: csl ~/Documents/articles/biblio/csl-styles/apa-7th.csl
#+LaTeX_HEADER: \usepackage[x11names]{xcolor}
#+LaTeX_HEADER: \hypersetup{linktoc = all, colorlinks = true, urlcolor = DodgerBlue4, citecolor = black, linkcolor = black}
#+latex_header: \usepackage[scaled]{helvet}
\renewcommand\familydefault{\sfdefault}

#+begin_src emacs-lisp
  (set-window-margins (selected-window) 2 2)
  (setq line-spacing 0.5)
  #+end_src

  #+RESULTS:
  : 0.5

* Abstract
** Beyond the unnecessary self

In my 2013 paper /The (un)necessary self/ [cite:@Frisk2013] I further explored the idea of the /giving up of the self/ as an important step towards the dismantling of the romantic idea of creation, and approach an understanding of creativity that is more closely aligned with the other. The other should be understood as anyone in the proximity of the artistic practice: a co-creator, a listener, a particpant or a remote collaborator. The point here is to move the focus from the creator to what is created and to understand the roles of the various agents involved.

In music, hyper-capitalism of the twenty first century is eager to commodify the artistic output, the artist, as well as the listeners. This is not only a problem for the freedom of art (a concept equally complex), it also makes the role of the self difficult to understand. But in the radicalization of the role of the creator, both a new work concept and a review of the self is necessary, even beyond the notion of giving up of the self. The ethics in artistic practices, that is, the moral values that are expressed through artistic practices in music, specifically improvisation, may complement traditional views on ethics and is an important aspect when discussing the roles of the self. The notion of the /Care of the Self/, as discussed in Michel Foucault's Volume Three of the /History of Sexuality/, is used as a method to approach this complex area. 

This presentation will be in the form of a lecture performance.
* Submission
Forum Artistic Research 2024
[[file:/Volumes/Freedom/Dropbox/Documents/articles/conferences/austria/submission.pdf]]
