# Created 2020-09-19 lör 14:11
#+TITLE: Aesthetics in machine improvisation (Machine (Un)intelligence)
#+AUTHOR: Henrik Frisk, henrik.frisk@kmh.se
* Prel abstract

The idea that artificial intelligence should be explored in music comes as a natural consequence of its impact in society today. Making use of distributed processing and connectionism in music, however, is not new and has influenced the development of many tools for music analysis and composition for decades already [[#Loy1989a][Loy1989a]],[[#Loy1989b][Loy1989b]],[[#frisk08phd][frisk08phd]]. In this article I will not discuss AI specifically, but rather explore how improvised music may serve as a context in which many of the issues that relate to AI may be interrogated. This is not primarily with the purpose to understand AI or the technology behind it, but with the intent to look at why a system for machine improvisation may or may not work and by which standard it may be evaluated. Playing with a system such as the one desecribed in this paper, with limited intelligence and no real cognitive skills will obviously reveal the weaknesses of the system, but it will also convey part of the preconditions and aesthetic frameworks that the human improviser brings to the table. If we want the autonomous system to have the same kind of freedom we commonly value in human players' improvisational practice, are we prepared to accept that it may develop in a direction that departs from our original aesthetic ambitions? If not, by what standard do we allow ourselves to limit its freedom? 

Within the frame of the artistic research projekt Goodbye Intuition (GI) hosted by the Norwegian Academy of Music in Oslo a group of musicians explore the meaning of the word intuition, musical structure and aesthetics by means of playing with a newly constructed improvisation machine (nick-named Kim Auto, or KA) [[#grydeland2018][grydeland2018]]. With an approach that may at first appear counterintuitive, GI attempts to challenge the roles and aesthetic values of the four musicans in the group by introducing a fifth member, a machine improvisor. The core method is artistic and the members engage in improvisations with the new machine member along with discussions and reflections, sometimes carried out in the context of open laboratories, including members of the audience in the discussions.

GI is not a music technology project and does not claim to be innovative on the level of the development of KA, nor is this paper a discussion of the underlying technology (unless when this is necessary for the discussion). Rather, the focus has come to focus on the aesthetics and ethics of improvisation in the context that GI affords. Of specific interest is the interpretative space that is opened up by the encounter with the seemingly responsive[fn:8] machine co-player. Analyzing a few of the labs performed in the project, the music that came out of it, as well as the responses from the participating musicians, sheds some light on the way that value judgements are developed and sometimes questioned in the group. The topic of interaction, and more specifically /interaction-as-control/ in contrast to /interaction-as-difference/ [[#frisk08phd][frisk08phd]] is revisited in order to explore the possible relations beteen musician and technology.

If music is to be regarded as a social activity that participates in expanding the communicative possibilities both within the group of musicans playing together, and to some extent among listeners, then the very idea of playing with a machine appear strange. Our communicative potential in even a sophisticated interactive system is relatively limited and different in nature from that in human-human communication. Even if the difficult question of empathy in music is put aside, the impact of a embodiment has received a lot of attention in the last few decades [[#Leman2015][Leman2015]]. In the act of playing a musical instrument, or even just while listening to music the role of the body is of great importance [[#kim2010imaginal][kim2010imaginal]]. Playing with a machine makes the conceptual assymetry between the embodied musician and their instruments and the abstract and disembodied computer come to the fore.


To improvise with a computer running an adaptive software for musical interaction raises questions that have relevance to both the designer of the improvising system, and the musicians playing with it. When dealing with any autonomous systems it is difficult to avoid some level of antropomorphism among the users [[#Blackwell2004][Blackwell2004]],[[#Young2009][Young2009]], but it is also clear that this effect contributes to the willingness to engage with the system [[#Nowak2003][Nowak2003]]. In this project it shows in the way we as musicians refer to the computer as if it was a human player and gives it a name. While this contributes to the sensation that the machine actually is intelligent in a human sense, it also puts a limitation to what is possible from the system point of view. If it proves to be possible to create a machine system that can improvise interactively with a human musician, why restraint the machine to behave like a human? This largely speculative and philosophical inquery leads to a number of questions but the primary focus in this paper is this:

If we want the autonomous system to have the same kind of freedom we commonly value in human players' improvisational practice, are we prepared to accept that it may develop in a direction that departs from our original aesthetic ambitions? If not, by what standard do we allow ourselves to limit its freedom? 

\printbibliography

[fn:8] KA is responsive in the sense that it listens to a limited number of parameters.

* Unused

To improvise with a computer running an adaptive software for musical interaction raises questions that have relevance to both the designer of the improvising system, and the musicians playing with it. 

and even if the difficult question of empathy in music is put aside, 

These questions are discussed based on the experiences from the laboratories performed in GI.


Regardless of the level of musical sophistication that a system such as KA may reach its lack of a physical presence greatly affects the playing experience. The extreme optimism in the field of robotics and AI in the 50s and 60s was dampened at about the same time that the impact of the body was put back "in the mind" [[#johnson1990][johnson1990]]. In music, and specifically in improvisation, the impact of the body has been widely discussed over the last few decades.

At the same time, this makes the context of musical improvisation the perfect test bed to test an automatic system. Furthermore it makes it possible to study the artistic consequences that the machine introduces and brings to the forefront questions concerning culture, aesthetics, style, presence and learning. In improvisation it is easy to take the question of aesthetics for granted, as something that is a result of who one decides to play with or in what contexts on may choose to play. The machine KA can be said to employ a complete lack of aesthetics as we know it or/and an incredibly rigid set of aethetic rules by which it plays.

It is common to think of the design of an electronic instrument as the employment of a set of stylistic rules rooted in an aesthetic tradition. In the introduction to his book /Composing Electronic Music: A new aestetic/ Curtis Roads speak of a convergence between the technical and aesthetic developments in music: "In paralell with technological developments, focused artistic practice has fostered a profound evolution in musical aesthetics and style" [[#roads2015][roads2015]]. While it is possible to see that this has had an important impact on the development of both popular and experimental music in the last century it is important to acknowledge that a musical automaton is not an electronic instrument. It goes far beyond the implications of an electronic instrument, even one that has some kind of musical logic built into it. 

This

* Notes from workshops and lab
** Ivar Lab #5, part 2, 16:40

"It was so strong what you did [referring to ...] in the way the machine picked it up that it was almost impossible to get away from. I kind of like that way... how this system dictates the form of the improvisation." Further on Ivar states that "the system forces us into the specific way to develop the material"

** Henrik #5, part 2, 17:30

Roughly:

In its current version to machine doesn't make a decision on the quality of the material it is being fed. Hence, what may happen if it picks up something you play which is not so strong, musically, or even an upright mistake it still may use that whith the consequence that you are forced to continue playing along with your own mistakes.

The machine makes you sound bad.

** Andrea Lab #5, part 2, 19:30

"For the first time now, I was  able to construct things with the machine. Normally [before the latest version of the software] it was more of a struggle. But here, because there is some organisation behind it which makes it interesting [makes the interaction interesting]" 

"I felt quite surprised sometimes that it acted... tasteful."

Music is structured in two interrelated phases: it is structured when created and it is re structured when listened to. From a semiotic point of view these processes are sometimes declared as the poietic and the esthesic phases.

The overarching ambition of musical semiology has been to provide tools for an
analytic understanding of the total symbolic fact of the musical work, and as such it is leaning towards Western classical music with a clear definition of the musical work [[#nattiez][nattiez]] but I will turn to it here to open up the discussion on the processes of musical structurality.
The modes of analysis offered by the tools developed by Nattiez and Molino [[#molino][molino]] all representing
the same work of art. The analysis at the different levels does not
necessarily have to lead to the same conclusions or results but,
according to Nattiez, it may help us to understand \emph{all} aspects
of the musical work:

 the structuring of the material, and the esthesic which is the 
From a musical point of view it is clear that 

Perhaps there is always an expectation of a meaningful response in any kind of communication, musical or otherwise. 

The encounter with another human may range from a willngness to command as well as to serve our relationship to technology is often less ambiguous. Traditionally speaking, if it does not allow itself to be controlled it is not because the relationship has failed, it is because the technology is faulty. If I press the button to turn on the light in a dark room, but the room remains dark it is fair to assume that there is something wrong with the technology. This distinction, however, may need to be reevaluated in the light of the broad range of applications that are gathered under the artificial intelligence. This space of uncertainty is what GI attempts to explore. 

There is an anticipation for structure that is 

In music this is shown This expectation is  strong that there is a tendency 

from one's co-player is 

** Morten Lab #5, part 2, 21:40

If I do this, what will the machine construct of it... I'm attracted to seeing what it does to the material if I keep it really [structured], like I did.

An aspect that I don´t like about improvisation
groups in the human domain is that the aesthetics or rules in a group, or of a
certain style or genre in improvisation are overpowering or blocking the
potential for development. [[#Qvenild2018][Qvenild2018]]

** Sidsel Lab #5, part 2, 22:10

With great clarity, one of the members of the group makes a comment that quite specifically points to the manifest difficulty of building an improvising machine:
#+begin_quote
If you play with humans you have an idea of their aesthetics so that part is kind of integrated, on beforehand. So maybe there is always some kind of quick preparation, or plan in order to feed into the total?
#+end_quote
Clearly, to play with someone is to encounter the other. Regardless if this is a musician known to oneself prior to this instance or not, a wide range of information is immediately gathered or created, merely through the encounter. The body and posture, the way the instrument is held, the facial expression, and many other things contribute to what one may expect this musician to play. Obviously, one may be utterly wrong in ones assumptions, but one is nevertheless likely to have some kind of groundwork or underpinning, even before engaging in play. It is obviously impossible, and possibly not even very interesting, to know exactly how much one is influenced on beforehand by the pressence of co-musicians. It is equally difficult to determine to what extent one is able to adjust ones presuppositions once the playing has begun. Based on my own experience I believ it fair to say that the empirical evidence of a musical encounter has a tendency to overwrite the preconception, but even so it is difficult to ignore the impact of the first meeting. In this case it is enough to take the experience witnessed by Sidsel as a point of departure. 

Sidsel's question is not only concerned with aesthetics but has also a bearing on the ethics of improvisation. 

She is pointing to the knowing of the other as other and perhaps it is possible to deduce from this that the playing they then engage in is a negotiation between the aesthetics of the other and those of oneself. This is made possible through the encounter and the willingsness to play music together, and, one may suspect, that this music should have qualities that both musicians appreciate. The ethics of this situation, the willingness to do good and to play good music respectful of the other, frames the aesthetic negotiation that one engages in through improvisation. Evidently, I am superimposing the idea of the willingness to be respectful, but the situation is not radically different if the musical encounter instead is framed by resistence and obstruction. The decisive aspect of understanding the other's aesthetics prior to playing is still in play.



Now, if the co-musicians lacks a body and has no extension in the physical realm and there is no sensation of the other,[fn:9] the situation is radically different. Your co-musician is a blank slate, not even non-existant, but with negative extension. The machine is a void until you start playing and when you do, it is relatively difficult to anticipate the output. In the case with GI however we had rehearsed and the output of the machine is, after all, relatively well structured so the situation, I would say, is not impossible. But comparing it to a real musician makes little sense because music in general, and improvisation specifically, commonly relies on a myriad of other parameters in addition to the sonic trace.

The important aspect here is practice. Machines that perform tasks similar to those usually performed by humans have a great disadvantage in their lack of presence. However, it appears that we are quick to adopt. There are a number of tasks and activities that belong to the social realm that we now carry out virtually. Social media for example. Although the discussion concerning the precariousness of committing your social life to social media pops up every so often[fn:10] we appear to be able to quite quickly adopt and willing to substitute a physical meeting with a chat on a media channel. But because it is possible, and maybe even desireable in one context does not mean that it is so in another. This is where the context of GI becomes even more interesting.

One of the topics I explored in my 2008 thesis [[#frisk08phd][frisk08phd]] was the error of logical reduction and the concept of interaction-as-control. To summarize, my argument was that interactivity as a concept had been hijacked by the huge field of interface design and the interactive experience deduced to the activity of control rather than mutual exchange. Of course, this makes sense, when in the car, for example, one rarely want exchange with the windscreen wipers or the car horn. We want them to start when I press the button, or honk, when I press the stearing wheel. But with the abundance of interactive technology combined with the statistical collection of data interactive as an activity looses its meaning. My interest was and still is related to the core ambition of GI, namely to explore the possible relations with technology in music and in that ambition I felt the need to restructure the meaning of interactive. 

Now, however, a little over ten years later, the reductive notion of interaction-as-control has been paired with the great possibilities of artificial intelligence. On one level though, as impressive as a song recognizing algorithm may be, most apps are still domain specific and the incredible performance of the context sensibility of human perception is not yet acessible to AI. Context sensibility is another way to describe the ability to sense the other's aestetical values before engaging in an improvisation.

[fn:9] When recording in a studio it is not uncommon that some of the other musicians are hidden from ones view but in these cases the mere sensation and nearness of the other is commonly enough. I can reconstruct my comusicians virtually.

[fn:10] See for example [[#lanier2018][lanier2018]] and also [[#lanier96][lanier96]].

** Ivar Lab #5, part 2, 23:55

We often question if we actually play together with this, if it's fair to call it... that we play together or if we play next to each other. But sometimes I actually feel like there is some kind of interplay.

** Lab #5, morning

20:00 The search for the perfect companion has failed. Why not instead look at it as a compositional frame. Instead of expecting it to respond to the way I play, I respond to a given form.

05'00'' (Morten)  Haunted territory in this project. Blindspot.
9'20'' (Andrea) Behind behing rude is a moral aspect, one that puts limitations on what rudeness can be. But there is also an aesthetic aspect of it. Expanding the horizon of what is possible and what one may allow one self? "who says playing a million notes when the other can only play two is rude? MAybe on another planet this is the most normal thing you can do?" 10:35 "Its more interesting to question what I feel is rude also towards humans."

Comment: There is a dynamic between what I allow myself to do and what I can actually do and this space needs to be approached

24:30 (andrea) want to be challenged, instead we adapt. Ah it works like this, then I do that.

26:25 (morten) I havew seen it as a compositional frame for a long time. 
27:30 (morten) The project is much more about us as improvisers needing different compositional frameworks. That could change me as an improviser whitout denying who I am. I still thgink we can be surprised.

** WS#5 Collective piece

https://vimeo.com/showcase/5025613/video/321213512

I perform with the system as I would with any other human improviser I would generally expect 

The search for the perfect companion has failed. Why not instead look at it as a compositional frame. Instead of expecting it to respond to the way I play, I respond to a given form.

Andrea

"The feeling that emerges from such a musical arrangement, a feeling of ‘hearing and being heard’, is, for me, one of the exceptional qualities of this direction in music." [[#Neumann2018][Neumann2018]]

"Another interest of mine lies in the physicality/performativity /theatricality of performing music – how the body is involved in playing music, what kind of physical posture you chose to play your instruments" [[#Neumann2018][Neumann2018]]

"My plan is to encounter my three colleagues by playing with their archives through Kim-Autos filter.  For sure this is an encounter around the corner." [[#Neumann2018][Neumann2018]]

"Two major problems still remain: how to start and how to end?" [[#grydeland2018b][grydeland2018b]]

"Also most of the usual inbred terms, perceptions and ways of understanding improvised interplay are non-valid in this duo: shared listening, communication, democracy, shared agency and responsibility for the outcome, instant mutual learning and tacit understanding of what is at hand as we play, our roles and functions, our frameworks, joint expectations, shared sense of form/structure, etc.  I need to reevaluate all of the above in this duo." [[#endresen2018][endresen2018]]

"how can I, ethically, relate to and play with KA with the same kind of trust
and respect as when I play with humans?" [[#endresen2018][endresen2018]]

Morten Qvenild 

"My playing here is very rude, I am being empathic towards KimAuto here, thats for sure. I am playing with a machine, and this rudeness is possible without hurting someone. I think this assertiveness is a good musical option sometimes. The non-listening and the not taking care of the other." [[#Qvenild2019][Qvenild2019]]

In improvisational interplay between humans, we tend to develop an expression
showing each other our likes and dislikes through music or through
conversations about music. An aspect that I don´t like about improvisation
groups in the human domain is that the aesthetics or rules in a group, or of a
certain style or genre in improvisation are overpowering or blocking the
potential for development. [[#Qvenild2018][Qvenild2018]]

Technology totally lacks the aesthetic preferences, it will not
judge and it will never discuss good or bad. The machine’s total lack of
judging music in a pre-conceived aesthetic framework is very refreshing and
inspirational to me. [[#Qvenild2018][Qvenild2018]]

To be rude. (See [[#Sandell][Sandell]]) 

Not sure if it helps to antropomorphize. Altering what it means to be empathetic. What is the machine in and of itself. The machine is so limited. 

05'00'' (Morten)  Haunted territory in this project. Blindspot.
9'20'' (Andrea) Behind behing rude is a moral aspect, one that puts limitations on what rudeness can be. But there is also an aesthetic aspect of it. Expanding the horizon of what is possible and what one may allow one self? "who says playing a million notes when the other can only play two is rude? MAybe on another planet this is the most normal thing you can do?" 10:35 "Its more interesting to question what I feel is rude also towards humans."

Comment: There is a dynamic between what I allow myself to do and what I can actually do and this space needs to be approached

24:30 (andrea) want to be challenged, instead we adapt. Ah it works like this, then I do that.

26:25 (morten) I havew seen it as a compositional frame for a long time. 
27:30 (morten) The project is much more about us as improvisers needing different compositional frameworks. That could change me as an improviser whitout denying who I am. I still thgink we can be surprised.

* Notes

Francois Pachet: https://www.francoispachet.fr/publications/ https://www.youtube.com/watch?v=ynPWOMzossI 


Chadabe in [[#10.2307/3680146][10.2307/3680146]]: "an intelligent musical instrument is a device that makes musical decisions as it produces sounds and responds to a performers controls."

The musicans' expectations commonly antoboth contribute to establishing the machine musician  

Following this discussion questions concerning machine ethics come to the forefront and are further explored. 

It is possible to imagine a musical Turing test for an improvising machine, one in which a musician and a machine are located in each their own room and merely hear each other. When they engage in an improvisation the test is successful if the musician cannot determine if the counterpart is human or machine.

There are a number of aspects to this test, the first of which is a problem with any Turing test, but is made more urgent in the context of music. An exchange of information between two humans has an embodied dimension to it which is disregarded in a Turing test. This embodiement 

and this was only relatively recently discovered.

It is still possible to play at a distance, especially if the relationship between musicians is already established, but making a meaningful assumption about a co-musician one has never met and do not encounter in the moment of playing will be very difficult. (The more rigid the system and the theory of the music the easier it gets.)

embodied music cognition, Leman [[#Leman2015][Leman2015]]
performativity Bolt [[#Bolt2009][Bolt2009]]
CMJ, 1989, vol 13:3-4 [[#Loy1989a][Loy1989a]],[[#Loy1989b][Loy1989b]]

In https://www.posthumanai.com/#/workshop-1/
One of the main challenges in Artificial Intelligence lies in the current approach to understanding information within AI systems- this understanding limits how we design with the social, cultural, emotional and multi-sensory information in intelligent systems. This type of information does not easily lend itself to quantification and the attempts to do so result in the numerical quantification of experience, which is best understood embodied. 

About the Wekinator [[#Fiebrink2011][Fiebrink2011]]
It's as if the tool becomes an aesthetic in and of itself.

Also using a Disklavier a group of researchers conducted an Similar to an experiment with an improvisor in Italy [[#Roda2015][Roda2015]]

* Calls
** OS                                                                :ATTACH:
[[mu4e:msgid:5d060b02-61c6-2de6-b2be-a41aa26f06f4@kth.se][CfP for a special issue of Organised Sound]]

*** Computation in the sonic arts

There are many ways to generate and organise the sounds of a composition. Notwithstanding the early precedents in musical dice games and the rules for contrapuntal voice leading, the use of formal procedures to make musical artifacts without direct human intervention became practicably realisable with the availability of digital computers. This occurred in the second half of the twentieth century at the same time as artificial intelligence researchers were dreaming of a model of the human personage in which bodies and minds were more like machines than self-generating organisms. Some composers took the opportunity to develop algorithmic procedures to model works of the past, others to explore the representation of mathematically defined, natural and abstract processes that have no immediate musical connection to music such as set and group theory, probability distributions, Markovian stochastics, self-similarity, iterated function systems, adaptive networks and other combinatorial techniques. More recently, attention has also turned to the representation of messy collected data, scraped from the internet, or gathered by monitoring human, natural, environmental and other activities.

Early collaborations with computational systems were met with some hostility by the musical establishment. Arguments ranged from whether or not, in replacing parts of the creative process with an automated system, we were dehumanising the resultant artifact. Were we cheating by letting the tools do the work? Was is it even possible to produce tools which can adequately challenge the intensely human “creative” process? Did reason alone have any place in musical composition in a domain of human activity which should be driven by feelings, intuition, and other non-algorithmic considerations?

This issue of Organised Sound seeks articles which go beyond the description of how specific compositional procedures are used in individual compositions in order to address the social and musicological dimensions of computation, specifically focusing on the sonic arts. 

Suggested themes include but are not restricted to:

- What styles of computational sonic arts exist today? How are they defined?

- What is social context in which they exist?

- Do or should listeners listen differently to music in which computers are involved in the creative decision-making?

- In what ways are the computers involve being creative or imitating creative processes? Is there a difference?

- Both in creation and performance, how does such work fulfill composer and listener needs for artifact formation and artistic communication?

- What is the role of the ego when composing computationally?

- In socio-cultural environments in which AI research is currently faced with difficult conceptual and definitional issues such as embodiment, has this affected how computational creativity is considered?

- In performances where computational algorithms are freely used in improvisation, what does it mean for a composition to be well formed? Does it matter?

- Is there a role for computational processes in music education?

- Are the compositional situations in which you would not consider using procedural approaches? Why?

* Aesthetics, interaction and machine improvisation
** KTH Submission jan 2020
*** Abstract

Departing from the artistic research project Goodbye Intuition (GI) hosted by the Norwegian Academy of Music in Oslo, this presentation discusses the aesthetics of improvising with machines. Playing with a system such as the one used by GI, with limited intelligence and no real cognitive skills will obviously reveal the weaknesseses of the system, but it will also convey part of the preconditions and aesthetic frameworks that the human improviser brings to the table. If we want the autonomous system to have the same kind of freedom we commonly value in human players' improvisational practice, are we prepared to accept that it may develop in a direction that departs from our original aesthetical ambitions? The analyses presented here are based on some of the documented interplay between the musicians in the group in workshops and laboratories. The question of what constitutes an ethical relationship in this kind of improvisation is briefly discussed. The aspect of the macines desembodied relation to the music emerges as a central obstacle in the development of musical improvisation with machines.

** ArtSearch jan 2020
*** Challenging machine aesthetics and the musical automation
**** Abstract

Departing from the artistic research project Goodbye Intuition (GI) hosted by the Norwegian Academy of Music in Oslo, this presentation discusses the aesthetics of improvising with machines. Playing with a system such as the one used by GI, with limited intelligence and no real cognitive skills will obviously reveal the weaknesseses of the system, but it will also convey part of the preconditions and aesthetic frameworks that the human improviser brings to the table. If we want the autonomous system to have the same kind of freedom we commonly value in human players' improvisational practice, are we prepared to accept that it may develop in a direction that departs from our original aesthetical ambitions? The analyses presented here are based on some of the documented interplay between the musicians in the group in workshops and laboratories. The question of what constitutes an ethical relationship in this kind of improvisation is briefly discussed. The aspect of the macines desembodied relation to the music emerges as a central obstacle in the development of musical improvisation with machines.

** Tallinn 2020
*** Aesthetics of a musical automaton
**** Abstract

Departing from the artistic research project Goodbye Intuition (GI) hosted by the Norwegian Academy of Music in Oslo, this presentation discusses the aesthetics of improvising with machines. Playing with a system such as the one used by GI, with limited intelligence and no real cognitive skills will obviously reveal the weaknesseses of the system, but it will also convey part of the preconditions and aesthetic frameworks that the human improviser brings to the table. If we want the autonomous system to have the same kind of freedom we commonly value in human players' improvisational practice, are we prepared to accept that it may develop in a direction that departs from our original aesthetical ambitions? The analyses presented here are based on some of the documented interplay between the musicians in the group in workshops and laboratories. The question of what constitutes an ethical relationship in this kind of improvisation is briefly discussed. The aspect of the macines desembodied relation to the music emerges as a central obstacle in the development of musical improvisation with machines.

** Info

Henrik Frisk, Professor of music, Royal College of Music, Stockholm \\
Väderkvarnsgatan 38C, 753 29 Uppsala, Sweden \\
henrik.frisk@kmh.se

** Abstract

Departing from the artistic research project Goodbye Intuition (GI) hosted by the Norwegian Academy of Music in Oslo, this paper discusses the aesthetics of improvising with machines. Playing with a system such as the one described in this paper, with limited intelligence and no real cognitive skills will obviously reveal the weaknesses of the system, but it will also convey part of the preconditions and aesthetic frameworks that the human improviser brings to the table. If we want the autonomous system to have the same kind of freedom we commonly value in human players' improvisational practice, are we prepared to accept that it may develop in a direction that departs from our original aesthetical ambitions? The analyses is based on some of the documented interplay between the musicians in the group in workshops and laboratories. The question of what constitutes an ethical relationship in this kind of improvisation is briefly discussed. The aspect of embodiment emerges as a central obstacle in the development of musical improvisation with machines.

** Introduction

The artistic research project /Goodbye Intuition/ (GI), hosted by the Norwegian Academy of Music in Oslo, is a platform to explore the meaning of intuition, musical structure and aesthetics by means of playing with a newly developed improvisation machine, nick-named Kim Auto, or KA in the following [[#grydeland2018][grydeland2018]]. By introducing this fifth member GI attempts to challenge the roles and aesthetical values of the four musicians in the group and explore what kinds of music may emerge from the experiments. The core method is artistic and the members engage in improvisations with the new machine member followed by discussions and reflections, sometimes carried out in the context of open laboratories. The labs are open and the audience is invited to listen and participate in the discussions. 

Whether KA is an instrument, a performer, a composer or a composition is difficult to define, but the meaning and significance of these different modalities of musical knowledge and communication has some impact on the relations that are possible within GI. That there is a dynamic variability concerning the possible roles of the computer in musical applications in interactive music is confirmed by composer Cort Lippe who states that:
#+begin_quote
a composer can assign a variety of roles to a computer in an interactive music
environment. The computer can be given the role of instrument, performer, conductor, and/or
composer. These roles can exist simultaneously and/or change continually, and it is not necessary
to conceive of this continuum horizontally. [[#Lippe2002][Lippe2002]]
#+end_quote

The basic outline of KA is that it collects material from whoever is playing with it and constructs an archive of material that it uses when it plays. It has four different personalities that may be configured and that defines how it responds to input. These are used to shape its output based on musical concepts such as high/low pitch, and structural aspects such as dense or sparse. By interpolating between the different personalities the responsiveness of the system and its output may be varied. 

The research questions in GI revolve around the notion of the improviser's identity in the music and whether the presence of a creative machine would alter the way they listen or play. Also included in the inquiry is the more general aesthetic question of what kind of music may emerge from these experiments. The question of whether KA is a /good/ co-player in a musical, or artistic sense is primarily investigated from the point of view of the practice of playing with it. Improvising with KA brings forward questions relating to both the point of view of what is expected from it, and what is expected from oneself come to the fore. GI is not a music technology project and does not primarily claim to be innovative on the level of the development of KA,[fn:11] nor is this paper a discussion of the underlying technology, except very briefly.

As was mentioned above, the project is set up around a series of internal workshops in which people external to the group are invited to discuss the processes. These include British musician and writer David Toop and myself, and one one occasion the workshop was led by American director and writer Annie Dorsen. We have been part of the discussions and to some extent we will also contribute artistically. Worth noting is the fact that the methodology of the project does not list concerts as the main form for output. Instead the work is presented in a laboratory format with the purpose to engage the audience in a discussion concerning the general goal of the project.

The focus for this paper is to discuss some of the preliminary results from my study on the interaction in /Goodbye Intuition/ and the machine improviser KA with the attempt to identify the aspects of the interplay that triggered discussions concerning aesthetical judgments and the sensation of interactivity. Analyzing some of the discussions in a few of the laboratories and workshops performed in the project, the music that came out of it, as well as the responses from the participating musicians, sheds some light on the way that value judgements are developed, and sometimes questioned in the group. There is a particular interpretative space that is opened up through the experience of playing with the seemingly responsive[fn:8] machine co-player that is examined within the project and also in this paper. [[#Bergson1912][Bergson1912]]

To improvise with a computer  running an adaptive software for musical interaction raises questions that have relevance to both the designer of the improvising system, and the musicians playing with it. In these cases it is difficult to avoid some level of anthropomorphism among the users [[#Blackwell2004][Blackwell2004]],[[#Young2009][Young2009]], but it is also clear that this effect contributes to the willingness to engage with the system [[#Nowak2003][Nowak2003]], and in some cases the ability to learn from it [[#Schneider2018][Schneider2018]]. In Gi the very fact that the machine is given a personal name points to the willingness to attribute some aspect of human traits to it. While this contributes to the sensation that the machine is intelligent in a human sense (which it is not), it also puts a limitation to what is possible from a system point of view. If it proves to be possible to create a machine system that can improvise interactively and creatively, why restraint the machine to behave like a human? If not, by what standard do we allow ourselves to limit its freedom? Although speculative and abstract in nature, this inquiry leads to a number of questions concerning, for example, machine ethics that I hope to continue to pursue in the near future, but which may also be seen as a backdrop for the present study.

[fn:11] It is NOTAM in Oslo that does the development of KA rather than the members of the group.

** Method and background

Since I have been an active part in many of the workshops and laboratories performed by the group Goodbye Intuition since the project was initiated in 2017, I am obviously involved in, and influenced by, any findings and discussions. In the workshop in Stockholm in February 2019 I also played with the group, but in general my role has been that of an external partner, or critical friend. 

Using a the qualitative method of purposeful sampling I have selected a few important points during the workshop in Stockholm, February 17-19, that will form the foundation for the discussion in this paper. Due to the nature of the process in the project's workshops and laboratories, in which a shared experience, and to some extent shared knowledge[fn:12] has developed, this method appeared to be the most appropriate. As described by [[#Patton2002][Patton2002]], purposeful sampling, or judgment sampling, "focuses on selecting information-rich cases whose study will illuminate the questions under study". Using my first hand experience it was relatively easy to choose the relevant parts to include in this study. In principle parts that were considered particularly unsuccessful and those that were perceived as successful were picked out.

In general the workshop in Stockholm in 2019 was an important event in the project for many reasons. Essential topics were aired and discussed, the software running KA had been improved and its modes of interaction had improved, and the laboratory format had matured.[fn:20] There was also a quartet performance with KA that came out both artistically and aesthetically convincing. With the purpose to engage in a discussion on the impact of technology in the form of artificial musicians on questions concerning musical ethics and improvisation aesthetics it seemed natural to pick out a few of the many information-rich contributions from this event

That the field of music is also affected by the huge interest in artificial intelligence is not surprising. The practice of improvisation in music is sometimes seen as a model form for organisation, or, as put by [[#Cook2017][Cook2017]], "[t]here is a long standing tradition of seeing jazz, particularly free and avantgarde jazz, as the expression of an ideal society". Given such an assumption, musical improvisation may appear to be the perfect case for evaluating the functionality of humanoid. Would it prove to be possible to write a software that can improvise with musicians in a manner that is indistinguishable from that of a human player, not only is this a significant engineering task, it may be assumed that this software can also function in other social contexts. Music as a test bed for intelligent technology. There are a number of criteria that would need to be met and the computer system's ability to respond to input is a challenge both in deciding what constitutes valid input, and what is a useful response.

One of the ways in which it has been theorized that a systems ability to think, or its responsiveness to human interaction, may be measured is the Turing test [[#Turing1950][Turing1950]]. There has been many ideas about various designs of a Turing test for music, also those that evaluate systems that improvise. In 1988 the topic was discussed in the Computer Music Journal [[#spiegel1988][spiegel1988]]. The piano competition Rencon, a "forum for presenting and discussing the latest research in automatic performance rendering" [[#Hiraga2004][Hiraga2004]] introduced a Turing test for evaluating methods for performance expression on the Disklavier in 2004. In [[#Roda2015][Roda2015]], likewise using the Disklavier, performed a Turing test in the context of a live performance. A software developed by [[#Pachet2003][Pachet2003]] and his team, The Continuator [[#Pachet2003][Pachet2003]],[[#Pachet2003b][Pachet2003b]], is an interactive system and a musical imitator that has been tested with a Turing test design [[#pachet2012][pachet2012]]. However, as was noted by Laurie Spiegel in a comment to the request for a musical Turing test in Computer Music Journal, one may question "[w]hat purpose would be satisfied by creating qualitative or quantitative metrics for musical intelligence, given the lack of successful similar criteria for natural musical intelligence, musicality, or even music per se" [[#spiegel1988][spiegel1988]]. She thereby puts the focus on the real issue concerning even a basic notion of artificial musical intelligence. 

The question of the nature of an instrument or system such as KA may appear to be a matter of primarily theoretical impact. As will be demonstrated in the next section, however, it is nevertheless of some importance. There has been no shortage of attempts to aim at a working metaphor for the emerging field of intelligent instruments. As noted by [[#Bowers2005][Bowers2005]] "[s]ince 2001 the NIME series of conferences has seen the presentation of a wealth of interface and instrument design ideas" [[#Bowers2005][Bowers2005]]. Before that the notion of the hyperinstrument was introduced by Tod Machover [[#Macover1989][Macover1989]].
In the previous section Cort Lippe pointed to how the interactive system can take on any number of roles in a musical context, and in her PhD thesis [[#Fiebrink2011][Fiebrink2011]] suggests that "when the computer takes the role of an instrument within an interactive computer music context, the process of designing how a performer will use the computer to play sound can be understood as both composition and instrument building" (p. 17). Fiebrink refers to the work by [[#Schnell2002][Schnell2002]] who used the term "composed instruments" [[#Schnell2002][Schnell2002]] to define the practice of designing computer systems for music. While we have often continued to label computer systems designed for music as /instruments/, in some cases these systems are as much a part of the score as the score is (if one at all exists). This has had an influence on the way that new interfaces, and composed instruments, has had on the practice of musicians and composers alike, as well as on the ontology of the musical work [[#frisk-ost06-2][frisk-ost06-2]],[[#frisk-ost06][frisk-ost06]]. With a terminology in part borrowed from game design composer and musician Per-Anders [[#Nilsson2011][Nilsson2011]] discusses software instrument building as part of either "design time" or "play time": "Design time is outside time activity, concerned with conception, representation, and articulation of ideas and knowledge, whereas play time deals with embodied knowledge, bodily activity, and interaction in real-time" [[#Nilsson2011][Nilsson2011]].

As was mentioned in the introduction, in GI there is a strong aspect of anthropomorphism that becomes obvious in a number of situations. KA is often talked about as "trying to do" something, being in a particular state of mind, or consciously going in a particular direction. On the one hand this is obviously false, KA does not have a consciousness in the was the is implied by this way of talking. It mainly listens to a few parameters of its input and records sound (a more detailed description is found below). On the other hand it says something about its output that leads us to anthropomorphise. This can be seen as a consequence of the close relationship between traditional musical practice and interactive music practices, as is pointed to by [[#Schnell2002][Schnell2002]]:

#+begin_quote
Interpreting the attitude of the performer of a composed instrument with the help of categories from the traditional way music is created leads to various metaphors such as that of playing a musical instrument, conducting an orchestra, playing together (ensemble) with a machine, acting as a one-man band.  [[#Schnell2002][Schnell2002]]
#+end_quote

The use of technology in art practices can have several different objectives. From a general standpoint one may argue that art should engage in available technologies for the simple reason that this contributes to our understanding of its social and cultural impact. Though this general notion is sometimes contested, most famously by Heidegger who instead saw the opposite, that the technology frames the human capacity  [[#heidegger93][heidegger93]],[fn:13] there are good reasons to evaluate uses of technology through artistic practices. From the point of view of innovation it has been seen in the past that artists' use of technology push the boundaries for what is possible [[#harris1999][harris1999]]. Although this has arguably been true, the resources that the multinational technology and media industry now are in control of makes it increasingly difficult for an independent artist, or even a university, to produce artefacts that may compete with the AR budgets of these companies, although the artistic qualities in and of themselves may be uncontested. 

[fn:12] It is only to a certain degree shared as the various kinds of experience (musical, interactional, intellectual, experiential) is distributed according to the various roles that we have in the project. Only to the extent to which we have had the chance to explore the knowledge acquired is it shared.

[fn:20] A documentation of the laboratory in Stockholm can be seen here: https://www.researchcatalogue.net/view/411228/431482

[fn:13] Aden Evens has written an interesting commentary on it in the digital age [[#evens05][evens05]].

** Analysis and results
*** Composition or improvisation

One of the topics raised early on in the workshop in Stockholm was the notion of KA as a composition rather than a co-improviser, or an instrument. This may at first seem odd, after all, GI is an improvisation group, what purpose serves the notion of a composition in this context? Despite the conceptual contradiction, this is related to the notion of composed instruments, as was discussed above: Some of the performance instructions, the score, is encoded in the system. Or, more plainly: "the /work/ is replaced by the /interface/" [[#frisk08phd][frisk08phd]]. As a composition it makes sense that it allows a certain type of music, or response, but not other kinds. 

It should be noted that constructing a system that plays back a preconceived composition is obviously a more manageable task than the attempt to create a system that is able to interact to unforeseen musical events. This insight may have had something to do with why the topic of KA as a compositional frame came up. However, there is a more practical and pragmatic aspect to this as well. The goal of the project is to challenge the roles and aesthetic values of the four musicians in the group, and reflect on the topics of /listening/ and /playing/. But if the responses from the system are not responsive enough, so to speak, if the co-player KA is not /listening/ attentively enough, then it becomes difficult to make meaningful commentaries about either the system, or of ones own strategies interacting with the system (even though, as will be shown in the next section, not listening may actually be a perfectly valid strategy). If the perfect playing companion is not available within KA, perhaps it is  possible to instead look at it as a compositional frame that affords certain musical behaviour? 

To some extent KA is already a compositional frame as can be judged from its design. A given archive with a specific setting renders a music that is recognizable from performance to performance. Assuming that the musician and the system share some notion of what is "good" music and what is "less good" music it would furthermore be reasonable to expect that it makes a judgment on what kind of material it should archive and what material to avoid. In the version of the software that we played with in the laboratory on February 19, 2019, it was however obvious that it did not do this when I played with it. Another interpretation is that KA has a set of aesthetic values that are different from mine. I was able to improvise with it and feel relatively good about the interaction, but the way it collects material makes it possible for it to pick up on a phrase that I considered a mistake, or badly shaped. Such material then quickly defines the character of the music and becomes an obstacle that is difficult to come by.[fn:15]

One of the members of the group comments on the same fact, saying that the system works quite well as long as one goes along with it. If you resist it, however, and oppose to its playing or the material it uses, it is very slow to response.[fn:22] In effect, what is emerging is a kind of composition, or a compositional frame. As long as one stays within the boundaries of the composition and play correctly, the musical result can be convincing. Perhaps this is more of a conceptual change, a difference in attitude towards the task of playing with a  machine improviser, rather than a practical, musical change. The performance following the discussion of KA as a compositional framework rather than an improviser was in some ways quite convincing. One of the performers remarked that it felt like the first time they were able to construct musical structures /with/ the machine without it being a struggle.

[fn:15] A discussion on this may be heard at 20'00'' [[#grydeland2019-1][grydeland2019-1]]

[fn:22] This is discussed in [[#grydeland2019-1][grydeland2019-1]] at 15'00''.

*** To not listen

One matter that has come up om multiple occasions is the idea of musical rudeness. Both in the sense that KA should be rude but also that the improviser may be rude to KA. There is no doubt that this freedom to shut another musician off, play louder than everyone else, or, in the words of improviser Sten Sandell, to be allowed to change direction at any time  [[#Sandell2013][Sandell2013]], has been an important aspect of some strands of free improvised music and jazz. What triggered this discussion was a reflection written by Morten Qvenild: 

#+begin_quote
My playing here is very rude, I am being empathic towards KimAuto here, thats for sure. I am playing with a machine, and this rudeness is possible without hurting someone. I think this assertiveness is a good musical option sometimes. The non-listening and the not taking care of the other. [[#qvenild2019][qvenild2019]]
#+end_quote

To be rude, or choose to not listen to the other, may appear contrary to the notion of music as an activity that creates and maintains social networks [[#monson98][monson98]], but may here be seen as a possibility to engage in a musical ethics. While it is true that listening and adopting are essential in improvisation as well as other practices,[fn:16] it is impossible to say what is generally right in improvisation. Marcel Cobussen writes that:

#+begin_quote
Reacting to the unfolding of the music, the musician and his instrument enter into a relation with already produced sounds, concretised musical ideas, present frames. All these cases contain an act of thinking during the act of doing. To listen to oneself and the other(s), to listen to the proceeding and developments of the music, to listen to the noises that direct the music to unknown areas.[fn:21] [[#Cobussen2005][Cobussen2005]]
#+end_quote

Interestingly enough, this could work as a characterization of KA whose archives may actually go beyond sounds recorded and develop into a storage of /thinking/ through the act of doing. But where does the rudeness come in? Well, in another text by Cobussen Keith Rowe's concept of non-listening is discussed in a way that appears to be approaching what Qvenild calls rude. Cobussen asks "how the concept of non-listening, as suggested by improvising guitar player Keith Rowe, can undermine, or, conversely, deepen an aural ethics" [[#cobussen2016][cobussen2016]]. And further:

#+begin_quote
[N]on-listening is meant to prevent any form of interaction. It is meant to avoid relapsing into a musical performance which is built on previous explorations and discoveries; it is meant to avoid too many conventions, too many tricks that have already proven their success, it is meant to stay open to another otherness. Rowe opens an ethical space of creativity and change through resistance. His attitudes makes space for musical interactions that demand a response-ability that is not already prescribed, a praxis of risk for which there can be no rules, no codes, no principles and no guarantees. [[#cobussen2016][cobussen2016]]
#+end_quote

The act of not listening is a tool for the improviser, and while a similar activity could be problematic in social interaction, in improvisation it instead appears to contribute to the openness. Non-listening introduces resistance in the interplay whereby the ethical capacity is increased rather than hindered. On member of the group commented on how in improvisation there is sometimes a regulatory force in the form of convention or aesthetics, and that this force may block the potential for development in the group. Another way to put it is to say that the capacity for being rude and break with the convention is somehow interrupted. Playing with a machine is deliberating according to the same testimony since the machine does not care, so to speak. Although it is not always obvious what may constitute a 'correct' intervention, this example points to the importance of allowing rudeness in improvisation. In some cases it may simply be the most ethical and respectful way forward.

In music it is possible, and in principle correct, that the aesthetical domain frames the ethical, but in reality it is clearly more complex. For now, based on the theory presented and the experience and discussions in GI, I believe it is possible to state that what constitutes ethical behaviour in musical improvisation and artistic practice extends what is generally seen as acceptable, or good, in social interaction, and that there is an interrelation between ethics and aesthetics. 

[fn:16] For an exploration of the philosophical impact of listening, see [[#nancy2007][nancy2007]].

[fn:21] For a discussion on the Self in improvisation, see [[#frisk12-improv][frisk12-improv]]

** Discussion

Apart from it being an interesting frame for artistic work, my interest in using digital technology in my artistic practice also departs from the belief that art practices in general offer a context in which experimentation and play is possible. That is, the aesthetics of the practice offers a set of value judgments that an engineering context may not provide, nor a traditional artistic practice. This, however, is not a property of the field of digital art but rather a function of it. In other words, only if the artist is consciously working for it does this experimental opportunity present itself. Furthermore, the framework of artistic practice does not by itself guarantee sound values and reasonable ethics, it is merely a /possibility/, a potential, albeit an important one. Somewhat besides the point, but worth mentioning is that this does not mean that the art, nor the artist, is always ethically just, or morally defensible. The emphasis here is on the practice and the way the practice organises itself when the value system is primarily aesthetical.

This, however, introduces a number of difficulties, the most important for the current discussion is the impact that this may have on the development of the  technological systems. Although writing code may be considered an art form in itself in practices such as live coding, the role that the technology plays in works that are called digital art is not always as obvious. An attempt at a definition is made by [[#lopes2009][lopes2009]] writing that "a item is a work of digital art just in case (1) it's art (2) made by computer or (3) made for display by computer (4) in a common digital code" [[#lopes2009][lopes2009]]. Sol LeWitt's famous essay on conceptual art predates the digital revolution, written long before digital technology became readily available in the way it is now, states that: "The idea becomes a machine that makes the art. This kind of art is not theoretical or illustrative of theories; it is intuitive, it is involved with all types of mental processes and it is purposeless." [[#Lewitt1967][Lewitt1967]] 

The question that remains unanswered is what the actual code of the machine improviser constitutes a group such as GI. It was discussed above that the ethics of improvisation is negotiated through the aesthetics of the context, but what is it actually that guides the aesthetics of KA? Judging from the discussions we have had in the workshops and laboratories, it is clear there has been, and still is, a serious attitude towards KA with a respect for its capabilities and an understanding for its flaws. It is accepted and allowed to not listen, or to enter into a musical context and change the course of action in what may seem to be a disrespectful manner, not through negotiation but by introducing change strong enough that it makes a difference. In other words, though there was a discussion about the way KA introduced music that not all members appreciated, it allowed for a very different kind of musical relationship. The group accepts KA as a fifth member as a co-musician and in that sense it is a /machine that makes the art/, but what is the identity of this machine, and who is in control of it? Is it the code, that machine running it, is the the sounds it produces or is it maybe just an extension of the programmer that created it? 

One may imagine that within not too long there are tools, like KA, but more advanced, that exhibits some notion of what we can call musical intelligence. Are we in that situation prepared to allow the machine to develop its own aesthetics, as we would with a human co-player? It is not difficult to imagine that such a machine can develop extremely fast, much faster than a human player. In this case, perhaps the machine eventually grows to be uninterested, not only in the music that humans play, but even loses interest in playing with humans at all. If the machine is still programmable by us we could of course put some limitations on the way its knowledge about music develops, thus avoiding this scenario. This kind of limitation could also be part of the design of the system from the beginning, which may appear to be a sensible thing to do, but it would nevertheless be to narrow its freedom in a way that is not often done for human musicians. If these systems in fact are intelligent in some manner, what are the consequences if we introduce constraints on the machines potential for development? Introducing a structural divide between one class of performers (humans) and another (machines) may have an effect on the way also our musical and aesthetical values develop. There are (at least) two aspects of this reasoning. 

First, the machine's capacity to learn and develop is obviously not only dependent on its input. Until machines are capable of creating machines without the interference of humans, they depend on designers and programmers that create the systems. These also have values and, as has been shown through studies such as [[#snow2018][snow2018]], also self-organizing neural nets inherit the biases of the programmer that created the system.[fn:18] Following this, even if the software is training itself it does not appear to be able to reach outside of its own context, and perhaps it should not try to. 

Secondly, musical aesthetics is commonly developed in a wide field of practices, not limited music. As a musician my freedom in performance, and my aesthetics, are shaped by a great number of impressions. Consequently, if the goal is to allow the machine to develop its own aesthetics its input should not be limited to sounds in performance, but include also all the other contexts in which music is negotiated in. This point, however, reveals the most obvious difference between KA and human musicians: KA has no real physicality. The lack of presence is a great disadvantage for KA, as is pointed to by one of the members of GI:
#+begin_quote
If you play with humans you have an idea of their aesthetics so that part is kind of integrated, on beforehand. So maybe there is always some kind of quick preparation, or plan in order to feed into the total? [fn:19]
#+end_quote
The question is not only concerned with aesthetics, but has also a bearing on the ethics of improvisation discussed above. [[#benson03][benson03]] makes the claim that the musical dialogue can be said to be ethical in nature “since music making is something we inevitably do with others (whether they are present or not)" [[#benson03][benson03]]. To play with someone is to encounter the other, but to play with a machine is not as simply analyzed. What is KA in this encounter? One of the members comment on this topic and asks: "How can I, ethically, relate to and play with KA with the same kind of trust and respect as when I play with humans?" [[#endresen2018][endresen2018]] Here, the focus is not on the failure of KA to be a good musician, but rather on the self. 

The larger question that emerges from this is: Is it at all possible to play, that is to fully play, without the feeling of a reciprocal trust that, one may suspect, goes beyond musical experience? If the co-musicians lacks a body and has no extension in the physical realm and there would be no sensation of the other, and the situation becomes radically different. The  co-musician is a blank slate, not even non-existent, but with negative extension. The machine is a void until it starts playing and even then, it is relatively difficult to anticipate the output. But even if the difficult question of empathy in music is put aside and disconnected from the question of physical presence, the impact of embodiment in music can not be disregarded [[#godoy2006][godoy2006]],[[#Leman2015][Leman2015]], and embodiment has had a big impact in the field of cognitive science. A slightly different question emerges: What are the strategies that may be employed that substitute for the lack of presence and lack of trust when playing with a machine? The simple answer is that it is possible. There is a great deal of music where one or more of the players is a machine, and GI's work with KA proves that it is possible, but the challenge is changing as the nature of the machine is changing. 

Concerning the general situation of computer interaction, it appears that we are quick to adopt. There are a number of tasks and activities that belong to the social realm that we now carry out virtually such as social media. Although the discussion concerning the precariousness of committing your social life to social media pops up every so often [[#lanier2018][lanier2018]],[[#lanier96][lanier96]] we appear to be able to quite quickly adjust and willing to substitute a physical meeting with a chat on a media channel. But because it is possible, and maybe even desirable in one context does not mean that it is so in another. To play with someone is to encounter this other and the ethics of this situation is greatly affected by the extent to which a physical meeting takes place. Regardless if this is a person on knows or not, a wide range of information is immediately gathered or created, merely through the first encounter. The body and posture, the way the instrument is held, the facial expression, and many other things contribute to what one may expect this musician to play. These impression forms the groundwork or underpinning for what will be played. 

If music is to be regarded as a social activity that participates in expanding the communicative possibilities both within the group of musicians playing together, and to some extent among listeners, then the very idea of playing with a machine does appear strange. The communicative potential in an interactive music system such as KA is relatively limited and different in nature from that of human-human communication. In the case with GI, however, the output of the machine is, after all, relatively well structured and possible to anticipate. GI has proved, as many other projects have done before, that it is possible to make meaningful music with a machine. But most noteworthy are the challenges the practice has shed light on. There is a need to better understand the possible modes of musical interaction with the kind of machine that KA is. But comparing it to a real musician makes little sense, because music in general, and improvisation in particular, commonly relies on a myriad of other parameters that are simply not available to KA. The most fascinating result of this, however, is (I) the extent to which musicians adopt and counteract the obvious shortcomings of the machine improviser and the reflections this leads to and, (II) the impact a conceptual change, such as thinking about KA as a composition rather than an improviser may have. Playing with a machine makes the conceptual asymmetry between the embodied musician and their instruments on the one hand, and the abstract and disembodied computer on the other, come to the fore. What we should do to overcome this difference, and why, will be an important question for the future.

[fn:18] 28 members of the US congress where mistakingly matched against pictures of convicted criminals and a disproportionate number of these were people of color.

[fn:19] Lab #5, part 2, February 19, 2019.

** Acknowledgments

I wish to thank all the members of Goodbye Intuition, David Toop and Annie Dorsen 

** Bibliography

\printbibliography
