* 119 Submission
:PROPERTIES:
:NOTER_DOCUMENT: 119 Submission.pdf
:END:
** Driving a LED
:PROPERTIES:
:NOTER_PAGE: 2
:END:

** Typo
:PROPERTIES:
:NOTER_PAGE: (4 0.13487071977638015 . 0.366600790513834)
:END:
``One one hand we''
** Typo
:PROPERTIES:
:NOTER_PAGE: (4 0.5814116002795248 . 0.18379446640316205)
:END:
``players, The works is part of a practice research''
** Missing image
:PROPERTIES:
:NOTER_PAGE: (5 0.6030747728860936 . 0.10770750988142291)
:END:
``#image:image_tlteSystem''
** Don't understand
:PROPERTIES:
:NOTER_PAGE: (5 0.7784765897973445 . 0.283596837944664)
:END:
#+BEGIN_QUOTE
Although an individual partic-
ipant rotating their interface will always create, a motor-sensory
loop closing, shift in the audio.
#+END_QUOTE
** Strange sentence
:PROPERTIES:
:NOTER_PAGE: (6 0.36827393431167016 . 0.5207509881422925)
:END:
#+BEGIN_QUOTE
We seem to have arrived at an interesting position then for TLTE,
where the design includes a strong route for, enactive based, func-
tional engagement; however the same could be also be said for
considering the participants as exploring within a post-human
entanglement of force and influence.
#+END_QUOTE

** Comments
1. Does the work ‘progress the field’ of interactive music performances, or music-making using technologies?
   Yes it does in the field of light controlled synthesis. This is a serious attempt at designing a new interface that can be used collectively.
2. Does the submission fit this year's special theme “entangled NIME”?
   Yes it does, explicitly. I am not, hoowever, convinced of the the way the connections is made in relation to the project. In the first instance, ligt, as particles, har a strong relation to entangled physical particles. But Barad goes further than that and claims a flat ontology on the level of subject/object. The paper claims that the object, that is the instrument they built, is an object that will support the entanglement between (post-)humans. The way this is described in section 4 is not very clear, nor convincing.
3. Does it inspire a shift in thinking about interactive musical performance?
   It does appear to forward the field of light controlled synthesis. The actual synthesis of the system is oddly absent.
4. Would you expect the paper to provide an interesting or original presentation/experience for NIME conference attendees?
   It could, potentially. 
* 113 Submission
:PROPERTIES:
:NOTER_DOCUMENT: 113 Submission.pdf
:END:
** This appears odd
:PROPERTIES:
:NOTER_PAGE: (3 0.4605171208944794 . 0.2727272727272727)
:END:
#+BEGIN_QUOTE
Embodied cognition emphasizes the
importance of the body in constraining intelligent behavior.
#+END_QUOTE

Isn't it rather shaping intelligent behaviour?
** Leading questions
:PROPERTIES:
:NOTER_PAGE: (3 0.5387840670859538 . 0.09683794466403162)
:END:

``5.1.1 Q &A''
** Discussion
:PROPERTIES:
:NOTER_PAGE: (4 0.7742837176799441 . 0.5217391304347826)
:END:
``6. DISCUSSION''

I lack a more substantial analysis of the questionaire. As it stands now it is more of a set of, sometimes quite leading questions, that are being answered. The research component is somewhat missing.
