 # Created 2020-09-19 lör 14:26
#+TITLE: GI and the critique of a machine
#+AUTHOR: Henrik Frisk, henrik.frisk@kmh.se

#+INCLUDE: "./setupfile.org"
#+LATEX_HEADER: \usepackage{biblatex}
#+LATEX_HEADER: \usepackage[style=authoryear-ibid,natbib=true,backend=biber,hyperref=false]{biblatex}
#+LATEX_HEADER: \bibliography{/home/henrikfr/Dropbox/Documents/articles/biblio/bibliography.bib}

(setq line-spacing 0.5)
* COMMENT Litterature
[[file:~/Docs/articles/biblio/bibliography.bib::Keyt1987][Keyt 1987: Three Fundamental Theorems Aristotles Politics]]

[[file:~/Docs/articles/biblio/bibliography.bib::Knoll2017][Jaulin & Güremen 2017: Aristotle Arguments Political]]

[[https://partiallyexaminedlife.com/2014/03/04/henri-bergson/][PEL on Bergson]]:

- Bergson, handen avhuggen PEL 39.00
- The Flux.
- The severed hand. The hand transforms to a different thing. The hand is a hand if it can fulfill its function. Parts only exist in the way they relate to each other. Reality is mobility.

https://lucian.uchicago.edu/blogs/elucidations/2012/08/10/episode-38-christopher-frey-discusses-aristotle-on-living-organisms-and-their-parts/

[[http://classics.mit.edu/Aristotle/politics.1.one.html][Aristotele, 1. 2.]]
since the whole is of necessity prior to the part; for example, if the whole body be destroyed, there will be no foot or hand, except in an equivocal sense, as we might speak of a stone hand; for when destroyed the hand will be no better than that. But things are defined by their working and power; and we ought not to say that they are the same when they no longer have their proper quality, but only that they have the same name. The proof that the state is a creation of nature and prior to the individual is that the individual, when isolated, is not self-sufficing; and therefore he is like a part in relation to the whole. But he who is unable to live in society, or who has no need because he is sufficient for himself, must be either a beast or a god: he is no part of a state. A social instinct is implanted in all men by nature, and yet he who first founded the state was the greatest of benefactors. For man, when perfected, is the best of animals, but, when separated from law and justice, he is the worst of all; since armed injustice is the more dangerous, and he is equipped at birth with arms, meant to be used by intelligence and virtue, which he may use for the worst ends. Wherefore, if he have not virtue, he is the most unholy and the most savage of animals, and the most full of lust and gluttony. But justice is the bond of men in states, for the administration of justice, which is the determination of what is just, is the principle of order in political society.

[[http://classics.mit.edu/Aristotle/meteorology.4.iv.html][Aristotele, Meteorology IV, 12]]
What a thing is always determined by its function: a thing really is itself when it can perform its function; an eye, for instance, when it can see. When a thing cannot do so it is that thing only in name, like a dead eye or one made of stone, just as a wooden saw is no more a saw than one in a picture. The same, then, is true of flesh, except that its function is less clear than that of the tongue. So, too, with fire; but its function is perhaps even harder to specify by physical inquiry than that of flesh. The parts of plants, and inanimate bodies like copper and silver, are in the same case. They all are what they are in virtue of a certain power of action or passion-just like flesh and sinew. But we cannot state their form accurately, and so it is not easy to tell when they are really there and when they are not unless the body is thoroughly corrupted and its shape only remains. So ancient corpses suddenly become ashes in the grave and very old fruit preserves its shape only but not its taste: so, too, with the solids that form from milk.

[[http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0052%3Abook%3D7%3Asection%3D1035b][Aristotele, Metaphysics, book 7, 1035b]]
But the body and its parts are posterior to this substance, and it is not the substance, but the concrete whole, which is resolved into these parts as into matter. Therefore in one sense these parts are prior to the concrete whole, and in another not; for they cannot exist in separation. A finger cannot in every state be a part of a living animal; for the dead finger has only the name in common with the living one.Some parts are contemporary with the whole: such as are indispensable and in which the formula and the essence are primarily present; e.g. the heart or perhaps the brain,2 for it does not matter which of them is of this nature.

[[http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0052%3Abook%3D7%3Asection%3D1036b][Aristotele, Metaphysics, book 7, 1036b]]
But the case is not similar; for the animal is sensible and cannot be defined without motion, and hence not unless its parts are in some definite condition; for it is not the hand in any condition that is a part of a man, but only when it can perform its function, and so has life in it. Without life in it it is not a part.

[[file:~/Dropbox/Documents/articles/lib/Bergson1912.pdf::%PDF-1.4 (agl)][Bergson, metaphysics page 47]]
analysis always operate on the immobile

Aristoteles from /Categories/:
"When things have only a name in common and the account of being [λόγος τῆς οὐσίας] which corresponds to the name is different, they are called homonymous … When things have the name in common and the account of being which corresponds to the name is the same, they are called synonymous"

See: https://core.ac.uk/download/pdf/30817764.pdf

ebib:sontag2013
[[file:~/Docs/articles/biblio/notes/bibnotes.org::#Sontag1986][Sontag, S. (1986): Against interpretation: and other essays]]

* Method development, style and the nature of machine improvisation
** Method development in GI

   French philosopher Henri Bergson sought to address the problem of what possible knowledge one may have of the world exterior to oneself and in this effort he defined the method of intuition. It may appear almost defensive to get into an indepth investigation of the term /intuition/ in a project that that has attempted to do away with it altogether. In the way that it is used in the title of the project intuition points to the ordinary use of the word which can be summarized as the "ability to understand or know something immediately based on your feelings rather than facts."[fn:2] Though not completely unrelated, Bergson's notion of intuition is rather different and for this reason also of interest for the present discussion. Intuition as a method can be useful and will by necessity include also other modes of thinking than the immediately present status of our more common view of intuition. The point here is not to give a full account of Bergson's philosophy, nor of his method, but, in order to better understand its kinship to the method development in GI, and the actual work that was performed within the project I will make a brief overview of what it entails. However, anyone with a particular philosophical interest should go to the source for more information. Furthermore, the method contains certain idiosyncharsies that may or may not work to the full extent in the frame of the other theories presented.

To understand intuition in the a Bergsonian way it may be necessary to contrst it with other definitions of intuition. The more general interpretation of intuition relates to the things we do without thinking about them; the intuitive knowledge that something is wrong or dangerous. Almost as if there is an automated system that gives us information through consiousness about what is going on in the world around us. In phenomenology intuition has a slightly different meaning where first-person knowledge can be acquired through intuition whereby an object can be /intuited/. Kant's distinction between concept and intuition is clearly a point of departure for Bergson's argument here and his use of the word is even further bemusing.

Bergson defines two incommensurable ways to approach an object: either from a point of view through signs and concepts, a /relative/ perspective, or through entering into the object, exploring it from the inside: an /absolute/ apprehension. This second method is achieved by entering into sympathy with the possible states of the object which allows him, as he describes it, to "insert myself in them by an effort of imagination." [[citep:Bergson1912][p. 2]] This, he continues, enables him to "no longer grasp the movement from without, remaining where I am, but from where it is, from within, as it is in itself." [[citep:Bergson1912][p. 3]] The latter is what he refers to as the /absolute/ knowledge: "the absolute is the object and not its representation, the original and not its translation, is perfect, by being perfectly what it is" [[citep:Bergson1912][p. 5-6]]. This is a quite radical proposition, in contrast to the dominant theories of mediated perception that most notably Kant had put forward. The concept of actually being able to possess the object, or rather, its motion, in itself makes possible a range of conceptions.

The example that Bergson gives us to better understand what he means by representational knowledge is a photographic model of a city. One where all angles and all surfaces have been photographed and documented to achieve something similar to a street view that online map programs sometimes offer. Exploring such a model can obviously  never be equated with the experience of being in the city. Another example brought up is the translation of a poem into many languages[fn:1] and how it can give the reader a good idea of its meaing, sometimes with even more details, but it will never form a complete image and would "never suceed in rendering the inner meaning of the original" [[citep:Bergson1912][p. 5]]. One of the central propositions is that analytical knowledge is always a reduction of the thing being analyzed. /Analysis/ is what might be referred to as an empirical understanding to which a defining aspect is its reductive force, dividing the objects into ever smaller elements that eventually resonate more with what we already know than with the thing we analyze. The thing analyzed then becomes merely a function of the perceiver rather than an object in and of itself. Auch an analysis creates representations that are discontinuous in the flow of time:

#+begin_quote
In its eternally unsatisfied desire to embrace the object around which it is compelled to turn, analysis multiplies without end the number of its points of view in order to complete its always incomplete representation, and ceaslessly varies its symbols that it may perfect the always imperfect translation. It goes on, therefore, to infinity. But intuition, if intuition is possible, is a simple act. [[citep:Bergson1912][p. 8]]
#+end_quote 
The /absolute/ is given from this /intuition/ and an /intellectual sympathy/ with an object that allows one to perceive its unique qualities beyond words. Hence, the /perfect absolute/ should be understood in relation to the imperfect analysis, and metaphysics is what allows one to experience what it means to have an intuition of the object at hand. To Bergson, the science of intuition is metaphysics, and metaphysics is "the science which claims to dispense with symbols" [[citep:Bergson1912][p. 9]]. Rather then engaging in representations of objects by means of symbols and concepts, we are urged to understand the object from within. This may be compared to self-reflection and Bergson describes the various strata of introspection that he goes through moving from the outside towards the centre of the self. A protecting "crust" via memories down to the motor habits that are both connected and detached from memories and perceptions. But at the core, Bergson describes the continuous flux of a concatenation of states, the beinnings and ends of which are merged together and extend back and forward. The metaphor used here is that of a coil constantly unrolled and rolled up again, although, admittedly, this is not very close to the truth. There are no two identical moments in consciousness and the rolling up of the coil may thus be misleading. Even going back in memory to a past event invades that memory with all the present and past events. This evokes the image presented in his earlier work, [[citetitle:bergson91]], of the cone whose tip is moving over a moving plane, and where the point of the cone represents the present and the cone itself the accumulated memories and experiences: 

#+begin_quote
  The bodily memory, made up of the sum of the sensori-motor systems organized by habit, is then a quasi-instantaneous memory to which the true memory of the past serves as base. Since they are not two separate things, since the first is only, as we have said, the pointed end, ever moving, inserted by the second in the shifting plane of experience, it is natural that the two functions should lend each other a mutual support.  So, on the one hand, the memory of the past offers to the sensori-motor mechanisms all the recollections capable of guiding them in their task and of giving to the motor reaction the direction suggested by the lessons of experience. It is in just this that the associations of contiguity and likeness consist. But, on the other hand, the sensori-motor apparatus furnish to ineffective, that is unconscious, memories, the means of taking on a body, of materializing themselves, in short of becoming present. [[citep:bergson91][p. 152-3]]
#+end_quote

The sensory motor-habits are informed by memories through which they will be guided to do the work they need to do, and because no single memory is ever stable--it is always altered by the present in the interaction between what Bergson refers to as the "pointed end" and the past memory--the present experience is continously altered by past experience which in turn is influencing the present. Hence, the general understanding of intuition, as an action guided by feelings rather than by facts, may be said to still hold true, but a comparison quickly becomes very difficult without defining what constitutes a /feeling/ or a /fact/. This is, however, not the primary purpose of this text, but what is of interest is the connection between sensori-motor mechanisms and past experience, and the fact that this connection is not only going one-way, from memory to habit, but also from habit back to memory. Embodied memory is in a changing flux and in constant interaction with experience and habit. There is an inclination to understand learned behaviour, such as playing an instrument or lifting a glass of water, as an act that is settled, almost as if it was independent of the conscious mind. To this there is a whole range of relevant research in  embodied cognition and consciousness that is out of scope to the topic of this essay, the purpose of which is mainly to look at intuition as a method for a better understanding of musical interaction with electronic instruments.

It is in thinking about embodiement and motor-habits that Bergson's understanding of what an intuition can be is perhaps best understood. If I move my leg or my hand, or even if it is my own body that is moving, I can only access the information that guides this movement through intuition. Analyzing the movement fails to understand it completely since the analysis only pins the movement to a sequence of states: first the arm was here, then here, then there. The actual change, the mobility or, as Bergson would put it, the duration, is only understood from the intuition. Furthermore, it would be wrong to say that the mobility is merely part of an automated task such as moving the hand, because any new experience within the movement, and any past experience will introduce change:

#+begin_quote
When you raise your arm, you accomplish a movement of which you have, from within, a simple perception; but for me, watching it from the outside, your arm passes through one point, then through another, and between these two there will be still other points; so that, if I began to count, the operation would go on forever. [[citep:Bergson1912][p. 6]]
#+end_quote

I have learned to move my arm but any new information about what I can do with it will add to my arm-moving-knowledge, and intuition is the modality through which this process is carried out. For the observer that is able to observe the thing from the inside, intuitively, there are no states, only duration and mobility informed by experience and knowledge. 

Conceptual knowledge is reached by way of concepts that represent the thing of which knowledge can be said to be had. These, says Bergson, have the "disadvantage of being in reality symbols substituted for the object they symbolize" [[citep:Bergson1912][p. 17]], and as such they demand very little of us. Furthermore, each concept merely expresses a comparison between itself and the object that resembles it and by way of this resemblance we imagine that by taking concept after concept and putting them side by side we are actually reconstructing the analyzed object. Through analysis we create concepts and symbols that allow us to structure and organize the world in a systematic manner. If metaphysics, then, is a serious science by which the world can be understood and experienced rather than just a mind operation, "it must transcend concepts in order to reach intuition" [[citep:Bergson1912][p.21]].  

The methods of analysis and the method of intuition proposed by Bergson has important relevance to the field of artistic research in general and to the project /Goodbye Intuition/ specifically, though perhpas less because of the project's title and more due to the method development has evolved over time. One of the defining ideas for artistic research is that there is a difference between knowledge that has been acquired from observing an artistic practice, and knowledge that is the result of taking part in the artistic practice. A common metaphor used to described this difference is to see the former as knowledge from the inside and the latter as knowledge from the outside--problematic in itself as the concepts of /inside/ and /outside/ are difficult to determine and rarely stable. In S\{o}ren Kj\{o}rup's contribution to [[citetitle:biggs10]] he comments on what may be the difference between the outside and the inside perspective and writes that:

#+begin_quote
if artistic research is supposed to be different from all other kinds of research, it is natural to focus on the artist as the researcher, and what is specific for the artist is he or his priveleged access to her of his own creative process. [[citep:kjorup10][p. 25]]
#+end_quote

This "priveleged access" may be seen as an alternative to knowledge mediated by symbols and concepts but a particular difficulty lies in the problematic relation between traditional epistemology and this inside perspective. One of the recurring themes in the early discussions on the identity of artistic research was, and still is, what kind of knowledge artistic knowledge and methodology could lead to, and what kind of relation it would have to other kinds of knowledge. How can artistic research as a discipline make sense "in a way that does not subordinate [it] to other activities of thought taken to be superior modes of knowing" [[citep:johnson2010][p. 150]]? Johnson further stresses that the potential in this kind of knowing lies in the experience rather than empirical knowledge:

#+begin_quote
The /research/ here would not be geared toward the accumulation of empirical facts or propositional knowledge, although that might be part of the story. Instead, /arts research/ would be inquiry into how to experience and transform the unifying quality of a given experience in search of deepened meaning, enhanced freedom, and increase of connections and relations. [[citep:johnson2010][p. 150]]
#+end_quote

Henk Borgdorff is an other often mentioned reference and has been one of the key figures in defining the development of European artistic research. His claim that "it is not formal knowledge that is the subject matter of artistic research, but thinking in, through, and with art" [[citep:borgdorff2012][p. 143]] has gained traction in the field in that it attempts to put the focus on the activity of creating art. It is possible to contest the proposed opposition between formal knowledge and what may be extracted from thinking in, through or with art, but what Borgdorff is pointing to is that there is a possibility for a "special articulation of the pre-reflective, non-conceptual content of art." [[citep:borgdorff2012][p. 143]] This may be understood as leaning on a Kantian notion of aesthetic experiences as pre-conceptual, again invoking a free-play of imagination, with the consequence that the kind of mediation through conceptual and symbolic representation that characterize most forms of knowledge is sidestepped. This creates a number of conflicts, the most obvious of which is the question of what kind of knowledge we are dealing with if the art (practice) is understood directly, in and of itself, and how it can be represented in a stable manner. The question at hand, then, is how can this unmediated experience be useful to the artistic researcher and, more importantly, how can it be described in a way that makes the results relevant for other researchers?

This is, without a doubt, one of the more pressing and still controversial questions in artistic research and the point on which this discipline is most oftenly criticized, but it is not my aim to address it directly here.[fn:3] Instead, my focus is to put Bergson's method of intuition in the context of the method development of the project /Goodbye Intuition/ and how I have approached the method in my attempt to understand what KA is and can be in an artistic practice. Bergson's method of intuition may contribute to showing that not only is it possible to gain formal knowledge from artistic research in a methodologially sound manner, but also, although artistic research has much to contribute the difference compared to other fields of knowledge production is perhaps less significant then what is commonly believed.

Bergson's description of the two profoundly different ways of knowing a thing, through /relative/ and /absolute/ knowledge may at first adhere to the idea of non-conceptual knowledge, but as was described above, it is in fact in starch contrast. According to Bergson it is in every way possible to achive absolute knowledge about a thing through the method of intuition and by way of /sympathy/ that allows for an understanding from the /inside/ of an object. Without this point of view one is left with the option of analysis and regardless of how many different perspectives this analysis is performed from, it will never fully capture the true motion of the object. Yet, this is the faculty of knowledge that is often seen as the principle mode of thinking. The contradictions between this and the intuitive, absolute, knowledge that Bergson is arguing for:

#+begin_quote
arise from the fact that we place ourselves in the immobile in order to lie in wait for the moving thing as it passes, instead of replacing ourselves in the moving thing itself, in order to traverse with it the immobile positions. They arise from our professing to reconstruct reality--which is tendency and consequently mobility--with percepts and concepts whose function it is to make it stationary. [[citep:Bergson1912][p. 67]]
#+end_quote

One central aspect of this distinction between analytical and intuitive knowledge is that the intuitive can always develop concepts and form the basis for analytical knowledge, whereas it is impossible to reconstruct mobility from fixed concepts. An analysis may result from intuition, but intuition cannot arise from analysis. The analysis is performed on one particular state of the duration and from multiple analyses it possible to think that the mobile may be reconstructed by simply adding the different states together. This is however the critical point that Bergson objects against. It is only through intuition that the variability of reality may be fully experienced as mobility, whereas the element, or the state, is the opposite. It is a frozen frame and an isolated view of reality. The error in thinking that reality may be accessed through analysis, claims Bergson, "consists in believing that we can reconstruct the real with these diagrams. As we have already said and may as well repeat here--from intuition on can pass to analysis, but not from analysis to intuition" [[citep:Bergson1912][p. 48]]

One important aspect of this is how the whole relates to the parts. According to Bergson dividing a whole up in parts is possible, but reconstructing the whole from the parts is utterly impossible. Again, taking the example of the moving hand, it is possible to analyze its movement as a successsion of states, but impossible to reconstruct the motion from these states. This holds true regardless of the precision and resolution of the collected frames--there will always be a space between current and previous frame. This corresponds to the Aristotelian view that the whole is always prior to the parts and that things can not be reduced to parts without loosing a significant part their identity.[fn:4] The hand is not a hand, except by name, unless it can perform the function of a hand. If the hand is removed from the body, the hand is no longer a hand although by its appearance it is still a hand:

#+begin_quote
What a thing is always determined by its function: a thing really is itself when it can perform its function; an eye, for instance, when it can see. When a thing cannot do so it is that thing only in name, like a dead eye or one made of stone, just as a wooden saw is no more a saw than one in a picture. The same, then, is true of flesh, except that its function is less clear than that of the tongue. [fn:5]
#+end_quote

In essence this means that the hand as an object is less than the hand that also performs its function, and that the hand, when still a part of the body, obviously stretches out beyond the merely physical hand; it is connected to the arm with muscles and tendons and to the brain with nerves. This is true of most instruments that has a specified function. A hammer can be said to only be a hammer when it performs as a hammer, and a piano is only a piano when it is performed by a pianist. The hammer as a sign is signified by both the physical hammer in general, and the hammer that performs a function, although the latter, of course, is dependent on a whole range of other things and energies in order to perform. From a more personal perspective, for me as a saxophonist, my saxophone similarily is perhpas primarily an object--a saxophone, or a musical instrument. However, once I pick it up and start playing it, it is a rather different thing. In my hands it becomes an extension of my body similar to the hand, primarily as a result of the many hours of practice that I have performed and as such it becomes an extension of my musical ambition. But as soon as I put it down it is nothing more than a piece of brass again and as such it is as useless as the severed hand.

Though it may at first be counterintuitive to look at a musical instrument as two different kinds of objects depending on if they are being played or not, this fact is further complicated by the fact that instruments also hold socio-cultural meanings that are independent, but related, to the music they are used perform, multiplying their possible signifiers manifold. With electronic instruments it is even more complex due to the fact that they commonly lack a physical interface that has a clear relation to the core engine of it that makes the sound. If the instrument is also intelligent in some way, that is, if its musical output is greater more than what it is given as input, the relations can become very obscure. In other words, while the musician playing an acoustic instrument quite easily becomes one system in which it is possible to enter into and gain an intuitive understanding of, that is, understnading it from within, for the electronic instrument this is much more convoluted. It is not much help to approach the electronic music instrument as an object independent of the person playing it. The issue for this discussion is consequently that it is not enough to perceive the movement from within, it is first necessary to see the full context of the system for which the intuition is desired and then move inside of it. If not it will mainly only be possible to perform an analysis of the parts which is always an incomplete picture, notwithstanding that only analysis rather than intuition is possible.

To do what Bergson asks us to do, to move inside an object to fully understand it and its mobility, its duration, it is important to understand what kind of object it is we attempt to move inside. As mentioned earlier, this is far removed from the Kantian view of the external world as something unreachable and impossible to have any true knowledge about. If I wish to understand what it means to play the saxophone, it is not the saxophone I need to enter inside, nor is it merely my own ambition with playing an instrument, I need to enter inside the larger performative system of both myself and the instrument. This unity is what creates the conditions for expression and musical creativity and analyzing the parts by themselves will only tell us what the parts are capable of and even if we manage to inside, say the saxophone, we will only be able to understand its motion as an independent object. Only if we see the whole as an integrated system, and only if we manage to get on the inside of this system, will we be able to fully understand it and the way it is conditioned by its motion. It from this analysis we then can proceed to analysis.

But what does it mean to get on the inside of a system such as a computerized instrument, the boundaries of which are seemingly unknown? An electronic instrument that, for example, is connected to the internet and that continously fetches information that influences its output in live performance is a very different thing from an acoustic musical instrument. Especially so if the mapping of the physical input from one or several performers is hidden from both performers and audience, or even remapped during the course of the performance. What is the embodied relation between such an instrument and the performer that allows for it to be understood as a unified system? While the saxophone can be said to cease to be the independent object 'saxophone' once it is picked up and played on, with the typical computer based instrument in the shape of a software running on a computer, which is what KA is, at what ways can the software instrument be embedded in a similar way?

An argument can be made is that for self-playing systems involving some kind of artificial intelligence, the system that rules the musical outcome is much larger than what may be experienced at first. What I see when I start such a program on my laptop, what I experience to be the system in play is just myself and the computer, where in reality it may involve previous input and output and the programmer's various positions and biases. The programmer is obviously concealed in this system, detached in both time and space, which makes it difficult to fully understand their impact. In a sense the electronic musical instrument is a system which is by some degree larger and more elaborate than the previous example with a an acoustic instrument. Furthermore, many electronic instruments, by their immediate relation to engineering and science lend themself naturally to an understanding based on analysis rather than intuition, which enforces their role as mere tools. The development of musical artificial intelligence and advanced electronic instruments has obviously profited from this and has clearly contributed to their fast development. At the same time there is a great interest in interfaces and systems that convey a certain stability that encourages long term development between performer and instrument. In other words, whereas quick development serves its purpose at several stages of the design of the instrument, it may become an obstacle when trying to understand it in a musical context and as an integrated part of a larger system.

Clearly, part of the challenge is understanding the interface between musician and an instrument, and part of it is understanding what type of electronic instrument is under scrutiny. My attempt here is not to make a general theory of the various types of electronic instruments that could be of interest to such a study, but instead to mainly focus on a particular case, the KA of /Goodbye Intuition/. Nonetheless it should be noted that other types of electronic instruments, such as a modular synthesizer, for example, that holds a whole range of possible modes of engagements, allow for quite a different set of possibilities than what a piece of software does that is completely lacking a physical interface. I believe that it is possible to approach also other kinds of systems with the same method and that this could contribute to furthering the knowledge about the musical opportunities of electronic instruments.

The question now is, how may it be possible to achieve the kind of /sympathy/ that Bergson is referring to that allows for an interior experience of system that is the combination of the performer and the instrument? He describes it in a way that have a great deal of resonance with artistic practice when referring to the /absolute/ movement and the states of mind that gives him access to the interior:

#+begin_quote
I also imply that I am in sympathy with those states, and that I insert myself in them by an effort of imagination. Then, according as the object is movin or stationary, according as it adopt one movement or another, what I experience will vary. And what I experience will depend neither on the point of view I may take up in regard to te object, since I am inside the object itself, nor on the symbol by which I may translate the motion, since I have rejected all translations in order to possess the original.[[citep:Bergson1912][p. 2-3]]
#+end_quote
** Biblography
\printbibliography
* Footnotes

[fn:5] See Aristotele, /Meteorology/ IV, 12 

[fn:4] See Aristotele /Politics/, \RN{1}.2 and /Metaphysics/ \RN{7}, 1035b.

[fn:3] For a more complete discussion on this topic, see citet:frisk-ost13.

[fn:2] Intuition. (n.d.). In /Cambridge Dictionary online/. Retrieved from https://dictionary.cambridge.org/dictionary/english/intuition 

[fn:1] As Swedish artist Andreas Gedin has proved, sequential translations of a poem into multiple languages changes the character of its content.
