#+title: On the ethics of instruments
#+NAME: XXXXXX
#+DATE: \today     
#+cite_export: csl ~/Documents/articles/biblio/csl-styles/apa-7th.csl
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc author:nil
#+LaTeX_HEADER: \usepackage[x11names]{xcolor}
#+LaTeX_HEADER: \hypersetup{linktoc = all, colorlinks = true, urlcolor = DodgerBlue4, citecolor = black, linkcolor = black}

#+begin_src emacs-lisp
   (set-window-margins (selected-window) 20 20)
    (setq line-spacing 0.5)
  #+end_src

  #+RESULTS:
  : 0.5

* On the ethics of instruments

\noindent
Proposal for /Vintage Materialities in Music/, lecture-recital.
** Abstract[fn:3]

In this lecture-recital [cite/text/c:@Tresch2013]'s notion that the material aspects, mediations and the telos of an instrument can provide grounds for an analysis of its  /ethics/ is discussed. It may first appear odd to speak of ethics in relation to objects such as a musical instruments, and this is an attempt to revisit the origin of this idea and critically examine it by briefly discussing its roots in Foucault's /History of Sexuality part 2/ [cite:@foucault2012]. In the presentation a performance on the /Dataton 3000/, a modular synthesizer and audio mixer designed in Sweden in the 1970's (see ANONYMIZED), is used to illustrate how these ideas can be understood and critically assessed. To attempt to understand the qualities and the particularities of this instrument a wide range of parameters need to be considered, including those related to the context in which it was originally created. Yet, development of performance practices may also happen by simply disregarding such information and treat the instrument primarily as a vehicle for the creativity of its player. In the attempt to understand the dialectical relation between staying true to the instrument's origin (according to some principle) and allowing new practices to be formed on top of old, or by simply bypassing existing and/or forgotten practices, there is a need for a method. Though the notion of an ethics of instruments as sketched out by Tresch and Dolan appears to be useful, it also raises questions related to the agency of the instrument in a network af agents formed through performance and through the interfaces that emrge in the playing.

\vspace{1cm}


** Bibliography
# #+bibliographystyle: unsrtnat
#+print_bibliography: title: "Bilblio"

* Abstract
In a project concerned with research into historically-informed sound synthesis a collection of electronic instruments from the sixties and seventies collected by the Swedish Performing Arts Agency and archived by the Performing Arts Museum, instruments in the collection are explored artistically in order to reveal both past practices as well as discover new ones. One of the concerns in this process is how this cultural heritage can be examined without conceptually dismantling the uniqueness of the properties of the actual instruments. The challenge is to identify and categorize the instrument in and of itself, not as an object of nostalgia or as an object with which contemporary ideas and trends are exploited, but instead attempt to approach it with taking into account its cultural, social and political affordances.

The idea is to develop a historically informed performance practice informed by possibly previously hidden features of the historic instrument. One of the instruments we have approached is the /Dataton 3000/, a modular synthesizer and audio mixer designed in Sweden in the 1970's. To attempt to understand the qualities the particularity of this instrument a wide range of parameters need to be considered related to the context in which it was originally created. Should this analysis not be successful there is a risk that either the instrument's proper affordances are misunderstood, or that one ends up recreating what has already been done with it, or both.
 
The challenge found a preliminary solution in [cite/text/c:@Tresch2013]'s notion of an /ethics of instruments/ [cite:see ;@Frisk2021a] leaning on the notion that the material aspects, mediations and the telos of an instrument can provide grounds for an analysis of its /ethics/. It may appear odd to speak of ethics in relation to dead objects such as a musical instruments, and this paper is an attempt to revisit the origin of this idea and critically examine it by briefly discussing its roots in Foucault's /History of Sexuality part 2/ [cite:@foucault2012] and related theories on ethics. The general idea that enables using ethics in this way is based on the fact that instruments have agency, and is further rooted in a relational ontology in which the instrument exists. The heritage process that we use [cite:@lundberg2015] implies that these objects have agency, and that it is of importance. The question approached in this paper is if the concept of "ethical specificities" [cite:@Tresch2013;p. 298] of instruments can contribute to knowledge about arrangements of historic electronic instruments and their players without blurring the conceptual differences between the actors involved and hence also the properties of the instrument.

There is an obvious risk that the instrument is anthropomorphized in the process of considering its ethics. In the flat ontology that this view is promoting there is further a number of problems that arises, the most urgent perhaps, is that even though the instrument has agency, on the surface level it still lacks the will and the freedom that a human possesses. This objection is clearly situated in a Western dualist view of the world. Traditional laws of causality enforce this view, but it may be useful to see the use of the instrument in (at least) two distinct but related articulations. First, there is the object in an of itself. As such it has certain observable properties and even in this stage it exposes its interface and through it, its connections: the fact that it is a musical instrument, that it is playable, that it belonged to a historic area, and so forth. At this stage there is no obvious causality. Second, in the situation when a musician engages with it a different epistemic network emerges. A cybernetic connection develops through the interface that the instrument exposes. The causal relations in this network are contributing to both the knowledge in the system and to its output.

Whether or not either of these contexts provides evidence for an ethics of the instrument is a philosophical question difficult to resolve from a practical perspective. If instead the focus is put on the /usefulness/ of an ethical perspective of the instrument this question is perhpas more easily approached. In a network consisting of human and non-human objects, such as a musician and a /Dataton/ module, it would be fair to say that the ethics of the human extends to instrument in a way that alters the possibilities of both musician and instrument, making the ethics of the situation useful to consider, artistically as well as from a heritage point of view. The musician has to adhere to the materiality of the instrument, its mediations and telos. As [cite//t:@dalton2018] concludes, "rejecting the freedom of material objects [\ldots] does not imply their moral neutrality" [cite:@dalton2018]. However, removing the instrument from this network neutralizes its ethical specificities making the player an ethical necessity. Returning to Foucault, however, this presents a possible conceptual problem, and one that was always present. The modes of subjectification that he promotes are rooted in his aesthetics of existence. As such it departs necessarily from the private sphere and will not function as a code exposed on an object from the outside.

** Bibliography
# #+bibliographystyle: unsrtnat
#+print_bibliography: title: "Bilblio"


* Footnotes

[fn:3] The main topic of the call addressed in this study is how obsolete technologies for music production and performance can become desirable again in an era of high-tech, across different genres, and in both the professional and amateur spheres. 
[fn:2]A ne of the abgisionArtistic research is the formalization of this connection. 

[fn:1]There are several artist-in-residence programs that have this explicit ambition, Xerox Parc [cite/p:@harris1999], Bell Labs [cite/p:@mccray2020], CERN
https://arts.cern/programme/artistic-residencies och NASA.
