#+cite_export: csl ~/Documents/articles/biblio/csl-styles/apa-7th.csl

#+LaTeX_HEADER: \usepackage[x11names]{xcolor}
#+LaTeX_HEADER: \hypersetup{linktoc = all, colorlinks = true, urlcolor = DodgerBlue4, citecolor = black, linkcolor = black}

#+begin_src emacs-lisp
   (set-window-margins (selected-window) 10 10)
    (setq line-spacing 0.7)
  #+end_src

  #+RESULTS:
  : 0.7

* Exploring an ethics of instruments
<1>
This presentation is part of a research project the title of which is /Historically informed design of sound synthesis: A multidisciplinary, structured approach to the digitisation and exploration of electronic music heritage/. <2> It engages with historically-informed sound synthesis through a collection of electronic instruments from the sixties and seventies collected by the Swedish Performing Arts Agency and archived by the Performing Arts Museum in Stockholm. In ths project instruments in the collection are explored artistically in order to reveal both past practices as well as discover new ones.

In a wider scope of contemporary technologies the rate at which the development in general is progressing can turn objects sometimes less than a decade old incompatible with current systems. A hypothesis of this project is that by learning from early electronic instruments using the methods we have proposed it may be possible to better understand the complexities of what can be seen as media archeology.

One of the concerns is how this cultural heritage can be examined without conceptually dismantling the uniqueness of the properties of the actual instruments. The challenge is to identify and categorize the instruments in and of themselves, not as objects of nostalgia or as objects with which contemporary ideas and trends are exploited, but instead attempt to approach them with taking into account their cultural, social and political affordances. Based on the heritage research methodology we have chosen to promote the possibility of a historically informed performance with the instruments themselves, or re-enactments of them. The challenge remains to address existing biases within artist and engineering communities. 
<3>
The idea is to develop a historically informed performance practice, informed by previously, possibly, hidden features of the historic instrument. One of the instruments we have approached is the /Dataton 3000/, a modular synthesizer and audio mixer designed in Sweden in the 1970's. To attempt to understand the qualities the particularity of this instrument a wide range of parameters need to be considered related to the context in which it was originally created. Should this analysis not be successful there is a risk that the instrument's proper qualities are misunderstood, or that one ends up recreating what has already been done with it, or both.

In design history we can see how inventive design is incorporated into mainstream products and some simple forgotten. It is not unlikely that some stuff has been forgatten or supressed in the fast development of technology over the last half century. As Pinch and Trocco concludes about the synthesizer: "from a flexible variety of possible control configurations, the synthesizer eventually stabilised into a keyboard instrument" [cite:@Pinch1998]. In other words, over time the field is narrowed and standardization and market forces excludes those items that are not successful enough focussing on one particular functionality.
<4>
An organology, or even just a deepened understanding of a single instrument's meaning and position in a context, past or present, should really include not only its design or functionality. It should also take into account whatever agency it has or had including what kind of music was meant to be played on this instrument. A banal example to clarify this point would be the comparison between playing a cembalo sound on a synthesizer, and playing a real cembalo. Even though they may potentially be sonically indistinguishable they are not equatable. Not only because the latter is a historic instrument, but because they are utterly different from a cultural, aesthetic and material point of view. They may have similar agency (they are part of the same network and may play the same role in it), but as instruments they function in very different ways.
<5>
Needless to say, most musical instrument are associated with a style or cultural context even if some, such as the piano, have multiple associations. Equally superfluous to point out is that any musical instrument can be used in a wide range of situations completely independent of its origin. One extreme example is Swedish organist and pianist Karl Erik Welin who in his last piano recital in 1964 performs /Rendez-Vous 1963/ by Théodore E Libèr [cite:@wiggen1964] in which he dismantles a piano by means of a chain saw. Nevertheless, even this radical way of "playing" the piano relies on the instrument's history and the fact that a piano has a series of cultural connotations. With electronic instruments, in particular those that are not actively played anymore, finding out the particular associations the instrument provides may be a difficult task. Part of the reason here is the fact that there is a technological sphere with which the instrument is associated, apart from the purely musical. If the instrument is not actively used anymore the gap between these various contexts of the instrument may have grown quite significantly. One such example is the Dataton. ( the functionality of which is described in [cite/text/c:@Frisk2021a]. )
<6>
The study of Western music has somehow always relied on a continuity/discontinuity that makes it possible to trace the developments that commonly takes time. Haydn left a mark on Beethoven that he developed and Mahler and Wagner continued and so forth, breaking with traditions as well as concurring to them. These particular kinds of trajectories, in this case specific but not unique to Western art music, is well documented and studied. The transformations increased in speed in the twentieth century though there are notable exceptions to be found such as Conlon Nancarrow and Harry Partch. With the introduction of electronic instruments that started in the late 19th century but gained new strength following the technological optimism and economic growth in the post war era the situation changed even more.

--------------
<7>
What is the difference between the traditional method for musical interpretation, rooted in Western musical practices (really art history) and so well described by Roland Barthes in the famous essay /The death of the Author/ [cite:@barthes68:death_of], where detailed biographical and historical knowledge about the composer is at the core inspirations in order to make a true interpretation of the work, and the excavation of the technological and cultural significances of a particular electronic musical instrument of the past? What is it we are looking for and what kind of knowledge may there be?

My primary interst in this project is not the objects in themselves. If it were we could for example say that there is nothing outside this piece of equipment to rudily paraphrase Derrida, there is only the object and what it tells us. Nor is it a artistically driven project where the end goal is the "work", but at the centre is the author. It is the possible interactions that are made possible by engaging in a play with the objects, a free play that does not have a purpose and no particular meaning at this point (it may well develop in other directions in the future). In this free play I can engage with certain questions in a way that would otherwise not have been possible.

The biggest difference between these latter two models is that the first has an origin (the composer) and the second is a network of relations that includes the onriginator but does not necessarily privilege them. This I would argue is not normative on the level of practice, it doesn't predict how one should do something, but rather it proposes how one may understand something one already does. The added value is that it opens up for an expanded ethical dimension of artistic parctices that value the larger context of, in this case obsolete instruments, and the relationships between the various agents involved in their past and current practices.
<8>
Similar to Foucault's notion of the /care of the self/ it is a particular development between self and others that is at the core, a method for developing an ethics through engaging with the self's relation to the self, a self that is rooted in "practices of freedom" [cite:@Foucault1997-2; p. 283]: "Freedom is the ontological condition of ethics. But ethics is the considered form that freedom takes when it is informed by reflection" [cite:@Foucault1997-2; p. 284].

I was inspired to develop this line of thought after our paper /Sounds of Future Past/ where  [cite:@Frisk2021a] the concept of an /ethics of instruments/ was explored as inspired from [cite/text:@Tresch2013]. Their paper is not focused on the care of the self per se, but rather on some of the conditions for, or elements of, ethical relations related to the technologies of the self, the ontology, deontology, ascetis and the teleology of ethical relations. The care of the self is rather the activity of which these elements are a part, and it is not a solipsitic activity that is focused on the body:
<9>
#+begin_quote
When you take care of the body you do not take care of the self. The self is not clothing, tools, or possessions; It is to be found in the principle that uses these tools, a principle not of the body of the soul. You have to worry about your soul--that is the nprincipal activity for caring for yourself. The care of the self is the care of the activity and not the care of the soul-as-substance. [cite:@Foucault1997-2; p.231-2]
#+end_quote
The principle that uses the tools of artistic practice is in essence the aesthetics of the creative act: the practice itself.

<10>
To me the notion of the care of the self opens up for a focus on the relations between the self and the things around me and this process helps me understand myself as a subject. Not only that these relations exist and that they matter, but that they need to be good and respectful. This is what makes possible for, in not an ethics of instruments, but a developed sense of ethics through a deep understanding for the relations I'm engaged in. The question approached here is if the concept of "ethical specificities" [cite:@Tresch2013;p. 298] of instruments can contribute to knowledge about arrangements of historic electronic instruments and their players without blurring the conceptual differences between the actors involved and hence also the properties of the instrument.

This is in a way what I belive Tresch and Dolan are speaking of but it is actually a bit unclear. Their idea of an /ethics of instruments/ [cite:see ;@Frisk2021a] is leaning on the notion that the material aspects, mediations and the telos of an instrument can provide grounds for an analysis of its /ethics/. These criterias thay have borrowd from Foucault's /Technologies of the self/. It may appear odd to speak of ethics in relation to dead objects such as a musical instruments and it is possible to critique cusch a notion based on the fact that not all humans enjoy ethical rights (composre the feminsita argument againse post-humanism that not all humas have treated humanly).

I should say that a full discussion of this would take much longer than what we have here, so this should be seen as a scratch on the surface. It should also be noted that Tresch and Dolan's main interest here is to use their framework to study historical instruments, both musical and scinetific, over time, whereas our insterest is narrower, both in time and in scope. The general idea leans on the notion that ethics guides the pursuit of knowledge, that ideals and activities and "understandings of the self" are part of the knowledge formation in certain cases. This is certainly true for the arts although, as I have written about in other contexts, ethics in the arts may also deviate from a general ethics, but that is also a side track in the current discussion. 

The general idea that enables using ethics in this way is based on the fact that instruments have agency, and is further rooted in a relational ontology in which the instrument exists. The heritage process that we use [cite:@lundberg2015] implies that these objects have agency already, and that it is of importance.

The expansion that is proposed by Tresch and Dolan is that this agency also extends to the epistemic virtues that "have guided the pursuit of knowledge" (p. 282). When we engage with these instruments they by necessity partake in the development of knowledge, knowledge not limited to ideas and practices, but together the parts create a form of life where a relation between all aspects of this epistemic system take part. This is realted to Foucault whom, we shall remember, depicted an ontological difference between knowledge of the self and care of the self.

There is an obvious risk that the instrument is anthropomorphized in the process of considering its ethics. In the flat ontology that this view is promoting there is further a number of problems that arises, the most urgent perhaps, is that even though the instrument has agency, on the surface level it still lacks the will and the freedom that a human possesses. This objection is obviously situated in a Western dualist view of the world, but  traditional laws of causality enforce this view. but it may be useful to see the use of the instrument in (at least) two distinct but related articulations:
<11>
1. First, there is the object in an of itself. As such it has certain observable properties and even in this stage it exposes its interface and through it, its connections. In this cas literally. The fact that it is a musical instrument, that it is playable, that it belonged to a historic area, and so forth further informs this view. At this stage there is no obvious causality. There is a state but no process.
2. Second, in the situation when a musician engages with it, a different epistemic network emerges and a cybernetic connection becomes possible through the interface that the instrument exposes. Here there is a strong causality and the player has a control function of the signal flow. The causal relations in this network are contributing to both the knowledge in the system and to its output.

These two contexts are clearly completely different from each other and even if I am personally not uninterested in the first, the second, where time, feedback and interaction is introduced is where my primary interest is.
<12>
Whether or not either of these contexts provides evidence for an ethics of the instrument is a philosophical question difficult to resolve from a practical perspective. If instead the focus is put on the /usefulness/ of an ethical perspective of the instrument in the present investigation the question may be explored. In a network consisting of human and non-human objects such as a musician and a /Dataton/ module it would be fair to say that the ethics of the human extends to the instrument in a way that alters the possibilities of both musician and instrument, making the ethics of the situation useful to consider, artistically as well as from a heritage point of view.

The musician has to adhere to the materiality of the instrument but also to all other past and present connections and this activity is part of the care of the self. And as Drew Datlon points out in his paper "Towards an Object Oriented Ethics" [cite//t:@dalton2018] "rejecting the freedom of material objects [\ldots] does not imply their moral neutrality" [cite:@dalton2018]. However, removing the instrument from this active network neutralizes its ethical specificities, which I believe it cannot withhold by itself. The musician in this case is an ethical necessity and the object partakes in their ethical development.

To summarize, thinking about an ethics of instruments may be a useful theoretical construct in the process of organology. Following Foucault, however, this presents us with a possible conceptual problem that was always present. In this third mode of subjectification, ethics, the transformation into a subject happens through certain practices, technologies of the self, that depart from the individual will to care for oneself. These are rooted in an aesthetics of existence and will not function as a code exposed on an object from the outside. I believe that this is one of the reason that artistic practice is the proper method for investigating this ethics of practice and that it can provide us access to inportant knowledge about the instruments that transcends so called biographical information.

* Bibliography
# #+bibliographystyle: unsrtnat
#+print_bibliography: title: "Bilblio"

* Footnotes
[fn:2]A ne of the abgisionArtistic research is the formalization of this connection.

[fn:1]There are several artist-in-residence programs that have this explicit ambition, Xerox Parc [cite/p:@harris1999], Bell Labs [cite/p:@mccray2020], CERN
https://arts.cern/programme/artistic-residencies och NASA.
