#+cite_export: csl ~/Documents/articles/biblio/csl-styles/apa-7th.csl

#+LaTeX_HEADER: \usepackage[x11names]{xcolor}
#+LaTeX_HEADER: \hypersetup{linktoc = all, colorlinks = true, urlcolor = DodgerBlue4, citecolor = black, linkcolor = black}

#+begin_src emacs-lisp
   (set-window-margins (selected-window) 40 30)
    (setq line-spacing 0.7)
  #+end_src

  #+RESULTS:
  : 0.7

* Paper

This presentation is part of a research project the title of which is /Historically informed design of sound synthesis: A multidisciplinary, structured approach to the digitisation and exploration of electronic music heritage/. It engages with historically-informed sound synthesis through a collection of electronic instruments from the sixties and seventies collected by the Swedish Performing Arts Agency and archived by the Performing Arts Museum. In ths project instruments in the collection are explored artistically in order to reveal both past practices as well as discover new ones.

One of the concerns in this process is how this cultural heritage can be examined without conceptually dismantling the uniqueness of the properties of the actual instruments. The challenge is to identify and categorize the instruments in and of themselves, not as objects of nostalgia or as objects with which contemporary ideas and trends are exploited, but instead attempt to approach them with taking into account their cultural, social and political affordances. Based on the heritage research methodology we had chosen to promote the possibility of a historically informed performance with the instruments themselves, or re-enactments of them, the challenge remains to address existing biases within artist and engineering communities. In short:  how a set of obsolete electronic music instruments can be artistically explored as a cultural heritage without dismantling the uniqueness of the properties of the actual instruments.

The idea is to develop a historically informed performance practice, informed by previously, possibly, hidden features of the historic instrument. One of the instruments we have approached is the /Dataton 3000/, a modular synthesizer and audio mixer designed in Sweden in the 1970's. To attempt to understand the qualities the particularity of this instrument a wide range of parameters need to be considered related to the context in which it was originally created. Should this analysis not be successful there is a risk that the instrument's proper qualities are misunderstood, or that one ends up recreating what has already been done with it, or both.

In a wider scope of contemporary technologies the rate at which the development in general is progressing can turn objects sometimes less than a decade old incompatible with current systems. A hypothesis of this project is that by learning from early electronic instruments using the methods we have proposed it may be possible to better understand the complexities of what can be seen as media archeology.

In design history we can see how inventive design is incorporated into mainstream products and some simple forgotten. It is not unlikely that some stuff has been forgatten or supressed in the fast development of technology over the last half century. As Pinch and Trocco concludes about the synthesizer: "from a flexible variety of possible control configurations, the synthesizer eventually stabilised into a keyboard instrument" [cite:@Pinch1998]. In other words, over time the field is narrowed and standardization and market forces excludes those items that are not successful enough focussing on one particular functionality.

An organology, or even just a deepened understanding of a single instrument's meaning and position in a context, past or present, should really include not only its design or functionality. It should also take into account whatever agency it has or had including what kind of music was meant to be played on this instrument. A banal example to clarify this point would be the comparison between playing a cembalo sound on a synthesizer, and playing a real cembalo. Even though they may potentially be sonically indistinguishable they are not equatable. Not only because the latter is a historic instrument, but because they are utterly different from a cultural, aesthetic and material point of view. They may have similar agency (they are part of the same network and may play the same role in it), but as instruments they function in very different ways.

Needless to say, most musical instrument are associated with a style or cultural context even if some, such as the piano, have multiple associations. Equally superfluous to point out is that any musical instrument can be used in a wide range of situations completely independent of its origin. One extreme example is Swedish organist and pianist Karl Erik Welin who in his last piano recital in 1964 performs /Rendez-Vous 1963/ by Théodore E Libèr [cite:@wiggen1964] in which he dismantles a piano by means of a chain saw. Nevertheless, even this radical way of "playing" the piano relies on the instrument's history and the fact that a piano has a series of cultural connotations. With electronic instruments, in particular those that are not actively played anymore, finding out the particular associations the instrument provides may be a difficult task. Part of the reason here is the fact that there is a technological sphere with which the instrument is associated, apart from the purely musical. If the instrument is not actively used anymore the gap between these various contexts of the instrument may have grown quite significantly. One such example is the Dataton. ( the functionality of which is described in [cite/text/c:@Frisk2021a]. )

The study of Western music has somehow relied on a continuity that makes it possible to trace the developments that commonly takes time. Haydn left a mark on Beethoven that he developed and Mahler and Wagner continued and so forth. These particular kinds of trajectories, in this case specific but not unique to Western art music, is well documented and studied despite often stretching over centuries. The transformations increased in speed in the twentieth century though there are notable exceptions to be found such as Conlon Nancarrow and Harry Partch. With the introduction of electronic instruments that started in the late 19th century but gained new strength following the technological optimism and economic growth in the post war era the situation changed.

--------------

What is the difference between the traditional method for musical interpretation, rooted in Western musical practices (really art history) and so well described by Roland Barthes in the famous essay /The death of the Author/ [cite:@barthes68:death_of], where detailed biographical and historical knowledge about the composer is at the core inspirations in order to make a true interpretation of the work, and the excavation of the technological and cultural significances of a particular electronic musical instrument of the past? What is it we are looking for and what kind of knowledge may there be?

My primary interst in this project is not the objects in themselves. If it were we could easily say that there is nothing outside this piece of equipment to rudily paraphrase Derrida, there is only the object and what it tells us. Nor is it a artistically driven project where the end goal is the "work" but at the centre is the author. It is the possible interactions that are made possible by engaging in a play with the objects, a free play that does not have a purpose and no particular meaning at this point (it may well develop in other directions in the future). In this free play I can engage with certain questions in a way that would otherwise not have been possible.

The biggest difference between these latter two models is that the first has an origin (the composer) and the second is a network of relations that includes the originator but does not necessarily privilege them. This I would argue is not normative on the level of practice, it doesn't predict how one should do something, but rather it proposes how one may understand something one already does. The added value is that it opens up for an expanded ethical dimension of artistic parctices that value the larger context of, in this case obsolete instruments, and the relationships between the various agents involved in their past and current practices.

Similar to Foucault's notion of the /care of the self/ it is a particular development between self and others that is at the core, a method for developing an ethics through engaging with the self's relation to the self, a self that is rooted in "practices of freedom" [cite:@Foucault1997-2; p. 283]: "Freedom is the ontological condition of ethics. But ethics is the considered form that freedom takes when it is informed by reflection" [cite:@Foucault1997-2; p. 284].

I was inspired to develop this line of thought after our paper /Sounds of Future Past/ where  [cite:@Frisk2021a] the concept of an /ethics of instruments/ was explored as inspired from [cite/text:@Tresch2013]. That paper is not focused on the care of the self per se, but rather on some of the conditions for or elements of ethical relations related to the technologies of the self, the ontology, deontoology, ascetis and the teleology. The care of the self is rather the activity of which these elements are a part, and it is not a solipsitic activity that is focused on the body:

#+begin_quote
When you take care of the body you do not take care of the self. The self is not clothing, tools, or possessions; It is to be found in the principle that uses these tools, a principle not of the body of the soul. You have to worry about your soul--that is the principal activity for caring for yourself. The care of the self is the care of the activity and not the care of the soul-as-substance. [cite:@Foucault1997-2; p.231-2]
#+end_quote
The principle that uses the tools of artistic practice is in essence the aesthetics of the creative act: the practice itself.

My argument here is that what the notion of the care of the self opens up is a focus on the relations between the self and the things around me and that this process helps me understand myself as a subject. Not only that these relations exist and that they matter, but that they need to be good and respectful. This is what opens up for, in not an ethics of instruments, but a developed sense of ethics through a deep understanding for the relations.

This is in a way what I belive Tresch and Dolan are speaking of but it is actually a bit unclear. Their idea of an /ethics of instruments/ [cite:see ;@Frisk2021a] is leaning on the notion that the material aspects, mediations and the telos of an instrument can provide grounds for an analysis of its /ethics/. These criterias thay have borrowd from Foucault's /Technologies of the self/. It may appear odd to speak of ethics in relation to dead objects such as a musical instruments and it is possible to critique cusch a notion based on the fact that not all humans enjoy ethical rights (composre the feminsita argument againse post-humanism that not all humas have treated humanly).

This paper is an attempt to revisit the origin of this idea and critically examine it by briefly discussing its roots in Foucault's /History of Sexuality part 2/ [cite:@foucault2012] and related theories on ethics. I should say that a full discussion of this would take much longer than what we have here, so this should be seen as a scratch on the surface. It should also be noted that Tresch and Dolan's main interest here is to use their framework to study historical instruments, both musical and scinetific, over time, whereas our insterest is narrower, both in time and in scope. The general idea leans on the notion that ethics guides the pursuit of knowledge, that ideals and activities and "understandings of the self" are part of the knowledge formation in certain cases. This is certainly true for the arts although, as I have written about in other contexts, ethics in the arts may also deviate from a general ethics, but that is also a side track in the current discussion. 

The general idea that enables using ethics in this way is based on the fact that instruments have agency, and is further rooted in a relational ontology in which the instrument exists. The heritage process that we use [cite:@lundberg2015] implies that these objects have agency already, and that it is of importance.

The expansion that is proposed by Tresch and Dolan is that this agency also extends to the epistemic virtues that "have guided the pursuit of knowledge" (p. 282). When we engage with these instruments they by necessity partake in the development of knowledge, knowledge not limited to ideas and practices, but together the parts create a form of life where a relation between all aspects of this epistemic system take part. This is realted to Foucault whom, we shall remember, depicted an ontological difference between knowledge of the self and care of the self. The latter is, he claims, a condition for the latter.

The question approached in this paper is if the concept of "ethical specificities" [cite:@Tresch2013;p. 298] of instruments can contribute to knowledge about arrangements of historic electronic instruments and their players without blurring the conceptual differences between the actors involved and hence also the properties of the instrument.

There is an obvious risk that the instrument is anthropomorphized in the process of considering its ethics. In the flat ontology that this view is promoting there is further a number of problems that arises, the most urgent perhaps, is that even though the instrument has agency, on the surface level it still lacks the will and the freedom that a human possesses. This objection is obviously situated in a Western dualist view of the world, but  traditional laws of causality enforce this view. but it may be useful to see the use of the instrument in (at least) two distinct but related articulations:

1. First, there is the object in an of itself. As such it has certain observable properties and even in this stage it exposes its interface and through it, its connections. In this cas literally. The fact that it is a musical instrument, that it is playable, that it belonged to a historic area, and so forth further informs this view. At this stage there is no obvious causality. There is a state but no process.
2. Second, in the situation when a musician engages with it, a different epistemic network emerges and a cybernetic connection becomes possible through the interface that the instrument exposes. Here there is a strong causality and the player has a control function of the signal flow. The causal relations in this network are contributing to both the knowledge in the system and to its output.

These two contexts are clearly completely different from each other and even if I am personally not uninterested in the first, the second, where time, feedback and interaction is introduced is where my primary interest is.

Whether or not either of these contexts provides evidence for an ethics of the instrument is a philosophical question difficult to resolve from a practical perspective. If instead the focus is put on the /usefulness/ of an ethical perspective of the instrument in the present investigation the query may be approached. In a network consisting of human and non-human objects such as a musician and a /Dataton/ module it would be fair to say that the ethics of the human extends to the instrument in a way that alters the possibilities of both musician and instrument, making the ethics of the situation useful to consider, artistically as well as from a heritage point of view. The musician has to adhere to the materiality of the instrument, its mediations and telos. As Drew Datlon points out in his paper "Towards an Object Oriented Ethics" [cite//t:@dalton2018] "rejecting the freedom of material objects [\ldots] does not imply their moral neutrality" [cite:@dalton2018]. However, removing the instrument from this network neutralizes its ethical specificities making the player an ethical necessity. Returning to Foucault, however, this presents a possible conceptual problem and one that was always present. The modes of subjectification that he promotes are rooted in his aesthetics of existence and departs thereby necessarily from the private sphere and will not function as a code exposed on an object from the outside.

* Call
 * On what grounds can obsolete technologies for music production and performance become desirable again in an era of  
  high-tech, across different genres, and in both the professional and amateur spheres?  
 * In what ways do vintage materialities and their technical affordances mediate or challenge present-day creative and  
  performative practices?  
 * How do vintage materialities respond to cultures, discourses, politics, and economies of, among others, retro style,  
  nostalgia, afro- and retrofuturism, and lo-fi?  

  Bringing old instruments to life in artistic practice happens all the time in various contexts.
  The heritage process that we use is designed to collect and systematize cultural practices, and in our case this implies that the object at hand has agency, and that it is of importance.
  
* Stuff

One of the challenges in this process is to identify and categorize the instrument in and of themselves, not as objects of nostalgia or as objects with which contemporary ideas and trends are exploited, but instead attempt to learn from them departing from what they meant in the cultural, social and political conditions of their own time. Not because this method should be better than any other, but because we are interested in what may have been lost in the transformation of electronic music from an experimental practice to one with also a strong commercial dimension. Based on the heritage research methodology [cite:@lundberg2015] that we have chosen we explore the possibility of a historically informed performance practice and explore this as a vehicle for artistic expression informed by possibly previously hidden features of the historic instrument. One of the instruments we have approached in this way is the /Dataton 3000/, a modular synthesizer and audio mixer designed in Sweden in the 1970's. To attempt to understand the qualities and the particularity of this instrument a wide range of parameters need to be considered commonly related to the context in which it was originally created. Should this analysis not be successful there is a risk that either the instrument's proper affordances are misunderstood, or that one ends up recreating what has already been done with it, or both.


What enables using ethics in this way is based on the fact that instruments have agency and is further rooted in a relational ontology in which the instrument are a part. The heritage process that we already use implies that these objects have agency, and that it is of importance.



The question approached in this paper is if the concept of "ethical specificities" [cite:@Tresch2013;p. 298] of instruments can contribute to knowledge about arrangements of historic electronic instruments and their players without blurring the conceptual differences between the actors involved.



** Bibliography
# #+bibliographystyle: unsrtnat
#+print_bibliography: title: "Bilblio"


* Introduction

In the research project /Historically informed design of sound synthesis: A multidisciplinary, structured approach to the digitisation and exploration of electronic music heritage/ we have discussed [cite/text/c:@Tresch2013]'s notion of an /ethics of instruments/ [cite:see ;@Frisk2021a]. This concept appeared as a possible and convenient resolution to some of the issues we had had with structuring a collection of old electronic instruments in a meaningful way. Based on the heritage research methodology we had chosen to promote the possibility of a historically informed performance with the instruments themselves, or re-enactments of them, the challenge remains to address existing biases within artist and engineering communities. To attempt to understand the qualities and affordances of a piece of music technological  instrument such as the /Dataton/, as was the goal in the workshops described in the article cited above, a wide range of parameters need to be considered related to the context in which it was originally created and the agency it originally possessed. Should this analysis not be successful there is a risk that either the instrument's proper affordances are misunderstood, or that one ends up recreating what has already been done with it, or both.



At first it may appear odd to speak of ethics in relation to dead objects such as a musical instruments, and this paper is an attempt to revisit the origin of this idea and critically examine it as well as briefly discussing its roots in Foucault's /History of Sexuality part 2/ [cite:@foucault2012]. As the general idea of using ethics in this way is based on the notion of agency, the discussion is further extended to contemporary musical instruments and AI enforced technology. Within the sphere of what may be referred to as intelligent instruments the notion of the agency of the instrument becomes more obvious: the voice of the instrument can appear to be independent, and sometimes in contrast, to that of its user.

[cite:@Rao20@11]
* The problem
Needless to say, most musical instrument are associated with a style or cultural context even if some, such as the piano, have multiple associations. Equally superfluous to point out is that any musical instrument can be used in a wide range of situations completely independent of its origin. One extreme example is Swedish organist and pianist Karl Erik Welin who in his last piano recital in 1964 performs /Rendez-Vous 1963/ by Théodore E Libèr [cite:@wiggen1964] in which he dismantles a piano by means of a chain saw. Nevertheless, even this radical way of "playing" the piano relies on the instrument's history and the fact that a piano has a series of cultural connotations. With electronic instruments, in particular those that are not actively played anymore, finding out the particular associations the instrument provides may be a difficult task. Part of the reason here is the fact that there is a technological sphere with which the instrument is associated, apart from the purely musical. If the instrument is not actively used anymore the gap between these various contexts of the instrument may have grown quite significantly. One such example is the Dataton, the functionality of which is described in [cite/text/c:@Frisk2021a]. 

The particular situation that will be examined in this paper, however, is the case of electronic instruments that are. . There is a twofold ambition with this work.  

The study of Western music has somehow relied on a continuity that makes it possible to trace the developments that commonly takes time. Haydn left a mark on Beethoven that he developed and Mahler and Wagner continued and so forth. These particular kinds of trajectories, in this case specific but not unique to Western art music, is well documented and studied despite often stretching over centuries. The transformations increased in speed in the twentieth century though there are notable exceptions to be found such as Conlon Nancarrow and Harry Partch. With the introduction of electronic instruments that started in the late 19th century but gained new strength following the technological optimism and economic growth in the post war era the situation changed.

[cite/text/c:@Tresch2013] point to the consequential and interesting "re-mediation of scientific instruments" (p. 280) into  musical instruments:

#+begin_quote
The fact that the arts and the sciences now share so many aspects of their technical
infrastructure results in isomorphic logics, shared working strategies, and common
imaginaries between them. It has also made it easier to recognize earlier conver-
gences between the fields and to find in them compelling anticipations of our own
moment, leading to reflection on the ways in which instruments have facilitated in-
tersections between the fine arts and the sciences, as well as the different ways they
have been understood in relation to humans. [cite//c:@Tresch2013;p. 280]
#+end_quote

By this Tresch and Dolan propose the need for a historical perspective on the changes leading up to the current state "by means of a comparative study of instruments in different ﬁeld" [cite:@Tresch2013;p. 281]. Without going into the results of this study the development described here as an alignment of two fields, the scientific and the artistic appears as a useful way of structuring our understanding of both and new electronic instruments. There are some noteable examples of how the arts has pushed for a hardware or software development, but it is likely that the opposite, the arts is finding new applications in scientifically developed hardware and software, is more common. Tresch and Dolan describes the two fields as complementary where the artist's intentionality and expressivity creates an outward pointing movement whereas the sciences can be seen to do the opposite in its attempts to describe the outside world. It is possible to envision a closed loop in which scienteific methods are used to study the ouput of the artist leading to new scientific inventions. Though such a loop would be difficult to maintain, there is no doubt that the current development has led to the possibility of a new kind of exchange between science and the arts.[fn:2] There are many examples where artists either stages scientific inventions or, more importantly, contributes to a deepened understanding of scientific explorations[fn:1]

The conceptual compatibility between a cembalo, a Hammerklavier and a modern piano can be found in some electronic instruments but is commonly completely absent.

* Footnotes
[fn:2]A ne of the abgisionArtistic research is the formalization of this connection.

[fn:1]There are several artist-in-residence programs that have this explicit ambition, Xerox Parc [cite/p:@harris1999], Bell Labs [cite/p:@mccray2020], CERN
https://arts.cern/programme/artistic-residencies och NASA.
