#+cite_export: csl ~/Documents/articles/biblio/csl-styles/apa-7th.csl

#+LaTeX_HEADER: \usepackage[x11names]{xcolor}
#+LaTeX_HEADER: \hypersetup{linktoc = all, colorlinks = true, urlcolor = DodgerBlue4, citecolor = black, linkcolor = black}

#+begin_src emacs-lisp
   (set-window-margins (selected-window) 50 50)
    (setq line-spacing 0.5)
  #+end_src

  #+RESULTS:
  : 0.5

* Call
 * On what grounds can obsolete technologies for music production and performance become desirable again in an era of  
  high-tech, across different genres, and in both the professional and amateur spheres?  
 * In what ways do vintage materialities and their technical affordances mediate or challenge present-day creative and  
  performative practices?  
 * How do vintage materialities respond to cultures, discourses, politics, and economies of, among others, retro style,  
  nostalgia, afro- and retrofuturism, and lo-fi?  

  Bringing old instruments to life in artistic practice happens all the time in various contexts.
  The heritage process that we use is designed to collect and systematize cultural practices, and in our case this implies that the object at hand has agency, and that it is of importance.
  
* Abstract
In the research project /Historically informed design of sound synthesis: A multidisciplinary, structured approach to the digitisation and exploration of electronic music heritage/ (HID) one of the questions concerns how a set of obsolete electronic music instruments can be artistically explored as a cultural heritage without dismantling the uniqueness of the properties of the actual instruments. 

One of the challenges in this process is to identify and categorize the instrument in and of itself, not as an object of nostalgia or as an object with which contemporary ideas and trends are exploited, but instead attempt to do it as closely as possible to the cultural, social and political affordances at its time. Based on the heritage research methodology  [cite:@lundberg2015] chosen the idea is to explore the possibility of a historically informed performance practice and explore this as a vehicle for artistic expression informed by possibly previously hidden features of the historic instrument. One of the instruments we have approached is the /Dataton 3000/, a modular synthesizer and audio mixer designed in Sweden in the 1970's. To attempt to understand the qualities the particularity of this instrument a wide range of parameters need to be considered related to the context in which it was originally created. Should this analysis not be successful there is a risk that either the instrument's proper affordances are misunderstood, or that one ends up recreating what has already been done with it, or both.
 
The challenge found a preliminary solution in [cite/text/c:@Tresch2013]'s notion of an /ethics of instruments/ [cite:see ;@Frisk2021a] leaning on the notion that the material aspects, mediations and the telos of an instrument can provide grounds for an analysis of its /ethics/. It may appear odd to speak of ethics in relation to dead objects such as a musical instruments, and this paper is an attempt to revisit the origin of this idea and critically examine it by briefly discussing its roots in Foucault's /History of Sexuality part 2/ [cite:@foucault2012] and related theories on ethics. The general idea that enables using ethics in this way is based on the fact that instruments have agency, and is further rooted in a relational ontology in which the instrument exists. The heritage process that we use implies that these objects have agency, and that it is of importance. The question approached in this paper is if the concept of "ethical specificities" [cite:@Tresch2013;p. 298] of instruments can contribute to knowledge about arrangements of historic electronic instruments and their players without blurring the conceptual differences between the actors involved.

There is an obvious risk that the instrument is anthropomorphized in the process of considering its ethics. In the flat ontology that this view is promoting there is further a number of problems that arises, the most urgent perhaps, is that even though the instrument has agency, on the surface level it still lacks the will and the freedom that a human possesses. This objection is clearly situated in a Western dualist view of the world. Traditional laws of causality enforce this view, but it may be useful to see the use of the instrument in (at least) two distinct but related articulations. First, there is the object in an of itself. As such it has certain observable properties and even in this stage it exposes its interface and through it its connections. The fact that it is a musical instrument, that it is playable, that it belonged to a historic area, and so forth. At this stage there is no obvious causality. Second, in the situation when a musician engages with it a different epistemic network emerges and a cybernetic connection emerges through the interface that the instrument exposes. The causal relations in this network are contributing to both the knowledge in the system and to its output.

Whether or not either of these contexts provides evidence for an ethics of the instrument is a philosophical question difficult to resolve from a prctical perspective. If instead the focus is put on the /usefulness/ of an ethical perspective of the instrument in the present investigation the query may be approached. In a network consisting of human and non-human objects such as a musician and a /Dataton/ module it would be fair to say that the ethics of the human extends to instrument in a way that alters the possibilities of both musician and instrument, making the ethics of the situation useful to consider, artistically as well as from a heritage point of view. The musician has to adhere to the materiality of the instrument, its mediations and telos. As [cite//t:@dalton2018] concludes, "rejecting the freedom of material objects [\ldots] does not imply their moral neutrality" [cite:@dalton2018]. However, removing the instrument from this network neutralizes its ethical specificities making the player an ethical necessity. Returning to Foucault, however, this presents a possible conceptual problem and one that was always present. The modes of subjectification that he promotes are rooted in his aesthetics of existence and departs thereby necessarily from the private sphere and will not function as a code exposed on an object from the outside.

** Bibliography
# #+bibliographystyle: unsrtnat
#+print_bibliography: title: "Bilblio"


* Introduction

In the research project /Historically informed design of sound synthesis: A multidisciplinary, structured approach to the digitisation and exploration of electronic music heritage/ we have discussed [cite/text/c:@Tresch2013]'s notion of an /ethics of instruments/ [cite:see ;@Frisk2021a]. This concept appeared as a possible and convenient resolution to some of the issues we had had with structuring a collection of old electronic instruments in a meaningful way. Based on the heritage research methodology we had chosen to promote the possibility of a historically informed performance with the instruments themselves, or re-enactments of them, the challenge remains to address existing biases within artist and engineering communities. To attempt to understand the qualities and affordances of a piece of music technological  instrument such as the /Dataton/, as was the goal in the workshops described in the article cited above, a wide range of parameters need to be considered related to the context in which it was originally created and the agency it originally possessed. Should this analysis not be successful there is a risk that either the instrument's proper affordances are misunderstood, or that one ends up recreating what has already been done with it, or both.

An organology, or even just a deepened understanding of a single instrument's meaning and position in a context, past or present, should really include not only its design or functionality. It should also take into account whatever agency it has or had including what kind of music was meant to be played on this instrument. A banal example to clarify this point would be the comparison between playing a cembalo sound on a synthesizer, and playing a real cembalo. Even though they may potentially be sonically indistinguishable they are not equatable. Not only because the latter is a historic instrument, but because they are utterly different from a cultural, aesthetic and material point of view. They may have similar agency (they are part of the same network and may play the same role in it), but as instruments they function in very different ways.

At first it may appear odd to speak of ethics in relation to dead objects such as a musical instruments, and this paper is an attempt to revisit the origin of this idea and critically examine it as well as briefly discussing its roots in Foucault's /History of Sexuality part 2/ [cite:@foucault2012]. As the general idea of using ethics in this way is based on the notion of agency, the discussion is further extended to contemporary musical instruments and AI enforced technology. Within the sphere of what may be referred to as intelligent instruments the notion of the agency of the instrument becomes more obvious: the voice of the instrument can appear to be independent, and sometimes in contrast, to that of its user.

[cite:@Rao20@11]
* The problem
Needless to say, most musical instrument are associated with a style or cultural context even if some, such as the piano, have multiple associations. Equally superfluous to point out is that any musical instrument can be used in a wide range of situations completely independent of its origin. One extreme example is Swedish organist and pianist Karl Erik Welin who in his last piano recital in 1964 performs /Rendez-Vous 1963/ by Théodore E Libèr [cite:@wiggen1964] in which he dismantles a piano by means of a chain saw. Nevertheless, even this radical way of "playing" the piano relies on the instrument's history and the fact that a piano has a series of cultural connotations. With electronic instruments, in particular those that are not actively played anymore, finding out the particular associations the instrument provides may be a difficult task. Part of the reason here is the fact that there is a technological sphere with which the instrument is associated, apart from the purely musical. If the instrument is not actively used anymore the gap between these various contexts of the instrument may have grown quite significantly. One such example is the Dataton, the functionality of which is described in [cite/text/c:@Frisk2021a]. 

The particular situation that will be examined in this paper, however, is the case of electronic instruments that are. . There is a twofold ambition with this work.  

The study of Western music has somehow relied on a continuity that makes it possible to trace the developments that commonly takes time. Haydn left a mark on Beethoven that he developed and Mahler and Wagner continued and so forth. These particular kinds of trajectories, in this case specific but not unique to Western art music, is well documented and studied despite often stretching over centuries. The transformations increased in speed in the twentieth century though there are notable exceptions to be found such as Conlon Nancarrow and Harry Partch.  With the introduction of electronic instruments that started in the late 19th century but gained new strength following the technological optimism and economic growth in the post war era the situation changed. [cite/text/c:@Tresch2013] point to the consequential and interesting "re-mediation of scientific instruments" (p. 280) into  musical instruments:

#+begin_quote
The fact that the arts and the sciences now share so many aspects of their technical
infrastructure results in isomorphic logics, shared working strategies, and common
imaginaries between them. It has also made it easier to recognize earlier conver-
gences between the fields and to find in them compelling anticipations of our own
moment, leading to reflection on the ways in which instruments have facilitated in-
tersections between the fine arts and the sciences, as well as the different ways they
have been understood in relation to humans. [cite//c:@Tresch2013;p. 280]
#+end_quote

By this Tresch and Dolan propose the need for a historical perspective on the changes leading up to the current state "by means of a comparative study of instruments in different ﬁeld" [cite:@Tresch2013;p. 281]. Without going into the results of this study the development described here as an alignment of two fields, the scientific and the artistic appears as a useful way of structuring our understanding of both and new electronic instruments. There are some noteable examples of how the arts has pushed for a hardware or software development, but it is likely that the opposite, the arts is finding new applications in scientifically developed hardware and software, is more common. Tresch and Dolan describes the two fields as complementary where the artist's intentionality and expressivity creates an outward pointing movement whereas the sciences can be seen to do the opposite in its attempts to describe the outside world. It is possible to envision a closed loop in which scienteific methods are used to study the ouput of the artist leading to new scientific inventions. Though such a loop would be difficult to maintain, there is no doubt that the current development has led to the possibility of a new kind of exchange between science and the arts.[fn:2] There are many examples where artists either stages scientific inventions or, more importantly, contributes to a deepened understanding of scientific explorations[fn:1]

The conceptual compatibility between a cembalo, a Hammerklavier and a modern piano can be found in some electronic instruments but is commonly completely absent.

* Footnotes
[fn:2]A ne of the abgisionArtistic research is the formalization of this connection.

[fn:1]There are several artist-in-residence programs that have this explicit ambition, Xerox Parc [cite/p:@harris1999], Bell Labs [cite/p:@mccray2020], CERN
https://arts.cern/programme/artistic-residencies och NASA.
