# Created 2019-12-26 Thu 19:11
#+TITLE: Före eller efter: om konstnärlig erfarenhet och kunskap i konstnärlig praktik
#+AUTHOR: Henrik Frisk
#+LATEX_HEADER: \usepackage[lf]{ebgaramond}
#+LATEX_HEADER: \usepackage{sectsty}
#+LATEX_HEADER: \allsectionsfont{\sf}
#+LATEX_HEADER: \usepackage[style=verbose-ibid, bibstyle=authoryear, backend=biber, hyperref=false]{biblatex}
#+LATEX_HEADER: \bibliography{/home/henrikfr/Dropbox/Documents/articles/biblio/bibliography.bib}
#+LATEX_HEADER: \renewcommand*{\nameyeardelim}{\space}%
#+LATEX_HEADER: \renewcommand{\postnotedelim}{: }%

* Recension

  
Avhandlingen /Before Sound: Transversal Processes in Site-Specific
Sonic Practice/ av Åsa Stjerna "utforskar konstnärlig transformation i
platsspecifik sonisk praktik" [fn:12]. Denna praktik involverar en rad
olika discipliner, är transformativ till sin natur, och utspelar sig i
det offentliga rummet. Detta skapar i sin tur sammanhang och
situationer som kräver förhandling och omförhandling i den konstnärlig
praktiken och den visar därmed på komplexiteten och sårbarheten som
finns i all slags aktivitet. Fyra konstnärliga processer beskrivs
detaljerat i avhandlingen och de processer som bidrar till det som rör
avhandlingens centrala frågeställning: själva omförhandlingen och
transformationen av platsen, utforskas. Detta diskuteras framförallt
utifrån Deleuze och Félix Guattaris teorier om transversala
processer. Som framgår av undertiteln är just begreppet transversal
centralt i undersökningen. Det ska här ses som något som innefattar
"en förståelse av konstnärlig produktion som etablerandet av
relationer mellan komponenter i ömsesidig kontinuerlig process av
tillblivelse". [fn:13] Eller, i Stjernas egen engelska formulering:

#+BEGIN_QUOTE
  "Transversal" here refers to an understanding of artistic production
  as the creation of affective, immanent relations between components in
  mutual continuous processes of becoming. These relations span be-
  tween material and discursive, and human and non-human, compo- nents.
  In exploring the acts performed by the artist within transversal
  processes, the aim is to develop explorative approaches and concepts
  that might contribute to a more complex understanding of the pro-
  cesses at work in site-specific sonic practice.
#+END_QUOTE

Deleuze har varit en populär referens för konstnärlig forskning redan
från början. Det finns onekligen en intressant korrelation mellan det
poststrukturala och postmoderna tänkandet som ger mening åt det ibalnd
instrospektiva tänkandet genom praktik som konstnärlig forskning står
för. I Sverige har tonsättare som Anders Hultqvist på
Göteborgs universitet haft ett nyligen avslutat VR-projekt som utgick från Deleuze
teoribildning[fn:1], likson improvisatören Klas Nevrin (VR-projektet /Musik i Oordning/
med hemvist på Kungliga Musikhögskolan). Nästan parallellt
med Åsa Stjerna gjorde tonsättaren Fredrik Hedelin sin avhandling på
Luleå Universitet i vilken han utför en analys av tre av sina egna
solokonserter i vilken begreppet ritornell blir en kontaktyta mellan
musik och Deleuze filosofi.[fn:2] I ett projekt tillsammans med Marcel
Cobussen och Bart Weijland gjorde vi ett försök att diskutera /The
Field of Musical Improvisation/ (FMI) utifrån komplexitetsteori och
Deleuze och Guattari på ett sätt som relaterar till den
begreppsapparat som Stjerna använder:

#+BEGIN_QUOTE
  Assemblages are wholes whose properties emerge from the interactions
  between parts, for example, interpersonal networks such as can be
  found in the FMI. In other words, assemblages cannot be defined by nor
  do they consist of the properties of their constituting parts. Think
  ecology instead of reductionism.[fn:3]
#+END_QUOTE

Det som Stjerna refererar till som de transversala processerna och som
hon använder för att visa på hur den konstnärliga praktiken är
rhizomatisk till sin natur finner en hel del resonans i annan
konstnärlig forskning, även den som inte explicit hänvisar till Deleuze.
Ambitionen att bryta ner de politiska och sociala hierarkier som i
århundraden präglat musiklivet och som fått fart i och med
institutionaliseringen och till viss del professionaliseringen av
musiklivet[fn:4] har diskuterats i många projekt och är något jag själv
har intresserat mig mycket för. I en rad studier från 2006 tittade vi på
hur agensen mellan tonsättare, musiker och teknologi påverkade och till
och med hade en avgörande betydelse på de konstnärliga
tillvägagångssätten.[fn:5] En stor del av mitt fokus i min avhandling
från 2008[fn:6] tar sin avstamp i erfarenheterna från ljudinstallationen
/etherSound/ och idéen om ickekontroll och perpetuell rörelse vilket på
vissa sätt ligger nära Stjernas icke-autonoma upphovsperson och
transversala praktik. Inget av dessa exempel tar avstamp i Deleuze utan
i min avhandling var det istället en annan postmodernist, dystopikern
Jean Baudrillard, som utgjorde en del av teorin. I de tidigare studierna
från 2006 var utgångspunkten snarare strukturalism och semiotik, även om
vi relativt snabbt sträckte oss förbi denna startpunkt. Men det finns
även reflektioner och associationer till angränsande fält som kanske vid
första anblick inte är relaterade. Doktoranden och konsertpianisten
Franciska Skoogh pekar på hur MPA (Music Performance Anxiety) ofta ses
som ett individuellt problem, något musikern själv får kompensera för,
när det i själva verket finns en rad strukturella faktorer som påverkar
situationen som konservatorietraditionen, som de kommersiella aktörerna
och den extrema kommodifieringen av musiken.[fn:7] Samtidigt är det
viktigt att påminna sig om att /Before Sound/ inte framförallt är ett
musikprojekt utan snarare ett konstprojekt och därför har en delvis
annan ingång.

Som tidigare nämnts kallar Stjerna sina metoder för /explorative
approaches/. Givet hur nära kopplade de är till teorin är det sannolikt
en klok strategi, även om det också kan skapa förvirring. De tre
övergripande utforskande tillvägagångssätten /att kartlägga de affektiva
linjerna/, /att skapa nya sammankopplingar/ samt /att bli icke-autonom/
(som diskuterades en del i förra avsnittet). Denna nära koppling mellan
teori och metod gör det på ett sätt enklare att diskutera utmaningarna i
projektet. Om vi fortsätter utifrån linjen att Deleuze och Guattaris
filosofi framförallt sysslar med begreppskapande (skapande av koncept),
är det inte långsökt att tänka sig att deras verktyg användas för att
skapa nödvändiga begrepp för att förstå och analysera den konstnärliga
praktiken. Frågan är om resultatet av den processen först och främst är
kunskap om konst eller om det är filosofi, men oavsett svaret så kan
resultatet ha validitet som forskning. En annan utmaning till följd av
denna användning av metod är att det av uppenbara skäl helt enkelt kan
uppstå en sammanblandning mellan teori, metod och resultat med utfallet
att den konceptuella stabiliteten blir lidande. Men samtidigt, som också
diskuterades ovan, är detta i realiteten ett sätt att hantera metod och
teori i konstnärlig forskning. Jag ska återkomma till det.

I Stjernas fall uppstår inte dessa problem, delvis tack vare att hon
handskas varsamt och ytterst konsekvent med begreppen. Dessutom ska man
inte glömma att teorin i /Before Sound/ i stor utsträckning relateras
till den kontextualisering och positionering som görs i kapitel två:
/Contextualisation--Artistic Strategies within the Field/. Denna typ av
situering är något som ibland förbises i konstnärliga avhandlingar
vilket kan få till följd att de konstnärliga resultaten blir svåra att
bedöma: Om det är oklart inom vilket konstnärligt fält
konstnären/forskaren rör sig kan det vara svårt att korrelera de
konstnärliga resultaten till konstfältet i stort. Samma problem uppstår
om fältet som beskrivs är alltför disparat eller alltomfattande, eller
alltför smalt. Eller, om fältet som beskrivs är ett annat än ämnet för
avhandlingen eller forskningen. Det finns flera anledningar till att det
tagit lång tid för konstnärlig forskning att hitta rätt på detta område
men några uppenbara skäl är:

1. Bristen på etablerade modeller för att referera till alla typer av
   konstverk och svårigheten beskriva dem på ett sätt som bidrar till
   att skapa en bild av ett fält är påtaglig. Ett sätt runt detta är att
   göra som Stjerna gör och referera till en (vetenskaplig) studie av
   verken i fråga.[fn:8] Detta är i grund och botten ett beprövat sätt
   att såväl inkludera den större diskursen om ett verks validitet för
   ett specifikt sammanhang och kan skapa trovärdighet i argumentationen
   när möjligheten att lyssna och uppleva, om än genom en dokumentation,
   också erbjuds. En eventuell baksida med denna metod är att
   argumentationen kan göra sig beroende av en annan disciplin, som
   filosofi, eller musikvetenskap i det här fallet, eller rent av
   resultera i en i huvudsak vetenskaplig undersökning. Detta är i sig
   inte ett problem, jag menar att konstnärlig forskning är i grunden
   tvärvetenskaplig, men det är samtidigt viktigt att det
   tvärvetenskapliga hanteras på ett sätt så att det understödjer, inte
   raserar, den konstnärliga undersökningen.

2. Det är tydligt att man i konstnärliga avhandlingar har lättare att
   referera till etablerade verk och studier av verk. Men utan en intern
   diskussion, och utan att varje avhandling också relaterar till det
   fält som är i dess omedelbara närhet, såsom samtida konstnärlig
   forskning eller konstnärlig praktik, riskerar studiens validitet att
   begränsas. Stjerna går elegant runt detta genom att med omsorg
   beskriva verktygen, tillvägagånssätten och det teoretiska
   perspektivet hon använder vilket skapar en tydlighet. Men jag skulle
   vilja gå så långt som att säga att den största utmaningen vi har för
   konstnärlig forskning idag är just bristen av ett befintligt
   forskningsfält där den konstnärliga undersökningen står i centrum.
   Detta kan byggas genom att doktorander samarbetar och refererar till
   varandras arbeten, gärna kritiskt men alltid noggrant, och genom att
   större forskningmiljöer skapas. Ett nytt samarbete mellan Kungliga
   Musikhögskolan och Musikhögskolan i Piteå, Luleå Tekniska
   Universitet, samlar mer än tio doktorander, en PostDoc och flera
   seniora forskare i vad vi kallar lab tre gånger per år. Det är en
   början men vi behöver fler samarbeten där utgångspunkten är
   diversitet, samarbete och kritisk granskning. 2018 skrev vi i
   programförklaringen till samarbetet mellan LTU och KMH att vi vill
   ytterligare arbeta för att skapa:

   #+BEGIN_QUOTE
     [...] former för kunskapsbyggande i konstnärlig forskning som är
     baserat på konstnärlig kunskap. Även teoretiskt drivna resonemang
     kan här ta sin utgångspunkt i den konstnärliga praktiken varför
     själva praktiken är central i seminarier och labsessioner. De
     gemensamma seminarier som vi planerar i Piteå och Stockholm ska ta
     formen av ett laboratorium som alla gemensamt ska bidra till den
     fortsatta utvecklingen av detta format. En viktig förutsättning är
     att skapa ett arbetsklimat som bygger på förtroende av samma slag
     som uppstår i konstnärliga samarbeten, och som därigenom skapar
     förutsättningar för en kritisk dialog som kan gå på djupet in i
     konstnärliga processer.[fn:9]
   #+END_QUOTE

   Idén är att sätta den konstnärliga praktiken i centrum i en skyddad
   seminariemiljö som erbjuder möjligheten att experimentera. I detta
   initiativ hoppas vi att det ska bli möjligt att i större utsträckning
   begreppsliggöra praktiken och undersökningen vilket samtidigt kan
   underlätta att arbetena också diskuteras, kritsikt granskas av
   jämlikar, samt att resultaten, såväl som metod och teori, delas.

3. Även det större fältet av konstnärlig praktik, utanför konstnärlig
   forskning, måste vara möjligt att referera till. Musikhögskolan i
   Piteå och konstnärliga fakulteten vid Göteborgs universitet har
   etablerade metoder för att registrera konstnärliga verk vilket gör
   det enkelt att hänvisa till dessa, och KMH och Musikhögskolan i
   Ingesund, Karlstads universitet, har påbörjat ett arbete som
   förhoppningsvis leder till att vi bidrar till ett fält som inkluderar
   akademien och skapar förutsättningar för forskningsanknuten
   undervisning. Om möjligheten för att publicera konstnärliga arbeten i
   forskningsdatabaser erbjuds kommer det uppstå en ackumulativ effekt
   som kan få mycket stor betydelse för hur konst som kunskapsfält kan
   utvecklas.

4. Utan tydliga begrepp för konstnärlig forskning och konstnärlig
   praktik kan det vara svårt att på ett öppet sätt beskriva det
   konstnärliga fält som är det centrala för studien, utan att samtidigt
   bli låst av det. Att använda filosofi, som tidigare diskuterats,
   eller andra discipliner är här en möjlighet som samtidigt kan bidra
   till en breddad förståelse för detta forskningsfält. Dock är det
   nödvändigt att även begreppen växer fram i gemensamma miljöer där
   resultat och diskussioner delas.

Det ackumulativa kunskapsbyggandet som kan bli resultatet av en stabil
forskningsmiljö där forskare på olika sätt bygger vidare på varandras
arbeten på ett genomskinligt och konsekvent sätt är en förutsättning för
att konstnärlig forskning ska få respekt och förtroende som ett
självständigt kunskapsfält, men också för att den interna
kunskapsutvecklingen ska ta fart. Detta sker naturligtvis redan idag i
viss utsträckning, men här finns ett stort utrymme för utveckling. I ett
nytt fält kan det vara naturligt att man framför allt vänder sig till
teoribildning utanför sitt eget fält, men nu är det viktigt att i ännu
större utsträckning rikta blicken också mot annan konstnärlig forskning
för att utvärdera och bygga vidare på dess teori, metod och
resultat.[fn:10] Jag menar att konstnärlig forskning inte bara är
tvärvetenskaplig utan också är multidisciplinär till sin natur, det vill
säga att den i vissa fall rent av är beroende av andra discipliner än
det rent konstnärliga för att kunskapen ska kunna kommuniceras såväl i
som utanför dess egen domän.[fn:11] Symptomatiskt beskriver även Stjerna
arbete med ljudinstallationer som en multidisciplinär praktik, och
själva avhandlingen i sin helthet kan även den ses som multidisciplinär.
Det är dock viktigt att förstå den politisk dimension som det
tvärdisciplinära pekar mot. Samverkan är ett ledord för samtliga
universitet och högskolor idag och tvärvetenskap har i vissa fall blivit
ett neoliberalt självändamål. Detta gagnar inte alltid utvecklingen av
ett forskningsfält där behoven också behöver komma inifrån, snarare än
att de läggs på utifrån.

I Stjernas avhandling harmonierar det sätt hon bygger upp det teoretiska
och metodologiska ramverket i stor utsträckning med hur jag i tidigare
nämnda bokkapitlet föreslår att den den gängse uppfattningen av
relationen mellan teori, metod och praktik behöver omformuleras. Även om
Stjerna inte beskriver det explicit är det min uppfattning att hon
bygger upp definitionen av begreppet "sound art", och dess ontologiska
underbyggnad, genom att korrelera sin egen erfarenhet som praktiker med
en filosofisk och musikvetenskaplig genomgång av hur begreppet har
etablerats.[fn:12] Hon ger följande beskrivning av praktiken:

#+BEGIN_QUOTE
  To engage in sound installation as a site-specific practice is thus to
  position oneself, as an artist, as a node in the heterogenic field of
  what often is referred to as "sound art" respectively "sound art in
  public space." It is to understand that sound installation, in all its
  specificity emanates from a variety of different practices and
  traditions, which together generate a spatially explorative,
  multi-disciplinary practice.[fn:13]
#+END_QUOTE

Även med en rudimentär förståelse av Deleuze och Guattaris filosofi är
det redan i detta citat möjligt att se hur valet av teori är
välmotiverad. Det multidisciplinära angreppssättet förutsätter att de
olika delarna i undersökningen är sammankopplade och hur de kommunicerar
med varandra, vilket är själva kärnan i hur begreppet transversalitet
ska förstås. I en miljö som är genuint multidisciplinär är det
nödvändigt att ha en metod som tillåter obruten kommunikation mellan de
olika delarna av projektet och begreppet transversalitet användes från
början av Guattari i ett liknande syftet, som en kritik mot den
dualistiska synen på relationen mellan analytiker och analysand:

#+BEGIN_QUOTE
  The concept of transversality emerges in part out of Guattari's
  prolonged critique of the 'personological' understanding of language
  at work within psychoanalysis, and, specifically, within Lacanian
  versions of analysis. While not initially conceptualized in terms of
  enunciation, transversality---in Guattari's early writings
  institutional transference (later reframed as 'group transversality')
  --- aims to capture the unconscious as an investment of the broader
  elements and processes within the specific social setting of the
  hospital, a pattern of investment that would come to light only with
  the greatest difficulty in the dyadic enunciative setting of the
  analyst's consulting room.[fn:14]
#+END_QUOTE

Själva begreppet bär alltså redan från början med sig det som Stjerna
beskriver som ett resultat: en sammanvävd transversal process som
omformulerar hierarkier till kontinuerliga och i vissa fall spatiala
system. Här ingår relationen mellan konstnärssubjektet och publiken, som
visserligen har utsatts för kritik sedan 1960-talet.[fn:15] I /Before
Sound/ är fokus processerna i skapandet och produktionen och publiken
framträder inte direkt som en agent som diskuteras. Det transversala
utspelar sig därför primärt mellan platsen, konstverket och
konstnärssubjektet:

#+BEGIN_QUOTE
  In this doctoral research, the concept of assemblage has enabled me to
  articulate a mode of artistic practice in which site-specific sonic
  conditions and production operate as immanent, inter-relational,
  machinic, and transversal processes. I acknowledge the importance of
  this way of thinking in the subtitle of the thesis, "Transversal
  Processes in Site-Specific Sonic Practice," and its influence can be
  seen in the previous chapter's presentation of the field. As I have
  suggested through my descriptions, the initial explorative process,
  the establishment of spatial perception, the development of sonic
  strategies and technology, and the construction process on site, all
  emerge as the result of complex, machinic interconnections that span
  transversally between "the site," "the artwork," and the
  "artist-subject." In this, I advocate a move beyond the traditional
  separations that establish these as three distinct entities.[fn:16]
#+END_QUOTE

Kanske kan man därigenom dra slutsatsen att den transversala processen
är både metod och resultat? Åtminstone är det som metod transversalitet
beskrivs i citatet ovan och som sådan borde den vara intressant även i
annan konstnärlig forskning. Det undermedvetna, som Guattari diskuterar
i citatet ovan och som jag återkommer till längre fram i kapitlet, har
en del med den konstnärliga upplevelsen att göra, och om transversalitet
kan bidra med att begreppsliggöra det som sker även i den konstnärlig
processen så skulle en del vara vunnet. Och, som sagt, /Before Sound/
visar att det kan vara möjligt.


  \printendnotes
  \printbibliography
  \end{document}
  .

[fn:26] \footcite{deAssis2017}.

[fn:27] \footcite{hultqvist2019}.

[fn:28] \footcite{Hedelin2017}.

[fn:29] \footcite{frisk-cobussen09}.

[fn:30] \footcite{frisk2016b}.

[fn:31] \footcite{frisk08phd}.

[fn:32] \footcite{frisk2019}.

[fn:33] \footcite[Se
t.ex. referenser till Cox och LaBelle: ][s.45]{Stjerna2018}.

[fn:34] \footcite{frisk2018:irl}.

[fn:35] \footcite[Se kapitel
tre]{Stjerna2018}.

[fn:36] \footcite[s.42]{Stjerna2018}.

[fn:37] \footcite[s.234]{Goffey2015}.

[fn:38] \footcite[s.48]{Stjerna2018}.

[fn:39] \footcite[s.92]{Stjerna2018}.

[fn:40] \footcite{deleuze80}.

[fn:41] \footcite[Se
t.ex. ][ Begrepp som \emph{rhizome}, \emph{double bind}, och
\emph{schizoanalysis} som alla var viktiga för Deleuze och Guattari
diskuterades långt tidigare av Bateson, även om just \emph{double
bind} introducerades av Nietsche.]{Shaw2015}.

[fn:42] \footcite[s.137]{bateson72}.

[fn:43] \footcite[s.139]{bateson72}.

[fn:44] \footcite[s.117]{litzweiler92}.

[fn:45] \footcite[Intervju med
Ornette Coleman i][s.33]{taylor77}.

[fn:46] \footcite{coleman66}.

[fn:47] \footcite[s.121]{litzweiler92}.

[fn:48] \footcite[s.119-20]{Stjerna2018}.

[fn:49] \footcite[s.145]{Stjerna2018}.

[fn:50] \footcite[s.85]{Stjerna2018}.

[fn:51] \footcite{deleuze1994}.

[fn:52] \footcite{deleuze1994}.

[fn:53] \footcite[Se t.ex. projektet ICASP
som jobbade enligt denna modell:][]{lewis09}.

[fn:54] \footcite{deleuze1994}.

[fn:55] \footcite[s.93]{Stjerna2018}.

[fn:56] \footcite[s.42]{Stjerna2018}.

[fn:57] \footcite[Se t.ex. ][]{Lilja2015}.

[fn:58] \footcite{macchiarini2019}.

[fn:59] \footcite{konig2018}.

[fn:60] \footcite{frisk08phd}.

[fn:61] \footcite[s.130]{Jackson1982}.

+* Introduktion 
Konstnärlig forskning har haft en dynamisk och positiv utveckling de senaste tjugo åren, men vägen är fortfarande ojämn och lite knagglig: Det finns fortfarande relativt lite kunskap om vad det egentligen är, även på vissa konstnärliga högskolor. Likaså finns det fortfarande frågor kring vad den kan bidra med. Man kan förvisso fråga sig om kunskapen om t.ex. den sociologiska eller antropologiska forskningens metoder och resultat egentligen är större, eller om det finns en bredare insikt i på vilket sätt forskning i fysik bidrar till samhällets utveckling. Dock är dessa exempel på forskningsgrenar uppenbart politiskt och kulturellt mer etablerade än den konstnärliga forskningen, varför okunskapen är ett större problem i detta fält än i andra. 

Den konstnärliga forskningen i musik har en på vissa sätt längre historia än andra konstnärliga fält, mycket tack vare de musikvetenskapliga initiativ till en forskarutbildning med praktisk ingång som togs i Göteborg i slutet av 80-talet av professor Jan Ling. Resultatet av detta och andra initativ blev en mjuk övergång från musikvetenskap, till musikpedagogik, och så småningom till konstnärlig forskning i musik. Detta har varit en fördel och delvis också en belastning. Det senare då den konstnärliga forskningen i musik delvis har präglats på detta vetenskapliga arv på ett sätt som till exempel den konstnärliga forskningen i fri konst inte har gjort på konstvetenskap i samma utsträckning. Till fördelarna hör delvis metodutveckling och etablerade teorier att knyta an till. 

När jag påbörjade min forskarutbildning på Musikhögskolan i Malmö vid konstnärliga fakulteten, Lunds universitet, var det ett medvetet val från fakulteten att vi som var doktorander på konst-, musik- och teaterhögskolan skulle närma oss frågan om metod utan större inflytande från etablerade discipliner. På Musikhögskolan innebar det att vi inte skulle ha gemensamma seminarier med musikpedagogiken, som var den enda forskning som fanns innan vi började. Istället hade vi gemensamma seminarier med de andra konstnärliga doktoranderna. Efter ett tag hoppade doktoranderna från teaterhögskolan av och gruppen bestod av mig och mina två kolleger  på musikhögskolan och de tre doktoranderna från konsthögskolan där seminarierna också ägde rum. Mycket tack vare Sarat Maharaj, Brittisk konsthistoriker och curator som ledde seminarierna, och Gertrud Sandqvist, professor och då rektor för konsthögskolan, fanns det trots denna relativa isolering ett stort intresse av att vända sig mot discipliner som sociologi, psykologi och historia, vilket gjorde att diskussionerna i stor utsträckning präglades av interdisciplinäritet. Ambitionen var att de konstnärliga projekten skulle styra valet av metod och teori, även om det i verkligheten nog snarare var en ganska dynamisk interaktion, och resultatet var en mycket stimulerande miljö. Hade resulta
tet blivit ett annat om vi från musikhögskolan istället hade haft vår seminarier med musikpedagogiken? Definitivt, men det är naturligtvis omöjligt att fastställa om det hade varit bättre eller sämre.

Avsaknaden av definierade teoribildningar och metoder är den konstnärliga forskningens välsignelse och förbannelse. Enligt en rapport från Vetenskapsrådet har utmaningen för forskningen, och det konstnärliga utvecklingsarbetet innan dess, varit att metodologin har varit för otydlig och att projekten inte har tagit sig ur den enskilda forskarens privata sfär.[[footcite:Dunin2007][p.105]] Det problemet kommer lösas så småningom även om man kan uppleva att det tar lång tid. Fler kontaktytor mot såväl övriga forskningsdiscipliner, resten av kulturlivet samt en bredare del av samhället skulle kunna bidra till en mer stabil utveckling som inte samtidigt behöver betyda att konstnärlig forskning tappar sin identitet som unikt och konstnärligt forskningsfält.

Historiskt har dock mycket energi har ägnats åt att hävda att den konstnärliga forskningen ska vara fri från den typen av band som annars förväntas från forskning i andra discipliner. En långvarig diskussion i det lilla kluster som jag beskrev ovan var om vi överhuvudtaget skulle ha metod (ett mantra som återkom var "fuck method") och på ett övergripande plan ville man till varje pris undvika en utdragen metoddiskussion i fältet. Det är tydligt att doktorander än idag tycker att metodbegreppet i konstnärliga forskning är svårt att hantera, men samtidigt att det finns ett större intresse för frågan. Det finns ingen brist på metodologiska tillvägagångssätt, men däremot kan det var svårt att hitta en röd tråd vilket, vill jag påstå, gör att fältet i sin helhet blir onödigt disparat. Lösningen på detta är inte homogenitet, utan en för fältet övergripande och bred diskussion om metodologi som samtidigt är djuplodande. 

Anledningen till att vi befinner oss i en situation av bristande metodologi har mycket att göra med det som är själva kärnan i utmaningen med konstnärliga forskning: nämligen att relationen mellan den konstnärliga praktiken och den forskande aktiviteten kan se ut och utveckla sig på en rad olika vis. Om forskningsprojektet är helt integrerat, det vill säga att forskningsen utgår helt från den konstnärliga praktiken är de metodologiska behoven naturligtvis annorlunda från ett projekt där en konstnärlig praktik utforskas av en konstnär som skiftar fram och tillbaks mellan den praktiska och analyserande rollen. Med andra ord, var den forskande praktiken befinner sig i relation till den konstnärliga arbetet är avgörande för valet av metod. Därför kan det svårt att se framför sig den typ av metodologisk enhetlighet i konstnärlig forskning som man kan se i vissa andra fält. Däremot borde den konstnärliga metoden vara gemensam för nästan all konstnärlig forskning. Det är den som gör forskningen relevant som just konstnärlig forskning då det är den som visar på att en del av valen som har gjorts har gjorts på konstnärlig grund.

Så länge den konstnärliga metoden är väl beskriven, stabil och hållbar, så finns det god sannolikhet för att det finns data som går att utforska. Varför dessa data är av intresse är det faktum att de kommit till genom konstnärliga överväganden snarare än vetenskapliga eller andra. I vår artikel /Beyond Validity/ footcite:frisk-ost13 diskuterar Stefan Östersjö och jag bland annat validitet i konstnärlig forskning och pekar på behovet av att dekonstruera den positivistiska betydelsen av detta begrepp vilket i sig förutsätter att vi också tittar närmare på några av de begrepp som färgat utvecklingen av konstnärlig forskning. Henk Borgdorff är en person som har haft en hel del inflytande över den tidiga utvecklingen av konstnärlig forskning i Sverige och fortfarande har det i Holland. Han var bland annat medlem i den externa referensgruppen för nationella konstnärliga forskarskolan som drevs av Lunds Universitet, och var likaså professor på GU i en period. I sin bok /Conflict of the Faculties/ artikulerar han den ganska utbredda hållningen att konstnärlig forskning inte söker efter att uttrycka explicit kunskap utan snarare om att:

#+begin_quote
provide a specific articulation of the pre-reflective, non-conceptual content of
art. It thereby invites unfinished thinking. Hence, it is not formal knowledge that is the subject
matter of artistic research, but thinking in, through, and with art. [[footcite:borgdorff2012][p.143]]
#+end_quote

Att konsten, och det konsten uttrycker, skulle vara icke-konceptuell, det vill säga att vi erfar till exempel musik utan att den passerar ett begreppsfilter, är en idé som har präglat den västerländska estetiken sedan Kant. Är den inte konceptuell, eller inte låter sig konceptualiseras så kan resultatet av den inte heller kommuniceras annat än metaforiskt, vilket i i så fall gör den till ett extremt flyktigt objekt som endast svårligen låter sig studeras. Åtminstone skulle det ställa väldigt höga metodologiska krav, och det finns något otillfredställande över att Borgdorff introducerar en hierarki mellan "färdig" och "ofärdigt tänkande", och mellan "kunskap" och "tänkande". Det pre-konceptuella är visserligen en viktig aspekt av Deleuze filosofi som jag går in på närmare längre fram i detta kapitel, men han handskas samtidigt ytterst varsamt med dessa kategorier. 

Samtidigt vore det fel att påstå att konstnärligt uttryck inte kan vara icke-konceptuellt. Ofta refererar vi till en stark upplevelse som något som går rakt in utan att passera en analytisk eller konceptualiserande fas. Huruvida detta per automatik resulterar i "ofärdigt" tänkande är svårt att säga något om utan en bättre definition av termen, men jag hävdar att det finns anledning att tvivla. Istället kan vi se den konstnärliga kunskapsutvecklingen som något som sker i olika strata av medvetande och färdighet och i olika konstnärliga projekt är de olika skikten mer eller mindre framträdande och mer eller mindre möjliga att verbalisera. Som vi konstaterar i artikeln finns det ett behov av att bättre förstå detta fält:

#+begin_quote
[...] we now have to examine more closely the notions of pre-reflective and non-conceptual contents of art. Are they the same or different things? Does not ‘pre-reflective’ indicate that there is something unfinished in its trajectory? The category of non-conceptual knowing seems to us to be distinct from the unfinished. This appears to be a field not sufficiently discussed and theorized within artistic research, and, still, it is the heart of the matter: in all artistic production, knowledge is created and passed on in ways that are most often distinct from the verbal domain. [[footcite:frisk-ost13][p.35]]
#+end_quote

Om konstnärlig kunskap är skapad och kommunicerad på sätt som är väsensskilt från verbal kommunikation så är en del av utmaningen i konstnärlig forskning att översätta denna så att den går att begreppsliggöra på ett sätt som gör kunskapen i de studerade processerna användbar.

För att åstadkomma detta kan filosofi vara användbart, inte minst med tanke på att Deleuze definierar filosofin som skapandet av begrepp, men även om detta ser rimligt ut på ytan finns det risk för att hamna i ett cirkelresonemang, något jag återkommer till nedan. För nu räcker det med att konstatera att en konstnärlig forskning som i huvudsak ser till processen i skapandet, hur den vecklar ut sig över tid och hur den förhåller sig till politiska och sociala mönster inte utan vidare kan jämföra sig med en konstnärlig forskning som i huvudsak ser på resultaten av det konstnärliga arbetet eller arbeten som kombinerar de två perspektiven. För att begreppsliggöra en konstnärlig process kan det behövas andra metoder än då målet är att förstå vari kunskapen i ett konstnärligt resultat består.

Oavsett vilket behövs det en metod för att instantiera denna fas. Att se på konstnärlig praktik som en multiplicitet av potentiella uttryck och kunskapsformer som aktualiseras genom forskning betyder också att metoden inte bara är viktig, utan att många olika typer av metoder är nödvändiga då det måste vara varje projekts individuella konstellation av relationer som styr vilken metod som är den riktiga. Det är viktigt att dessa strata av konstnärlig kommunikation alltså inte på något sätt omöjliggör att någon del av, eller hela erfarenheten, verbaliseras. Istället, menar jag, borde det vara möjligt att:

#+begin_quote
[...] reconsider the theory-practice, method-practice and theory-method relationships beyond their most obvious appearances. If we can reassess the dual nature of these relationships and begin to see them as movements instead, continuities from practice to method to theory and then back, from concept to abstraction to specificity, the generalising and contextualising power of the theoretical approach may be less of an obstacle to the practice-oriented artistic researcher and doctoral candidate.[[footcite:frisk2015][p.120]]
#+end_quote

Här börjar nu själva kärnan av problemet träda fram: hur kan hållbara resultat utvinnas om koncept och kontext är i ständig rörelse och hur kan metoden väljas om ingenting är konstant? Det finns flera sätt att angripa dessa frågor på men först vill jag lägga till denna diskussion till listan av ej tillräckligt diskuterade problem i konstnärlig forskning och det här kapitlet är ett försök på en början. Det är utan tvivel så att det stora av fältet vetenskaplig forskning är otroligt disparat, och synen på den ideala, rigida vetenskapliga metoden är överdrivet enhetlig och förenklad. Samtidigt räcker det inte för den konstnärliga forskningen att återkommande hänvisa till att det finns experimentella kvalitativa metoder som används inom vetenskapen också, eller att det vetenskapliga forskningsfältet är minst lika disparat och heterogent som det konstnärliga. Metoderna, vare sig de avviker från vetenskapen eller inte, måste kunna förklaras och redovisas och metodutvecklingen inom fältet behöver få ett större fokus.

Här finns det metoder som kan användas och en som har visat sig relativt bra för att fånga kognitiva processer som det som Borgdorff kallar icke-konceptuella intryck är /stimulated recall/. I en översiktlig artikel som är en metastudie på en rad studier av denna metod skriver Lyle:
#+begin_quote
As this article will demonstrate, there is no doubt that there are significant limitations in incorporating SR procedures into research designs. Nevertheless, the method has considerable potential for studies into cognitive strategies and other learning processes, and also for teacher/educator behaviour, particularly complex, interactive contexts characterised by novelty, uncertainty and non-deliberative behaviour.[[footcite:Lyle2003][p.861-2]]
#+end_quote

Att kunna fånga det som den konstnärliga processen uttrycker, vare sig det är konstnären själv som upplever det i skapandet eller om det är lyssnaren/publiken som erfar det i lyssnandet måste ses som en central funktion för konstnärlig forskning. Det är här mycket av den specifika kunskapen finns och den är ofta dold eller vag även för den som erfar den. Här finns många frågor att ställa som till exempel men man ska komma ihåg att det sannolikt är olika kategorier av kunskap som finns i lyssnandet jämfört med den som finns i skapandet, även om de sammanfaller till stor del.

All konstnärlig praktik befinner sig inte heller i ett ständigt flux. Det finns flera exempel på praktiker som är konceptuellt stabila, men i allmänhet finns det mycket rörelse och det är detta som gör konstnärlig forskning såväl svår att förklara och definiera och samtidigt så otroligt användbar: generella förklaringsmodeller håller inte. Detta är en egenskap som ska underhållas och inte undertryckas. Resultatet av en dynamisk konstnärlig praktik kan fortfarande analyseras genom kvantitativa metoder och forma modeller. Dessa modeller kan ge resultat men för sig själva är det tveksamt vad de representerar. Om praktiken som genererade dem inkluderas i beskrivningen är det större sannolikhet för att de genererar kunskap som är användbar i konstnärlig forskning. Därför är det inte i reduktionen, eller den deduktiva metoden, som resultaten ska sökas utan i komplexiteten och instabiliteten, eller kort, i relationen till kaos. Det är detta som Deleuze och Guattari pekar på som skillnaden mellan filosofi och vetenskap, och jag skulle hävda att det är samma sak som skiljer konst från filosofi och konst från vetenskap:

#+begin_quote
The object of science is not concepts but rather functions that are presented as propositions in discursive systems. The elements of functions are called /functives/. A scientific notion is defined not by concepts but by functions or propositions. This is a very complex idea with many aspects as can be seen already from the use to which it is put buy mathematics and biology respectively. Nevertheless, it is this idea of the function which enables the sciences to reflect and communicate. Science does not need to philosophy for these tasks. On the other hand, when an object---a geometrical space, for example is---scientifically constructed by functions its philosophical concept, which is by no means given in the function, must still be discovered. Furthermore, a concept may take as its components the functives of any possible function without thereby having the least scientific value, but with the aim of marking the differences in kind between concepts and functions.

Under these conditions, the first difference between science and philosophy is their respective attitudes toward chaos. [[footcite:deleuze1994][p.117-8]]
#+end_quote

De fortsätter med beskriva den vetenskapliga metoden som en process som saktar ner tiden, som tar ett komplext fenomen och reducerar det till en enda funktion. Reduktion och representation vilket genererar tillstånd, funktioner och referentiella propositioner [[footcite:deleuze1994][p.197]]. Även om vetenskapen inte behöver filosofin, eller konsten, kompletterar de tre perspektiven varandra och i [[citetitle:deleuze1994]] strävar Deleuze och Guattari efter att placera filosofin och tänkandet i relation till vetenskapen och konsten och samtidigt undvika att skapa hierarkier dem emellan. Tillblivelse och transformation framför varande. Begrepp, inte som former som fylls med innehåll utan som uppstår i relation till varandra i ständig rörelse. Vad betyder detta för diskussionen om den konstnärlig forskningens betydelse och förmåga att skapa resultat relevanta för en värld i kaos? Olika projekt har olika mål men hur vet vi i bedömningen av konstnärlig forskning vad som är avsikten med ett givet projekt, om det är själva verket eller analysen eller båda två som vi ska se på?

Deleuze och Guattaris uppdelning i de tre tankeaktiviteterna konst, vetenskap och filosofin för det med sig att vissa frågeställningar blir enklare. Även om ingen av de tre formerna egentligen är beroende av varandra så erbjuder denna beskrivning av dem en potentiell renodling och en möjlig interaktion och med ett gemensamt mål: att möta kaoset. I den här beskrivningen finns det ett visst fokus på vad konsten (som konst) i sig självt uttrycker respektive vad filosofin respektive vetenskapen vill uttrycka. Hur ickehierarkisk relationen dem emellan än är så kan från citatet nedan detta framstå som att konsten inte i huvudsak är kunskap, och inte heller bygger stabila begrepp, utan är baserad på tidlöshet, sensationer och känslor, eller affekter:

#+begin_quote
What deinfes thought in its three great forms---art, science and philosophy---is always confronting chaos, layng out a plane, throwing a plane over chaos. [\ldots] Art wants to create the finite that restores the infinite: it lays out the plane of composition that, in turn, through the action of aesthetic figures, bears monuments for composite sensations.[[footcite:deleuze1994][p.197]]
#+end_quote

Konsten är inte en syntes av filosofin och vetenskapen och den ena formen för tänkandet är inte överlägsen någon av de andra men möjligheten för dem att bli sammanflätade eller korsa varandra utan att det för den sakens skull uppstår en sammanblandning dem emellan.

Om vi följer Deleuze och Guattaris diskussion ovan måste vi också ställa oss frågan vad konstnärlig forskning kan vara för något i deras beskrivning. Det är ingen tvekan om att de har en relativt traditionell syn på konst, i bemärkelsen att det framförallt är konstverkets potential som de diskuterar här. Kommentarer som "the act of painting that appears as a painting"[[footcite:deleuze1994][p.197]] antyder att process och resultat överlappar. Vad betyder det för den typen av transversal praktik som Åsa Stjerna bedriver? Är deras resonemang fortfarande relevanta för den hybrid som konstnärlig forskning utgör eller är det i huvudsak en ganska gammaldags syn på estetik och konstnärlig kunskap? Och vad är förhållandet mellan filosofin som begreppsskapande aktivitet och konsten som aktivitet?

Att döma av det stora intresse som Deleuze och Guattari har ägnats av konstnärliga forskare tyder mycket på att deras tänkande har en hel del relevans för konstfältet. I början av 2000-talet var det kanske framförallt bildkonsten som vurmade för Deleuze som ett tag sågs som konstens galjonsfigur. Efterhand har man dock inom musiken också öppnat ögonen för dessa filosofer. I december 2019 hölls den 3e internationella konferensen om Deleuze och konstnärlig forskning på Orpheus Institutet i Ghent, Belgien och alldeles nyligen släppte även Leuven University Press den andra delen i serien /Deleuze and Artistic Research: Aberrant Nuptials/[[footcite:deAssis2017]][fn:3] (den första hette /The Dark Precursor/[[footcite:deAssis2017]]). Dessa är imponerande samlingar, inte bara sett till innehållet men också till omfånget och med ett huvudsakligt, dock inte exklusivt, fokus på musik. I Sverige har vi det av Vetenskapsrådet(VR)-finansierade projektet [[citetitle:hultqvist2019]] lett av Anders Hultqvist  (2015-2018) på GU som också utgick från Deleuze teoribildning[[footcite:hultqvist2019]] samt Klas Nevrins VR-projekt /Musik i Oordning/ med hemvist på Kungliga Musikhögskolan, som avslutades i december 2018, likaså med tydligt avstamp i Deleuze tänkande. Nästan helt parallellt med Åsa Stjerna gjorde tonsättaren Fredrik Hedelin sin avhandling på Luleå Universitet i vilken han utför en analys av tre av sina egna solokonserter och begreppet ritornell blir en kontaktyta mellan musik och filosofi.[[footcite:Hedelin2017]] I ett projekt tillsammans med Marcel Cobussen gjorde vi ett försök att diskutera /The Field of Musical Improvisation/ (FMI) utifrån komplexitetsteori och Deleuze och Guattari på ett sätt som relaterar till den begreppsapparat som Stjerna använder:

#+begin_quote
Assemblages are wholes whose properties emerge from the interactions between parts,
for example, interpersonal networks such as can be found in the FMI. In other words,
assemblages cannot be defined by nor do they consist of the properties of their
constituting parts. Think ecology instead of reductionism.[[footcite:frisk-cobussen09]]
#+end_quote

Det som Stjerna refererar till de transversala processerna och som hon använder för att visa på hur den konstnärliga praktiken är rhizomatisk till sin natur finner viss resonans i annan konstnärlig forskning. Ambitionen att bryta ner de politiska och sociala hierarkier som i århundraden präglat musiklivet och som fått fart i och med institutionaliseringen och professionaliseringen har diskuterats i många projekt och är något jag själv har intresserat mig mycket för. I en rad studier från 2006 tittade vi på hur agensen mellan tonsättare, musiker och teknologi påverkade och till och med hade en avgörande betydelse på de konstnärliga tillvägagångssätten.[fn:2] En stor del av mitt fokus i min avhandling från 2008[[footcite:frisk08phd]] tar sin avstamp i erfarenheterna från ljudinstallationen /etherSound/ och idéen om ickekontroll och perpetuell rörelse vilket på vissa sätt ligger nära Stjerna icke-autonoma upphovsperson och transversala praktik. Inget av dessa exempel tar avstamp i Deleuze, i min avhandling var det istället en annan postmodernist, dystopikern Jean Baudrillard, som utgjorde en del av teorin och i de tidigare studierna var utgångspunkten snarare strukturalism, även om vi relativt snabbt sträckte oss förbi denna startpunkt. Men det finns även reflektioner som kanske vid första anblick inte är relaterade till detta fält som man kan göra. Till exempel så pekar doktoranden och konsertpianisten Franciska Skoogh på hur MPA (Music Performance Anxiety) ofta ses som ett individuellt problem, något musikern själv får kompensera för, när det i själva verket finns en rad strukturella faktorer som påverkar situationen som konservatorietraditionen, de kommersiella aktörerna och den extrema kommodifieringen av musiken.[[footcite:frisk2019]] Samtidigt är det viktigt att påminna sig om att /Before Sound/ inte framförallt är ett musikprojekt utan snarare ett konstprojekt.

Det finns en möjlig negativ, om än ofullständig, definition av vad konstnärlig kunskap kan utgöra som grundar sig i empirisk kunskap. Föreställ dig allt som du kan kan säga någonting om utifrån vedertagna vetenskapliga definitioner såsom gravitationens inverkan på din kropp, luftens och vattnets sammansättning, de politiska och sociala system som du ingår i och påverkas ev, etc. Det konsten kan säga någonting om är allt det andra; hur det känns att vara utsatt för gravitation, hur luften doftar och vattnet smakar och de känslomässiga konsekvenser som det sociala och politiska har på dig. Eller som Eisner skriver: 

#+begin_quote
"For me, the defining feature that allows us to talk collectively about the arts is that art forms share the common mission of achieving expressiveness through the ways in which form has been crafted or shape. The arts historically have addressed the task of evoking emotion. We sometimes speak of the arts as resources that can take us on a ride. The arts, as I have indicated elsewhere, provide a natural high. They can also provide a natural low. The range of emotional responses is enormous. These emotional consequences in relation to a referent color the referent by virtue of the character of the emotion that the artistically crafted form possesses." footcite:Eisner2008
#+end_quote

Det är ingen tvekan om att det finns många och stora likheter mellan konstnärlig forskning i musik och till exempel vetenskaplig forskning. Men det är heller ingen tvekan om att det finns stora skillnader. Den kanske främsta anledningen till att det kan vara svårt att samarbeta över gränserna när det gäller konstnärlig forskning det som ger konstnärlig forskning sin särprägel nämligen den konstnärliga metoden och den konstnärliga grunden. Man kan tycka att det borde vara enkelt eftersom det vetenskapliga och det konstnärliga kompletterar varandra så väl. Om vi använder allegorin från början av kapitlet och definierar det konstnärliga som allt det som vi inte säkert kan säga någonting om och resten dvs det som vi kan säga någonting om utifrån vedertagna metoder så blir det tydligt att det kan Vara svårt att samarbete. Själva grundvalen för att avgöra om forskningen är högkvalitativ är helt annorlunda för vilket det måste finnas förståelse och respekt om ett samarbete ska kunna bli ömsesidigt värdefullt.


* Problemet 4000
  Åsa Stjernas avhandling "utforskar konstnärlig transformation i platsspecifik sonisk praktik" [[citetitle:Stjerna2018][s.291]]. Denna praktik är multidisciplinär och transformativ och äger rum i det offentliga rummet vilket gör skapar sammanhang och situationer som kräver förhandling och omförhandling i de platsliga situationerna och i sig visar på komplexiteten i all mänsklig aktivitet. Fyra konstnärliga processer, varav tre är platsspecifika, beskrivs detaljerat och de processer som bidrar till det som rör avhandlingens centrala frågeställning: själva omförhandlingen och transformationen av platsen diskuteras utifrån kanske framförallt Gilles Deleuze och Félix Guattaris teori. Som framgår av undertiteln är begreppet transversal centralt i undersökningen. Transversalt ska här ses som "en förståelse av konstnärlig produktion som etablerandet av relationer mellan komponenter i ömsesidig kontinuerlig process av tillblivelse". [[footcite:Stjerna2018][p.293]] Eller, i hennes egna engelska formulering:

  #+begin_quote
  "Transversal" here refers to an understanding of artistic production as
  the creation of affective, immanent relations between components in
  mutual continuous processes of becoming. These relations span be-
  tween material and discursive, and human and non-human, compo-
  nents. In exploring the acts performed by the artist within transversal
  processes, the aim is to develop explorative approaches and concepts
  that might contribute to a more complex understanding of the pro-
  cesses at work in site-specific sonic practice.
  #+end_quote

  Stjerna strävar efter att undvika de traditionellt starka dikotomier som präglar förståelsen av konstverket och som kan representeras av begrepp som konstnär-publik, skapande-lyssnande, innanför-utanför eller kropp-själ. Istället för dessa ontologiska relationer lyfter hon fram en "förståelse av konstnärlig praktik som befattandet med affektiva, /immanenta/, kraftrelationer i vilka varje komponent har agens, det vill säga kapaciteten att både påverka och påverkas. Detta är i mångt och mycket i överensstämmelse med Deleuze filosofiska perspektiv och delvis kan avhandlingen därigenom ses som en instantiering, eller ett utforskande, av det teoretiska ramverk som läggs fram.[[footcite:Stjerna2018][Se t.ex. Kapitel 8, avsnitt /Machinic Interferences in the Oslo Opera House
  as a Smooth and Striated Space./ :: s.240-5]]

  Utifrån denna ambition är tre forskningsfrågor formulerade:

  #+begin_quote
  - På vilket sätt kan jag som konstnär utveckla utforskande tillvägagångssätt som understödjer en transversal skapandeprocess?
  - Vilka begrepp behöver jag som konstnär kunna artikulera för att kunna synliggöra och förstå nyanserna av en sådan transversal process?
  - Vilka konsekvenser har dessa utforskande tillvägagångssätt och begrepp i förståelsen av den platsspecifika soniska praktiken? [[footcite:Stjerna2018][p.294 (p.27)]]
  #+end_quote

  Som metoder, här kallade utforskande tillvägagångssätt, pekar Stjerna på i huvudsak tre strategier: "att kartlägga de affektiva linjerna, att skapa nya sammankopplingar samt att bli icke-autonom" [[footcite:Stjerna2018][p.294]]. Alla dessa tre är även kopplade till Deleuze och Guattari på olika nivåer, kanske framförallt metoden att skapa nya sammankopplingar som i sig kan ses som en del av den transversala ambitionen. Som en central tes som lyfts fram på flera platser i avhandlingen, och som är bakgrunden till titeln, är att ljud är något som ska ses som en effekt av affektiva, transversala och immanenta processer som samtliga äger rum /före ljudet/. Etablerandet av nya kopplingar lyfter fram den konstnärliga processen som både transformativ och transversala [[footcite:Stjerna2018][p.119]] och dessa kopplingar är helt centrala för de olika aspekter, eller modaliteter som Stjerna lyfter fram för sin egen praktik: sonifiering, teknologi och på-plats installation. Men det är också genom transversala processer som nya kopplingar skapas mellan heterogena objekt, vilket är den central del av den konstnärliga praktiken, som ljudet uppstår.

  I avhandlingen diskuteras fyra konstnärliga projekt: /Currents/ (2011), An /Excursion to Nairobi/
  (2013), /The Well/ (2014) och /Sky Brought Down/ (2017) och av dessa kommer jag framförallt fokusera på den första, /Currents/. /Currents/ var ett egeninitierat projekt som utvecklade sig till en beställning av Ultima-festivalen, en nutida musikfestival i Oslo, avsedd för foajén på nya operahuset vid hamninloppet i Oslo. Utgångspunkten för verket är data från Nordatlantiska strömmen och i samverkan med ett forskningsprojekt som studerade issmältningen på norra halvklotet till följd av den globala uppvärmningen fick Stjerna tillgång till datan. Ambitionen var att utforska i vilken utsträckning ljud som konstnärligt material kan mediera frågor av stor politisk relevans och hur dessa frågor kan ge upphov till förkroppsligade upplevelser i ett publikt sammanhang.

  Anledningen till att jag väljer just detta projekt är på grund av de frågor som det ställer kring relationen mellan representation och uttryck och hur de politiska och sociala aspekterna naturligt hamnar i fokus. Dessutom ligger flera av frågeställningarna nära de jag själv ha ställt och känns därför intressant för mig att reflektera över. Projektet är samtidigt en tydlig illustration av hur en transversal process kan se ut. De olika komponenterna i de olika faserna av projektet, såsom forskningsprojektet som höll i datainsamlingen, processen att extrahera relevanta delar av den vetenskapliga datan, operahuset som social och politisk plats och plats för själva renderingen av verket, den konstnärliga utvecklingen av mjuk- och hårdvara, och Stjerna själv som konstnär [[footcite:Stjerna2018][p.133]]  är var och en för sig självständiga agenter, maskiner [fn:1], assemblage och utmaningen, i det här sammanhanget, är att artikulera hur dessa kopplingar uppträder och hur de uppstår.

  En annan aspekt av /Currents/ som Stjerna diskuterar i kapitel 5 är frågan om konstnären som subjekt och dennes begränsade oberoende eller autonomi, eller snarare, Stjernas önskan att uppnå icke-autonomi: 
  #+begin_quote
  The second issue that I address in this chapter concerns the artist subject’s minimized autonomy. Through Currents I show the ways in which the artist subject is implicated in a continuous, affective relation with a myriad of agencies, all with their specific capacity to affect the process. This implies a model of daily practice that exceeds the established idea of an active, sovereign artist-subject exercising their power to produce a work, which is subsequently placed in a space. On the contrary, the account given here emphasizes an ethological process in which I as artist stand in continuous encounter with the different agencies spanning from the scientific data to the Oslo Opera, the programmer, as well as the software, which all had a direct effect on the artistic process of developing /Currents/.[[footcite:Stjerna2018][s.133]]
  #+end_quote

  Det är klart att den väv av relationer som skissas här ovan också gör det tydligt att det blir svårt för konstnären att hävda ensidig bestämmanderätt, utan snarare ska ses som en agent av många. Men valet att uttrycka det som en modell som går bortom det suveräna subjektet är intressant och talande här. Det handlar inte om att konstnären här blir berövad möjligheten att vara autonom, utan att hon istället erbjuds ett mer omfattande ramverk. Den autonoma konstnären ses ofta som ett ideal, tätt kopplat till den fria konstnären, ett begrepp som likaväl kan, och bör, ifrågasättas.[[footcite:peters09][Se till exempel :: s.21]] Utöver den möjlighet till transversalitet som Stjerna betonar lyfts fram genom det icke-autonoma, finns det både etiska och konstnärliga skäl att ifrågasätta frihetsbegreppet. Men, det är viktigt att de tre centrala delarna här: platsen, verket och konstnärssubjektet, ses som integrerade helheter snarare än åtskilda:

  #+begin_quote
  As I have suggested it through my descriptions, the initial explorative process, the establishment of spatial perception, the development of sonic strategies and technology, and the construction process on site, all emerge as the result of complex, machinic interconnections that span transversally between the site, the artwork, and the artist-subject. In this, I advocate a move beyond the traditional separations that establish these as three distinct entities.[[footcite:Stjerna2018][s.92]]
  #+end_quote

  Slutligen diskuteras frågan om sonifiering som metod och hur den kan förstås som en transversal process. Sonifiering är såväl en vetenskaplig som konstnärlig metod och Stjerna gör en genomgång av olika aspekter av de olika förhållningssätten. Som vetenskaplig metod är det i sonifiering ofta nödvändigt att skapa en mer eller mindre direkt korrespondens mellan den data som ska sonifieras och det ljudande resultatet. Detta är en typ av representation som varken går ihop med den teori som arbetet vilar på eller nödvändigtvis är särskilt intressant rent konstnärligt. Syftet med sonifiering i vetenskapliga sammanhang är att erbjuda en klanglig ingång till en  datamängd. Det kan till exempel handla om att titta på extremt komplex data som inte är möjlig att läsa, men möjliga att höra. Även om det motivet ligger nära användningen i /Currents/ har sonifiering en mycket bredare betydelse för Stjerna och som konstnärlig metod är den tätt sammanvävd med det teoretiska ramverket i avhandlingen:

  #+BEGIN_QUOTE
  From this outset, sonification emerges as a practice of transforming affective forces between bodies—-material, social, discursive—-in which the practice of transformation should be considered to constitute a creative, machinic process that generates new expressions of becoming. This process is always situated and dependent on its specific conditions, meaning that the sonification process of Currents must be understood in relation not only to the scientific data but to all the other assemblages involved, including the Oslo Opera’s unique ecology.[[footcite:Stjerna2018][s.157]]
  #+END_QUOTE

  På ett processplan är det inte svårt att se att denna sonifieringsprocess i allt väsentligt måste ses i relation till det transversala flöde som alla andra delar av installationen vilar på. Samtidigt är det en utmaning att se hur detta kan erfaras. Datan från havsströmmarna är uppdelade i två olika delar varav en är i realtid medan den andra har genererats i icke-realtid vilket kanske understryker betydelsen av att se /Currents/ som spatial snarare än temporal. Detta öppnar upp för en annan fråga som i all korthet skulle kunna formuleras i stil med: Jag har i huvudsak förstått Deleuze immanensplan som ett brott mot den västerländska filosofins upptagenhet med det spatiala, till förmån för Bergsons temporala tänkande, men i /Before Sound/ framhålls ambitionen att arbeta med ljudinstallation som en spatial praktik. Vilken funktion har det temporala i /Before Sound/?

** hittills nästan lika
* Metoder i Before Sound 4000
** used
   I /Before Sound/ är kallar Stjerna sina metoder för /explorative approaches/. Givet hur nära kopplade de är till teorin är det sannolikt en klok strategi även om det också kan skapa förvirring. Som nämnts ovan är de tre övergripande strategierna /att kartlägga de affektiva linjerna/, /att skapa nya sammankopplingar/ samt /att bli icke-autonom/. Denna nära koppling mellan teori och metod gör det på ett sätt enklare att diskutera utmaningarna i projektet. Om vi fortsätter utifrån linjen att Deleuze och Guattaris filosofi framförallt sysslar med begreppskapande, kan deras verktyg användas för att skapa nödvändiga begrepp för att förstå och analysera den konstnärliga praktiken. Frågan är om resultatet av den processen först och främst är kunskap om konst eller om filosofi, men oavsett svaret så kan resultatet validitet som forskning. En annan utmaning till följd av denna användning av metod är att det helt enkelt kan uppstå en sammanblandning mellan teori, metod och resultat med utfallet att den konceptuella stabiliteten blir lidande, men samtidigt, som diskuterades ovan, är detta i realiteten ett sätt att hantera metod och teori i konstnärlig forskning. Jag ska återkomma till det.

   I detta fall uppstår inte dessa problem, delvis tack vare att Stjerna handskas varsamt och konsekvent med begreppen. Dessutom ska man inte glömma att teorin kanske framförallt utgörs av den kontextualisering och positionering som görs i kapitel 2: /Contextualisation--Artistic Strategies within the Field/. Denna typ av situering är något som ibland förbises i konstnärliga avhandlingar vilket får till följd att de konstnärliga resultaten kan bli svåra att relatera till då det blir oklart inom vilket konstnärligt fält konstnären/forskaren rör sig. Samma problem uppstår om fältet som beskrivs är alltför disparat eller alltomfattande, eller alltför smalt. Det finns flera anledningar till att det tagit lång tid för konstnärlig forskning att hitta rätt på detta område men några uppenbara skäl är:

   1. Bristen på etablerade modeller för att referera till alla typer av konstverk och svårigheten beskriva dem på ett sätt som bidrar till att skapa en bild av ett fält är påtaglig. Ett sätt runt detta är att göra som Stjerna gör och referera till en (vetenskaplig) studie av verket i fråga.[[footcite:Stjerna2018][Se t.ex. referenser till Cox och LaBelle: ::p.45]] Detta är i grund och botten ett beprövat sätt att såväl inkludera den större diskursen om ett verks validitet för ett specifikt sammanhang och kan skapa trovärdighet i argumentationen när möjligheten att lyssna och uppleve, om än genom en dokumentation, också erbjuds. En eventuell baksida med denna metod är att argumentationen kan göra sig beroende av en annan disciplin, som filosofi eller musikvetenskap i det här fallet eller rent utan resultera i en vetenskaplig undersökning. Detta är i sig inte ett problem, jag menar att konstnärlig forskning är i grunden tvärvetenskaplig, men det är samtidigt viktigt att det tvärvetenskaplig hanteras varsamt och på ett sätt att det understödjer den konstnärliga undersökningen.

   2. Det är tydligt att man i konstnärliga avhandlingar har lättare att referera till etablerade verk och studier av verk. Men utan en intern diskussion och utan att varje avhandling också relaterar till det fält som är i dess  omedelbara närhet, som samtida konstnärlig forskning eller konstnärlig praktik riskerar studien att begränsas. Stjerna går elegant runt detta genom att med omsorg beskriva verktygen, tillvägagånssätten och det teoretiska perspektivet hon använder vilket skapar en tydlighet. Men jag skulle vilja gå så långt som att säga att den största utmaningen vi har för konstnärlig forskning idag är just bristen på ett forskningsfält där den konstnärliga undersökningen står i centrum. Detta kan byggas genom att doktorander samarbetar och refererar till varandras arbeten, gärna kritiskt men alltid noggrant och genom att större forskningmiljöer skapas. Ett nytt samarbete mellan Kungliga Musikhögskolan och Musikhögskolan i Piteå, Luleå Tekniska Universitet, samlar mer än tio doktorander, en PostDoc och flera seniora forskare i vad vi kallar lab tre gånger per år. Det är en början men vi behöver fler samarbeten där utgångspunkten är diversitet, samarbete och kritisk granskning. 2018 skrev vi i programförklaringen att vi vill ytterligare arbeta för att skapa
   #+begin_quote
   [\ldots]  former för kunskapsbyggande i konstnärlig forskning som är baserat på konstnärlig kunskap. Även teoretiskt drivna resonemang kan här ta sin utgångspunkt i den konstnärliga praktiken varför själva praktiken är central i seminarier och labsessioner. De gemensamma seminarier som vi planerar i Piteå och Stockholm ska ta formen av ett laboratorium som alla gemensamt ska bidra till den fortsatta utvecklingen av detta format. En viktig förutsättning är att skapa ett arbetsklimat som bygger på förtroende av samma slag som uppstår i konstnärliga samarbeten, och som därigenom skapar förutsättningar för en kritisk dialog som kan gå på djupet in i konstnärliga processer. 
   #+end_quote
   Idén är att sätta den konstnärliga praktiken i centrum i en skyddad seminariemiljö som erbjuder möjligheten att experimentera. I denna process hoppas vi att det ska bli möjligt att i större utsträckning begreppsliggöra praktiken och undersökningen vilket samtidigt kan underlätta att arbetena också diskuteras av jämlikar.

   3. Men även det större fältet av konstnärlig praktik, utanför konstnärlig forskning, måste vara möjligt att referera till. Musikhögskolan i Piteå och konstnärliga fakulteten vid  Göteborgs universitet har etablerade metoder för att registrera konstnärliga verk vilket gör det enkelt att hänvisa till dessa, och KMH och Musikhögskolan i Ingesund, Karlstad Universitet, har påbörjat ett arbete som förhoppningsvis leder till att vi bidrar till ett fält som inkluderar akademien och skapar förutsättningar för forskningsanknuten undervisning.

   4. Utan tydliga begrepp för konstnärlig forskning och konstnärlig praktik kan det vara svårt att på ett öppet sätt beskriva det konstnärliga fält som är det centrala för studien, utan att bli låst av det.

   Det ackumulativa kunskapsbyggandet som kan bli resultatet av en stabil forskningsmiljö där forskare på olika sätt bygger vidare på varandras arbeten är en förutsättning för att konstnärlig forskning ska få respekt och förtroende som ett självständigt kunskapsfält, men också för att den interna kunskapsutvecklingen ska ta fart. Jag menar att konstnärlig forskning inte bara är tvärvetenskaplig utan också är multidisciplinär till sin natur, det vill säga att den är beroende av andra discipliner än den rent konstnärliga aspekten för att kunna förstås som kunskap utanför sin egen domän. För konstnärlig forskning som är helt inriktad på att skapa ny kunskap inom sitt eget fält, ett exempel skulle kunna vara ett forskningsprojekt som studerar hur man bäst preparerar ett piano för ett givet verk, har eventuellt inte det multidisciplinära perspektivet samma betydelse. Symptomatiskt beskriver även Stjerna ljudinstallation som en multidisciplinär praktik och själva avhandlingen i sin helthet får även den ses som multidisciplinär. Det är dock viktigt att det transdisciplinära har en politisk dimension som det är viktigt att förstå. Samverkan är ett ledord för samtliga universitet och högskolor idag och tvärvetenskap har blivit ett självändamål.

   För att återgå till Stjernas avhandling så harmonierar det sätt hon bygger upp det teoretiska och metodologiska ramverket i stor utsträckning med hur jag i tidigare nämnda[[citetitle:frisk2015]] föreslår att den den gängse uppfattningen av relationen mellan teori, metod och praktik ska omformuleras. Även om Stjerna inte beskriver det explicit är det min uppfattning att hon bygger upp definitionen av begreppet sound art, och dess ontologi, genom att korrelera sin egen erfarenhet som praktiker med en filosofisk och musikvetenskaplig genomgång av hur begreppet har etablerats[[footcite:Stjerna2018][Se kapitel 3]] och ger en beskrivning av praktiken:

   #+begin_quote
   To engage in sound installation as a site-specific practice is thus to position oneself, as an artist, as a node in the heterogenic field of what often is referred to as “sound art” respectively “sound art in public space.” It is to understand that sound installation, in all its specificity emanates from a variety of different practices and traditions, which together generate a spatially explorative, multi-disciplinary practice.[[footcite:Stjerna2018][p.42]]
   #+end_quote

   Redan i detta citat är det möjligt att se hur teorin, i detta fall Deleuze och Guattari, är motiverad. Det multidisciplinära angreppssättet förutsätter att de olika delarna i undersökningen är sammankopplade och kommunicerar vilket är själva kärnan i begreppet transversalitet. I en miljö som är genuint multidisciplinär är det nödvändigt att ha en metod som tillåter obruten kommunikation mellan de olika delarna av projektet och begreppet transversalitet skapades av Guattari som en kritik mot den dualistiska synen på relationen mellan analytiker och analysand:

   #+begin_quote
   The concept of transversality emerges in part out of Guattari’s
   prolonged critique of the ‘personological’ understanding of language at
   work within psychoanalysis, and, specifically, within Lacanian versions
   of analysis. While not initially conceptualized in terms of enunciation,
   transversality—in Guattari’s early writings institutional transference (later
   reframed as ‘group transversality’) — aims to capture the unconscious
   as an investment of the broader elements and processes within the
   specific social setting of the hospital, a pattern of investment that
   would come to light only with the greatest difficulty in the dyadic
   enunciative setting of the analyst’s consulting room.[[footcite:Goffey2015][p.234]]
   #+end_quote

   Själva begreppet bär alltså med sig det som Stjerna beskriver som ett resultat; en sammanvävd transversal process som omformulerar hierarkier till kontinuerliga och i vissa fall spatiala system. Framförallt relationen mellan konstnärssubjektet och publiken som utsatts för kritik sedan 1960-talet,[[footcite:Stjerna2018][p.48]] men i /Before Sound/ är publiken inte en agent som diskuteras då fokus är processerna i skapandet och produktionen varför det snarare är relationerna mellan platsen, konstverket och konstnärssubjektet:

   #+begin_quote
   In this doctoral research, the concept of assemblage has enabled me to articulate a mode of artistic practice in which site-specific sonic conditions and production operate as immanent, inter-relational, machinic, and transversal processes. I acknowledge the importance of this way of thinking in the subtitle of the thesis, “Transversal Processes in Site-Specific Sonic Practice,” and its influence can be seen in the previous chapter’s presentation of the field. As I have suggested through my descriptions, the initial explorative process, the establishment of spatial perception, the development of sonic strategies and technology, and the construction process on site, all emerge as the result of complex, machinic interconnections that span transversally between “the site,” “the artwork,” and the “artist-subject.” In this, I advocate a move beyond the traditional separations that establish these as three distinct entities.[[footcite:Stjerna2018][p.92]]
   #+end_quote

   Kanske kan man därigenom dra slutsatsen att den transversala processen är både metod och resultat? Åtminstone är det som metod transversalitet beskrivs i citatet ovan och som sådan borde den vara intressant i konstnärlig forskning. Det undermedvetna har en hel del med den konstnärliga upplevelsen att göra och om transversalitet kan bidra med att begreppsliggöra det som sker i den konstnärlig processen så skulle en del vara vunnet. Och, som sagt, /Before Sound/ visar att det kan vara möjligt.

   Att begreppet härstammar från Guattaris önskan att fånga förståelsen av det undermedvetna är inte oväsentligt, inte heller brottet med Lacanska tradition för psykoanalys. Lite förenklat kan vi knyta Guattaris ambition att bryta med den binära analytiska modellen till Deleuze kritik av det transcendentala tänkandet som har varit så central för Europeisk filosofi. Genom att ersätta den binära relationen mellan analytiker och analysand med en grupptransversalitet kunde man sannolikt närma sig själva terapisessionen mer som en process av tillblivelse och det undermedvetna snarare som en aspekt av det medvetna (eller omvänt). Detta påminner samtidigt om de försök att dekonstruera de binära eller dyadiska relationerna mellan olika agenter i den konstnärliga produktionen som så många konstnärliga forskare, inklusive Åsa Stjerna, har varit upptagna med. Frågan är hur vi från denna förståelse av relationerna mellan de aktiva och sammanvävda komponenterna kan ta oss mot en insikt i vad dessa relationer säger om till exempel den konstnärliga praktiken.

   För att förstå varför det undermedvetna är relevant i det här sammanhanget vill jag återkomma till en text av Gregory Bateson som jag hänvisat till många gånger tidigare. Bateson var en brittisk antropolog, sociolog, filosof och cybernetiker som har en nära relation till Deleuze. Det finns ett fåtal referenser till Bateson hos Deleuze, bland annat två i Mille Plateaux, men det finns de som menar att inflytande från Bateson var betydligt större.[[footcite:Shaw2015][Se t.ex. :: Begrepp som /rhizome/, /double bind/, och /schizoanalysis/ som alla var viktiga för Deleuze och Guattari diskuterades långt tidigare av Bateson, även om just /double bind/ introduceerades av Nietsche.]] Det som gör Bateson intressant i den specifika diskussionen om konstnärlig forsknings kunskapsbildning är dock hans syn på just det undermedvetna och hur information kodas i hjärnan såväl som i kroppen. Följande citat här hämtat ur 

   I Freudiansk teori delar man upp mental aktivitet i primära och sekundära processer. De primära är icke-verbala och drömlika och företar de sekundära som är det reflekterande och medvetna jagets uttryck, och konst är generellt ``an exercise in communicating about the species of unconsciousness [\ldots] a play behaviour whose function is [\ldots] to practice and make more perfect communication of this kind.''[[footcite:bateson72][p.137]] Nu kan det framstå som att vi har återinfört en separation mellan det inre, de primära processerna och det yttre, de sedundära. Sannolikt så var det bland annat denna uppdelning som Guattari ville komma åt när han försökte tänka om terapisituationen. Men dessa två kategorier av processer behöver inte vara väsensskilda utan kan snarare ses som två möjliga sätt att koda kunskap och erfarenhet, eller affekter. Då är inte frågan hur vi ställer de mot varandra ut hur vi kommunicerar mellan dem (eller inom dem). Bateson skriver:

   #+begin_quote
   [The] algorithms of the heart, or, as they say, of the unconscious, are, however, coded and organized in a manner totally different from the algorithms of language. And since a great deal of conscious thought is structured in terms of the logics of language, the algorithms of the unconscious are double inaccessible. It is not only that the conscious mind has poor access to this material, but also that when such access is achieved. \emph{e.g.}, in dreams, art, poetry, religion, intoxication, and the like, there is still a formidable problem of translation.[[footcite:bateson72][p.139]]
   #+end_quote

   I inledningen pekade jag i all korthet på hur konstnärlig kunskap ofta inte utan vidare låter sig beskrivas verbalt. I ljuset av detta kan det vara tilltalande att se en översättning från det omedvetna till det medvetna som lösningen, men det finns flera saker som behöver lyftas för att vi på ett hållbart sätt ska kunna ta ställning till problemet. För det första har vi frågan om begreppsliggörandet av den konstnärliga praktiken, det vill säga processen av att skapa begrepp som gör det möjligt att artikulera en kunskap. I /Before Sound/ gör Åsa Stjerna gör detta bland annat genom att använda Deleuze begreppsapparat vilket också leder henne till vissa specifika resultat som relaterar till det platsspecifika, såväl som till hur själva praktiken ter sig. Men om man tänker sig att man är i behov av att formulera egna begrepp så kan man stå inför Batesons utmaning, nämligen hur vi omformulerar eller översätter en konstnärlig strategi till en verbal utan att den samtidigt förlorar mening eller fastnar i en meningslös metafor eller representation.

   Men det finns även inomkonstnärliga begrepp som inte behöver en översättning för att fungera. För detta är kontextualiseringen av projektet viktig så att de begrepp man använder sig av får pregnans och tillåter att diskursen inom fältet blir användbar. I musik kan även till exempel musikteoretiska begrepp nyttjas och om dessa relateras till praktiken på ett användbart sätt så kan den kunskapen som finns i praktiken lyftas fram. Både Deleuze och Guattari i [[citetitle:deleuze1994]] och Bateson i [[citetitle:bateson72]] diskuterar dock framförallt det som en konstnärlig upplevelse ger upphov till rent kognitivt. Mycket konstnärlig forskning, så även Åsa Stjerna, beskäftigar sig framförallt med hur processen att /göra/ konst fungerar och i den undersökningen så är resultatet, förutom att det är konst, ett sätt att validera utforskandet av processen. 

   Det är inte säkert att den konstnärliga processen som leder fram till ett konstnärligt resultat är densamma som att erfara resultatet. I vissa fall kan den vara det men i andra fall, som också kan ses i /Before Sound/, är det ställningstaganden som har med praktiska omständigheter att göra; hur fungerar en sladd, hur kan en högtalare installeras, etc. Är dessa kodade i det omedvetnas algoritmer, för att använda Batesons terminologi, eller är de del av en process som egentligen ligger närmare annan humanistisk forskning än vad man kanske först vill tro? Jag menar att det är så men att vi samtidigt inte får glömma att även om processerna och ställningstagandena är alldagliga så är den centrala aspekten av konstnärlig forskning att det är en konstnärlig sensibilitet som ligger bakom valen som görs och förmågan att föreställa sig det konstnärliga resultatet som just konst som är avgörande. Av den anledningen är det svårt att helt komma bort från det affektiva eller det undermedvetnas logik när vi vill beskriva den konstnärliga forskningsprocessen .

   Frågan är om det egentligen handlar mindre om en översättning och mer om att förstå hur vi kan förhålla oss till mänsklig kommunikation. Guattari ville komma runt det han benämnde det "personologiska" språkbruket i pyskoterapin och Bateson pekar på att konsten har en kommunikationskapacitet som gör den mer lik till exempel andliga upplevelser, berusning och drömmar. Utmaningen är inte att det finns olika logiska typer av medvetande och kunskap utan hur vi kan förstå dem genom en kommunikativ helhet som inte delar upp de olika tillstånden i olika fack som i grunden är olika. Klart är i alla fall att den transversala processer kan spela en stor roll här. Kvar har vi frågan om detta i sig kan ge oss mer stringent formulerad konstnärlig forskning där det blir lättare för andra forskare att förstå och relatera till vad tidigare forskning har resulterat i.

   Att det som vi här förenklat benämner det inre och det yttre inte är två åtskilda paradigm för förståelse, kunskap och kommunikation kan inte nog poängteras. Konst har länge präglats av idén på det 'rena' inre uttrycket som står i kontrast till det yttre 'befläckade'. Den inre är idealistiskt och ärligt och det yttre kan vara kommersiellt, beräknande och materialistiskt. Även om det är förhållandevis lätt att ta avstånd från dessa grovt tillyxade kategorier har de stort inflytande över hur konstlivet utvecklar sig vilket uppmuntrar sökandet efter det ``rena'' uttrycket, det som passerar förbi medvetandet, förbi det självmedvetna jaget. Ibland är strävan efter orignaliteten själva källan till sökandet efter det av medvetnadet obesudlade uttrycket; om varje individ är unik och oberoende borde också det genuint personliga uttrycket vara originellt. Saxofonisten Ornette Coleman talar om strävan efter ett så spontant skapande som möjligt, om en kreativitet utan minne.[[footcite:litzweiler92][s.117]] Han talar om hur hans spel innan han nådde framgångar var mera ärligt än det sedan blev och valde att börja spela trumpet och violin för att slippa onödig kunskap.[[footcite:taylor77][Intervju med Ornette Coleman i::s.33]] För övrigt påfallande likt Marcel Duchamp tal om traditionens fängelse och att glömma med handen: ``I unlearned to draw. The  point was to forget \emph{with my hand}.''[[footcite:tomkins65][s.29]]. 

   På skivan /The empty foxhole/ från 1966[[footcite:coleman66]] spelar Ornette Coleman tillsammans med sin tioåriga son Denardo Coleman på trummor och beskriver sin tillfredställelse över att spela med någon som inte behövde bry sig om kritiker eller konsertarrangörer, utan som kunde spela och vara fri.[[footcite:litzweiler92][s.121]]  Detta hör Ornette för att han lyssnar på Denardo men också för att han har förmågan att lyssna på sig själv; han kan ju konstatera att sonen besitter en egenskap han själv har förlorat. Det yttre lyssnandet, att lyssna på den andre, kompletteras av ett inre lyssnande. Och, jämfört med att lyssna på den andre så är det betydligt svårare att lyssna på sig själv. Som konstnärliga metoder är dessa exempel oproblematiska och i vilar på en önskan att vidareutveckla sin praktik. Vi kan se deras önskan att släppa taget om det invanda och inlärda som ett försök att etablera nya transversala relationer mellan den medvetna och språkligt kodade viljan att förnya och den konstnärligt kodade kunskapen om hur detta ska gestaltas. Men om vi vill förstå den har praktiken utan att i övrigt göra en djupare analys kan man lätt landa i en syn på en relation mellan det trascendentala inre och det fysiska yttre som i grunden är hierarkisk. Utifrån den blir det väldigt svårt att beskriva vad konstnärlig kunskap är.

   En anledning till att vi har en tendens att se konstnärlig praktik som en individuellt artikulerad form för kunskap är att vi i huvudsak ser konstnärlig verksamhet som en individuellt situerad praktik. Det är den säkert i vissa fall, och utan tvekan är detta den romantiska bilden av konsten som något som kretsar kring ett solipsistiskt geni. Stjerna tar spjärn mot denna bild när hon diskuterar sin metod:
   #+begin_quote
   established traditions in contemporary art practice still harbour segments of binaries that separate an autonomous active (white, male) subject and a (passive) urban text. Rejecting this traditional view, in proposing that we become non-autonomous, I advocate that we view the artist-subject’s agency in artistic production as transversal.[[footcite:Stjerna2018][s.119-20]]
   #+end_quote

   Därför är det lätt att hamna i en dubbelt problematisk situation när konstnärlig forskning diskuteras. Först är det nödvändigt att beskriva konstnärlig praktik som något som är byggt på kunskap och erfarenhet och som inte är mystiskt, hemligt eller underligt. Först när det är möjligt att finna samsyn kring denna bild är det möjligt att påvisa att det i denna praktik finn kunskap som har ett allmängiltigt värde.

* Att kommunicera erfarenheten i öppen form 5000
  I en avhandling som [[citetitle:Stjerna2018]] är gränserna mellan praktik, metod och teori inte artikulerad utan ständigt rörlig. Terminologin hämtad från Deleuze och Guattari är till exempel såväl metod, teori och i vissa fall resultat och det är inte alltid självklart vad som är målet. Om vi tittar på den första  forskningsfrågan, /På vilket sätt kan jag som konstnär utveckla utforskande tillvägagångssätt som understödjer en transversal skapandeprocess?/, så är det klart att den transversala skapandeprocessen är ett mål i sig, men lika tydligt är det i kapitel fem att Stjerna genom sin praktik redan i början av projektet etablerar transversala kopplingar [[footcite:Stjerna2018][p.145]]. Genom hela avhandlingen argumenterar hon för en syn på själva ljudinstallationen som en transformativ praktik som löper mellan ett flertal konstnärliga strategier som var och en är en transversal process. Slutligen pekar hon även på att den komplexa transversala processen är ett analytiskt verktyg som utövar inflytande på den inbegripna processerna. Hur kan då samma begreppsapparat vara mål och metod?

  Det är ännu svårt att se konstnärlig forskning som en disciplin som genererar tydliga resultat utifrån väl beprövade metoder. Istället finns det en rad möjliga artikulationer av kunskapsutveckling som alla delar attityden att det i den konstnärliga praktiken finns en epistemologisk potential, en möjlig kunskap som om den begreppsliggörs kan ha stort inflytande på en rad olika fält. I sammanhanget kan det påpekas att denna tro på konsten som kunskapsbärande är delvis överensstämmande med Deleuze och Guattaris resonemang i deras sista samarbete /What is Philosophy?/ där de definierar tre kreativa metoder: filosofi, vetenskap och konst. Egentligen kan man gå ännu längre och säga att det i princip överensstämmer med Deleuzes hela filosofiska gärning, inklusive önskan att bryta ner de ontologiska hierarkier som han ser genom hela filsofins historia, att se konst som en form för kunskap eller tänkande. Men om konst är kunskap, eller bär på en kunskapsbärande potential, vari består den? Deleuze och Guattari skriver vidare: 
  #+begin_quote
  What about the creator? It is independent of the creator through the self positing of the created, which is preserved in itself. What is preserved---this thing for the work of art---/is a bloc of sensations, that is to say, a compound of percepts and affects/. [\ldots] The artist creates blocs of percepts and affects, but the ony law of creation is that the compound must stand up on its own. [[footcite:deleuze1994][kursivering av författaren][p.164]]
  #+end_quote
  Att konstverket i sig självt, och oberoende av upphovspersonen, har en potential är tydligt, likaså att det bör frigöra sig själv, men i konstnärlig forskning är det ofta praktiken och vad för slags kunskap den kan bära eller föra med sig, snarare än resultatet, som står i centrum. Om filosofi är en konceptskapande process är konst en teckenskapande process (och vetenskap en funktionsskapande process).

  Det är möjligt att se konstnärlig praktik som ett sätt att förstå annan kunskap såsom teknik eller filosofi. I dessa fall kan man se den konstnärliga praktiken som en testbädd för ett konceptuellt ramverk. Det finns en aspekt av detta i /Before Sound/ där de filosofiska koncepten prövas mot en existerande praktik och sättet som praktiken utvecklar sig kan då ses som ett utforskande av filosofin. Begreppet /det immanenta planet/ är ett exempel på ett koncept som är centralt för Stjerna (och för Deleuze filosofi) och som kan ses få, om inte en förklaring så en praktisk applikation, genom den konstnärliga praktiken. I teknologisammanhang kan man föreställa sig att en teknik, säg ett programmeringsgränssnitt eller en specifik hårdvara, utforskas i en konstnärlig praktik. Den konstnärliga metoden, som i detta fall ska ses som en experimentell praktik där koncept prövas och utvärderas baserat på hur bra eller dåligt de fullföljer den konstnärliga ambitionen, används för att validera teknologin. Det betyder att en teknologi som i allt väsentligt ses som funktionell och stabil från ett tekniskt synsätt kan framstå som annorlunda genom en konstnärlig undersökning. Det konstnärliga ramverket behöver i sig inte vara experimentell utan kan mycket väl följa en befintlig tradition helt idiomatiskt En undersökning på denna nivå kan mycket väl leda fram till att till exempel teknologin är bra men den fungerar dåligt i detta konstnärliga sammanhang. Detta förhållningssätt kan ses som en kritiskt evaluering genom konstnärlig metod. Skulle denna studie även utforskas med en filosofisk begreppsapparat som Stjerna gör i /Before Sound/ så skulle de tre perspektiven konst, vetenskap och filosofi samverka på ett sätt som påminner om hur Deleuze och Guattari föreslår i [[citetitle:deleuze1994]].[[footcite:deleuze1994]] 

  Insikten om att den konstnärliga sensibiliteten kan behövas i större utsträckning än vad vetenskapstraditionen kanske fram till nu har velat göra gällande kommer dock inte bara från konstnärlig forskning eller filosofin. Det samarbete som Kungliga Musikhögskolan och Kungliga Tekniska Högskolan initierade 2016 byggde till exempel på KTH:s insikt att en framtida ingenjör behöver en kompetens som går bortom den rent vetenskapliga kompetensen och speciellt intressant är det konstnärliga perspektivet. Det är likaledes motivationen bakom det nyligen uppstartade tvärvetenskapliga centrumet NAVET på KTH där KMH, Stockholms konstnärliga högskola samt Konstfack är partner.

  Med en användbar metod kan även själva praktiken ses som en kunskapsgenererande fas. Här ingår de numera ganska vanliga studierna i interpretation eller alternativa tekniker. En frågeställning utforskas genom praktiken och om experimentet lyckas så är det ett bevis på att praktiken är användbar även för andra som söker svar på liknande problem. Även denna typ av undersökningar kan dock sträcka sig bortom den konstnärliga sfären i vilket fall valideringen kan ske åt två håll. En studie i gruppimprovisation kan till exempel visa att visa typer av musikalisk interaktion är gynnsam givet ett visst avsett ändamål. Samma metod kan sedan prövas i andra interaktiva situationer, som social interaktion, och om den visar sig framgångsrik även där så går det att återföra till det musikaliska sammanhanget. Även denna typ av undersökning finns representerad i /Before Sound/, kanske framförallt i relation till den andra forskningsfrågan. I exemplet med /Currents/ är beskrivningen av arbetsmetoderna en kommunikation av en process som inte bara gestaltade dataströmmarna och förhöll sig till de uppställda metoderna utan som också skapar en modell för ett konstnärligt tillvägagångsätt som har politiska och konstnärliga konsekvenser.

  En tredje variant är att se det resulterande konstverket som en kunskapskälla på det sätt som Deleuze och Guattari framhåller ovan. Denna strategi har den uppenbara nack- eller fördelar (beroende på hur man ser det). Om det ska stå för sig själv ("stand up on its own",[[footcite:deleuze1994][[p.164]] som i citatet ovan). så måste det, åtminstone i musik, förlita sig på ickekonceptualiserade kommunikationsformer. Tidigt i konstnärlig forskning var detta normen. Det skulle vara konsten i och för sig själv som utgjorde slutresultatet och det kunskapsbärande elementet i konstnärlig forskning. I praktiken var det endast ett fåtal avhandlingar som gjordes så här men fortfarande är diskussionen om balansen mellan det som lite slarvigt kallas för "det skrivna" och "det gestaltade" aktuell. Det finns naturligtvis flera anledningar till detta, men en relevant punkt som förtjänar att framhållas är att det hela tiden finns en risk att en konstnärlig avhandling är en avhandling med en omfattning som motsvarar monografier inom humaniora inklusive ett konstnärligt arbete som är lika omfångsrikt. Helt enkelt en dubbel avhandling. Om nu det konstnärliga resultatet i sig skulle vara så viktigt hur kan då en avhandling i musik överhuvudtaget kommuniceras utanför sitt uppförande. Om vi accepterar en representation av det i form av en dokumentation, vad är det som säger att en inspelning är bättre än en beskrivande text? Det kan naturligtvis finnas många falla där det är det men den poäng jag försöker göra här är att förutsättningarna för vad som är en relevant dokumentation och/eller diskussion av ett konstnärligt resultat inte kan avgöras på generell nivå utan måste göras på individuell basis.

  I /Before Sound/ pekar de tre forskningsfrågorna mot processen snarare än resultatet varför den begränsade dokumentationen inte kan ses som ett problem. Dessutom är det platsspecifika en helt central parameter i Stjernas praktik såsom den presenteras i avhandlingen vilket gör en eventuell dokumentation ännu mindre relevant. Även om detta är en aspekt som ytterligare kan diskuteras vill jag här först kommentera hur det platsspecifika är sammanvävt med den teoretiska ingången i avhandlingen. Centralt för Deleuze och Guattaris filosofi i /Capitalism and Schizophrenia/ och /What is Philosophy?/ är immanensplanet, som i sin tur har sitt ursprung hos Spinozas panteism,[[footcite:Stjerna2018][p.93]] eller tanken på att allt är en substans snarare än ordnat i en hierarkisk och dualistisk struktur. Givet att Stjerna utgår från detta immanensplan när hon beskriver den konstanta rörelse i tillblivelse som de transversala processerna är sammanvävda i är idén om det platsspecifika och odokumenterbara installationen helt konsekvent (även om själva begreppet platsspecifik kan ses som problematisk i det ammanhanget).

* Teorin inverkan på metodval och strategier 4000
* Den konstnärliga kunskapens dynamik 4000
  Utvecklingen av konstnärlig forskning i Sverige kan ses utifrån minst tre delvis överlappande processer. Den ena rör den utbildningspolitiska aspekten av konstnärlig utbildning i Bolgna-modellen, men började ännu tidigare än så, i Sverige med högskolereformen 1977.[[footcite:Lilja2015][Se t.ex. ::]] Då nu alla högskolor skulle bygga på utbildning som är baserad på forskning så måste även de konstnärliga utbildningarna bedriva forskning och eftersom dessa bedriver konstnärlig undervisning eller undervisning med konstnärliga metoder så måste de även bedriva konstnärlig forskning. I grunden ligger jämställandet av konstnärlig och vetenskaplig forskning som nu ses som två uttryck för kunskapsproduktion. 

  Den andra processen är mer svårfångad men handlar om hur konst- och kulturlivet i samhället har utvecklat sig under de senaste decennierna. Det fält inom vilket konstnärliga uttryck diskuteras och kommuniceras har för vissa uttryck, som musik, förändrats i ganska stor grad. Dagspressens recensionsverksamhet, Public Service avtryck på musiklivet och det offentligas stöd till musiklivet har förändrats vilket har skapat nya behov för ytor att diskutera och experimentera med konstnärliga uttryck och här har den konstnärliga forskningen börjat fylla ett stort hål. 

  En tredje process rör en mer filosofiskt orienterad epistemologisk fråga om vad kunskap kan ses vara och hur den kan kommuniceras. En vanlig, initial, invändning mot konstnärlig forskning som diskuterades ovan är att något som i allt väsentligt är beroende av sinnesintryck, som konstnärligt uttryck kan sägas vara, inte kan utgöra grunden för forskningsmässig kunskap. Även om denna invändning vilar på en missuppfattning av såväl forskningsmässig kunskap som konstnärlig kunskap så rör den vid den viktig grundförutsättning för all kunskapsutveckling, nämligen att det finns grundläggande förutsättningar som det går att enas omkring.

  Det finns en möjlig negativ, om än ofullständig, definition av vad konstnärlig kunskap kan utgöra. Om vedertagna vetenskapliga definitioner och allmän empiri ger oss de fakta som vi behöver för att förstå en sida av vår tillvaro så konsten kan säga någonting om är allt det andra, det vi inte omedelbart kan se. Eller som Eisner skriver:

  #+begin_quote
  "For me, the defining feature that allows us to talk collectively about the arts is that art forms share the common mission of achieving expressiveness through the ways in which form has been crafted or shape. The arts historically have addressed the task of evoking emotion. We sometimes speak of the arts as resources that can take us on a ride. The arts, as I have indicated elsewhere, provide a natural high. They can also provide a natural low. The range of emotional responses is enormous. These emotional consequences in relation to a referent color the referent by virtue of the character of the emotion that the artistically crafted form possesses. Through art we come to feel, very often, what we cannot see directly.[[footcite:Eisner2008][s.8]]
  #+end_quote

  Trots att det inte borde vara det, kan det vara en utmaning att argumentera för konstnärlig  kunskap i en samtid som samtidigt präglas av en övertro på det vetenskapliga kunskapssystemet, en postmodernistisk avart där varken rätt eller fel existerar och en hyperkapitalism som inte ser sina gränser. Machiarini-skandalen är ett exempel på vad som händer när dessa tre samverkar och havererar. Jag ska försöka peka på några områden där jag ser att konstnärlig forskning kan komma att få stor betydelse om kunskapen hanteras, men jag argumenterar framförallt utifrån ett musikperspektiv och bilden kan vara väsentligt annorlunda inom andra konstnärliga fält.

  Det digitala har idag helt genomsyrat såväl produktion, distribution som konsumtion av musik samtidigt som det digitala endast i liten utsträckning är en teknik som präglas av konstnärlig utveckling. Det betyder att produktionsverktyg, som mjukvara för inspelning och redigering samt program för uppspelning visserligen för det allra mesta har en förståelse för förutsättningarna för dessa verksamheter men förhållandevis liten kunskap om de faktiska processer som ligger bakom. Etableringen av artificiell intelligens visar ytterligare på behovet av nya metoder för att bättre förstå vidden av förändringen som vi är inne i. Även om internet inte är nytt var det inte många som för tio år sedan hade trott att vi idag, genom våra telefoner, trådlöst har kontakt med en till synes oändlig samling musik. Följden av detta är att en majoritet av människor i västvärlden, själva designar sin egen ljudmiljö. Många av de verktyg som har möjliggjort denna transformation är produkter av en ingenjörskonst på mycket hög nivå. Spotify tog utgångspunkt i teknik som vuxit fram i en dunkel periferi genom Pirate Bay och gjorde delningen legal och legitim, fick tekniskt försprång och blev ensam herre på täppan. Detta är dock en utveckling som har skett helt och hållet på kommersiella grunder och helt utan konstnärliga ambitioner. Tvärtom var själva förutsättningen för Spotifys framgång att man sänkte ersättningen till de artister som spelades vilket kan ses som ett makroekonomisk variant av att såga av den gren man sitter på. Ändå talar man om  Spotify som del av det svenska musikundret.[[footcite:k%C3%B6nig2018]]

  Här framträder problemet som musik lider av: musiken som konstform har aldrig gjort upp med musik som produkt utan de båda är i allt väsentligt sammanvävda. Musiken är hel och full kommodifierad och därför kan "det svenska musikundret" samtidigt inkludera Sound Cloud och Ann-Sofie von Otter. Nu finns det naturligtvis extremt starka kommersiella krafter i operabranschen, men skillnaden är den att von Otter hade aldrig kunnat ta sig till den position hon har utan att hon hade otvetydiga konstnärliga kvaliteter, medan teknikföretag som Sound Cloud och Spotify kan utvecklas helt utan dessa att konstnärliga överväganden styr utvecklingen. 

  Här finns en viktig plats för den konstnärliga forskningen och här kan dess resultat utvärderas på en marknad långt utanför akademiens skyddande väggar. I min avhandling från 2008 pekade jag på behovet att inkludera en konstnärlig dimension när modeller för interaktivitet skapas.[[footcite:frisk08phd]] Den bakomliggande idén var den att en teknologiskt orienterad interaktivitet inte bara riskerar att bli en grov förenkling av vad vi förväntar oss av en interaktiv upplevelse, resultatet kan istället bli att förväntningarna sänks. Genom att istället se på utvecklingen av interaktivitet utifrån vad jag som musiker och tonsättare vill få ut av den med målet att använda den konstnärligt skapar andra insikter och nya förutsättningar.

  Utifrån det komplexa och svårgreppbara fältet av artificiell intelligens finns flera möjligheter för konstnärlig forskning att spela en roll. Liksom i exemplet ovan beträffande interaktivitet är AI ett område där antaganden om mänsklig interaktion spelar roll, men även antaganden om vad mänsklig erfarenhet utgör. Dessutom har vi den otroligt svåra etiska frågan. Alla dessa kan angripas genom konstnärliga experiment där det mest omedelbara är att genom experiment utnyttja en teknologi för konstnärlig produktion. Ett sådant experiment kommer både säga något om teknologins stabilitet och om hur konstnärlig aktivitet fungerar i interaktion med teknik.[fn:4]

  Genom metoder som vi har lånat från postkolonialismen har vi i gruppen The Six Tones under en rad år arbetat med interkulturella möten. Med det övergripande målet att överbrygga kulturella avstånd och avsaknad av ett gemensamt språk har vi metodiskt arbetat konstnärligt. Även om målet i varje projekt har varit att komma fram till ett övertygande konstnärligt resultat har vi inte strävat efter harmoni och kunskapsöverföring utan med gemensamt lärande, differens och lyssnande. Genom en rad turnéer och skivinspelningar har vi haft möjlighet att utvärdera praktiken i ett flertal sammanhang. Under 2020 kommer vi arbeta med migrerade musiker i Sverige för att bland annat försöka hur Sverige konsekvent har uteslutit dessa musikers kulturtraditioner som inte i allmänhet ses representerade på konserthus och scener och inte heller i kulturpolitiska sammanhang. Konsekvensen är att en del av dessa musiker befinner sig i ett ingemansland, långt från sitt hemlands levande tradition men utan möjlighet att etablera sig i sitt nya land. I projektet hoppas vi bättre förstå dessa musikers traditioner, men också bygga upp en kunskap som kan skapa en skillnad. Att arbeta med konst på liknande sätt, med väl utarbetade metoder i ett forskningssammanhang är ett sätt att utnyttja konstnärlig kunskap inom ett fält där Sverige i dagsläget har svårt att politiskt, etiskt och kulturellt har väldigt svårt att hitta rätt.

  Jag vill än en gång återkomma till den interrelation mellan konst, vetenskap och filosofi som tre former för tänkande som Deleuze och Guattari propagerar för i [[citetitle:deleuze1994]] och som präglar undersökningen i /Before Sound/. Jag menar att det finns en viktig poäng i deras resonemang som finner viss resonans i den för Sverige ganska unika uppdelning mellan konstnärlig och vetenskaplig forskning i den svenska högskoleförordningen. Filosofin ingår visserligen i det vetenskapliga i den svenska modellen men just det kan vi bortse från för ett ögonblick. Att se det konstnärliga och det vetenskapliga två som väsenskilda men samtidigt kompletterande former för tänkande får vissa konsekvenser för hur vi ska, eller kan, se på konstnärlig forskning. Även om vi kan peka på en konkret nytta med med konstnärlig forskning, en nytta som i någon mening är relaterad till nyttoaspekten av en del vetenskaplig forskning, är det inte säkert att detta ska vara modellen för all konstnärlig forskning. För det första är frågan om vad som är nyttigt ur ett samhällsperspektiv något som i sig är ett begrepp i rörelse och i stor utsträckning knutet till de politiska och ekonomiska sfärerna genom vilka vad som är nyttigt till viss utsträckning bestäms. Det går därför inte att fastslå nyttigheten i en forskningspraktik utan att lyfta blicken och se bredare på frågan. Det finns tydliga paralleller mellan filosofi och konst som kunskapsområden. Båda har i allmänhet setts som viktiga delar av (den västerländska) kunskapsutvecklingen och båda har i någon mening förlorat sin särställning och betydelse i samtiden. Det räcker med att ytligt betrakta filosofin, som är en av våra äldsta forskningspraktiker i västvärlden, för att snabbt konstatera att den konkreta nyttan har varit begränsad utifrån dagens måttstockar, som /impact/ och samverkan. Lika otvetydigt är det att den som konceptskapande kraft har lagt grunderna till själva fundamentet till vårt samhälle idag. Konsten har haft en lika otvetydigt funktion för vår kultur och har lika svårt att mäta sig som filosofin.

  Samtidigt kan vi inte mäta den konstnärliga forskningens värde utifrån vad den kan åstadkomma /som vetenskap/, helt enkelt för att det inte finns någon större poäng med det. Hybridkonstellationer kan skapas, likt de jag presenterar ovan, i alla korthet. Dessa kan genom sitt tvärdisciplinära angreppssätt bli ytterst effektiva sätt att utöka kunskapen inom avgränsade fält. Men detta är och ska vara ett komplement till mer öppet definierad konstnärlig forskning och denna senare form för forskning behöver inte därigenom präglas av esoteriska metoder utan relevans för omvärlden All forskning ska naturligtvis förhålla sig till sin omvärld och agera i samverkan med det omgivande samhället. Vi kan också ställa oss frågan varför vi behöver konstnärlig forskning snarare än bara konstnärlig praktik, men på den frågan finns det ett ganska enkelt svar: för det första behöver vi båda två, tillsammans och oberoende av varandra. För det andra är det genom forskningen som vi har möjligheten att komma åt den verkligt intressanta kunskapen som tidigare in funnits tillgänglig. Genom en jämförelse med filosofen Frank Jacksons berömda kunskapsargument, ett tankexperiment vars syfte det vad att visa att det finns icke-fysiska aspekter av medvetandet. Tankeexperimentet går ut på att en kvinna som växer upp helt avskärmad från världen, i en helt svartvit miljö, som aldrig har sett färger, lär sig allt, precis allt som finns att veta om färger. Hon lär sig även om det neurofysiologiska och vad som händer när olika vågländer av ljus träffar näthinnan. Hon kan föreställa sig hur det fysiskt är att se färg, men har aldrig upplevt det. Vad händer när hon får komma ut ur sitt rum och får uppleva färger på riktigt? Lär hon sig då något nytt? Det vill säga, finns det något utöver det fysiska att lära sig som vi bara kommer åt genom upplevelsen?[[footcite:Jackson1982][s.130]] 

  Om vi på samma sätt som i exemplet ovan tror att vetenskapen bara kan ge oss en del av sanningen och att det finns kompletterande fält av kunskap, som empiri, etik och konst, som behövs för att vi ska kunna skapa oss en så komplett bild som möjligt av tillvaron, då finns det goda chanser att konstnärlig forskning kan bidra till den konskapen. Exempel på sådan kunskap kan vara forskning på förkroppsligad kunskap, kommunikativa strategier och interaktion. Alla dessa tre har varit fokus för flera konstnärliga projekt och på alla dessa tre områden har det varit tydligt att den konstnärliga sensibiliteten och undersökningen har kunna öppna upp för en förståelse som endast svårligen hade kunna angripas på annat vis. Jag tror att frågan om vad konstnärlig forskning är, eller vilken nytta den har, är felställd. Frågan vi borde ställa oss är snarare i linje med: Hur kommer ett samhälle som inte har en otvetydig relation till konstnärlig sensibilitet och filosofiskt resonemang se ut? Utifrån den frågan blir det klart att det inte kan vara enbart upp till de konstnärliga högskolorna att motivera nyttan med konstnärlig forskning utan att det måste vara en fråga som diskuteras på bred front i samhället. 

  Det är ingen tvekan om att vi lever i ett vetenskapssamhälle först och främst och att det har i sin tur skapat ett tekniksamhälle. Om det finns övertygande argument för att vetenskapen inte behöver konsten och filosofin så är jag beredd att tänka om. Tills dess menar jag att allt pekar på att vi behöver tillgång till alla typer av tänkande vi kan komma åt för att lösa de utmaningar vi står inför i världen idag.


* Diskussion 2500

  Stjerna beskriver sin praktik som multidisciplinär[[footcite:Stjerna2018][p.42]] och även om det inte är nödvändigt att en undersökning av denna samtidigt är interdisciplinär[fn:5] betyder det att flera olika kunskapsfält samsas sida vid sida i forskningen. Detta kan lätt bli en utmaning och även om Stjerna elegant navigerar runt behovet att beskriva den filosofi som hon utgår från och lyckas dra rimliga gränser för vad som inkluderas och vad som exkulderas, är det tveklöst en avhandling i minst två discipliner: filosofi och konst. Detta är inte, vill jag betona, ett problem, snarare är det en nödvändighet för att komma åt de verkligt intressanta perspektiven, och här behöver vi goda exempel som kan föra fältet framåt. Ytterligheterna här är annars risken för dubbla avhandlingar, det vill säga avhandlingar som egentligen avhandlar två ämnen, risken för avhandlingar som undviker det konstnärliga perspektivet och fokuserar på ett angränsande ämne, eller avhandlingar som inte tydligt nog relaterar till det ansgränsande ämnets fält och vilket leder till att argumentationen i det konstnärliga ämnet faller. Samtliga dessa faror går att undvika med rätt handledning, men problemet med att hitta rätt handledare är uppenbart när det handlar om ämnen som eventuellt inte finns representerade på doktorandens fakultet.

  Detta är en anledning till varför bihandledaren fyller en så viktig roll i konstnärlig forskning på ett sätt hen inte gör i vetenskaplig forskning.[fn:6] Bihandledaren kan vara den personen som garanterar att angränsande ämnen får tillräckligt stor roll i arbetets helhet och kan i vissa fall framstå som projektets huvudhandledare. Det finns ytterligare en anledning till bihandledarens betydelse som har att göra med svårigheten att hitta rätt handledarkompetens på fakulteten eller inom högskolan då endast ett fåtal lärare på de konstnärliga lärosätena ännu är disputerade (även om variationen här är stor mellan lärosätena). Då det ofta finns ett behov av att huvudhandledaren och doktoranden är på samma institution så kan en lösning vara att huvudhandledaren blir mer av en institutionshandledare och att den huvudsakliga handledningen sköts av bihandledarna. Även om detta inte behöver vara problematiskt i sig kan det leda till obalans i hur forskningsfältet utvecklar sig i relation till andra. Handledarkompetens och seminarieverksamahet är centrala delar av en forskningsmiljö.

  Samtidigt ska möjligheterna utnyttjas att inom ramarna för de konstnärliga högskolornas forskningsverksamhet appropriera musiken som konstform och studera den kunskap som gör det möjligt för musiker att åstadkomma det de gör. Konstnärlig forskning som en ny arena för experimentell konst, experimentell i den bemärkelsen att den utmanar de gängse metoderna för såväl konst som forskning även om inte resultatet i sig behöver vara experimentellt rent stilistiskt. Det kan vara Barockmusik eller elektroakustisk musik, eller någon annan genre.
* Footnotes

[fn:6] I KMH:s samarbete med KTH har jag blivit varse detta. Bihandledare är inte arvoderade i deras system och ses inte som tillnärmesivis lika viktiga i avhandlingsarbetet som huvudhandledaren.

[fn:5] En praktik som kombinerar många olika praktiker men som i grunden vilar på konstnärliga frågeställningar kan naturligtvis undersökas utifrån en konstnärlig grund och med konstnärliga metoder och därmed undvika att forskningen av den anledningen bli interdisciplinär. Denna avvägning är inte oviktig då ett problem som vi åtminstone i Sverige har inom konstnärlig forskning är att undersökningarna och förväntningarna på resultaten bli orimligt höga vilket leder till avhandlingar som är orimligt omfattande. Nyligen har jag varit opponent i såväl Estland som Nederländerna där textdelens omfattning på avhandlingen är ner mot en fjärdedel av vad svenska avhandlingar tenderar bli.

[fn:4] I ett pågående projekt på Musikhögskolan i Oslo med titeln Goodbye Intuition under ledning av Ivar Grydeland jobbar vi med dessa och liknande frågor. En ej ännu publicerad artikel i Organised Sound beskriver detta: /Aesthetics, interaction and machine improvisation/ (Frisk 2019)

[fn:3] I denna volym har jag tillsammans med Anders Elberling bidragit med ett kapitel med viss bäring på denna diskussion. Det är en text om vårt videoverk /Machinic Proposisitions/ som är uppbyggt utifrån några av de theorem för deterrioralisering som Deleuze och Guattari beskriver i Mille Plateaux och vilket på det viset är ett annat exempel på hur filosofi kan diskuteras genom konstnärlig praktik. I /Machinic Propositions/ är vi dock noga med at påpeka att syftet inte är att skapa filosofi utan att använda konstnärlig praktik för att förstå och kritiskt granska filosofi. [[fullcite:frisk2017e][p.121-9]]

[fn:2] See bland annat [[fullcite:frisk-ost06]] och [[fullcite:frisk-ost06-2]].

[fn:1] Maskin ska här läsas i den mening som Deleuze och Guattari använder /machine/ och /machinic/. Stjerna använder också termen återkommande och kan ses som en metod att förklara en typ av rörelse som opererar rhizomatiskt och som kan skapa transversala kopplingar till andra maskiner.
