* Henrik Frisk: Vad är 'jaget' i konstnärlig praktik?
 
Att lyssna på den andre. Vad betyder det egentligen? Att kunna lyssna på den andre och förstå henne som den andra, inte genom sig själv utan som den helt "andra". Är det möjligt? Detta är frågor som ligger nära de frågor som många filosofer har frågat sig, t.ex. Emmanuel Levinas (Le Temps et l'Autre) och som i grunden är etiska frågor: när alla är lika olika mig kan jag också bättre förstå alla andra på lika villkor. Eller helt kort: jag kan lyssna på den andre. 

I musiken har vi lärt oss att det är viktigt att lyssna på den andre, det är själv grunden i centrala moment som intonation, improvisation och rytmik. Att lyssna i musiken är därför på ett sätt enklare: det är här mer självklart att det inte handlar om att /bli/ den andre, eller att ge upp sig själv till förmån för de andra musikerna utan om att hitta det utrymme som ligger mellan att anpassa sig efter den andre och lyssna på sig själv. Men som musiker är det kanske ännu svårare är att lyssna på sig själv än att lyssna på andra: var finns det centrum i mig som definierar vad jag är och vad jag vill: var är mitt jag som är förutsättningen för den andre?

I några av de konstnärliga forskningsprojekt som jag har gjort har lyssnandet på den andre och sig själv, i musiken såväl som utanför musikens sfär, varit centrala frågeställlningar. I gruppen The Six Tones har tre koncept, som alla har en viktig funktion på hur man uppfattar jaget, haft stor vikt: frihet, vana och individualitet.

1. Frihet kan vara frihet från sig själv och självets egen frihet.
2. Vanan kan begränsa friheten men likväl bidra till att öppna upp för den.
3. Individualitet är en komplex faktor som tillsammans med jagets egen frihet kan skapa en dominerande maktfaktor, men som också är förutsättningen för friheten.

Sammantaget har jag i projekten försökt förstå det som jag ser som självklart i konstnärligt arbete - som att i och genom musik lyssna på den andre - och filtrera den erfarenheten genom reflektion och tanke med förhoppningen att etablera en preliminär och lokal teori med vilken jag bättre kan förstå vad det är vi gör tillsammans i gruppen. Jag återkommer till detta snart.

Hur kan det musikaliska jaget vara fritt, responsivt och öppet för den andre, och samtidigt uttrycka individualism, och vilken kunskap döljer sig i den processen? De flesta musiker som har improviserat känner igen detta, åtminstone på ett intuitivt plan. Frihet är trots allt ett återkommande tema i improviserad musik och att röra sig mellan att ta initiativ som inte tar hänsyn till de andra i gruppen och att vika undan och låta andra ta plats, är en naturlig del av processen. Men hur det händer och vad som föranleder att det händer 

Men i mötet med en annan musikkultur blir frågan om frihet mer laddad. Vilken frihet har jag att uttrycka mig i en kontext som inte är min? När blir min frihet något som förhindrar någon annans frihet snarare än ett musikaliskt verktyg? Dessa var frågor som vi ställde oss när vi först började jobba med gruppen The Six Tones som består av två svenska musiker och två Vietnamesiska. Jag ska inte här gå in i detalj i vad de projekten har inneburit utan istället peka på några principiellt viktiga steg i processen. Dessa inkluderade vikten av att förstå betydelses av de värderingar man själv tar med sig in i en process. I sin tur kan det leda till en insikt om vad som är centrum och vad som är periferi, och hur man konstant kan röra sig i det fältet. Att detta har betydelse är inte svårt att förstå, men att undersöka det genom musikalisk praktik kan leda till nya insikter.

Det som jag hade lärt mig och som blivit enkelt var nu plötsligt komplicerat. När jag lyssnade på mig själv hörde jag sådant som mina medmusiker varken förstod eller visste att de kunde lyssna på. När jag lyssnade på dem upplevde jag att det uppstod en hierarki i mitt lyssnande som varken var produktivt eller försvarbart. Min musikaliska praktik byggde på att några estetiska ramar som de jag spelade med var överens om även om vi inte pratade om dem och nu var den, i bästa fall, upp och ner. Att lyssna på mig själv hade blivit den största utmaningen.

Genom att arbeta systematiskt med lyssnandet i gruppen kunde vi långsamt bygga upp ett nytt fundament som var stadigt nog att stå på. Vi kunde se hur lyssnandet till den andre gick genom flera olika stadier av förändring och vi analyserade hur vårt lyssnande ibland misslyckades, ibland lyckades och ibland ledde till helt oväntade resultat. Så småningom kunde vi också ge oss själva friheter att t.ex. /inte/ lyssna på den andre eller, ännu svårare /inte/ lyssna på sig själv. Insikter som dessa kan bidra till en bättre förståelse av specifika musikaliska kontexter, men också sociala, och den inledande frågan, om att lyssna till den andre, kan hamna i ett nytt ljus. Kanske kan vi tänka på en etik informerad av musikalisk praktik?

Sammanfattningsvis kan alltså en abstrakt frågeställning undersökas i konstnärlig praktik och sedan lyftas ut igen och utveckla förståelsen av det ursprungliga sammanhanget. Detta är för mig en av de metoder jag använder i konstnärlig forskning. Genom att "flytta runt" en fråga ger det mig möjligheten att komma runt låsningar som frågeställningen i sin grundform har: att lyssna på den andre är en laddad etisk frågeställning och genom att lyfta in den i ett musikaliskt sammanhang "löses den" upp och ett annat angreppssätt möjliggörs. Detta växelspel mellan metod, praktik, teori ser jag som en viktig aspekt av den konstnärliga forskningspraktiken. Syftet? Det är att bättre förstå hur musikalisk kunskap kan påverka och utveckla såväl musiken som sociala strukturer.
