(TeX-add-style-hook "_region_"
 (lambda ()
    (LaTeX-add-index-entries
     "interaction!human-computer"
     "HCI"
     "interaction!as control"
     "interaction!as
difference"
     "interaction-as-difference"
     "Self"
     "software")
    (LaTeX-add-bibliographies
     "bibliography")
    (LaTeX-add-environments
     "squote")
    (LaTeX-add-labels
     "cha:abstract")
    (TeX-add-symbols
     '("tagword" ["argument"] 1)
     "musicannot"
     "captionfonts"
     "listoftags"
     "HRule"
     "T"
     "TT"
     "B"
     "BB"
     "section"
     "subsection"
     "subsubsection")
    (TeX-run-style-hooks
     "hypcap"
     "all"
     "hyperref"
     "pdfpagelabels"
     "pdftex"
     "urlcolor=svart"
     "linkcolor=svart"
     "citecolor=svart"
     "colorlinks=true"
     "plainpages=false"
     "a4paper=true"
     "draft=false"
     "tabularx"
     "lscape"
     "amsmath"
     "glossary"
     "hyper=true"
     "hypertoc=true"
     "makeidx"
     "sectsty"
     "enumerate"
     "rotfloat"
     "wrapfig"
     "float"
     "appendix"
     "page"
     "toc"
     "setspace"
     "fancyhdr"
     "geometry"
     "color"
     "usenames"
     "biblatex"
     "sorting=nyt"
     "indexing=cite"
     "style=verbose-ibid"
     "epigraph"
     ""
     "csquotes"
     "babel"
     "british"
     "latex2e"
     "bk10"
     "book"
     "a4paper"
     "include/ImpComInt-glossary")))

